// Copyright 2026, Jamf Software LLC

package platform

// resourceTemplate emits one Go file per platform resource. Generated commands
// take *jamfplatform.Client from CLIContext.PlatformSDKClient and call
// .Transport().DoExpect{,WithContentType}() for every API request — the SDK
// transport handles auth, retry, and tenant injection.
//
// Each generated file exposes a single constructor New<Resource>Cmd(cliCtx)
// returning a *cobra.Command tree. Hand-written code in pro.go, school.go etc.
// calls the constructor to wire the resource under whichever parent it wants.
//
// Current scope:
//   - GET (with or without path params, no body)
//   - POST actions (bodyless, with --yes for destructive)
//   - POST/PATCH with JSON body via --file/--set; POST uses application/json,
//     PATCH uses application/merge-patch+json
//   - DELETE with --yes confirmation
//   - Op-specific success status codes from spec responses
//   - url.PathEscape on path parameters
//   - Query parameter flags (CLI flag in kebab-case, query key from spec)
//   - Pagination loop for ops exposing page+page-size; aggregates the named
//     result array and emits a single flat JSON array
//   - List response unwrapping for non-paginated lists with exactly one
//     array property
//
// Still pending: --name → ID resolution, table column hints, scaffold output.
const resourceTemplate = `// Copyright 2026, Jamf Software LLC
// Code generated by jamf-cli generator. DO NOT EDIT.

package generated

import (
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"strconv"
	"strings"

	"github.com/spf13/cobra"

	"github.com/Jamf-Concepts/jamf-cli/internal/platform"
	"github.com/Jamf-Concepts/jamf-cli/internal/registry"
)

// New{{.GoName}}Cmd returns the cobra command tree for the {{.Name}} platform
// resource. Wire it into a product namespace via AddCommand.
func New{{.GoName}}Cmd(cliCtx *registry.CLIContext) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "{{.Name}}",
		Short: "Manage {{.Name}} (Platform API)",
{{- if .Long }}
		Long:  {{printf "%q" .Long}},
{{- end }}
	}
{{- range .Operations }}
	cmd.AddCommand(new{{$.GoName}}{{.GoName}}Cmd(cliCtx))
{{- end }}
	return cmd
}
{{ range .Operations }}
func new{{$.GoName}}{{.GoName}}Cmd(cliCtx *registry.CLIContext) *cobra.Command {
{{- if .HasBody }}
	var bodyFile string
	var setFlags []string
	var scaffoldFlag bool
{{- end }}
{{- if .IsDestructive }}
	var yes bool
{{- end }}
{{- if .SupportsNameLookup }}
	var nameFlag string
{{- end }}
{{- range .QueryParams }}
{{- if eq .GoType "bool" }}
	var {{.Var}} bool
{{- else if eq .GoType "int" }}
	var {{.Var}} int
{{- else if eq .GoType "[]string" }}
	var {{.Var}} []string
{{- else }}
	var {{.Var}} string
{{- end }}
{{- end }}
	cmd := &cobra.Command{
		Use:   "{{.Use}}",
		Short: "{{.Short}}",
{{- if .Long }}
		Long:  {{printf "%q" .Long}},
{{- end }}
{{- $ann := opAnnotations . }}{{ if $ann }}
		Annotations: {{ $ann }},
{{- end }}
{{- if and .PathParams (not .SupportsNameLookup) }}
{{- if .HasBody }}
		Args: func(cmd *cobra.Command, args []string) error {
			if scaffoldFlag {
				return nil
			}
			return cobra.ExactArgs({{len .PathParams}})(cmd, args)
		},
{{- else }}
		Args:  cobra.ExactArgs({{len .PathParams}}),
{{- end }}
{{- else if .SupportsNameLookup }}
		Args:  cobra.MaximumNArgs(1),
{{- end }}
		RunE: func(cmd *cobra.Command, args []string) error {
{{- if .HasBody }}
			if scaffoldFlag {
				// Scaffold prints raw JSON regardless of -o, so the output
				// can be piped straight back into --file.
				fmt.Println({{printf "%q" .Scaffold}})
				return nil
			}
{{- end }}
			if err := platform.RequirePlatformClient(cliCtx.PlatformSDKClient); err != nil {
				return err
			}
{{- if .SupportsNameLookup }}
			var resolvedID string
			if nameFlag != "" {
				listPath := strings.Replace({{printf "%q" .ListPath}}, "{tenantId}", url.PathEscape(cliCtx.PlatformSDKClient.Transport().TenantID()), 1)
				id, err := platform.ResolveIDByName(cmd.Context(), cliCtx.PlatformSDKClient, listPath, nameFlag)
				if err != nil {
					return err
				}
				resolvedID = id
			} else if len(args) == 1 {
				resolvedID = args[0]
			} else {
				return fmt.Errorf("provide a positional ID or --name")
			}
{{- end }}
{{- if .IsDestructive }}
			if err := platform.ConfirmAction("{{.Name}}", {{if .SupportsNameLookup}}resolvedID{{else if .PathParams}}args[0]{{else}}"{{.Name}}"{{end}}, yes); err != nil {
				return err
			}
{{- end }}
			path := {{printf "%q" .Path}}
			path = strings.Replace(path, "{tenantId}", url.PathEscape(cliCtx.PlatformSDKClient.Transport().TenantID()), 1)
{{- $op := . }}
{{- range $i, $p := .PathParams }}
{{- if $op.SupportsNameLookup }}
			path = strings.Replace(path, "{{"{"}}{{$p}}{{"}"}}", url.PathEscape(resolvedID), 1)
{{- else }}
			path = strings.Replace(path, "{{"{"}}{{$p}}{{"}"}}", url.PathEscape(args[{{$i}}]), 1)
{{- end }}
{{- end }}
			q := url.Values{}
{{- range .QueryParams }}
{{- if eq .GoType "bool" }}
			if {{.Var}} {
				q.Set("{{.Name}}", "true")
			}
{{- else if eq .GoType "int" }}
			if cmd.Flags().Changed("{{.FlagName}}") {
				q.Set("{{.Name}}", strconv.Itoa({{.Var}}))
			}
{{- else if eq .GoType "[]string" }}
			for _, v := range {{.Var}} {
				q.Add("{{.Name}}", v)
			}
{{- else }}
			if {{.Var}} != "" {
				q.Set("{{.Name}}", {{.Var}})
			}
{{- end }}
{{- end }}
{{- if .HasBody }}
			body, err := platform.ReadBody(bodyFile, setFlags)
			if err != nil {
				return err
			}
{{- else }}
			var body any
{{- end }}
{{- if .Paginate }}
			const pageSize = 100
			var aggregated []json.RawMessage
			for page := 0; ; page++ {
				pq := url.Values{}
				for k, v := range q {
					pq[k] = v
				}
				pq.Set("page", strconv.Itoa(page))
				pq.Set("page-size", strconv.Itoa(pageSize))
				endpoint := path
				if encoded := pq.Encode(); encoded != "" {
					endpoint += "?" + encoded
				}
				var pageResult struct {
					Results []json.RawMessage ` + "`json:\"{{.ListArrayKey}}\"`" + `
				}
				if err := cliCtx.PlatformSDKClient.Transport().DoExpect(cmd.Context(), {{methodConstant .Method}}, endpoint, body, {{statusConstant .SuccessCode}}, &pageResult); err != nil {
					return fmt.Errorf("{{.Name}}: %w", err)
				}
				aggregated = append(aggregated, pageResult.Results...)
				if len(pageResult.Results) < pageSize {
					break
				}
			}
			b, err := json.MarshalIndent(aggregated, "", "  ")
			if err != nil {
				return err
			}
{{- if .ListTableColumns }}
			b = platform.SelectTableColumns(b, []platform.TableColumn{
			{{- range .ListTableColumns }}
				{Field: {{printf "%q" .Field}}, Label: {{printf "%q" .Label}}},
			{{- end }}
			}, cliCtx.Output.Format())
{{- end }}
			return cliCtx.Output.PrintRaw(b)
{{- else }}
			if encoded := q.Encode(); encoded != "" {
				path += "?" + encoded
			}
{{- if .HasResult }}
			var result any
{{- end }}
{{- if .UsesMergePatch }}
			if err := cliCtx.PlatformSDKClient.Transport().DoWithContentType(cmd.Context(), {{methodConstant .Method}}, path, body, "application/merge-patch+json", {{statusConstant .SuccessCode}}, {{if .HasResult}}&result{{else}}nil{{end}}); err != nil {
				return fmt.Errorf("{{.Name}}: %w", err)
			}
{{- else if and .HasBody (eq .Method "POST") }}
			if err := cliCtx.PlatformSDKClient.Transport().DoWithContentType(cmd.Context(), {{methodConstant .Method}}, path, body, "application/json", {{statusConstant .SuccessCode}}, {{if .HasResult}}&result{{else}}nil{{end}}); err != nil {
				return fmt.Errorf("{{.Name}}: %w", err)
			}
{{- else }}
			if err := cliCtx.PlatformSDKClient.Transport().DoExpect(cmd.Context(), {{methodConstant .Method}}, path, body, {{statusConstant .SuccessCode}}, {{if .HasResult}}&result{{else}}nil{{end}}); err != nil {
				return fmt.Errorf("{{.Name}}: %w", err)
			}
{{- end }}
{{- if .HasResult }}
			if result == nil {
				return nil
			}
{{- if .ListArrayKey }}
			if obj, ok := result.(map[string]any); ok {
				if arr, ok := obj["{{.ListArrayKey}}"].([]any); ok {
					result = arr
				}
			}
{{- end }}
			b, err := json.MarshalIndent(result, "", "  ")
			if err != nil {
				return err
			}
{{- if .ListTableColumns }}
			b = platform.SelectTableColumns(b, []platform.TableColumn{
			{{- range .ListTableColumns }}
				{Field: {{printf "%q" .Field}}, Label: {{printf "%q" .Label}}},
			{{- end }}
			}, cliCtx.Output.Format())
{{- end }}
			return cliCtx.Output.PrintRaw(b)
{{- else }}
			return nil
{{- end }}
{{- end }}
		},
	}
{{- if .HasBody }}
	cmd.Flags().StringVar(&bodyFile, "file", "", "Path to JSON file containing the request body")
	cmd.Flags().StringArrayVar(&setFlags, "set", nil, "Override body values (key=value, repeatable, supports nested.keys)")
	cmd.Flags().BoolVar(&scaffoldFlag, "scaffold", false, "Print an example request body and exit")
{{- end }}
{{- if .IsDestructive }}
	cmd.Flags().BoolVar(&yes, "yes", false, "Skip confirmation prompt")
{{- end }}
{{- if .SupportsNameLookup }}
	cmd.Flags().StringVar(&nameFlag, "name", "", "Resolve target by name instead of ID (uses the resource list endpoint)")
{{- end }}
{{- range .QueryParams }}
{{- if eq .GoType "bool" }}
	cmd.Flags().BoolVar(&{{.Var}}, "{{.FlagName}}", false, {{printf "%q" .Description}})
{{- else if eq .GoType "int" }}
	cmd.Flags().IntVar(&{{.Var}}, "{{.FlagName}}", 0, {{printf "%q" .Description}})
{{- else if eq .GoType "[]string" }}
	cmd.Flags().StringArrayVar(&{{.Var}}, "{{.FlagName}}", nil, {{printf "%q" .Description}})
{{- else }}
	cmd.Flags().StringVar(&{{.Var}}, "{{.FlagName}}", "", {{printf "%q" .Description}})
{{- end }}
{{- if .Required }}
	_ = cmd.MarkFlagRequired("{{.FlagName}}")
{{- end }}
{{- end }}
	return cmd
}
{{ end }}
// guards against unused-import errors when no op uses path substitution,
// destructive confirmation, request bodies, JSON marshalling, or URL escaping
var (
	_ = strings.Replace
	_ = url.PathEscape
	_ = json.Marshal
	_ = http.MethodGet
	_ = strconv.Itoa
	_ = platform.ConfirmAction
	_ = platform.ReadBody
	_ = platform.ResolveIDByName
)
`
