// Copyright 2026, Jamf Software LLC

package classic

import (
	"fmt"
	"os"
	"path/filepath"
	"slices"
	"sort"
	"strings"
	"text/template"

	"github.com/iancoleman/strcase"
)

// CodegenHeader is the marker line at the top of every classic API generated file.
// Must match the first line of classicResourceTemplate and classicRegistryTemplate.
const CodegenHeader = "// Code generated by jamf-cli generator (classic). DO NOT EDIT."

// Generator generates Go command files from ClassicResource definitions.
type Generator struct {
	outputDir string
}

// NewGenerator creates a new Classic API code generator.
func NewGenerator(outputDir string) *Generator {
	return &Generator{outputDir: outputDir}
}

// Generate writes a Go command file for a single Classic API resource.
func (g *Generator) Generate(resource ClassicResource) (string, error) {
	tmpl, err := template.New("classic_resource").Funcs(templateFuncs()).Parse(classicResourceTemplate)
	if err != nil {
		return "", fmt.Errorf("parsing template: %w", err)
	}

	filename := fmt.Sprintf("classic_%s.go", strings.ReplaceAll(resource.CLIName, "-", "_"))
	// strip the leading "classic_classic_" that would result from cli_name already containing "classic-"
	filename = strings.Replace(filename, "classic_classic_", "classic_", 1)
	outPath := filepath.Join(g.outputDir, filename)

	f, err := os.Create(outPath)
	if err != nil {
		return "", fmt.Errorf("creating file: %w", err)
	}

	if err := tmpl.Execute(f, resource); err != nil {
		_ = f.Close()
		_ = os.Remove(outPath)
		return "", fmt.Errorf("executing template: %w", err)
	}

	_ = f.Close()
	return outPath, nil
}

// GenerateRegistry writes the classic_registry.go file that registers all Classic commands.
func (g *Generator) GenerateRegistry(resources []ClassicResource) (string, error) {
	tmpl, err := template.New("classic_registry").Funcs(templateFuncs()).Parse(classicRegistryTemplate)
	if err != nil {
		return "", fmt.Errorf("parsing template: %w", err)
	}

	outPath := filepath.Join(g.outputDir, "classic_registry.go")

	f, err := os.Create(outPath)
	if err != nil {
		return "", fmt.Errorf("creating file: %w", err)
	}

	sorted := make([]ClassicResource, len(resources))
	copy(sorted, resources)
	sort.Slice(sorted, func(i, j int) bool {
		return sorted[i].CLIName < sorted[j].CLIName
	})

	if err := tmpl.Execute(f, sorted); err != nil {
		_ = f.Close()
		_ = os.Remove(outPath)
		return "", fmt.Errorf("executing template: %w", err)
	}

	_ = f.Close()
	return outPath, nil
}

func templateFuncs() template.FuncMap {
	return template.FuncMap{
		"toCamel":      strcase.ToCamel,
		"toKebab":      strcase.ToKebab,
		"toLower":      strings.ToLower,
		"hasOp":        hasOp,
		"hasLookup":    hasLookup,
		"extraLookups": extraLookups,
		"classicExample": func(r ClassicResource, op string) string {
			bin := "jamf-cli"
			name := r.CLIName
			singular := r.Singular
			switch op {
			case "list":
				return fmt.Sprintf("  # List all %s\n  %s %s list\n\n  # List %s and extract IDs\n  %s %s list --field id",
					r.Name, bin, name, r.Name, bin, name)
			case "get":
				if r.HasLookup("name") {
					return fmt.Sprintf("  # Get a %s by ID\n  %s %s get 1\n\n  # Get a %s by name\n  %s %s get --name \"Example\"\n\n  # Get a %s and output as YAML\n  %s %s get 1 -o yaml",
						singular, bin, name, singular, bin, name, singular, bin, name)
				}
				return fmt.Sprintf("  # Get a %s by ID\n  %s %s get 1\n\n  # Get a %s and output as YAML\n  %s %s get 1 -o yaml",
					singular, bin, name, singular, bin, name)
			case "create":
				return fmt.Sprintf("  # Create a %s from XML\n  cat %s.xml | %s %s create",
					singular, singular, bin, name)
			case "update":
				return fmt.Sprintf("  # Update a %s from XML\n  cat %s.xml | %s %s update 1",
					singular, singular, bin, name)
			case "delete":
				if r.HasOperation("delete") && r.HasLookup("name") {
					return fmt.Sprintf("  # Delete a %s (with confirmation)\n  %s %s delete 1\n\n  # Delete by name\n  %s %s delete --name \"Example\" --yes\n\n  # Delete without confirmation prompt\n  %s %s delete 1 --yes",
						singular, bin, name, bin, name, bin, name)
				}
				return fmt.Sprintf("  # Delete a %s (with confirmation)\n  %s %s delete 1\n\n  # Delete without confirmation prompt\n  %s %s delete 1 --yes",
					singular, bin, name, bin, name)
			case "apply":
				return fmt.Sprintf("  # Apply a %s from an XML file\n  %s %s apply --from-file %s.xml\n\n  # Apply from stdin\n  cat %s.xml | %s %s apply\n\n  # Apply without replacement confirmation\n  %s %s apply --from-file %s.xml --yes",
					singular, bin, name, singular, singular, bin, name, bin, name, singular)
			default:
				return ""
			}
		},
		"lookupFlag": func(l string) string {
			return strcase.ToKebab(l)
		},
		"lookupCamel": func(l string) string {
			return strcase.ToCamel(l)
		},
		"needsIO": func(r ClassicResource) bool {
			// list and get use io.ReadAll for response unwrapping; create/update read from stdin
			return r.HasOperation("list") || r.HasOperation("get") || r.HasOperation("create") || r.HasOperation("update")
		},
		"idPath": func(r ClassicResource) string { return r.IDPath },
		"needsFmt": func(r ClassicResource) bool {
			return r.HasOperation("delete") || r.HasOperation("create") || r.HasOperation("update") || r.HasOperation("get")
		},
		"needsOS": func(r ClassicResource) bool {
			return r.HasOperation("create") || r.HasOperation("update") || r.HasOperation("delete")
		},
		"needsXMLConv": func(r ClassicResource) bool {
			return r.HasOperation("list") || r.HasOperation("get")
		},
		"needsScope": func(r ClassicResource) bool {
			return r.HasScope
		},
		"hasApply": func(r ClassicResource) bool {
			return r.HasOperation("create") && r.HasOperation("update") && r.HasLookup("name")
		},
		"needsBytes": func(r ClassicResource) bool {
			return (r.HasOperation("create") && r.HasOperation("update") && r.HasLookup("name")) ||
				(r.IsConfigProfile && r.HasOperation("update"))
		},
		"anyIsConfigProfile": func(resources []ClassicResource) bool {
			for _, r := range resources {
				if r.IsConfigProfile {
					return true
				}
			}
			return false
		},
		"hasDeleteByName": func(r ClassicResource) bool {
			return r.HasOperation("delete") && r.HasLookup("name")
		},
		"anyHasApply": func(resources []ClassicResource) bool {
			for _, r := range resources {
				if r.HasOperation("create") && r.HasOperation("update") && r.HasLookup("name") {
					return true
				}
			}
			return false
		},
		"anyNeedsClassicNameResolve": func(resources []ClassicResource) bool {
			for _, r := range resources {
				if r.HasLookup("name") && (r.HasOperation("delete") ||
					(r.HasOperation("create") && r.HasOperation("update"))) {
					return true
				}
			}
			return false
		},
		"anyClassicFileFields": func(resources []ClassicResource) bool {
			for _, r := range resources {
				if len(r.FileFields) > 0 {
					return true
				}
			}
			return false
		},
		"hasFetchMergePut": func(r ClassicResource) bool {
			for _, ff := range r.FileFields {
				if ff.FetchMergePut {
					return true
				}
			}
			return false
		},
		"parentPathLiteral": func(path string) string {
			parts := strings.Split(path, "/")
			out := "[]string{"
			for i, p := range parts[:len(parts)-1] {
				if i > 0 {
					out += ", "
				}
				out += "\"" + p + "\""
			}
			out += "}"
			return out
		},
		"leafName": func(path string) string {
			parts := strings.Split(path, "/")
			return parts[len(parts)-1]
		},
	}
}

func hasOp(ops []string, target string) bool {
	return slices.Contains(ops, target)
}

func hasLookup(lookups []string, target string) bool {
	return slices.Contains(lookups, target)
}

func extraLookups(lookups []string) []string {
	var extra []string
	for _, l := range lookups {
		if l != "id" {
			extra = append(extra, l)
		}
	}
	return extra
}

// classicResourceTemplate generates a single Go file per Classic API resource.
const classicResourceTemplate = `// Copyright 2026, Jamf Software LLC
// Code generated by jamf-cli generator (classic). DO NOT EDIT.
package generated

import (
{{- if needsBytes . }}
	"bytes"
{{- end }}
{{- if or (hasOp .Operations "list") (hasOp .Operations "get") }}
	"encoding/json"
{{- end }}
{{- if needsFmt . }}
	"fmt"
{{- end }}
{{- if needsIO . }}
	"io"
{{- end }}
{{- if hasOp .Operations "delete" }}
	"net/http"
{{- end }}
{{- if or (hasOp .Operations "get") (hasOp .Operations "update") (hasOp .Operations "delete") (hasApply .) }}
	"net/url"
{{- end }}
{{- if needsOS . }}
	"os"
{{- end }}

	"github.com/spf13/cobra"

{{- if hasOp .Operations "delete" }}
	"github.com/Jamf-Concepts/jamf-cli/internal/cooldown"
{{- end }}
	"github.com/Jamf-Concepts/jamf-cli/internal/registry"
{{- if needsXMLConv . }}
	"github.com/Jamf-Concepts/jamf-cli/internal/xmlconv"
{{- end }}
{{- if needsScope . }}
	"github.com/Jamf-Concepts/jamf-cli/internal/scope"
{{- end }}
)

// New{{ .GoName }}Cmd creates the {{ .CLIName }} command group
func New{{ .GoName }}Cmd(ctx *registry.CLIContext) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "{{ .CLIName }}",
		Short: "{{ .Description }} (Classic API)",
		Long:  ` + "`" + `Manage {{ .Description | toLower }} via the Jamf Pro Classic API (/JSSResource/).` + "`" + `,
	}
{{ if hasOp .Operations "list" }}
	cmd.AddCommand(new{{ .GoName }}ListCmd(ctx))
{{- end }}
{{ if hasOp .Operations "get" }}
	cmd.AddCommand(new{{ .GoName }}GetCmd(ctx))
{{- end }}
{{ if hasOp .Operations "create" }}
	cmd.AddCommand(new{{ .GoName }}CreateCmd(ctx))
{{- end }}
{{ if hasOp .Operations "update" }}
	cmd.AddCommand(new{{ .GoName }}UpdateCmd(ctx))
{{- end }}
{{ if hasOp .Operations "delete" }}
	cmd.AddCommand(new{{ .GoName }}DeleteCmd(ctx))
{{- end }}
{{ if hasApply . }}
	cmd.AddCommand(new{{ .GoName }}ApplyCmd(ctx))
{{- end }}
{{ if needsScope . }}
	cmd.AddCommand(scope.NewScopeCmd(ctx, scope.Resource{
		APIPath:     "{{ .Path }}",
		SingularKey: "{{ .Singular }}",
	}))
{{- end }}

	return cmd
}
{{ if hasOp .Operations "list" }}
func new{{ .GoName }}ListCmd(ctx *registry.CLIContext) *cobra.Command {
	return &cobra.Command{
		Use:   "list",
		Short: "List all {{ .Name }}",
		Example: ` + "`" + `{{ classicExample . "list" }}` + "`" + `,
		RunE: func(cmd *cobra.Command, args []string) error {
			reqCtx := cmd.Context()
			resp, err := ctx.Client.Do(reqCtx, "GET", "/JSSResource/{{ .Path }}", nil)
			if err != nil {
				return err
			}
			defer resp.Body.Close()

			// Classic API returns XML list responses.
			body, err := io.ReadAll(resp.Body)
			if err != nil {
				return err
			}
			// Default to pretty-printed XML; use -o json/yaml/table/csv for structured output.
			// -o xml = pretty-printed XML, -o raw = exact wire bytes.
			if (!cmd.Flags().Changed("output") && !cmd.Flags().Changed("field") && ctx.Output.Format() == "json") || ctx.Output.Format() == "xml" || ctx.Output.Format() == "raw" {
				return ctx.Output.PrintBytes(body)
			}
			if xmlconv.IsXML(body) {
				items, err := xmlconv.ExtractListItems(body)
				if err == nil {
					jsonItems, err := json.Marshal(items)
					if err == nil {
						return ctx.Output.PrintRaw(jsonItems)
					}
				}
				return ctx.Output.PrintRaw(body)
			}
			// JSON fallback
			var wrapper map[string]json.RawMessage
			if err := json.Unmarshal(body, &wrapper); err == nil {
				if inner, ok := wrapper["{{ .Name }}"]; ok {
					return ctx.Output.PrintRaw(inner)
				}
			}
			return ctx.Output.PrintRaw(body)
		},
	}
}
{{ end }}
{{ if hasOp .Operations "get" }}
func new{{ .GoName }}GetCmd(ctx *registry.CLIContext) *cobra.Command {
{{ if extraLookups .Lookups }}	var (
{{ range extraLookups .Lookups }}		flag{{ lookupCamel . }} string
{{ end }}	)
{{ end }}
	cmd := &cobra.Command{
{{ if extraLookups .Lookups }}		Use:   "get [<id>]",
{{ else }}		Use:   "get <id>",
{{ end }}		Short: "Get a {{ .Singular }} by ID",
		Example: ` + "`" + `{{ classicExample . "get" }}` + "`" + `,
{{ if extraLookups .Lookups }}		Args:  cobra.MaximumNArgs(1),
{{ else }}		Args:  cobra.ExactArgs(1),
{{ end }}		RunE: func(cmd *cobra.Command, args []string) error {
			reqCtx := cmd.Context()
{{ if extraLookups .Lookups }}
			// Resolve lookup: check flags first, then positional ID
			var path string
{{ range extraLookups .Lookups }}			if flag{{ lookupCamel . }} != "" {
				path = fmt.Sprintf("/JSSResource/{{ $.Path }}/{{ . }}/%s", url.PathEscape(flag{{ lookupCamel . }}))
			} else {{ end }}if len(args) > 0 {
				path = fmt.Sprintf("/JSSResource/{{ .Path }}/{{ idPath . }}/%s", url.PathEscape(args[0]))
			} else {
				return fmt.Errorf("provide an <id> argument{{ range extraLookups .Lookups }}, --{{ lookupFlag . }}{{ end }}")
			}
{{ else }}			path := fmt.Sprintf("/JSSResource/{{ .Path }}/{{ idPath . }}/%s", url.PathEscape(args[0]))
{{ end }}
			resp, err := ctx.Client.Do(reqCtx, "GET", path, nil)
			if err != nil {
				return err
			}
			defer resp.Body.Close()

			// Classic API returns XML; pass through by default.
			body, err := io.ReadAll(resp.Body)
			if err != nil {
				return err
			}
			// Default to pretty-printed XML; use -o json/yaml/table/csv for structured output.
			// -o xml = pretty-printed XML, -o raw = exact wire bytes.
			if (!cmd.Flags().Changed("output") && !cmd.Flags().Changed("field") && ctx.Output.Format() == "json") || ctx.Output.Format() == "xml" || ctx.Output.Format() == "raw" {
				return ctx.Output.PrintBytes(body)
			}
			if xmlconv.IsXML(body) {
				if jsonBody, err := xmlconv.ToJSON(body); err == nil {
					body = jsonBody
				}
			}
			var wrapper map[string]json.RawMessage
			if err := json.Unmarshal(body, &wrapper); err == nil {
				if inner, ok := wrapper["{{ .Singular }}"]; ok {
					return ctx.Output.PrintRaw(inner)
				}
			}
			return ctx.Output.PrintRaw(body)
		},
	}
{{ if extraLookups .Lookups }}
{{ range extraLookups .Lookups }}	cmd.Flags().StringVar(&flag{{ lookupCamel . }}, "{{ lookupFlag . }}", "", "Look up {{ $.Singular }} by {{ . }}")
{{ end }}{{ end }}
	return cmd
}
{{ end }}
{{ if hasOp .Operations "create" }}
func new{{ .GoName }}CreateCmd(ctx *registry.CLIContext) *cobra.Command {
{{ if .FileFields }}	var (
{{ range .FileFields }}		flag{{ lookupCamel .Flag }} string
{{ end }}	)
{{ end }}	cmd := &cobra.Command{
		Use:   "create",
		Short: "Create a {{ .Singular }}",
		Long:  "Create a new {{ .Singular }}. Reads XML body from stdin.",
		Example: ` + "`" + `{{ classicExample . "create" }}` + "`" + `,
		RunE: func(cmd *cobra.Command, args []string) error {
			reqCtx := cmd.Context()

{{ if .FileFields }}
			var bodyBytes []byte
			stat, _ := os.Stdin.Stat()
			if (stat.Mode() & os.ModeCharDevice) == 0 {
				var err error
				bodyBytes, err = io.ReadAll(os.Stdin)
				if err != nil {
					return fmt.Errorf("reading input: %w", err)
				}
			}
			anyFileFlag := {{ range $i, $ff := .FileFields }}{{ if $i }} || {{ end }}flag{{ lookupCamel $ff.Flag }} != ""{{ end }}
			if len(bodyBytes) == 0 && !anyFileFlag {
				return fmt.Errorf("request body required on stdin (pipe XML input) or supply --{{ (index .FileFields 0).Flag }}")
			}
			bodyBytes, err := injectClassicFileFields(bodyBytes, "{{ .Singular }}", []classicFileFieldSpec{
{{ range .FileFields }}				{FilePath: flag{{ lookupCamel .Flag }}, ParentPath: {{ parentPathLiteral .XMLPath }}, LeafName: "{{ leafName .XMLPath }}", Encoding: "{{ .Encoding }}", NameFallback: "{{ .NameFallback }}"},
{{ end }}			})
			if err != nil {
				return err
			}
			resp, err := ctx.Client.Do(reqCtx, "POST", "/JSSResource/{{ .Path }}/{{ idPath . }}/0", bytes.NewReader(bodyBytes))
{{ else }}
			var body io.Reader
			stat, _ := os.Stdin.Stat()
			if (stat.Mode() & os.ModeCharDevice) == 0 {
				body = os.Stdin
			} else {
				return fmt.Errorf("request body required on stdin (pipe XML input)")
			}

			resp, err := ctx.Client.Do(reqCtx, "POST", "/JSSResource/{{ .Path }}/{{ idPath . }}/0", body)
{{ end }}
			if err != nil {
				return err
			}
			defer resp.Body.Close()

			return ctx.Output.PrintResponse(resp)
		},
	}
{{ if .FileFields }}
{{ range .FileFields }}	cmd.Flags().StringVar(&flag{{ lookupCamel .Flag }}, "{{ .Flag }}", "", "{{ .Desc }}")
{{ end }}{{ end }}	return cmd
}
{{ end }}
{{ if hasOp .Operations "update" }}
func new{{ .GoName }}UpdateCmd(ctx *registry.CLIContext) *cobra.Command {
{{ if hasLookup .Lookups "name" }}	var flagName string
{{ end }}{{ if .FileFields }}	var (
{{ range .FileFields }}		flag{{ lookupCamel .Flag }} string
{{ end }}	)
{{ end }}
	cmd := &cobra.Command{
{{ if hasLookup .Lookups "name" }}		Use:   "update [<id>]",
{{ else }}		Use:   "update <id>",
{{ end }}		Short: "Update a {{ .Singular }}",
		Long:  "Update an existing {{ .Singular }} by ID. Reads XML body from stdin.",
		Example: ` + "`" + `{{ classicExample . "update" }}` + "`" + `,
{{ if hasLookup .Lookups "name" }}		Args:  cobra.MaximumNArgs(1),
{{ else }}		Args:  cobra.ExactArgs(1),
{{ end }}		RunE: func(cmd *cobra.Command, args []string) error {
			reqCtx := cmd.Context()

{{ if or .IsConfigProfile .FileFields }}
			var bodyBytes []byte
			stat, _ := os.Stdin.Stat()
			if (stat.Mode() & os.ModeCharDevice) == 0 {
				var err error
				bodyBytes, err = io.ReadAll(os.Stdin)
				if err != nil {
					return fmt.Errorf("reading input: %w", err)
				}
			}
{{ if .FileFields }}
			anyFileFlag := {{ range $i, $ff := .FileFields }}{{ if $i }} || {{ end }}flag{{ lookupCamel $ff.Flag }} != ""{{ end }}
			if len(bodyBytes) == 0 && !anyFileFlag {
				return fmt.Errorf("request body required on stdin (pipe XML input) or supply --{{ (index .FileFields 0).Flag }}")
			}
{{ else }}
			if len(bodyBytes) == 0 {
				return fmt.Errorf("request body required on stdin (pipe XML input)")
			}
{{ end }}

			// Resolve ID and preserve PayloadUUID/PayloadIdentifier.
			var resolvedID string
{{ if .IsConfigProfile }}			var existingPayload []byte
{{ end }}{{ if hasFetchMergePut . }}			var existingBody []byte
{{ end }}{{ if hasLookup .Lookups "name" }}
			if flagName != "" {
{{ if hasFetchMergePut . }}
				id, body, ferr := fetchClassicFullXMLByName(reqCtx, ctx.Client, "{{ .Path }}", flagName)
				if ferr != nil || id == "" {
					return fmt.Errorf("no {{ .Singular }} found with name %q", flagName)
				}
				resolvedID = id
				existingBody = body
{{ else }}
				resolvedID, existingPayload = fetchClassicProfileByName(reqCtx, ctx.Client, "{{ .Path }}", flagName)
				if resolvedID == "" {
					return fmt.Errorf("no {{ .Singular }} found with name %q", flagName)
				}
{{ end }}
			} else if len(args) > 0 {
				resolvedID = args[0]
{{ if hasFetchMergePut . }}
				path := fmt.Sprintf("/JSSResource/{{ .Path }}/{{ idPath . }}/%s", url.PathEscape(resolvedID))
				respX, ferr := ctx.Client.Do(reqCtx, "GET", path, nil)
				if ferr != nil {
					return fmt.Errorf("fetching existing {{ .Singular }}: %w", ferr)
				}
				var readErr error
				existingBody, readErr = io.ReadAll(respX.Body)
				_ = respX.Body.Close()
				if readErr != nil {
					return fmt.Errorf("reading existing {{ .Singular }}: %w", readErr)
				}
				if respX.StatusCode >= 400 {
					return fmt.Errorf("fetching existing {{ .Singular }}: GET %s returned %d: %s", path, respX.StatusCode, string(existingBody))
				}
{{ else }}
				existingPayload = fetchClassicProfilePayloadPlist(reqCtx, ctx.Client, "{{ .Path }}", resolvedID)
{{ end }}
			} else {
				return fmt.Errorf("provide an <id> argument or --name")
			}
{{ else }}
			if len(args) > 0 {
				resolvedID = args[0]
{{ if hasFetchMergePut . }}
				path := fmt.Sprintf("/JSSResource/{{ .Path }}/{{ idPath . }}/%s", url.PathEscape(resolvedID))
				respX, ferr := ctx.Client.Do(reqCtx, "GET", path, nil)
				if ferr != nil {
					return fmt.Errorf("fetching existing {{ .Singular }}: %w", ferr)
				}
				var readErr error
				existingBody, readErr = io.ReadAll(respX.Body)
				_ = respX.Body.Close()
				if readErr != nil {
					return fmt.Errorf("reading existing {{ .Singular }}: %w", readErr)
				}
				if respX.StatusCode >= 400 {
					return fmt.Errorf("fetching existing {{ .Singular }}: GET %s returned %d: %s", path, respX.StatusCode, string(existingBody))
				}
{{ else }}
				existingPayload = fetchClassicProfilePayloadPlist(reqCtx, ctx.Client, "{{ .Path }}", resolvedID)
{{ end }}
			} else {
				return fmt.Errorf("provide an <id> argument")
			}
{{ end }}

{{ if hasFetchMergePut . }}
			// Fetch-merge-put: start from the existing record, overlay file field.
			if len(existingBody) == 0 {
				return fmt.Errorf("could not fetch existing {{ .Singular }} for merge-put")
			}
			bodyBytes = existingBody
{{ end }}

{{ if .FileFields }}
			var injErr error
			bodyBytes, injErr = injectClassicFileFields(bodyBytes, "{{ .Singular }}", []classicFileFieldSpec{
{{ range .FileFields }}				{FilePath: flag{{ lookupCamel .Flag }}, ParentPath: {{ parentPathLiteral .XMLPath }}, LeafName: "{{ leafName .XMLPath }}", Encoding: "{{ .Encoding }}", NameFallback: "{{ .NameFallback }}"},
{{ end }}			})
			if injErr != nil {
				return injErr
			}
{{ end }}
{{ if .IsConfigProfile }}
			bodyBytes = injectClassicProfilePayloadUUIDs(bodyBytes, existingPayload)
{{ end }}

			path := fmt.Sprintf("/JSSResource/{{ .Path }}/{{ idPath . }}/%s", url.PathEscape(resolvedID))
			resp, err := ctx.Client.Do(reqCtx, "PUT", path, bytes.NewReader(bodyBytes))
{{ else }}
			var body io.Reader
			stat, _ := os.Stdin.Stat()
			if (stat.Mode() & os.ModeCharDevice) == 0 {
				body = os.Stdin
			} else {
				return fmt.Errorf("request body required on stdin (pipe XML input)")
			}

{{ if hasLookup .Lookups "name" }}
			var path string
			if flagName != "" {
				path = fmt.Sprintf("/JSSResource/{{ .Path }}/name/%s", url.PathEscape(flagName))
			} else if len(args) > 0 {
				path = fmt.Sprintf("/JSSResource/{{ .Path }}/{{ idPath . }}/%s", url.PathEscape(args[0]))
			} else {
				return fmt.Errorf("provide an <id> argument or --name")
			}
{{ else }}			path := fmt.Sprintf("/JSSResource/{{ .Path }}/{{ idPath . }}/%s", url.PathEscape(args[0]))
{{ end }}
			resp, err := ctx.Client.Do(reqCtx, "PUT", path, body)
{{- end }}
			if err != nil {
				return err
			}
			defer resp.Body.Close()

			return ctx.Output.PrintResponse(resp)
		},
	}

{{ if hasLookup .Lookups "name" }}	cmd.Flags().StringVar(&flagName, "name", "", "Look up {{ .Singular }} by name")
{{ end }}
{{ if .FileFields }}
{{ range .FileFields }}	cmd.Flags().StringVar(&flag{{ lookupCamel .Flag }}, "{{ .Flag }}", "", "{{ .Desc }}")
{{ end }}{{ end }}	return cmd
}
{{ end }}
{{ if hasOp .Operations "delete" }}
func new{{ .GoName }}DeleteCmd(ctx *registry.CLIContext) *cobra.Command {
	var (
		flagYes    bool
		flagDryRun bool
{{ if hasDeleteByName . }}		flagName   string
{{ end }}	)

	cmd := &cobra.Command{
{{ if hasDeleteByName . }}		Use:   "delete [<id>]",
{{ else }}		Use:   "delete <id>",
{{ end }}		Short: "Delete a {{ .Singular }}",
		Example: ` + "`" + `{{ classicExample . "delete" }}` + "`" + `,
{{ if hasDeleteByName . }}		Args:  cobra.MaximumNArgs(1),
{{ else }}		Args:  cobra.ExactArgs(1),
{{ end }}		RunE: func(cmd *cobra.Command, args []string) error {
			reqCtx := cmd.Context()
{{ if hasDeleteByName . }}
			// Resolve ID from --name or positional arg
			var resolvedID string
			noInput, _ := cmd.Flags().GetBool("no-input")
			if flagName != "" {
				id, err := resolveClassicNameToIDForApply(reqCtx, ctx.Client, "{{ .Path }}", "{{ .Name }}", flagName, noInput)
				if err != nil {
					return err
				}
				if id == "" {
					return fmt.Errorf("no {{ .Singular }} found with name %q", flagName)
				}
				resolvedID = id
			} else if len(args) > 0 {
				resolvedID = args[0]
			} else {
				return fmt.Errorf("provide an <id> argument or --name")
			}

			if flagDryRun {
				fmt.Fprintf(os.Stderr, "[dry-run] Would delete {{ .Singular }} %s\n", resolvedID)
				return nil
			}
			if !flagYes {
				if noInput {
					return fmt.Errorf("destructive operation requires --yes when --no-input is set")
				}
				fmt.Fprintf(os.Stderr, "This will delete {{ .Singular }} %s. Type 'yes' to confirm: ", resolvedID)
				var confirm string
				fmt.Scanln(&confirm)
				if confirm != "yes" {
					return fmt.Errorf("aborted")
				}
			}

			if err := cooldown.Enforce(ctx.ProfileName, noInput, ctx.DestructiveCooldown); err != nil {
				return err
			}
			path := fmt.Sprintf("/JSSResource/{{ .Path }}/{{ idPath . }}/%s", url.PathEscape(resolvedID))
{{ else }}
			if flagDryRun {
				fmt.Fprintf(os.Stderr, "Would delete {{ .Singular }} %s\n", args[0])
				return nil
			}
			if !flagYes {
				noInput, _ := cmd.Flags().GetBool("no-input")
				if noInput {
					return fmt.Errorf("destructive operation requires --yes when --no-input is set")
				}
				fmt.Fprintf(os.Stderr, "This will delete {{ .Singular }} %s. Type 'yes' to confirm: ", args[0])
				var confirm string
				fmt.Scanln(&confirm)
				if confirm != "yes" {
					return fmt.Errorf("aborted")
				}
			}

			noInputForCooldown, _ := cmd.Flags().GetBool("no-input")
			if err := cooldown.Enforce(ctx.ProfileName, noInputForCooldown, ctx.DestructiveCooldown); err != nil {
				return err
			}
			path := fmt.Sprintf("/JSSResource/{{ .Path }}/{{ idPath . }}/%s", url.PathEscape(args[0]))
{{ end }}
			resp, err := ctx.Client.Do(reqCtx, "DELETE", path, nil)
			if err != nil {
				return err
			}
			defer resp.Body.Close()

			if resp.StatusCode == http.StatusNoContent || resp.StatusCode == http.StatusOK {
				cooldown.Record(ctx.ProfileName)
				fmt.Fprintln(os.Stderr, "Deleted successfully")
				return nil
			}

			return ctx.Output.PrintResponse(resp)
		},
	}

	cmd.Flags().BoolVar(&flagYes, "yes", false, "Skip confirmation prompt")
	cmd.Flags().BoolVarP(&flagDryRun, "dry-run", "n", false, "Preview without executing")
{{ if hasDeleteByName . }}	cmd.Flags().StringVar(&flagName, "name", "", "Look up {{ .Singular }} by name")
{{ end }}
	return cmd
}
{{ end }}
{{ if hasApply . }}
func new{{ .GoName }}ApplyCmd(ctx *registry.CLIContext) *cobra.Command {
	var (
		fromFile   string
		flagYes    bool
		flagDryRun bool
{{ if hasFetchMergePut . }}		flagName   string
{{ end }}{{ if .FileFields }}{{ range .FileFields }}		flag{{ lookupCamel .Flag }} string
{{ end }}{{ end }}	)

	cmd := &cobra.Command{
		Use:   "apply",
		Short: "Create or replace a {{ .Singular }} by name",
		Long: ` + "`" + `Create or replace a {{ .Singular }}. Reads XML from --from-file or stdin.

The name field in the input XML is used to check if the resource already
exists. If it does, the resource is replaced (with confirmation).
If not, a new resource is created.` + "`" + `,
		Example: ` + "`" + `{{ classicExample . "apply" }}` + "`" + `,
		RunE: func(cmd *cobra.Command, _ []string) error {
			reqCtx := cmd.Context()

			// Read input
			data, err := readApplyInput(fromFile)
{{ if .FileFields }}
			anyFileFlag := {{ range $i, $ff := .FileFields }}{{ if $i }} || {{ end }}flag{{ lookupCamel $ff.Flag }} != ""{{ end }}
			if err != nil && !anyFileFlag {
				return err
			}
			err = nil
{{ else }}
			if err != nil {
				return err
			}
{{ end }}
{{ if .FileFields }}
			// Inject file fields before name extraction so name-fallback (if any)
			// can populate <general><name> for lookup.
			data, err = injectClassicFileFields(data, "{{ .Singular }}", []classicFileFieldSpec{
{{ range .FileFields }}				{FilePath: flag{{ lookupCamel .Flag }}, ParentPath: {{ parentPathLiteral .XMLPath }}, LeafName: "{{ leafName .XMLPath }}", Encoding: "{{ .Encoding }}", NameFallback: "{{ .NameFallback }}"},
{{ end }}			})
			if err != nil {
				return err
			}
{{ end }}

			// Extract name: for fetch-merge-put resources, --name is the primary
			// input (body typically empty); fall back to XML name if flag absent.
			var name string
{{ if hasFetchMergePut . }}
			if flagName != "" {
				name = flagName
			} else {
				name, err = extractClassicName(data, "{{ .Singular }}")
				if err != nil {
					return fmt.Errorf("--name is required when input body is empty: %w", err)
				}
			}
{{ else }}
			name, err = extractClassicName(data, "{{ .Singular }}")
			if err != nil {
				return err
			}
{{ end }}

			// Check if resource exists by name (read-only, runs even in dry-run)
			noInput, _ := cmd.Flags().GetBool("no-input")
			id, err := resolveClassicNameToIDForApply(reqCtx, ctx.Client, "{{ .Path }}", "{{ .Name }}", name, noInput)
			if err != nil {
				return err
			}

			if id == "" {
				// Not found — create (not allowed for fetch-merge-put resources)
{{ if hasFetchMergePut . }}
				return fmt.Errorf("no {{ .Singular }} found with name %q — this resource must already exist (apply is fetch-merge-put only)", name)
{{ else }}
				if flagDryRun {
					fmt.Fprintf(os.Stderr, "[dry-run] Would create {{ .Singular }} %q\n", name)
					return nil
				}
				resp, err := ctx.Client.Do(reqCtx, "POST", "/JSSResource/{{ .Path }}/{{ idPath . }}/0", bytes.NewReader(data))
				if err != nil {
					return err
				}
				defer resp.Body.Close()
				fmt.Fprintf(os.Stderr, "Created {{ .Singular }} %q\n", name)
				return ctx.Output.PrintResponse(resp)
{{ end }}
			}

			// Found — replace
			if flagDryRun {
				fmt.Fprintf(os.Stderr, "[dry-run] Would replace {{ .Singular }} %q (id: %s)\n", name, id)
				return nil
			}
			if !flagYes {
				if noInput {
					return fmt.Errorf("{{ .Singular }} %q already exists (id: %s); use --yes to replace when --no-input is set", name, id)
				}
				fmt.Fprintf(os.Stderr, "{{ .Singular }} %q already exists (id: %s) and will be replaced. Type 'yes' to confirm: ", name, id)
				var confirm string
				fmt.Scanln(&confirm)
				if confirm != "yes" {
					return fmt.Errorf("aborted")
				}
			}

{{ if hasFetchMergePut . }}
			// Fetch the existing full record and overlay the file field(s) — the
			// user's input (if any) is ignored beyond name resolution; AppConfig
			// injection preserves every other field on the record.
			_, fullBody, ferr := fetchClassicFullXMLByName(reqCtx, ctx.Client, "{{ .Path }}", name)
			if ferr != nil || len(fullBody) == 0 {
				return fmt.Errorf("fetching existing {{ .Singular }} for merge-put: %w", ferr)
			}
			data = fullBody
			data, err = injectClassicFileFields(data, "{{ .Singular }}", []classicFileFieldSpec{
{{ range .FileFields }}				{FilePath: flag{{ lookupCamel .Flag }}, ParentPath: {{ parentPathLiteral .XMLPath }}, LeafName: "{{ leafName .XMLPath }}", Encoding: "{{ .Encoding }}", NameFallback: "{{ .NameFallback }}"},
{{ end }}			})
			if err != nil {
				return err
			}
{{ end }}
{{ if .IsConfigProfile }}
			// Preserve existing PayloadUUID and PayloadIdentifier.
			existingPayload := fetchClassicProfilePayloadPlist(reqCtx, ctx.Client, "{{ .Path }}", id)
			data = injectClassicProfilePayloadUUIDs(data, existingPayload)
{{ end }}
			updatePath := fmt.Sprintf("/JSSResource/{{ .Path }}/{{ idPath . }}/%s", url.PathEscape(id))
			resp, err := ctx.Client.Do(reqCtx, "PUT", updatePath, bytes.NewReader(data))
			if err != nil {
				return err
			}
			defer resp.Body.Close()
			fmt.Fprintf(os.Stderr, "Replaced {{ .Singular }} %q (id: %s)\n", name, id)
			return ctx.Output.PrintResponse(resp)
		},
	}

	cmd.Flags().StringVar(&fromFile, "from-file", "", "Path to XML input file (or pipe XML to stdin)")
	cmd.Flags().BoolVar(&flagYes, "yes", false, "Skip confirmation prompt when replacing")
	cmd.Flags().BoolVarP(&flagDryRun, "dry-run", "n", false, "Preview without executing")
{{ if hasFetchMergePut . }}	cmd.Flags().StringVar(&flagName, "name", "", "Name of the existing {{ .Singular }} to update (required when body is empty)")
{{ end }}{{ if .FileFields }}
{{ range .FileFields }}	cmd.Flags().StringVar(&flag{{ lookupCamel .Flag }}, "{{ .Flag }}", "", "{{ .Desc }}")
{{ end }}{{ end }}
	return cmd
}
{{ end }}
`

const classicRegistryTemplate = `// Copyright 2026, Jamf Software LLC
// Code generated by jamf-cli generator (classic). DO NOT EDIT.
package generated

import (
{{- if or (anyNeedsClassicNameResolve .) (anyClassicFileFields .) }}
	"context"
	"encoding/json"
	"encoding/xml"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"strings"
{{- end }}
{{- if or (anyIsConfigProfile .) (anyClassicFileFields .) }}
	"bytes"
	"net/url"
{{- end }}

	"github.com/spf13/cobra"

	"github.com/Jamf-Concepts/jamf-cli/internal/registry"
{{- if or (anyNeedsClassicNameResolve .) (anyClassicFileFields .) }}
	"github.com/Jamf-Concepts/jamf-cli/internal/xmlconv"
{{- end }}
{{- if anyIsConfigProfile . }}
	"github.com/Jamf-Concepts/jamf-cli/internal/profileconvert"
{{- end }}
)

// RegisterClassicCommands registers all Classic API resource commands.
func RegisterClassicCommands(root *cobra.Command, ctx *registry.CLIContext) {
{{- range . }}
	root.AddCommand(New{{ .GoName }}Cmd(ctx))
{{- end }}
}
{{ if anyNeedsClassicNameResolve . }}
// Classic apply/delete-by-name helpers. These share the generated package with
// registry.go and depend on readApplyInput and extractIDString defined there.

// extractClassicName extracts the resource name from XML input.
// It tries direct-child "name" first, then checks under common sub-elements
// like "general". The singularKey is the XML wrapper element (e.g., "policy").
func extractClassicName(data []byte, singularKey string) (string, error) {
	m, err := xmlconv.ToMap(data)
	if err != nil {
		return "", fmt.Errorf("parsing XML: %w", err)
	}

	// Unwrap the root element if it matches the singular key
	inner, ok := m[singularKey]
	if !ok {
		// Try without wrapper (user may omit it)
		inner = m
	}

	obj, ok := inner.(map[string]any)
	if !ok {
		return "", fmt.Errorf("unexpected XML structure")
	}

	// Direct name field
	if name, ok := obj["name"].(string); ok && name != "" {
		return name, nil
	}

	// Check under "general" sub-element (policies, profiles, etc.)
	if general, ok := obj["general"].(map[string]any); ok {
		if name, ok := general["name"].(string); ok && name != "" {
			return name, nil
		}
	}

	return "", fmt.Errorf("could not find 'name' field in XML input")
}

// resolveClassicNameToIDForApply looks up a classic resource by name using
// the list endpoint. Returns all matching IDs for collision detection.
// Returns ("", nil) when no resource is found (caller should create).
// Returns (id, nil) when exactly one match is found.
// Returns ("", error) when multiple matches or lookup fails.
func resolveClassicNameToIDForApply(ctx context.Context, client registry.HTTPClient, apiPath, wrapperKey, name string, noInput bool) (string, error) {
	resp, err := client.Do(ctx, "GET", "/JSSResource/"+apiPath, nil)
	if err != nil {
		return "", fmt.Errorf("listing resources: %w", err)
	}
	defer func() { _ = resp.Body.Close() }()

	body, err := io.ReadAll(resp.Body)
	if err != nil {
		return "", fmt.Errorf("reading list response: %w", err)
	}

	var items []map[string]any
	if xmlconv.IsXML(body) {
		items, err = xmlconv.ExtractListItems(body)
		if err != nil {
			return "", fmt.Errorf("parsing XML list: %w", err)
		}
	} else {
		// JSON fallback
		var wrapper map[string]json.RawMessage
		if err := json.Unmarshal(body, &wrapper); err == nil {
			if inner, ok := wrapper[wrapperKey]; ok {
				_ = json.Unmarshal(inner, &items)
			}
		}
	}

	// Filter by exact name match
	type classicMatch struct {
		id string
	}
	var matches []classicMatch
	for _, item := range items {
		itemName, _ := item["name"].(string)
		if itemName == name {
			if id := extractIDString(item, "id"); id != "" {
				matches = append(matches, classicMatch{id: id})
			}
		}
	}

	if len(matches) == 0 {
		return "", nil
	}
	if len(matches) == 1 {
		return matches[0].id, nil
	}

	// Collision: multiple resources with the same name
	if noInput {
		ids := make([]string, len(matches))
		for i, m := range matches {
			ids[i] = m.id
		}
		return "", fmt.Errorf("multiple resources found with name %q (IDs: %s); resolve duplicates or use update with a specific ID", name, strings.Join(ids, ", "))
	}

	// Interactive: prompt user to pick
	fmt.Fprintf(os.Stderr, "Multiple resources found with name %q:\n", name)
	for i, m := range matches {
		fmt.Fprintf(os.Stderr, "  [%d] ID: %s\n", i+1, m.id)
	}
	fmt.Fprintf(os.Stderr, "Enter number to replace (or 0 to cancel): ")
	var choice int
	if _, err := fmt.Fscan(os.Stdin, &choice); err != nil || choice < 1 || choice > len(matches) {
		return "", fmt.Errorf("aborted")
	}
	return matches[choice-1].id, nil
}
{{ end }}
{{ if anyIsConfigProfile . }}
// fetchClassicProfileByName fetches a Classic config profile by name and returns
// its numeric ID and existing payload plist in a single API call. Returns ("", nil)
// when not found; callers should proceed without UUID injection if payload is nil.
//
// Errors (including non-404 server errors) are silently swallowed — UUID
// preservation is best-effort and must never block an update.
func fetchClassicProfileByName(ctx context.Context, client registry.HTTPClient, apiPath, name string) (id string, payloadPlist []byte) {
	path := fmt.Sprintf("/JSSResource/%s/name/%s", apiPath, url.PathEscape(name))
	resp, err := client.Do(ctx, "GET", path, nil)
	if err != nil {
		return "", nil
	}
	defer func() { _ = resp.Body.Close() }()

	body, err := io.ReadAll(resp.Body)
	if err != nil {
		return "", nil
	}

	if !xmlconv.IsXML(body) {
		return "", nil
	}

	m, err := xmlconv.ToMap(body)
	if err != nil {
		return "", nil
	}

	for _, rootVal := range m {
		if root, ok := rootVal.(map[string]any); ok {
			if general, ok := root["general"].(map[string]any); ok {
				id = extractIDString(general, "id")
				if payloads, ok := general["payloads"].(string); ok {
					payloadPlist = []byte(payloads)
				}
				return id, payloadPlist
			}
		}
	}
	return "", nil
}

// fetchClassicProfilePayloadPlist fetches the payload plist for an existing
// Classic config profile via the /subset/General endpoint. Returns nil when
// the payload cannot be fetched; callers should proceed without UUID injection.
func fetchClassicProfilePayloadPlist(ctx context.Context, client registry.HTTPClient, apiPath, id string) []byte {
	path := fmt.Sprintf("/JSSResource/%s/id/%s/subset/General", apiPath, url.PathEscape(id))
	resp, err := client.Do(ctx, "GET", path, nil)
	if err != nil {
		return nil
	}
	defer func() { _ = resp.Body.Close() }()

	body, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil
	}

	if !xmlconv.IsXML(body) {
		return nil
	}

	m, err := xmlconv.ToMap(body)
	if err != nil {
		return nil
	}

	for _, rootVal := range m {
		if root, ok := rootVal.(map[string]any); ok {
			if general, ok := root["general"].(map[string]any); ok {
				if payloads, ok := general["payloads"].(string); ok && payloads != "" {
					return []byte(payloads)
				}
			}
		}
	}
	return nil
}

// replaceClassicProfilePayload replaces the <payloads> CDATA block in a Classic
// API config profile XML body with newPayload. The replacement targets only the
// <payloads> element used by osxconfigurationprofiles and
// mobiledeviceconfigurationprofiles. Returns xmlBody unchanged when no
// <payloads> element is present.
func replaceClassicProfilePayload(xmlBody, newPayload []byte) []byte {
	const openTag = "<payloads>"
	const closeTag = "</payloads>"

	si := bytes.Index(xmlBody, []byte(openTag))
	ei := bytes.Index(xmlBody, []byte(closeTag))
	if si == -1 || ei == -1 || si >= ei {
		return xmlBody
	}

	var buf bytes.Buffer
	buf.Write(xmlBody[:si])
	buf.WriteString(openTag + "<![CDATA[")
	buf.Write(newPayload)
	buf.WriteString("]]>" + closeTag)
	buf.Write(xmlBody[ei+len(closeTag):])
	return buf.Bytes()
}

// injectClassicProfilePayloadUUIDs extracts the mobileconfig plist from xmlBody,
// injects PayloadUUID and PayloadIdentifier from existingPayload, and returns the
// modified XML body. Returns xmlBody unchanged on any failure (best-effort).
func injectClassicProfilePayloadUUIDs(xmlBody, existingPayload []byte) []byte {
	if len(existingPayload) == 0 {
		return xmlBody
	}

	m, err := xmlconv.ToMap(xmlBody)
	if err != nil {
		return xmlBody
	}

	var newPayloadPlist []byte
	for _, rootVal := range m {
		if root, ok := rootVal.(map[string]any); ok {
			if general, ok := root["general"].(map[string]any); ok {
				if payloads, ok := general["payloads"].(string); ok && payloads != "" {
					newPayloadPlist = []byte(payloads)
					break
				}
			}
		}
	}

	if len(newPayloadPlist) == 0 {
		return xmlBody
	}

	modified, err := profileconvert.InjectIdentifiers(newPayloadPlist, existingPayload)
	if err != nil {
		return xmlBody
	}

	return replaceClassicProfilePayload(xmlBody, modified)
}
{{ end }}
{{ if anyClassicFileFields . }}
// classicFileFieldSpec describes one Classic XML field sourced from a local file.
type classicFileFieldSpec struct {
	FilePath      string   // user-supplied path (empty = skip)
	ParentPath    []string // path to the immediate parent element under the root (e.g. ["general"])
	LeafName      string   // name of the element receiving the file contents (e.g. "payloads")
	Encoding      string   // "xml-cdata" | "raw"
	NameFallback  string   // "none" | "keep-ext" | "strip-ext"
}

// injectClassicFileFields overlays file-sourced XML fields into body. The body
// may be empty or missing the target path entirely; missing ancestors are
// constructed. File contents overwrite any existing leaf value; name fallback
// adds a name element under the parent's sibling "general" only when absent.
func injectClassicFileFields(body []byte, rootName string, specs []classicFileFieldSpec) ([]byte, error) {
	active := false
	for _, s := range specs {
		if s.FilePath != "" {
			active = true
			break
		}
	}
	if !active {
		return body, nil
	}

	bodyStr := string(bytes.TrimSpace(body))
	if bodyStr == "" {
		bodyStr = "<" + rootName + "></" + rootName + ">"
	}

	for _, s := range specs {
		if s.FilePath == "" {
			continue
		}
		data, err := os.ReadFile(s.FilePath)
		if err != nil {
			return nil, fmt.Errorf("reading %s: %w", s.FilePath, err)
		}
		var inner string
		if s.Encoding == "xml-cdata" {
			inner = "<![CDATA[" + string(data) + "]]>"
		} else {
			inner = string(data)
		}
		wrapped := "<" + s.LeafName + ">" + inner + "</" + s.LeafName + ">"

		// Replace an existing leaf anywhere in the body. Safe for our known
		// XML shapes because "payloads"/"preferences" only appear inside their
		// expected parents.
		openTag := "<" + s.LeafName + ">"
		closeTag := "</" + s.LeafName + ">"
		if si := strings.Index(bodyStr, openTag); si >= 0 {
			if ei := strings.Index(bodyStr[si:], closeTag); ei >= 0 {
				bodyStr = bodyStr[:si] + wrapped + bodyStr[si+ei+len(closeTag):]
			} else {
				return nil, fmt.Errorf("malformed XML: %s opens without close", openTag)
			}
		} else {
			// Insert before </parent>. If the parent is missing, build the path.
			parentName := s.ParentPath[len(s.ParentPath)-1]
			parentClose := "</" + parentName + ">"
			if idx := strings.Index(bodyStr, parentClose); idx >= 0 {
				bodyStr = bodyStr[:idx] + wrapped + bodyStr[idx:]
			} else {
				build := wrapped
				for i := len(s.ParentPath) - 1; i >= 0; i-- {
					build = "<" + s.ParentPath[i] + ">" + build + "</" + s.ParentPath[i] + ">"
				}
				rootClose := "</" + rootName + ">"
				if idx := strings.LastIndex(bodyStr, rootClose); idx >= 0 {
					bodyStr = bodyStr[:idx] + build + bodyStr[idx:]
				} else {
					return nil, fmt.Errorf("root </%s> not found in body", rootName)
				}
			}
		}

		if s.NameFallback != "" && s.NameFallback != "none" {
			// Only fill a name if one isn't already present under <general>.
			// Users often provide scope/category with their own <name> elements —
			// those are distinct, so we target <general><name> specifically.
			if !hasClassicGeneralName(bodyStr) {
				nm := filepath.Base(s.FilePath)
				if s.NameFallback == "strip-ext" {
					if dot := strings.LastIndex(nm, "."); dot > 0 {
						nm = nm[:dot]
					}
				}
				nameEl := "<name>" + classicXMLEscape(nm) + "</name>"
				if gi := strings.Index(bodyStr, "</general>"); gi >= 0 {
					bodyStr = bodyStr[:gi] + nameEl + bodyStr[gi:]
				} else if ri := strings.LastIndex(bodyStr, "</"+rootName+">"); ri >= 0 {
					bodyStr = bodyStr[:ri] + "<general>" + nameEl + "</general>" + bodyStr[ri:]
				}
			}
		}
	}
	return []byte(bodyStr), nil
}

// hasClassicGeneralName returns true if <general>…<name>…</name>…</general>
// appears in the XML body.
func hasClassicGeneralName(bodyStr string) bool {
	gOpen := strings.Index(bodyStr, "<general>")
	if gOpen < 0 {
		return false
	}
	gClose := strings.Index(bodyStr[gOpen:], "</general>")
	if gClose < 0 {
		return false
	}
	inner := bodyStr[gOpen : gOpen+gClose]
	return strings.Contains(inner, "<name>")
}

// classicXMLEscape escapes reserved characters for an XML text node.
func classicXMLEscape(s string) string {
	var b strings.Builder
	_ = xml.EscapeText(&b, []byte(s))
	return b.String()
}

// fetchClassicFullXMLByName fetches a Classic resource's full XML body by name,
// returning the bytes and its ID. Used by apply for resources that need
// fetch-merge-put semantics (e.g. mac/mobile app AppConfig). Returns an error
// if the API responds with a non-2xx status so the caller doesn't PUT back an
// HTML error page as the "existing record".
func fetchClassicFullXMLByName(ctx context.Context, client registry.HTTPClient, apiPath, name string) (id string, body []byte, err error) {
	path := fmt.Sprintf("/JSSResource/%s/name/%s", apiPath, url.PathEscape(name))
	resp, err := client.Do(ctx, "GET", path, nil)
	if err != nil {
		return "", nil, err
	}
	defer func() { _ = resp.Body.Close() }()
	body, err = io.ReadAll(resp.Body)
	if err != nil {
		return "", nil, fmt.Errorf("reading GET %s: %w", path, err)
	}
	if resp.StatusCode >= 400 {
		return "", nil, fmt.Errorf("GET %s returned %d: %s", path, resp.StatusCode, string(body))
	}
	m, mapErr := xmlconv.ToMap(body)
	if mapErr == nil {
		for _, rootVal := range m {
			if root, ok := rootVal.(map[string]any); ok {
				if general, ok := root["general"].(map[string]any); ok {
					id = extractIDString(general, "id")
				}
			}
		}
	}
	return id, body, nil
}
{{ end }}
`
