package classic

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestGenerate_ProducesFile(t *testing.T) {
	dir := t.TempDir()
	gen := NewGenerator(dir)

	resource := ClassicResource{
		Name:        "policies",
		Path:        "policies",
		CLIName:     "classic-policies",
		GoName:      "ClassicPolicies",
		Singular:    "policy",
		Description: "Deployment policies",
		Operations:  []string{"list", "get", "create", "update", "delete"},
		Lookups:     []string{"id", "name"},
	}

	outPath, err := gen.Generate(resource)
	if err != nil {
		t.Fatalf("Generate() error = %v", err)
	}

	if _, err := os.Stat(outPath); os.IsNotExist(err) {
		t.Fatalf("expected file %s to exist", outPath)
	}

	content, err := os.ReadFile(outPath)
	if err != nil {
		t.Fatal(err)
	}

	code := string(content)

	// Verify generated code contains expected elements
	checks := []string{
		"package generated",
		"Code generated by jamfpro-cli generator (classic). DO NOT EDIT.",
		"NewClassicPoliciesCmd",
		`Use:   "classic-policies"`,
		"newClassicPoliciesListCmd",
		"newClassicPoliciesGetCmd",
		"newClassicPoliciesGetByNameCmd",
		"newClassicPoliciesCreateCmd",
		"newClassicPoliciesUpdateCmd",
		"newClassicPoliciesDeleteCmd",
		"/JSSResource/policies",
		`wrapper["policy"]`,
	}

	for _, check := range checks {
		if !strings.Contains(code, check) {
			t.Errorf("generated code missing %q", check)
		}
	}
}

func TestGenerate_ListOnly(t *testing.T) {
	dir := t.TempDir()
	gen := NewGenerator(dir)

	resource := ClassicResource{
		Name:        "patchavailabletitles",
		Path:        "patchavailabletitles",
		CLIName:     "classic-patch-available-titles",
		GoName:      "ClassicPatchAvailableTitles",
		Singular:    "patch_available_title",
		Description: "Available patch titles",
		Operations:  []string{"list", "get"},
		Lookups:     []string{"id"},
	}

	outPath, err := gen.Generate(resource)
	if err != nil {
		t.Fatalf("Generate() error = %v", err)
	}

	content, err := os.ReadFile(outPath)
	if err != nil {
		t.Fatal(err)
	}

	code := string(content)

	// Should have list and get but not create/update/delete
	if !strings.Contains(code, "ListCmd") {
		t.Error("expected list command")
	}
	if !strings.Contains(code, "GetCmd") {
		t.Error("expected get command")
	}
	if strings.Contains(code, "CreateCmd") {
		t.Error("unexpected create command for list-only resource")
	}
	if strings.Contains(code, "UpdateCmd") {
		t.Error("unexpected update command for list-only resource")
	}
	if strings.Contains(code, "DeleteCmd") {
		t.Error("unexpected delete command for list-only resource")
	}
}

func TestGenerate_ExtraLookups(t *testing.T) {
	dir := t.TempDir()
	gen := NewGenerator(dir)

	resource := ClassicResource{
		Name:        "policies",
		Path:        "policies",
		CLIName:     "classic-policies",
		GoName:      "ClassicPolicies",
		Singular:    "policy",
		Description: "Deployment policies",
		Operations:  []string{"list", "get"},
		Lookups:     []string{"id", "name"},
	}

	outPath, err := gen.Generate(resource)
	if err != nil {
		t.Fatalf("Generate() error = %v", err)
	}

	content, err := os.ReadFile(outPath)
	if err != nil {
		t.Fatal(err)
	}

	code := string(content)

	if !strings.Contains(code, "GetByNameCmd") {
		t.Error("expected get-by-name command for resource with name lookup")
	}
	if !strings.Contains(code, `"get-by-name`) {
		t.Error("expected get-by-name use string")
	}
}

func TestGenerateRegistry(t *testing.T) {
	dir := t.TempDir()
	gen := NewGenerator(dir)

	resources := []ClassicResource{
		{CLIName: "classic-policies", GoName: "ClassicPolicies"},
		{CLIName: "classic-packages", GoName: "ClassicPackages"},
	}

	outPath, err := gen.GenerateRegistry(resources)
	if err != nil {
		t.Fatalf("GenerateRegistry() error = %v", err)
	}

	content, err := os.ReadFile(outPath)
	if err != nil {
		t.Fatal(err)
	}

	code := string(content)

	if !strings.Contains(code, "RegisterClassicCommands") {
		t.Error("expected RegisterClassicCommands function")
	}
	if !strings.Contains(code, "NewClassicPackagesCmd") {
		t.Error("expected NewClassicPackagesCmd registration")
	}
	if !strings.Contains(code, "NewClassicPoliciesCmd") {
		t.Error("expected NewClassicPoliciesCmd registration")
	}

	// Verify sorted order: packages before policies
	pkgIdx := strings.Index(code, "NewClassicPackagesCmd")
	polIdx := strings.Index(code, "NewClassicPoliciesCmd")
	if pkgIdx > polIdx {
		t.Error("expected classic-packages before classic-policies (sorted by CLIName)")
	}
}

func TestGenerate_Filename(t *testing.T) {
	dir := t.TempDir()
	gen := NewGenerator(dir)

	resource := ClassicResource{
		Name:        "policies",
		Path:        "policies",
		CLIName:     "classic-policies",
		GoName:      "ClassicPolicies",
		Singular:    "policy",
		Description: "Deployment policies",
		Operations:  []string{"list"},
		Lookups:     []string{"id"},
	}

	outPath, err := gen.Generate(resource)
	if err != nil {
		t.Fatalf("Generate() error = %v", err)
	}

	expectedFile := filepath.Join(dir, "classic_policies.go")
	if outPath != expectedFile {
		t.Errorf("output path = %q, want %q", outPath, expectedFile)
	}
}
