// Copyright 2026, Jamf Software LLC

package classic

import (
	"fmt"
	"os"
	"path/filepath"
	"slices"
	"sort"
	"strings"
	"text/template"

	"github.com/iancoleman/strcase"
)

// CodegenHeader is the marker line at the top of every classic API generated file.
// Must match the first line of classicResourceTemplate and classicRegistryTemplate.
const CodegenHeader = "// Code generated by jamf-cli generator (classic). DO NOT EDIT."

// Generator generates Go command files from ClassicResource definitions.
type Generator struct {
	outputDir string
}

// NewGenerator creates a new Classic API code generator.
func NewGenerator(outputDir string) *Generator {
	return &Generator{outputDir: outputDir}
}

// Generate writes a Go command file for a single Classic API resource.
func (g *Generator) Generate(resource ClassicResource) (string, error) {
	tmpl, err := template.New("classic_resource").Funcs(templateFuncs()).Parse(classicResourceTemplate)
	if err != nil {
		return "", fmt.Errorf("parsing template: %w", err)
	}

	filename := fmt.Sprintf("classic_%s.go", strings.ReplaceAll(resource.CLIName, "-", "_"))
	// strip the leading "classic_classic_" that would result from cli_name already containing "classic-"
	filename = strings.Replace(filename, "classic_classic_", "classic_", 1)
	outPath := filepath.Join(g.outputDir, filename)

	f, err := os.Create(outPath)
	if err != nil {
		return "", fmt.Errorf("creating file: %w", err)
	}

	if err := tmpl.Execute(f, resource); err != nil {
		_ = f.Close()
		_ = os.Remove(outPath)
		return "", fmt.Errorf("executing template: %w", err)
	}

	_ = f.Close()
	return outPath, nil
}

// GenerateRegistry writes the classic_registry.go file that registers all Classic commands.
func (g *Generator) GenerateRegistry(resources []ClassicResource) (string, error) {
	tmpl, err := template.New("classic_registry").Funcs(templateFuncs()).Parse(classicRegistryTemplate)
	if err != nil {
		return "", fmt.Errorf("parsing template: %w", err)
	}

	outPath := filepath.Join(g.outputDir, "classic_registry.go")

	f, err := os.Create(outPath)
	if err != nil {
		return "", fmt.Errorf("creating file: %w", err)
	}

	sorted := make([]ClassicResource, len(resources))
	copy(sorted, resources)
	sort.Slice(sorted, func(i, j int) bool {
		return sorted[i].CLIName < sorted[j].CLIName
	})

	if err := tmpl.Execute(f, sorted); err != nil {
		_ = f.Close()
		_ = os.Remove(outPath)
		return "", fmt.Errorf("executing template: %w", err)
	}

	_ = f.Close()
	return outPath, nil
}

// lookupFlagAliases maps a canonical Classic lookup path segment to additional
// CLI flag names that resolve to the same lookup. The API path segment stays
// canonical; the alias is registered as a second flag bound to the same
// variable. --serial mirrors the modern commands' --serial flag while the
// Classic API path segment remains "serialnumber".
var lookupFlagAliases = map[string][]string{
	"serialnumber": {"serial"},
}

func templateFuncs() template.FuncMap {
	return template.FuncMap{
		"toCamel":            strcase.ToCamel,
		"toKebab":            strcase.ToKebab,
		"toLower":            strings.ToLower,
		"hasOp":              hasOp,
		"hasLookup":          hasLookup,
		"extraLookups":       extraLookups,
		"scopeResolveByList": func(r ClassicResource) bool { return !r.HasLookup("name") },
		"classicExample": func(r ClassicResource, op string) string {
			bin := "jamf-cli pro"
			name := r.CLIName
			singular := r.Singular
			switch op {
			case "list":
				return fmt.Sprintf("  # List all %s\n  %s %s list\n\n  # List %s and extract IDs\n  %s %s list --field id",
					r.Name, bin, name, r.Name, bin, name)
			case "get":
				if r.HasLookup("name") {
					return fmt.Sprintf("  # Get a %s by ID\n  %s %s get 1\n\n  # Get a %s by name\n  %s %s get --name \"Example\"\n\n  # Get a %s and output as YAML\n  %s %s get 1 -o yaml",
						singular, bin, name, singular, bin, name, singular, bin, name)
				}
				return fmt.Sprintf("  # Get a %s by ID\n  %s %s get 1\n\n  # Get a %s and output as YAML\n  %s %s get 1 -o yaml",
					singular, bin, name, singular, bin, name)
			case "create":
				return fmt.Sprintf("  # Create a %s from XML\n  cat %s.xml | %s %s create",
					singular, singular, bin, name)
			case "update":
				return fmt.Sprintf("  # Update a %s from XML\n  cat %s.xml | %s %s update 1",
					singular, singular, bin, name)
			case "delete":
				if r.HasOperation("delete") && r.HasLookup("name") {
					return fmt.Sprintf("  # Delete a %s (with confirmation)\n  %s %s delete 1\n\n  # Delete by name\n  %s %s delete --name \"Example\" --yes\n\n  # Delete without confirmation prompt\n  %s %s delete 1 --yes",
						singular, bin, name, bin, name, bin, name)
				}
				return fmt.Sprintf("  # Delete a %s (with confirmation)\n  %s %s delete 1\n\n  # Delete without confirmation prompt\n  %s %s delete 1 --yes",
					singular, bin, name, bin, name)
			case "apply":
				return fmt.Sprintf("  # Apply a %s from an XML file\n  %s %s apply --from-file %s.xml\n\n  # Apply from stdin\n  cat %s.xml | %s %s apply\n\n  # Apply without replacement confirmation\n  %s %s apply --from-file %s.xml --yes",
					singular, bin, name, singular, singular, bin, name, bin, name, singular)
			default:
				return ""
			}
		},
		"lookupFlag": func(l string) string {
			return strcase.ToKebab(l)
		},
		"lookupCamel": func(l string) string {
			return strcase.ToCamel(l)
		},
		"lookupAliases": func(l string) []string {
			return lookupFlagAliases[l]
		},
		"needsIO": func(r ClassicResource) bool {
			// list and get use io.ReadAll for response unwrapping; create/update read from stdin
			return r.HasOperation("list") || r.HasOperation("get") || r.HasOperation("create") || r.HasOperation("update")
		},
		"idPath": func(r ClassicResource) string { return r.IDPath },
		"needsFmt": func(r ClassicResource) bool {
			return r.HasOperation("delete") || r.HasOperation("create") || r.HasOperation("update") || r.HasOperation("get")
		},
		"needsOS": func(r ClassicResource) bool {
			return r.HasOperation("create") || r.HasOperation("update") || r.HasOperation("delete")
		},
		"needsXMLConv": func(r ClassicResource) bool {
			return r.HasOperation("list") || r.HasOperation("get")
		},
		"needsScope": func(r ClassicResource) bool {
			return r.HasScope
		},
		"hasApply": func(r ClassicResource) bool {
			return r.HasOperation("create") && r.HasOperation("update") && r.HasLookup("name")
		},
		"needsBytes": func(r ClassicResource) bool {
			return (r.HasOperation("create") && r.HasOperation("update") && r.HasLookup("name")) ||
				(r.IsConfigProfile && r.HasOperation("update"))
		},
		"anyIsConfigProfile": func(resources []ClassicResource) bool {
			for _, r := range resources {
				if r.IsConfigProfile {
					return true
				}
			}
			return false
		},
		"hasDeleteByName": func(r ClassicResource) bool {
			return r.HasOperation("delete") && r.HasLookup("name")
		},
		"anyHasApply": func(resources []ClassicResource) bool {
			for _, r := range resources {
				if r.HasOperation("create") && r.HasOperation("update") && r.HasLookup("name") {
					return true
				}
			}
			return false
		},
		"anyNeedsClassicNameResolve": func(resources []ClassicResource) bool {
			for _, r := range resources {
				if r.HasLookup("name") && (r.HasOperation("delete") ||
					(r.HasOperation("create") && r.HasOperation("update"))) {
					return true
				}
			}
			return false
		},
		"anyClassicFileFields": func(resources []ClassicResource) bool {
			for _, r := range resources {
				if len(r.FileFields) > 0 {
					return true
				}
			}
			return false
		},
		"anyHasCustomPayload": func(resources []ClassicResource) bool {
			for _, r := range resources {
				if r.HasCustomPayload {
					return true
				}
			}
			return false
		},
		"anyListSubset": func(resources []ClassicResource) bool {
			for _, r := range resources {
				if r.ListSubset != "" {
					return true
				}
			}
			return false
		},
		"anyClassicExtraLookups": func(resources []ClassicResource) bool {
			for _, r := range resources {
				for _, l := range r.Lookups {
					if l != "id" && l != "name" {
						return true
					}
				}
			}
			return false
		},
		"anyHasSubsets": func(resources []ClassicResource) bool {
			for _, r := range resources {
				if len(r.Subsets) > 0 {
					return true
				}
			}
			return false
		},
		"anyHasGroupPath": func(resources []ClassicResource) bool {
			for _, r := range resources {
				if r.GroupPath != "" {
					return true
				}
			}
			return false
		},
		"groupMembersKey": func(groupPath string) string {
			return groupMembersKey(groupPath)
		},
		"groupMemberKey": func(groupPath string) string {
			return groupMemberKey(groupPath)
		},
		"hasFetchMergePut": func(r ClassicResource) bool {
			for _, ff := range r.FileFields {
				if ff.FetchMergePut {
					return true
				}
			}
			return false
		},
		"parentPathLiteral": func(path string) string {
			parts := strings.Split(path, "/")
			var out strings.Builder
			out.WriteString("[]string{")
			for i, p := range parts[:len(parts)-1] {
				if i > 0 {
					out.WriteString(", ")
				}
				out.WriteString("\"" + p + "\"")
			}
			out.WriteString("}")
			return out.String()
		},
		"leafName": func(path string) string {
			parts := strings.Split(path, "/")
			return parts[len(parts)-1]
		},
	}
}

func hasOp(ops []string, target string) bool {
	return slices.Contains(ops, target)
}

func hasLookup(lookups []string, target string) bool {
	return slices.Contains(lookups, target)
}

func extraLookups(lookups []string) []string {
	var extra []string
	for _, l := range lookups {
		if l != "id" {
			extra = append(extra, l)
		}
	}
	return extra
}

func groupMembersKey(groupPath string) string {
	switch groupPath {
	case "computergroups":
		return "computers"
	case "mobiledevicegroups":
		return "mobile_devices"
	default:
		return "members"
	}
}

func groupMemberKey(groupPath string) string {
	switch groupPath {
	case "computergroups":
		return "computer"
	case "mobiledevicegroups":
		return "mobile_device"
	default:
		return "member"
	}
}

// classicResourceTemplate generates a single Go file per Classic API resource.
const classicResourceTemplate = `// Copyright 2026, Jamf Software LLC
// Code generated by jamf-cli generator (classic). DO NOT EDIT.
package generated

import (
{{- if needsBytes . }}
	"bytes"
{{- end }}
{{- if or (hasOp .Operations "list") (hasOp .Operations "get") }}
	"encoding/json"
{{- end }}
{{- if needsFmt . }}
	"fmt"
{{- end }}
{{- if needsIO . }}
	"io"
{{- end }}
{{- if hasOp .Operations "delete" }}
	"net/http"
{{- end }}
{{- if or (hasOp .Operations "get") (hasOp .Operations "update") (hasOp .Operations "delete") (hasApply .) }}
	"net/url"
{{- end }}
{{- if needsOS . }}
	"os"
{{- end }}

	"github.com/spf13/cobra"

{{- if hasOp .Operations "delete" }}
	"github.com/Jamf-Concepts/jamf-cli/internal/cooldown"
{{- end }}
	"github.com/Jamf-Concepts/jamf-cli/internal/registry"
{{- if needsXMLConv . }}
	"github.com/Jamf-Concepts/jamf-cli/internal/xmlconv"
{{- end }}
{{- if needsScope . }}
	"github.com/Jamf-Concepts/jamf-cli/internal/scope"
{{- end }}
)

// New{{ .GoName }}Cmd creates the {{ .CLIName }} command group
func New{{ .GoName }}Cmd(ctx *registry.CLIContext) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "{{ .CLIName }}",
		Short: "{{ .Description }} (Classic API)",
		Long:  ` + "`" + `Manage {{ .Description | toLower }} via the Jamf Pro Classic API (/JSSResource/).` + "`" + `,
	}
{{ if hasOp .Operations "list" }}
	cmd.AddCommand(new{{ .GoName }}ListCmd(ctx))
{{- end }}
{{ if hasOp .Operations "get" }}
	cmd.AddCommand(new{{ .GoName }}GetCmd(ctx))
{{- end }}
{{ if hasOp .Operations "create" }}
	cmd.AddCommand(new{{ .GoName }}CreateCmd(ctx))
{{- end }}
{{ if hasOp .Operations "update" }}
	cmd.AddCommand(new{{ .GoName }}UpdateCmd(ctx))
{{- end }}
{{ if hasOp .Operations "delete" }}
	cmd.AddCommand(new{{ .GoName }}DeleteCmd(ctx))
{{- end }}
{{ if hasApply . }}
	cmd.AddCommand(new{{ .GoName }}ApplyCmd(ctx))
{{- end }}
{{ if needsScope . }}
	cmd.AddCommand(scope.NewScopeCmd(ctx, scope.Resource{
		APIPath:       "{{ .Path }}",
		SingularKey:   "{{ .Singular }}",
		{{- if scopeResolveByList . }}
		ResolveByList: true,
		{{- end }}
	}))
{{- end }}

	return cmd
}
{{ if hasOp .Operations "list" }}
func new{{ .GoName }}ListCmd(ctx *registry.CLIContext) *cobra.Command {
	return &cobra.Command{
		Use:   "list",
		Short: "List all {{ .Name }}",
		Example: ` + "`" + `{{ classicExample . "list" }}` + "`" + `,
		RunE: func(cmd *cobra.Command, args []string) error {
			reqCtx := cmd.Context()
			resp, err := ctx.Client.Do(reqCtx, "GET", "/JSSResource/{{ .Path }}", nil)
			if err != nil {
				return err
			}
			defer resp.Body.Close()

			// Classic API returns XML list responses.
			body, err := io.ReadAll(resp.Body)
			if err != nil {
				return err
			}
{{- if .ListSubset }}
			// /JSSResource/{{ .Path }} returns users + groups combined; narrow to
			// the "{{ .ListSubset }}" subset so this command behaves like a
			// standalone list. Default to pretty-printed XML (matching other
			// classic lists); -o json/yaml/table/csv extract structured items.
			subsetXML := sliceClassicListSubsetXML(body, "{{ .ListSubset }}")
			if (!cmd.Flags().Changed("output") && !cmd.Flags().Changed("field") && ctx.Output.Format() == "json") || ctx.Output.Format() == "xml" || ctx.Output.Format() == "raw" {
				return ctx.Output.PrintBytes(subsetXML)
			}
			if xmlconv.IsXML(body) {
				items, err := extractClassicListSubset(body, "{{ .ListSubset }}")
				if err == nil {
					jsonItems, mErr := json.Marshal(items)
					if mErr == nil {
						return ctx.Output.PrintRaw(jsonItems)
					}
				}
			}
			return ctx.Output.PrintRaw(subsetXML)
{{- else }}
			// Default to pretty-printed XML; use -o json/yaml/table/csv for structured output.
			// -o xml = pretty-printed XML, -o raw = exact wire bytes.
			if (!cmd.Flags().Changed("output") && !cmd.Flags().Changed("field") && ctx.Output.Format() == "json") || ctx.Output.Format() == "xml" || ctx.Output.Format() == "raw" {
				return ctx.Output.PrintBytes(body)
			}
			if xmlconv.IsXML(body) {
				items, err := xmlconv.ExtractListItems(body)
				if err == nil {
					jsonItems, err := json.Marshal(items)
					if err == nil {
						return ctx.Output.PrintRaw(jsonItems)
					}
				}
				return ctx.Output.PrintRaw(body)
			}
			// JSON fallback
			var wrapper map[string]json.RawMessage
			if err := json.Unmarshal(body, &wrapper); err == nil {
				if inner, ok := wrapper["{{ .Name }}"]; ok {
					return ctx.Output.PrintRaw(inner)
				}
			}
			return ctx.Output.PrintRaw(body)
{{- end }}
		},
	}
}
{{ end }}
{{ if hasOp .Operations "get" }}
func new{{ .GoName }}GetCmd(ctx *registry.CLIContext) *cobra.Command {
{{ if extraLookups .Lookups }}	var (
{{ range extraLookups .Lookups }}		flag{{ lookupCamel . }} string
{{ end }}	)
{{ end }}
{{ if .Subsets }}	var flagSubset string
{{ end }}
	cmd := &cobra.Command{
{{ if extraLookups .Lookups }}		Use:   "get [<id>]",
{{ else }}		Use:   "get <id>",
{{ end }}		Short: "Get a {{ .Singular }} by ID",
		Example: ` + "`" + `{{ classicExample . "get" }}` + "`" + `,
{{ if extraLookups .Lookups }}		Args:  cobra.MaximumNArgs(1),
{{ else }}		Args:  cobra.ExactArgs(1),
{{ end }}		RunE: func(cmd *cobra.Command, args []string) error {
			reqCtx := cmd.Context()
{{ if extraLookups .Lookups }}
			// Resolve lookup: check flags first, then positional ID
			var path string
{{ if .Subsets }}			var pathByID bool
{{ end }}{{ range extraLookups .Lookups }}			if flag{{ lookupCamel . }} != "" {
				path = fmt.Sprintf("/JSSResource/{{ $.Path }}/{{ . }}/%s", registry.EscapeClassicPathSegment(flag{{ lookupCamel . }}))
			} else {{ end }}if len(args) > 0 {
				path = fmt.Sprintf("/JSSResource/{{ .Path }}/{{ idPath . }}/%s", url.PathEscape(args[0]))
{{ if .Subsets }}				pathByID = true
{{ end }}			} else {
				return fmt.Errorf("provide an <id> argument{{ range $l := extraLookups .Lookups }}, --{{ lookupFlag $l }}{{ range $alias := lookupAliases $l }}, --{{ $alias }}{{ end }}{{ end }}")
			}
{{ else }}			path := fmt.Sprintf("/JSSResource/{{ .Path }}/{{ idPath . }}/%s", url.PathEscape(args[0]))
{{ end }}
{{ if .Subsets }}
			if flagSubset != "" {
{{ if extraLookups .Lookups }}				// The Platform Gateway's Classic proxy 403s /subset/ on non-id lookup
				// paths; resolve to an id first so the request uses id/{id}/subset/,
				// which works on both direct and gateway transports. See
				// docs/solutions/conventions/scope-put-avoid-subset-2026-07-08.md.
				if !pathByID {
					id, err := resolveClassicRecordID(reqCtx, ctx.Client, path, "{{ .Singular }}")
					if err != nil {
						return err
					}
					path = fmt.Sprintf("/JSSResource/{{ .Path }}/{{ idPath . }}/%s", url.PathEscape(id))
				}
{{ end }}				// Same encoding as lookups; safe for the curated single-token subset values.
				path += "/subset/" + registry.EscapeClassicPathSegment(flagSubset)
			}
{{ end }}
			resp, err := ctx.Client.Do(reqCtx, "GET", path, nil)
			if err != nil {
				return err
			}
			defer resp.Body.Close()

			// Classic API returns XML; pass through by default.
			body, err := io.ReadAll(resp.Body)
			if err != nil {
				return err
			}
			// Default to pretty-printed XML; use -o json/yaml/table/csv for structured output.
			// -o xml = pretty-printed XML, -o raw = exact wire bytes.
			if (!cmd.Flags().Changed("output") && !cmd.Flags().Changed("field") && ctx.Output.Format() == "json") || ctx.Output.Format() == "xml" || ctx.Output.Format() == "raw" {
				return ctx.Output.PrintBytes(body)
			}
			if xmlconv.IsXML(body) {
				if jsonBody, err := xmlconv.ToJSON(body); err == nil {
					body = jsonBody
				}
			}
			var wrapper map[string]json.RawMessage
			if err := json.Unmarshal(body, &wrapper); err == nil {
				if inner, ok := wrapper["{{ .Singular }}"]; ok {
					return ctx.Output.PrintRaw(inner)
				}
			}
			return ctx.Output.PrintRaw(body)
		},
	}
{{ if extraLookups .Lookups }}
{{ range $l := extraLookups .Lookups }}	cmd.Flags().StringVar(&flag{{ lookupCamel $l }}, "{{ lookupFlag $l }}", "", "Look up {{ $.Singular }} by {{ $l }}{{ range $alias := lookupAliases $l }} (alias: --{{ $alias }}){{ end }}")
{{ range $alias := lookupAliases $l }}	cmd.Flags().StringVar(&flag{{ lookupCamel $l }}, "{{ $alias }}", "", "Alias for --{{ lookupFlag $l }}")
{{ end }}{{ end }}{{ end }}
{{ if .Subsets }}	cmd.Flags().StringVar(&flagSubset, "subset", "", "Return only this section of the record, server-side (single value; tab-complete for values)")
	_ = cmd.RegisterFlagCompletionFunc("subset", func(_ *cobra.Command, _ []string, _ string) ([]string, cobra.ShellCompDirective) {
		return []string{ {{ range .Subsets }}"{{ . }}", {{ end }}}, cobra.ShellCompDirectiveNoFileComp
	})
{{ end }}	return cmd
}
{{ end }}
{{ if hasOp .Operations "create" }}
func new{{ .GoName }}CreateCmd(ctx *registry.CLIContext) *cobra.Command {
{{ if .FileFields }}	var (
{{ range .FileFields }}		flag{{ lookupCamel .Flag }} string
{{ end }}{{ if .HasCustomPayload }}		flagCustomPayloadFiles  []string
		flagCustomPayloadDomain string
{{ end }}	)
{{ end }}	cmd := &cobra.Command{
		Use:   "create",
		Short: "Create a {{ .Singular }}",
		Long:  "Create a new {{ .Singular }}. Reads XML body from stdin.",
		Example: ` + "`" + `{{ classicExample . "create" }}` + "`" + `,
		RunE: func(cmd *cobra.Command, args []string) error {
			reqCtx := cmd.Context()

{{ if .FileFields }}
			var bodyBytes []byte
			stat, _ := os.Stdin.Stat()
			if (stat.Mode() & os.ModeCharDevice) == 0 {
				var err error
				bodyBytes, err = io.ReadAll(os.Stdin)
				if err != nil {
					return fmt.Errorf("reading input: %w", err)
				}
			}
			anyFileFlag := {{ range $i, $ff := .FileFields }}{{ if $i }} || {{ end }}flag{{ lookupCamel $ff.Flag }} != ""{{ end }}{{ if .HasCustomPayload }} || len(flagCustomPayloadFiles) > 0{{ end }}
{{ if .HasCustomPayload }}
			if flag{{ lookupCamel (index .FileFields 0).Flag }} != "" && len(flagCustomPayloadFiles) > 0 {
				return fmt.Errorf("--{{ (index .FileFields 0).Flag }} and --custom-payload-file are mutually exclusive")
			}
			if flagCustomPayloadDomain != "" && len(flagCustomPayloadFiles) != 1 {
				return fmt.Errorf("--custom-payload-domain requires exactly one --custom-payload-file")
			}
{{ end -}}
			if len(bodyBytes) == 0 && !anyFileFlag {
				return fmt.Errorf("request body required on stdin (pipe XML input) or supply --{{ (index .FileFields 0).Flag }}{{ if .HasCustomPayload }} or --custom-payload-file{{ end }}")
			}
{{ if .HasCustomPayload }}
			var err error
			if len(flagCustomPayloadFiles) > 0 {
				var mcBytes []byte
				mcBytes, err = buildCustomPayloadMobileconfig(flagCustomPayloadFiles, flagCustomPayloadDomain)
				if err != nil {
					return err
				}
				bodyBytes, err = injectClassicFileFields(bodyBytes, "{{ .Singular }}", []classicFileFieldSpec{
					{FileBytes: mcBytes, FileNameHint: flagCustomPayloadFiles[0], ParentPath: []string{"general"}, LeafName: "payloads", Encoding: "xml-cdata", NameFallback: "strip-ext"},
				})
			} else {
				bodyBytes, err = injectClassicFileFields(bodyBytes, "{{ .Singular }}", []classicFileFieldSpec{
{{ range .FileFields }}				{FilePath: flag{{ lookupCamel .Flag }}, ParentPath: {{ parentPathLiteral .XMLPath }}, LeafName: "{{ leafName .XMLPath }}", Encoding: "{{ .Encoding }}", NameFallback: "{{ .NameFallback }}"},
{{ end }}				})
			}
			if err != nil {
				return err
			}
{{ else -}}
			bodyBytes, err := injectClassicFileFields(bodyBytes, "{{ .Singular }}", []classicFileFieldSpec{
{{ range .FileFields }}				{FilePath: flag{{ lookupCamel .Flag }}, ParentPath: {{ parentPathLiteral .XMLPath }}, LeafName: "{{ leafName .XMLPath }}", Encoding: "{{ .Encoding }}", NameFallback: "{{ .NameFallback }}"},
{{ end }}			})
			if err != nil {
				return err
			}
{{- end }}
{{ if .IsConfigProfile }}
			bodyBytes = normalizeClassicProfilePayloadsForSend(bodyBytes)
			resp, err := ctx.Client.Do(reqCtx, "POST", "/JSSResource/{{ .Path }}/{{ idPath . }}/0", bytes.NewReader(bodyBytes))
			if err != nil {
				return err
			}
			defer resp.Body.Close()
			respBody, readErr := io.ReadAll(resp.Body)
			if readErr != nil {
				return readErr
			}
			verifyClassicProfileStored(reqCtx, ctx.Client, "{{ .Path }}", classicCreatedResourceID(respBody), bodyBytes)
			return ctx.Output.PrintRaw(respBody)
{{ else -}}
			resp, err := ctx.Client.Do(reqCtx, "POST", "/JSSResource/{{ .Path }}/{{ idPath . }}/0", bytes.NewReader(bodyBytes))
			if err != nil {
				return err
			}
			defer resp.Body.Close()

			return ctx.Output.PrintResponse(resp)
{{ end -}}
{{ else }}
			var body io.Reader
			stat, _ := os.Stdin.Stat()
			if (stat.Mode() & os.ModeCharDevice) == 0 {
				body = os.Stdin
			} else {
				return fmt.Errorf("request body required on stdin (pipe XML input)")
			}

			resp, err := ctx.Client.Do(reqCtx, "POST", "/JSSResource/{{ .Path }}/{{ idPath . }}/0", body)
			if err != nil {
				return err
			}
			defer resp.Body.Close()

			return ctx.Output.PrintResponse(resp)
{{ end }}
		},
	}
{{ if .FileFields }}
{{ range .FileFields }}	cmd.Flags().StringVar(&flag{{ lookupCamel .Flag }}, "{{ .Flag }}", "", "{{ .Desc }}")
{{ end }}{{ end }}{{ if .HasCustomPayload }}	cmd.Flags().StringArrayVar(&flagCustomPayloadFiles, "custom-payload-file", nil, "Path to a preference plist (XML or binary); wrapped into a com.apple.ManagedClient.preferences payload (repeatable; mutually exclusive with --mobileconfig-file)")
	cmd.Flags().StringVar(&flagCustomPayloadDomain, "custom-payload-domain", "", "Preference domain override (inferred from filename by default; only valid with a single --custom-payload-file)")
{{ end }}	return cmd
}
{{ end }}
{{ if hasOp .Operations "update" }}
func new{{ .GoName }}UpdateCmd(ctx *registry.CLIContext) *cobra.Command {
{{ if hasLookup .Lookups "name" }}	var flagName string
{{ end }}{{ if .FileFields }}	var (
{{ range .FileFields }}		flag{{ lookupCamel .Flag }} string
{{ end }}{{ if .HasCustomPayload }}		flagCustomPayloadFiles  []string
		flagCustomPayloadDomain string
{{ end }}	)
{{ end }}
	cmd := &cobra.Command{
{{ if hasLookup .Lookups "name" }}		Use:   "update [<id>]",
{{ else }}		Use:   "update <id>",
{{ end }}		Short: "Update a {{ .Singular }}",
		Long:  "Update an existing {{ .Singular }} by ID. Reads XML body from stdin.",
		Example: ` + "`" + `{{ classicExample . "update" }}` + "`" + `,
{{ if hasLookup .Lookups "name" }}		Args:  cobra.MaximumNArgs(1),
{{ else }}		Args:  cobra.ExactArgs(1),
{{ end }}		RunE: func(cmd *cobra.Command, args []string) error {
			reqCtx := cmd.Context()

{{ if or .IsConfigProfile .FileFields }}
			var bodyBytes []byte
			stat, _ := os.Stdin.Stat()
			if (stat.Mode() & os.ModeCharDevice) == 0 {
				var err error
				bodyBytes, err = io.ReadAll(os.Stdin)
				if err != nil {
					return fmt.Errorf("reading input: %w", err)
				}
			}
{{ if .FileFields }}
{{ if .HasCustomPayload }}
			if flag{{ lookupCamel (index .FileFields 0).Flag }} != "" && len(flagCustomPayloadFiles) > 0 {
				return fmt.Errorf("--{{ (index .FileFields 0).Flag }} and --custom-payload-file are mutually exclusive")
			}
			if flagCustomPayloadDomain != "" && len(flagCustomPayloadFiles) != 1 {
				return fmt.Errorf("--custom-payload-domain requires exactly one --custom-payload-file")
			}
{{- end }}
			anyFileFlag := {{ range $i, $ff := .FileFields }}{{ if $i }} || {{ end }}flag{{ lookupCamel $ff.Flag }} != ""{{ end }}{{ if .HasCustomPayload }} || len(flagCustomPayloadFiles) > 0{{ end }}
			if len(bodyBytes) == 0 && !anyFileFlag {
				return fmt.Errorf("request body required on stdin (pipe XML input) or supply --{{ (index .FileFields 0).Flag }}{{ if .HasCustomPayload }} or --custom-payload-file{{ end }}")
			}
{{ else }}
			if len(bodyBytes) == 0 {
				return fmt.Errorf("request body required on stdin (pipe XML input)")
			}
{{ end }}

			// Resolve ID and preserve PayloadUUID/PayloadIdentifier.
			var resolvedID string
{{ if .IsConfigProfile }}			var existingPayload []byte
{{ end }}{{ if hasFetchMergePut . }}			var existingBody []byte
{{ end }}{{ if hasLookup .Lookups "name" }}
			if flagName != "" {
{{ if hasFetchMergePut . }}
				id, body, ferr := fetchClassicFullXMLByName(reqCtx, ctx.Client, "{{ .Path }}", flagName)
				if ferr != nil || id == "" {
					return fmt.Errorf("no {{ .Singular }} found with name %q", flagName)
				}
				resolvedID = id
				existingBody = body
{{ else }}
				resolvedID, existingPayload = fetchClassicProfileByName(reqCtx, ctx.Client, "{{ .Path }}", flagName)
				if resolvedID == "" {
					return fmt.Errorf("no {{ .Singular }} found with name %q", flagName)
				}
{{ end }}
			} else if len(args) > 0 {
				resolvedID = args[0]
{{ if hasFetchMergePut . }}
				path := fmt.Sprintf("/JSSResource/{{ .Path }}/{{ idPath . }}/%s", url.PathEscape(resolvedID))
				respX, ferr := ctx.Client.Do(reqCtx, "GET", path, nil)
				if ferr != nil {
					return fmt.Errorf("fetching existing {{ .Singular }}: %w", ferr)
				}
				var readErr error
				existingBody, readErr = io.ReadAll(respX.Body)
				_ = respX.Body.Close()
				if readErr != nil {
					return fmt.Errorf("reading existing {{ .Singular }}: %w", readErr)
				}
				if respX.StatusCode >= 400 {
					return fmt.Errorf("fetching existing {{ .Singular }}: GET %s returned %d: %s", path, respX.StatusCode, string(existingBody))
				}
{{ else }}
				existingPayload = fetchClassicProfilePayloadPlist(reqCtx, ctx.Client, "{{ .Path }}", resolvedID)
{{ end }}
			} else {
				return fmt.Errorf("provide an <id> argument or --name")
			}
{{ else }}
			if len(args) > 0 {
				resolvedID = args[0]
{{ if hasFetchMergePut . }}
				path := fmt.Sprintf("/JSSResource/{{ .Path }}/{{ idPath . }}/%s", url.PathEscape(resolvedID))
				respX, ferr := ctx.Client.Do(reqCtx, "GET", path, nil)
				if ferr != nil {
					return fmt.Errorf("fetching existing {{ .Singular }}: %w", ferr)
				}
				var readErr error
				existingBody, readErr = io.ReadAll(respX.Body)
				_ = respX.Body.Close()
				if readErr != nil {
					return fmt.Errorf("reading existing {{ .Singular }}: %w", readErr)
				}
				if respX.StatusCode >= 400 {
					return fmt.Errorf("fetching existing {{ .Singular }}: GET %s returned %d: %s", path, respX.StatusCode, string(existingBody))
				}
{{ else }}
				existingPayload = fetchClassicProfilePayloadPlist(reqCtx, ctx.Client, "{{ .Path }}", resolvedID)
{{ end }}
			} else {
				return fmt.Errorf("provide an <id> argument")
			}
{{ end }}

{{ if hasFetchMergePut . }}
			// Fetch-merge-put: start from the existing record, overlay file field.
			if len(existingBody) == 0 {
				return fmt.Errorf("could not fetch existing {{ .Singular }} for merge-put")
			}
			bodyBytes = existingBody
{{ end }}

{{ if .FileFields }}
{{ if .HasCustomPayload }}
			var injErr error
			if len(flagCustomPayloadFiles) > 0 {
				var mcBytes []byte
				mcBytes, injErr = buildCustomPayloadMobileconfig(flagCustomPayloadFiles, flagCustomPayloadDomain)
				if injErr != nil {
					return injErr
				}
				bodyBytes, injErr = injectClassicFileFields(bodyBytes, "{{ .Singular }}", []classicFileFieldSpec{
					{FileBytes: mcBytes, FileNameHint: flagCustomPayloadFiles[0], ParentPath: []string{"general"}, LeafName: "payloads", Encoding: "xml-cdata", NameFallback: "strip-ext"},
				})
			} else {
				bodyBytes, injErr = injectClassicFileFields(bodyBytes, "{{ .Singular }}", []classicFileFieldSpec{
{{ range .FileFields }}				{FilePath: flag{{ lookupCamel .Flag }}, ParentPath: {{ parentPathLiteral .XMLPath }}, LeafName: "{{ leafName .XMLPath }}", Encoding: "{{ .Encoding }}", NameFallback: "{{ .NameFallback }}"},
{{ end }}				})
			}
			if injErr != nil {
				return injErr
			}
{{- else }}
			var injErr error
			bodyBytes, injErr = injectClassicFileFields(bodyBytes, "{{ .Singular }}", []classicFileFieldSpec{
{{ range .FileFields }}				{FilePath: flag{{ lookupCamel .Flag }}, ParentPath: {{ parentPathLiteral .XMLPath }}, LeafName: "{{ leafName .XMLPath }}", Encoding: "{{ .Encoding }}", NameFallback: "{{ .NameFallback }}"},
{{ end }}			})
			if injErr != nil {
				return injErr
			}
{{- end }}
{{ end }}
{{ if .IsConfigProfile }}
			bodyBytes = injectClassicProfilePayloadUUIDs(bodyBytes, existingPayload)
			bodyBytes = injectClassicRedeployOnUpdate(bodyBytes)
			bodyBytes = normalizeClassicProfilePayloadsForSend(bodyBytes)

			path := fmt.Sprintf("/JSSResource/{{ .Path }}/{{ idPath . }}/%s", url.PathEscape(resolvedID))
			resp, err := ctx.Client.Do(reqCtx, "PUT", path, bytes.NewReader(bodyBytes))
			if err == nil {
				verifyClassicProfileStored(reqCtx, ctx.Client, "{{ .Path }}", resolvedID, bodyBytes)
			}
{{ else }}
			path := fmt.Sprintf("/JSSResource/{{ .Path }}/{{ idPath . }}/%s", url.PathEscape(resolvedID))
			resp, err := ctx.Client.Do(reqCtx, "PUT", path, bytes.NewReader(bodyBytes))
{{ end }}
{{ else }}
			var body io.Reader
			stat, _ := os.Stdin.Stat()
			if (stat.Mode() & os.ModeCharDevice) == 0 {
				body = os.Stdin
			} else {
				return fmt.Errorf("request body required on stdin (pipe XML input)")
			}

{{ if hasLookup .Lookups "name" }}
			var path string
			if flagName != "" {
				path = fmt.Sprintf("/JSSResource/{{ .Path }}/name/%s", registry.EscapeClassicPathSegment(flagName))
			} else if len(args) > 0 {
				path = fmt.Sprintf("/JSSResource/{{ .Path }}/{{ idPath . }}/%s", url.PathEscape(args[0]))
			} else {
				return fmt.Errorf("provide an <id> argument or --name")
			}
{{ else }}			path := fmt.Sprintf("/JSSResource/{{ .Path }}/{{ idPath . }}/%s", url.PathEscape(args[0]))
{{ end }}
			resp, err := ctx.Client.Do(reqCtx, "PUT", path, body)
{{- end }}
			if err != nil {
				return err
			}
			defer resp.Body.Close()

			return ctx.Output.PrintResponse(resp)
		},
	}

{{ if hasLookup .Lookups "name" }}	cmd.Flags().StringVar(&flagName, "name", "", "Look up {{ .Singular }} by name")
{{ end }}
{{ if .FileFields }}
{{ range .FileFields }}	cmd.Flags().StringVar(&flag{{ lookupCamel .Flag }}, "{{ .Flag }}", "", "{{ .Desc }}")
{{ end }}{{ end }}{{ if .HasCustomPayload }}	cmd.Flags().StringArrayVar(&flagCustomPayloadFiles, "custom-payload-file", nil, "Path to a preference plist (XML or binary); wrapped into a com.apple.ManagedClient.preferences payload (repeatable; mutually exclusive with --mobileconfig-file)")
	cmd.Flags().StringVar(&flagCustomPayloadDomain, "custom-payload-domain", "", "Preference domain override (inferred from filename by default; only valid with a single --custom-payload-file)")
{{ end }}	return cmd
}
{{ end }}
{{ if hasOp .Operations "delete" }}
func new{{ .GoName }}DeleteCmd(ctx *registry.CLIContext) *cobra.Command {
	var (
		flagYes    bool
		flagDryRun bool
{{ if hasDeleteByName . }}		flagName string
		fromFile string
{{ end }}{{ if .GroupPath }}		flagGroup string
{{ end }}	)

	cmd := &cobra.Command{
{{ if hasDeleteByName . }}		Use:   "delete [<id>]",
{{ else }}		Use:   "delete <id>",
{{ end }}		Short: "Delete a {{ .Singular }}",
		Example: ` + "`" + `{{ classicExample . "delete" }}` + "`" + `,
		Annotations: map[string]string{"jamf:destructive": "true"},
{{ if hasDeleteByName . }}		Args:  cobra.MaximumNArgs(1),
{{ else }}		Args:  cobra.ExactArgs(1),
{{ end }}		RunE: func(cmd *cobra.Command, args []string) error {
			reqCtx := cmd.Context()
{{ if hasDeleteByName . }}
			// --from-file: bulk delete from a file of IDs or names
			if fromFile != "" {
				entries, err := readDeleteFile(fromFile)
				if err != nil {
					return fmt.Errorf("reading --from-file: %w", err)
				}
				if len(entries) == 0 {
					return fmt.Errorf("--from-file %q: no entries found", fromFile)
				}
				type bulkEntry struct{ id, label string }
				bulk := make([]bulkEntry, 0, len(entries))
				noInputBulk, _ := cmd.Flags().GetBool("no-input")
				for _, entry := range entries {
					if isNumericID(entry) {
						if entry == "0" {
							return fmt.Errorf("--from-file: ID 0 is not valid (Jamf Pro uses 0 as a sentinel value)")
						}
						bulk = append(bulk, bulkEntry{id: entry, label: entry})
					} else {
						var resolvedID string
{{ range extraLookups .Lookups }}{{ if ne . "name" }}					if resolvedID == "" {
							id, lookupErr := resolveClassicLookupToID(reqCtx, ctx.Client, "/JSSResource/{{ $.Path }}/{{ . }}", entry)
							if lookupErr != nil {
								return fmt.Errorf("resolving %q via {{ . }}: %w", entry, lookupErr)
							}
							resolvedID = id
						}
{{ end }}{{ end }}					if resolvedID == "" {
							id, err := resolveClassicNameToIDForApply(reqCtx, ctx.Client, "{{ .Path }}", "{{ .Name }}", entry, noInputBulk)
							if err != nil {
								return fmt.Errorf("resolving %q: %w", entry, err)
							}
							resolvedID = id
						}
						if resolvedID == "" {
							return fmt.Errorf("no {{ .Singular }} found matching %q", entry)
						}
						bulk = append(bulk, bulkEntry{id: resolvedID, label: entry})
					}
				}
				// Deduplicate resolved IDs to avoid double-delete errors.
				{
					seen := make(map[string]bool, len(bulk))
					deduped := bulk[:0]
					for _, e := range bulk {
						if !seen[e.id] {
							seen[e.id] = true
							deduped = append(deduped, e)
						}
					}
					bulk = deduped
				}
				if flagDryRun {
					for _, e := range bulk {
						fmt.Fprintf(os.Stderr, "[dry-run] Would delete {{ .Singular }} %q (id: %s)\n", e.label, e.id)
					}
					return nil
				}
				if !flagYes {
					if noInputBulk {
						return fmt.Errorf("destructive operation requires --yes when --no-input is set")
					}
					fmt.Fprintf(os.Stderr, "⚠️  This will delete %d {{ .Name }}. Type 'yes' to confirm: ", len(bulk))
					var confirm string
					fmt.Scanln(&confirm)
					if confirm != "yes" {
						return fmt.Errorf("aborted")
					}
				}
				if err := cooldown.Enforce(ctx.ProfileName, noInputBulk, ctx.DestructiveCooldown); err != nil {
					return err
				}
				var okCount, failCount int
				var firstErr error
				for _, e := range bulk {
					delPath := fmt.Sprintf("/JSSResource/{{ .Path }}/{{ idPath . }}/%s", url.PathEscape(e.id))
					resp, err := ctx.Client.Do(reqCtx, "DELETE", delPath, nil)
					if err != nil {
						fmt.Fprintf(os.Stderr, "delete {{ .Singular }} %q (id: %s) failed: %v\n", e.label, e.id, err)
						if firstErr == nil {
							firstErr = err
						}
						failCount++
						continue
					}
					resp.Body.Close()
					if resp.StatusCode == http.StatusNoContent || resp.StatusCode == http.StatusOK {
						fmt.Fprintf(os.Stderr, "Deleted {{ .Singular }} %q (id: %s)\n", e.label, e.id)
						okCount++
					} else {
						fmt.Fprintf(os.Stderr, "delete {{ .Singular }} %q (id: %s) failed: HTTP %d\n", e.label, e.id, resp.StatusCode)
						if firstErr == nil {
							firstErr = fmt.Errorf("HTTP %d", resp.StatusCode)
						}
						failCount++
					}
				}
				cooldown.Record(ctx.ProfileName)
				return batchDeleteError(cmd, okCount, failCount, firstErr, "{{ .Name }} deletes")
			}
{{ if .GroupPath }}
			// --group: delete all members of the named mobile device group
			if flagGroup != "" {
				memberIDs, err := fetchClassicGroupMemberIDs(reqCtx, ctx.Client, "/JSSResource/{{ .GroupPath }}", "{{ groupMembersKey .GroupPath }}", "{{ groupMemberKey .GroupPath }}", flagGroup)
				if err != nil {
					return fmt.Errorf("resolving group %q: %w", flagGroup, err)
				}
				if len(memberIDs) == 0 {
					return fmt.Errorf("group %q has no members", flagGroup)
				}
				type bulkEntry struct{ id, label string }
				bulk := make([]bulkEntry, 0, len(memberIDs))
				for _, id := range memberIDs {
					bulk = append(bulk, bulkEntry{id: id, label: id})
				}
				noInputGroup, _ := cmd.Flags().GetBool("no-input")
				if flagDryRun {
					for _, e := range bulk {
						fmt.Fprintf(os.Stderr, "[dry-run] Would delete {{ .Singular }} id: %s (from group %q)\n", e.id, flagGroup)
					}
					return nil
				}
				if !flagYes {
					if noInputGroup {
						return fmt.Errorf("destructive operation requires --yes when --no-input is set")
					}
					fmt.Fprintf(os.Stderr, "⚠️  This will delete %d {{ .Name }} from group %q. Type 'yes' to confirm: ", len(bulk), flagGroup)
					var confirm string
					fmt.Scanln(&confirm)
					if confirm != "yes" {
						return fmt.Errorf("aborted")
					}
				}
				if err := cooldown.Enforce(ctx.ProfileName, noInputGroup, ctx.DestructiveCooldown); err != nil {
					return err
				}
				var okCount, failCount int
				var firstErr error
				for _, e := range bulk {
					delPath := fmt.Sprintf("/JSSResource/{{ .Path }}/{{ idPath . }}/%s", url.PathEscape(e.id))
					resp, err := ctx.Client.Do(reqCtx, "DELETE", delPath, nil)
					if err != nil {
						fmt.Fprintf(os.Stderr, "delete {{ .Singular }} id %s failed: %v\n", e.id, err)
						if firstErr == nil {
							firstErr = err
						}
						failCount++
						continue
					}
					resp.Body.Close()
					if resp.StatusCode == http.StatusNoContent || resp.StatusCode == http.StatusOK {
						fmt.Fprintf(os.Stderr, "Deleted {{ .Singular }} id: %s\n", e.id)
						okCount++
					} else {
						fmt.Fprintf(os.Stderr, "delete {{ .Singular }} id %s failed: HTTP %d\n", e.id, resp.StatusCode)
						if firstErr == nil {
							firstErr = fmt.Errorf("HTTP %d", resp.StatusCode)
						}
						failCount++
					}
				}
				cooldown.Record(ctx.ProfileName)
				return batchDeleteError(cmd, okCount, failCount, firstErr, "{{ .Name }} deletes")
			}
{{ end }}
			// Resolve ID from --name or positional arg
			var resolvedID string
			noInput, _ := cmd.Flags().GetBool("no-input")
			if flagName != "" {
				id, err := resolveClassicNameToIDForApply(reqCtx, ctx.Client, "{{ .Path }}", "{{ .Name }}", flagName, noInput)
				if err != nil {
					return err
				}
				if id == "" {
					return fmt.Errorf("no {{ .Singular }} found with name %q", flagName)
				}
				resolvedID = id
			} else if len(args) > 0 {
				resolvedID = args[0]
			} else {
				return fmt.Errorf("provide an <id> argument or --name")
			}

			if flagDryRun {
				fmt.Fprintf(os.Stderr, "[dry-run] Would delete {{ .Singular }} %s\n", resolvedID)
				return nil
			}
			if !flagYes {
				if noInput {
					return fmt.Errorf("destructive operation requires --yes when --no-input is set")
				}
				fmt.Fprintf(os.Stderr, "This will delete {{ .Singular }} %s. Type 'yes' to confirm: ", resolvedID)
				var confirm string
				fmt.Scanln(&confirm)
				if confirm != "yes" {
					return fmt.Errorf("aborted")
				}
			}

			if err := cooldown.Enforce(ctx.ProfileName, noInput, ctx.DestructiveCooldown); err != nil {
				return err
			}
			path := fmt.Sprintf("/JSSResource/{{ .Path }}/{{ idPath . }}/%s", url.PathEscape(resolvedID))
{{ else }}
			if flagDryRun {
				fmt.Fprintf(os.Stderr, "Would delete {{ .Singular }} %s\n", args[0])
				return nil
			}
			if !flagYes {
				noInput, _ := cmd.Flags().GetBool("no-input")
				if noInput {
					return fmt.Errorf("destructive operation requires --yes when --no-input is set")
				}
				fmt.Fprintf(os.Stderr, "This will delete {{ .Singular }} %s. Type 'yes' to confirm: ", args[0])
				var confirm string
				fmt.Scanln(&confirm)
				if confirm != "yes" {
					return fmt.Errorf("aborted")
				}
			}

			noInputForCooldown, _ := cmd.Flags().GetBool("no-input")
			if err := cooldown.Enforce(ctx.ProfileName, noInputForCooldown, ctx.DestructiveCooldown); err != nil {
				return err
			}
			path := fmt.Sprintf("/JSSResource/{{ .Path }}/{{ idPath . }}/%s", url.PathEscape(args[0]))
{{ end }}
			resp, err := ctx.Client.Do(reqCtx, "DELETE", path, nil)
			if err != nil {
				return err
			}
			defer resp.Body.Close()

			if resp.StatusCode == http.StatusNoContent || resp.StatusCode == http.StatusOK {
				cooldown.Record(ctx.ProfileName)
				fmt.Fprintln(os.Stderr, "Deleted successfully")
				return nil
			}

			return ctx.Output.PrintResponse(resp)
		},
	}

	cmd.Flags().BoolVar(&flagYes, "yes", false, "Skip confirmation prompt")
	cmd.Flags().BoolVarP(&flagDryRun, "dry-run", "n", false, "Preview without executing")
{{ if hasDeleteByName . }}	cmd.Flags().StringVar(&flagName, "name", "", "Look up {{ .Singular }} by name")
	cmd.Flags().StringVar(&fromFile, "from-file", "", "Path to file listing IDs or names to delete (one per line, # comments ignored)")
{{ end }}{{ if .GroupPath }}	cmd.Flags().StringVar(&flagGroup, "group", "", "Delete all {{ .Name }} from a Classic API group (name or ID)")
{{ end }}{{ if hasDeleteByName . }}	cmd.MarkFlagsMutuallyExclusive("from-file", "name")
{{ if .GroupPath }}	cmd.MarkFlagsMutuallyExclusive("from-file", "group")
	cmd.MarkFlagsMutuallyExclusive("group", "name")
{{ end }}{{ end }}
	return cmd
}
{{ end }}
{{ if hasApply . }}
func new{{ .GoName }}ApplyCmd(ctx *registry.CLIContext) *cobra.Command {
	var (
		fromFile   string
		flagYes    bool
		flagDryRun bool
{{ if hasFetchMergePut . }}		flagName   string
{{ end }}{{ if .FileFields }}{{ range .FileFields }}		flag{{ lookupCamel .Flag }} string
{{ end }}{{ end }}{{ if .HasCustomPayload }}		flagCustomPayloadFiles  []string
		flagCustomPayloadDomain string
{{ if not (hasFetchMergePut .) }}		flagName               string
{{ end }}{{ end }}	)

	cmd := &cobra.Command{
		Use:   "apply",
		Short: "Create or replace a {{ .Singular }} by name",
		Long: ` + "`" + `Create or replace a {{ .Singular }}. Reads XML from --from-file or stdin.

The name field in the input XML is used to check if the resource already
exists. If it does, the resource is replaced (with confirmation).
If not, a new resource is created.` + "`" + `,
		Example: ` + "`" + `{{ classicExample . "apply" }}` + "`" + `,
		RunE: func(cmd *cobra.Command, _ []string) error {
			reqCtx := cmd.Context()

			// Read input
			data, err := readApplyInput(fromFile)
{{ if .FileFields }}
			anyFileFlag := {{ range $i, $ff := .FileFields }}{{ if $i }} || {{ end }}flag{{ lookupCamel $ff.Flag }} != ""{{ end }}{{ if .HasCustomPayload }} || len(flagCustomPayloadFiles) > 0{{ end }}
{{ if .HasCustomPayload }}
			if flag{{ lookupCamel (index .FileFields 0).Flag }} != "" && len(flagCustomPayloadFiles) > 0 {
				return fmt.Errorf("--{{ (index .FileFields 0).Flag }} and --custom-payload-file are mutually exclusive")
			}
			if flagCustomPayloadDomain != "" && len(flagCustomPayloadFiles) != 1 {
				return fmt.Errorf("--custom-payload-domain requires exactly one --custom-payload-file")
			}
{{ end -}}
			if err != nil && !anyFileFlag {
				return err
			}
			err = nil
{{ else }}
			if err != nil {
				return err
			}
{{ end }}
{{ if .FileFields }}
			// Inject file fields before name extraction so name-fallback (if any)
			// can populate <general><name> for lookup.
{{ if .HasCustomPayload }}
			if flagName != "" {
				data = setClassicGeneralName(data, "{{ .Singular }}", flagName)
			}
			if len(flagCustomPayloadFiles) > 0 {
				var mcBytes []byte
				mcBytes, err = buildCustomPayloadMobileconfig(flagCustomPayloadFiles, flagCustomPayloadDomain)
				if err != nil {
					return err
				}
				data, err = injectClassicFileFields(data, "{{ .Singular }}", []classicFileFieldSpec{
					{FileBytes: mcBytes, FileNameHint: flagCustomPayloadFiles[0], ParentPath: []string{"general"}, LeafName: "payloads", Encoding: "xml-cdata", NameFallback: "strip-ext"},
				})
			} else {
				data, err = injectClassicFileFields(data, "{{ .Singular }}", []classicFileFieldSpec{
{{ range .FileFields }}				{FilePath: flag{{ lookupCamel .Flag }}, ParentPath: {{ parentPathLiteral .XMLPath }}, LeafName: "{{ leafName .XMLPath }}", Encoding: "{{ .Encoding }}", NameFallback: "{{ .NameFallback }}"},
{{ end }}				})
			}
{{ else -}}
			data, err = injectClassicFileFields(data, "{{ .Singular }}", []classicFileFieldSpec{
{{ range .FileFields }}				{FilePath: flag{{ lookupCamel .Flag }}, ParentPath: {{ parentPathLiteral .XMLPath }}, LeafName: "{{ leafName .XMLPath }}", Encoding: "{{ .Encoding }}", NameFallback: "{{ .NameFallback }}"},
{{ end }}			})
{{- end }}
			if err != nil {
				return err
			}
{{ end }}

			// Extract name: for fetch-merge-put resources, --name is the primary
			// input (body typically empty); fall back to XML name if flag absent.
			var name string
{{ if hasFetchMergePut . }}
			if flagName != "" {
				name = flagName
			} else {
				name, err = extractClassicName(data, "{{ .Singular }}")
				if err != nil {
					return fmt.Errorf("--name is required when input body is empty: %w", err)
				}
			}
{{ else }}
			name, err = extractClassicName(data, "{{ .Singular }}")
			if err != nil {
				return err
			}
{{ end }}

			// Check if resource exists by name (read-only, runs even in dry-run)
			noInput, _ := cmd.Flags().GetBool("no-input")
			id, err := resolveClassicNameToIDForApply(reqCtx, ctx.Client, "{{ .Path }}", "{{ .Name }}", name, noInput)
			if err != nil {
				return err
			}

			if id == "" {
				// Not found — create (not allowed for fetch-merge-put resources)
{{ if hasFetchMergePut . }}
				return fmt.Errorf("no {{ .Singular }} found with name %q — this resource must already exist (apply is fetch-merge-put only)", name)
{{ else }}
				if flagDryRun {
					fmt.Fprintf(os.Stderr, "[dry-run] Would create {{ .Singular }} %q\n", name)
					return nil
				}
{{ if .IsConfigProfile }}
				data = normalizeClassicProfilePayloadsForSend(data)
				resp, err := ctx.Client.Do(reqCtx, "POST", "/JSSResource/{{ .Path }}/{{ idPath . }}/0", bytes.NewReader(data))
				if err != nil {
					return err
				}
				defer resp.Body.Close()
				respBody, readErr := io.ReadAll(resp.Body)
				if readErr != nil {
					return readErr
				}
				verifyClassicProfileStored(reqCtx, ctx.Client, "{{ .Path }}", classicCreatedResourceID(respBody), data)
				fmt.Fprintf(os.Stderr, "Created {{ .Singular }} %q\n", name)
				return ctx.Output.PrintRaw(respBody)
{{ else -}}
				resp, err := ctx.Client.Do(reqCtx, "POST", "/JSSResource/{{ .Path }}/{{ idPath . }}/0", bytes.NewReader(data))
				if err != nil {
					return err
				}
				defer resp.Body.Close()
				fmt.Fprintf(os.Stderr, "Created {{ .Singular }} %q\n", name)
				return ctx.Output.PrintResponse(resp)
{{ end -}}
{{ end }}
			}

			// Found — replace
			if flagDryRun {
				fmt.Fprintf(os.Stderr, "[dry-run] Would replace {{ .Singular }} %q (id: %s)\n", name, id)
				return nil
			}
			if !flagYes {
				if noInput {
					return fmt.Errorf("{{ .Singular }} %q already exists (id: %s); use --yes to replace when --no-input is set", name, id)
				}
				fmt.Fprintf(os.Stderr, "{{ .Singular }} %q already exists (id: %s) and will be replaced. Type 'yes' to confirm: ", name, id)
				var confirm string
				fmt.Scanln(&confirm)
				if confirm != "yes" {
					return fmt.Errorf("aborted")
				}
			}

{{ if hasFetchMergePut . }}
			// Fetch the existing full record and overlay the file field(s) — the
			// user's input (if any) is ignored beyond name resolution; AppConfig
			// injection preserves every other field on the record.
			_, fullBody, ferr := fetchClassicFullXMLByName(reqCtx, ctx.Client, "{{ .Path }}", name)
			if ferr != nil || len(fullBody) == 0 {
				return fmt.Errorf("fetching existing {{ .Singular }} for merge-put: %w", ferr)
			}
			data = fullBody
			data, err = injectClassicFileFields(data, "{{ .Singular }}", []classicFileFieldSpec{
{{ range .FileFields }}				{FilePath: flag{{ lookupCamel .Flag }}, ParentPath: {{ parentPathLiteral .XMLPath }}, LeafName: "{{ leafName .XMLPath }}", Encoding: "{{ .Encoding }}", NameFallback: "{{ .NameFallback }}"},
{{ end }}			})
			if err != nil {
				return err
			}
{{ end }}
{{ if .IsConfigProfile }}
			// Preserve existing PayloadUUID and PayloadIdentifier.
			existingPayload := fetchClassicProfilePayloadPlist(reqCtx, ctx.Client, "{{ .Path }}", id)
			data = injectClassicProfilePayloadUUIDs(data, existingPayload)
			data = injectClassicRedeployOnUpdate(data)
			data = normalizeClassicProfilePayloadsForSend(data)

			updatePath := fmt.Sprintf("/JSSResource/{{ .Path }}/{{ idPath . }}/%s", url.PathEscape(id))
			resp, err := ctx.Client.Do(reqCtx, "PUT", updatePath, bytes.NewReader(data))
			if err != nil {
				return err
			}
			verifyClassicProfileStored(reqCtx, ctx.Client, "{{ .Path }}", id, data)
{{ else }}
			updatePath := fmt.Sprintf("/JSSResource/{{ .Path }}/{{ idPath . }}/%s", url.PathEscape(id))
			resp, err := ctx.Client.Do(reqCtx, "PUT", updatePath, bytes.NewReader(data))
			if err != nil {
				return err
			}
{{ end }}
			defer resp.Body.Close()
			fmt.Fprintf(os.Stderr, "Replaced {{ .Singular }} %q (id: %s)\n", name, id)
			return ctx.Output.PrintResponse(resp)
		},
	}

	cmd.Flags().StringVar(&fromFile, "from-file", "", "Path to XML input file (or pipe XML to stdin)")
	cmd.Flags().BoolVar(&flagYes, "yes", false, "Skip confirmation prompt when replacing")
	cmd.Flags().BoolVarP(&flagDryRun, "dry-run", "n", false, "Preview without executing")
{{ if hasFetchMergePut . }}	cmd.Flags().StringVar(&flagName, "name", "", "Name of the existing {{ .Singular }} to update (required when body is empty)")
{{ end }}{{ if .FileFields }}
{{ range .FileFields }}	cmd.Flags().StringVar(&flag{{ lookupCamel .Flag }}, "{{ .Flag }}", "", "{{ .Desc }}")
{{ end }}{{ end }}{{ if .HasCustomPayload }}	cmd.Flags().StringArrayVar(&flagCustomPayloadFiles, "custom-payload-file", nil, "Path to a preference plist (XML or binary); wrapped into a com.apple.ManagedClient.preferences payload (repeatable; mutually exclusive with --mobileconfig-file)")
	cmd.Flags().StringVar(&flagCustomPayloadDomain, "custom-payload-domain", "", "Preference domain override (inferred from filename by default; only valid with a single --custom-payload-file)")
{{ if not (hasFetchMergePut .) }}	cmd.Flags().StringVar(&flagName, "name", "", "Profile name (overrides filename-based default when using --custom-payload-file)")
{{ end }}{{ end }}
	return cmd
}
{{ end }}
`

const classicRegistryTemplate = `// Copyright 2026, Jamf Software LLC
// Code generated by jamf-cli generator (classic). DO NOT EDIT.
package generated

import (
{{- if or (anyNeedsClassicNameResolve .) (anyClassicFileFields .) (anyHasGroupPath .) }}
	"context"
	"encoding/json"
	"encoding/xml"
	"io"
	"os"
	"path/filepath"
	"strings"
{{- end }}
{{- if anyIsConfigProfile . }}
	"strconv"
{{- end }}
{{- if or (anyNeedsClassicNameResolve .) (anyClassicFileFields .) (anyListSubset .) (anyHasGroupPath .) }}
	"fmt"
{{- end }}
{{- if or (anyIsConfigProfile .) (anyClassicFileFields .) (anyListSubset .) (anyClassicExtraLookups .) (anyHasGroupPath .) }}
	"bytes"
{{- end }}
{{- if or (anyIsConfigProfile .) (anyClassicFileFields .) (anyClassicExtraLookups .) }}
	"net/url"
{{- end }}
{{- if anyHasCustomPayload . }}
	"crypto/rand"
{{- end }}

	"github.com/spf13/cobra"

	"github.com/Jamf-Concepts/jamf-cli/internal/registry"
{{- if anyClassicExtraLookups . }}
	"github.com/Jamf-Concepts/jamf-cli/internal/exitcode"
{{- end }}
{{- if or (anyNeedsClassicNameResolve .) (anyClassicFileFields .) (anyListSubset .) }}
	"github.com/Jamf-Concepts/jamf-cli/internal/xmlconv"
{{- end }}
{{- if or (anyIsConfigProfile .) (anyClassicFileFields .) }}
	"github.com/Jamf-Concepts/jamf-cli/internal/profileconvert"
{{- end }}
{{- if anyHasCustomPayload . }}
	"howett.net/plist"
{{- end }}
)

// RegisterClassicCommands registers all Classic API resource commands.
func RegisterClassicCommands(root *cobra.Command, ctx *registry.CLIContext) {
{{- range . }}
	root.AddCommand(New{{ .GoName }}Cmd(ctx))
{{- end }}
}
{{ if anyNeedsClassicNameResolve . }}
// Classic apply/delete-by-name helpers. These share the generated package with
// registry.go and depend on readApplyInput and extractIDString defined there.

// extractClassicName extracts the resource name from XML input.
// It tries direct-child "name" first, then checks under common sub-elements
// like "general". The singularKey is the XML wrapper element (e.g., "policy").
func extractClassicName(data []byte, singularKey string) (string, error) {
	m, err := xmlconv.ToMap(data)
	if err != nil {
		return "", fmt.Errorf("parsing XML: %w", err)
	}

	// Unwrap the root element if it matches the singular key
	inner, ok := m[singularKey]
	if !ok {
		// Try without wrapper (user may omit it)
		inner = m
	}

	obj, ok := inner.(map[string]any)
	if !ok {
		return "", fmt.Errorf("unexpected XML structure")
	}

	// Direct name field
	if name, ok := obj["name"].(string); ok && name != "" {
		return name, nil
	}

	// Check under "general" sub-element (policies, profiles, etc.)
	if general, ok := obj["general"].(map[string]any); ok {
		if name, ok := general["name"].(string); ok && name != "" {
			return name, nil
		}
	}

	return "", fmt.Errorf("could not find 'name' field in XML input")
}

// resolveClassicNameToIDForApply looks up a classic resource by name using
// the list endpoint. Returns all matching IDs for collision detection.
// Returns ("", nil) when no resource is found (caller should create).
// Returns (id, nil) when exactly one match is found.
// Returns ("", error) when multiple matches or lookup fails.
func resolveClassicNameToIDForApply(ctx context.Context, client registry.HTTPClient, apiPath, wrapperKey, name string, noInput bool) (string, error) {
	resp, err := client.Do(ctx, "GET", "/JSSResource/"+apiPath, nil)
	if err != nil {
		return "", fmt.Errorf("listing resources: %w", err)
	}
	defer func() { _ = resp.Body.Close() }()

	body, err := io.ReadAll(resp.Body)
	if err != nil {
		return "", fmt.Errorf("reading list response: %w", err)
	}

	var items []map[string]any
	if xmlconv.IsXML(body) {
		items, err = xmlconv.ExtractListItems(body)
		if err != nil {
			return "", fmt.Errorf("parsing XML list: %w", err)
		}
	} else {
		// JSON fallback
		var wrapper map[string]json.RawMessage
		if err := json.Unmarshal(body, &wrapper); err == nil {
			if inner, ok := wrapper[wrapperKey]; ok {
				_ = json.Unmarshal(inner, &items)
			}
		}
	}

	// Filter by case-insensitive name match (consistent with classicFindIDByName).
	type classicMatch struct {
		id string
	}
	var matches []classicMatch
	for _, item := range items {
		itemName, _ := item["name"].(string)
		if strings.EqualFold(itemName, name) {
			if id := extractIDString(item, "id"); id != "" {
				matches = append(matches, classicMatch{id: id})
			}
		}
	}

	if len(matches) == 0 {
		return "", nil
	}
	if len(matches) == 1 {
		return matches[0].id, nil
	}

	// Collision: multiple resources with the same name
	if noInput {
		ids := make([]string, len(matches))
		for i, m := range matches {
			ids[i] = m.id
		}
		return "", fmt.Errorf("multiple resources found with name %q (IDs: %s); resolve duplicates or use update with a specific ID", name, strings.Join(ids, ", "))
	}

	// Interactive: prompt user to pick
	fmt.Fprintf(os.Stderr, "Multiple resources found with name %q:\n", name)
	for i, m := range matches {
		fmt.Fprintf(os.Stderr, "  [%d] ID: %s\n", i+1, m.id)
	}
	fmt.Fprintf(os.Stderr, "Enter number to replace (or 0 to cancel): ")
	var choice int
	if _, err := fmt.Fscan(os.Stdin, &choice); err != nil || choice < 1 || choice > len(matches) {
		return "", fmt.Errorf("aborted")
	}
	return matches[choice-1].id, nil
}
{{ end }}
{{ if anyClassicExtraLookups . }}
// resolveClassicLookupToID resolves a Classic API resource by a path-based lookup
// (e.g. /JSSResource/mobiledevices/serialnumber/{value}) and returns its numeric id.
// Returns ("", nil) when not found; ("", err) on failure.
func resolveClassicLookupToID(ctx context.Context, client registry.HTTPClient, basePath, value string) (string, error) {
	path := fmt.Sprintf("%s/%s", basePath, registry.EscapeClassicPathSegment(value))
	resp, err := client.Do(ctx, "GET", path, nil)
	if err != nil {
		if exitcode.CodeFrom(err) == exitcode.NotFound {
			return "", nil
		}
		return "", err
	}
	defer func() { _ = resp.Body.Close() }()
	body, err := io.ReadAll(io.LimitReader(resp.Body, 1<<20))
	if err != nil {
		return "", fmt.Errorf("reading lookup response: %w", err)
	}
	// Classic API resources return <id> either as a direct child of the root
	// element or nested under <general> (e.g. mobile_device, computer).
	var result struct {
		IDDirect  string ` + "`" + `xml:"id"` + "`" + `
		IDGeneral string ` + "`" + `xml:"general>id"` + "`" + `
	}
	if err := xml.NewDecoder(bytes.NewReader(body)).Decode(&result); err != nil {
		return "", nil
	}
	if result.IDDirect != "" {
		return result.IDDirect, nil
	}
	return result.IDGeneral, nil
}
{{ end }}
{{ if anyIsConfigProfile . }}
// fetchClassicProfileByName fetches a Classic config profile by name and returns
// its numeric ID and existing payload plist in a single API call. Returns ("", nil)
// when not found; callers should proceed without UUID injection if payload is nil.
//
// Errors (including non-404 server errors) are silently swallowed — UUID
// preservation is best-effort and must never block an update.
func fetchClassicProfileByName(ctx context.Context, client registry.HTTPClient, apiPath, name string) (id string, payloadPlist []byte) {
	path := fmt.Sprintf("/JSSResource/%s/name/%s", apiPath, registry.EscapeClassicPathSegment(name))
	resp, err := client.Do(ctx, "GET", path, nil)
	if err != nil {
		return "", nil
	}
	defer func() { _ = resp.Body.Close() }()

	body, err := io.ReadAll(resp.Body)
	if err != nil {
		return "", nil
	}

	if !xmlconv.IsXML(body) {
		return "", nil
	}

	m, err := xmlconv.ToMap(body)
	if err != nil {
		return "", nil
	}

	for _, rootVal := range m {
		if root, ok := rootVal.(map[string]any); ok {
			if general, ok := root["general"].(map[string]any); ok {
				id = extractIDString(general, "id")
				if payloads, ok := general["payloads"].(string); ok {
					payloadPlist = []byte(payloads)
				}
				return id, payloadPlist
			}
		}
	}
	return "", nil
}

// fetchClassicProfilePayloadPlist fetches the payload plist for an existing
// Classic config profile via the /subset/General endpoint. Returns nil when
// the payload cannot be fetched; callers should proceed without UUID injection.
func fetchClassicProfilePayloadPlist(ctx context.Context, client registry.HTTPClient, apiPath, id string) []byte {
	path := fmt.Sprintf("/JSSResource/%s/id/%s/subset/General", apiPath, url.PathEscape(id))
	resp, err := client.Do(ctx, "GET", path, nil)
	if err != nil {
		return nil
	}
	defer func() { _ = resp.Body.Close() }()

	body, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil
	}

	if !xmlconv.IsXML(body) {
		return nil
	}

	m, err := xmlconv.ToMap(body)
	if err != nil {
		return nil
	}

	for _, rootVal := range m {
		if root, ok := rootVal.(map[string]any); ok {
			if general, ok := root["general"].(map[string]any); ok {
				if payloads, ok := general["payloads"].(string); ok && payloads != "" {
					return []byte(payloads)
				}
			}
		}
	}
	return nil
}

// replaceClassicProfilePayload replaces the <payloads> CDATA block in a Classic
// API config profile XML body with newPayload. The replacement targets only the
// <payloads> element used by osxconfigurationprofiles and
// mobiledeviceconfigurationprofiles. Returns xmlBody unchanged when no
// <payloads> element is present.
func replaceClassicProfilePayload(xmlBody, newPayload []byte) []byte {
	const openTag = "<payloads>"
	const closeTag = "</payloads>"

	si := bytes.Index(xmlBody, []byte(openTag))
	ei := bytes.Index(xmlBody, []byte(closeTag))
	if si == -1 || ei == -1 || si >= ei {
		return xmlBody
	}

	var buf bytes.Buffer
	buf.Write(xmlBody[:si])
	buf.WriteString(openTag + "<![CDATA[")
	// Guard "]]>" so the payload can never terminate the CDATA section early
	// (XML 1.0 §2.4/§2.7).
	buf.Write(bytes.ReplaceAll(newPayload, []byte("]]>"), []byte("]]&gt;")))
	buf.WriteString("]]>" + closeTag)
	buf.Write(xmlBody[ei+len(closeTag):])
	return buf.Bytes()
}

// injectClassicProfilePayloadUUIDs extracts the mobileconfig plist from xmlBody,
// injects PayloadUUID and PayloadIdentifier from existingPayload, and returns the
// modified XML body. Returns xmlBody unchanged on any failure (best-effort).
func injectClassicProfilePayloadUUIDs(xmlBody, existingPayload []byte) []byte {
	if len(existingPayload) == 0 {
		return xmlBody
	}

	m, err := xmlconv.ToMap(xmlBody)
	if err != nil {
		return xmlBody
	}

	var newPayloadPlist []byte
	for _, rootVal := range m {
		if root, ok := rootVal.(map[string]any); ok {
			if general, ok := root["general"].(map[string]any); ok {
				if payloads, ok := general["payloads"].(string); ok && payloads != "" {
					newPayloadPlist = []byte(payloads)
					break
				}
			}
		}
	}

	if len(newPayloadPlist) == 0 {
		return xmlBody
	}

	modified, err := profileconvert.InjectIdentifiers(newPayloadPlist, existingPayload)
	if err != nil {
		return xmlBody
	}

	return replaceClassicProfilePayload(xmlBody, modified)
}

// injectClassicRedeployOnUpdate ensures <redeploy_on_update>All</redeploy_on_update>
// is present inside <general>. If the XML already contains <redeploy_on_update>
// (e.g. supplied by the caller), the existing value is left unchanged.
func injectClassicRedeployOnUpdate(body []byte) []byte {
	s := string(body)
	if strings.Contains(s, "<redeploy_on_update>") {
		return body
	}
	gOpen := strings.Index(s, "<general>")
	if gOpen < 0 {
		return body
	}
	insertAt := gOpen + len("<general>")
	return []byte(s[:insertAt] + "<redeploy_on_update>All</redeploy_on_update>" + s[insertAt:])
}

// stripCDATASections rewrites every <![CDATA[...]]> section in an XML
// document as equivalent escaped character data. The parsed document is
// unchanged (CDATA content is literal text by definition — XML 1.0 §2.7),
// but the literal "]]>" terminators disappear, so the result can itself be
// CDATA-wrapped. Content after an unterminated <![CDATA[ is left untouched.
func stripCDATASections(data []byte) []byte {
	s := string(data)
	esc := strings.NewReplacer("&", "&amp;", "<", "&lt;", ">", "&gt;")
	var b strings.Builder
	for {
		si := strings.Index(s, "<![CDATA[")
		if si < 0 {
			break
		}
		ei := strings.Index(s[si:], "]]>")
		if ei < 0 {
			break
		}
		b.WriteString(s[:si])
		b.WriteString(esc.Replace(s[si+len("<![CDATA[") : si+ei]))
		s = s[si+ei+len("]]>"):]
	}
	if b.Len() == 0 {
		return data
	}
	b.WriteString(s)
	return []byte(b.String())
}

// minimizeClassicPlistSourceEscaping decodes every character/entity
// reference in plist XML source EXCEPT those encoding "&" and "<" — e.g.
// "&quot;"/"&#34;" become a literal quote, "&#xA;" a literal newline,
// "&gt;" a literal ">". Both representations parse to identical values,
// but the wire representation is what the server's verbatim-stored
// payload types preserve (PI-827): avoidable references would surface as
// literal text in stored values. This matters for the update path, where
// injectClassicProfilePayloadUUIDs re-serialises the plist via
// howett.net/plist, whose encoding/xml backend escapes quotes and value
// newlines/tabs numerically.
func minimizeClassicPlistSourceEscaping(s string) string {
	var b strings.Builder
	for i := 0; i < len(s); {
		c := s[i]
		if c != '&' {
			b.WriteByte(c)
			i++
			continue
		}
		semi := strings.IndexByte(s[i:], ';')
		if semi < 0 || semi > 12 {
			b.WriteByte(c)
			i++
			continue
		}
		ref := s[i+1 : i+semi]
		var r rune = -1
		switch {
		case ref == "quot":
			r = '"'
		case ref == "apos":
			r = '\''
		case ref == "gt":
			r = '>'
		case strings.HasPrefix(ref, "#x") || strings.HasPrefix(ref, "#X"):
			if n, err := strconv.ParseInt(ref[2:], 16, 32); err == nil {
				r = rune(n)
			}
		case strings.HasPrefix(ref, "#"):
			if n, err := strconv.ParseInt(ref[1:], 10, 32); err == nil {
				r = rune(n)
			}
		}
		if r < 0 || r == '&' || r == '<' {
			b.WriteString(s[i : i+semi+1])
		} else {
			b.WriteRune(r)
		}
		i += semi + 1
	}
	return b.String()
}

// normalizeClassicProfilePayloadsForSend rewrites the <payloads> element
// into the only wire form the Classic API accepts for entity-bearing
// plists, immediately before the request is sent: the plist inside a
// single CDATA section with source escaping minimised (see
// minimizeClassicPlistSourceEscaping), "]]>" entity-guarded, and every
// "&" escaped once.
// Text-form payloads (e.g. a GET/backup response piped back in) are
// entity-decoded once to recover the plist first. Bodies without a
// non-empty <payloads> element are returned unchanged.
//
// Why the escape (PI-827, wire-verified 2026-07-30 on two tenants): the
// server validates payload content after one entity decode and 409s
// ("Unable to update the database") when that yields a bare "&" or "<" —
// so spec-correct raw CDATA is rejected for ANY plist containing "&amp;"
// or "&lt;", whatever the payload types. Storage is then per-payload-type:
// fragments of types the server re-renders (com.apple.ManagedClient
// .preferences custom settings, notification settings) are entity-decoded
// once — the escape stores them byte-exact — while other payload types'
// fragments are stored verbatim, keeping the extra layer. Profiles with
// "&"/"<" in values of those types cannot be stored faithfully by any
// client (verifyClassicProfileStored warns after the write).
func normalizeClassicProfilePayloadsForSend(body []byte) []byte {
	const openTag = "<payloads>"
	s := string(body)
	si := strings.Index(s, openTag)
	if si < 0 {
		return body
	}
	ci := si + len(openTag)
	var inner string
	var restAt int // index into s of the first byte after </payloads>
	if strings.HasPrefix(s[ci:], "<![CDATA[") {
		end := strings.Index(s[ci:], "]]></payloads>")
		if end < 0 {
			return body
		}
		inner = s[ci+len("<![CDATA[") : ci+end]
		restAt = ci + end + len("]]></payloads>")
	} else {
		end := strings.Index(s[ci:], "</payloads>")
		if end < 0 {
			return body
		}
		var decoded struct {
			Data string ` + "`" + `xml:",chardata"` + "`" + `
		}
		if err := xml.Unmarshal([]byte(openTag+s[ci:ci+end]+"</payloads>"), &decoded); err != nil {
			return body
		}
		inner = decoded.Data
		restAt = ci + end + len("</payloads>")
	}
	if inner == "" {
		return body
	}
	inner = minimizeClassicPlistSourceEscaping(inner)
	inner = strings.ReplaceAll(inner, "]]>", "]]&gt;")
	inner = strings.ReplaceAll(inner, "&", "&amp;")
	return []byte(s[:ci] + "<![CDATA[" + inner + "]]></payloads>" + s[restAt:])
}

// classicProfilePayloadFromBody returns the true plist inside the request
// body's <payloads> CDATA block, or nil. The block carries the normalizer's
// escaped form (every "&" escaped once); undoing that single escape — our
// own, exactly invertible — recovers the submitted plist for comparison
// against what the server stored.
func classicProfilePayloadFromBody(body []byte) []byte {
	s := string(body)
	si := strings.Index(s, "<payloads><![CDATA[")
	if si < 0 {
		return nil
	}
	ci := si + len("<payloads><![CDATA[")
	ei := strings.Index(s[ci:], "]]></payloads>")
	if ei < 0 {
		return nil
	}
	return []byte(strings.ReplaceAll(s[ci:ci+ei], "&amp;", "&"))
}

// classicCreatedResourceID extracts the numeric <id> from a Classic create
// response body, or "" when absent.
func classicCreatedResourceID(respBody []byte) string {
	s := string(respBody)
	si := strings.Index(s, "<id>")
	if si < 0 {
		return ""
	}
	ei := strings.Index(s[si:], "</id>")
	if ei < 0 {
		return ""
	}
	return s[si+len("<id>") : si+ei]
}

// verifyClassicProfileStored fetches the stored payload after a successful
// write and warns on stderr when the server did not store the submitted
// values faithfully. This is reachable for profiles that mix payload types
// with entities on the source-level side (PI-827) — no wire form can store
// those correctly, so surfacing the exact paths is the only honest
// behaviour. Best-effort: silent on any verification failure.
func verifyClassicProfileStored(ctx context.Context, client registry.HTTPClient, apiPath, id string, sentBody []byte) {
	intended := classicProfilePayloadFromBody(sentBody)
	if len(intended) == 0 || id == "" {
		return
	}
	stored := fetchClassicProfilePayloadPlist(ctx, client, apiPath, id)
	if len(stored) == 0 {
		return
	}
	diffs, err := profileconvert.DiffPayloadValues(intended, stored)
	if err != nil || len(diffs) == 0 {
		return
	}
	total := len(diffs)
	if total > 5 {
		diffs = append(diffs[:5], "…")
	}
	fmt.Fprintf(os.Stderr, "warning: the server stored %d payload value(s) differently than submitted (Jamf PI-827 — no wire format stores this mix of payload types faithfully): %s\n", total, strings.Join(diffs, ", "))
}
{{ end }}
{{ if anyClassicFileFields . }}
// classicFileFieldSpec describes one Classic XML field sourced from a local file or in-memory bytes.
type classicFileFieldSpec struct {
	FilePath     string   // user-supplied path (empty = skip when FileBytes also nil)
	FileBytes    []byte   // alternative to FilePath; used when content is built in memory
	FileNameHint string   // path hint used with FileBytes for NameFallback (filepath.Base applied internally)
	ParentPath   []string // path to the immediate parent element under the root (e.g. ["general"])
	LeafName     string   // name of the element receiving the file contents (e.g. "payloads")
	Encoding     string   // "xml-cdata" | "raw"
	NameFallback string   // "none" | "keep-ext" | "strip-ext"
}

// injectClassicFileFields overlays file-sourced XML fields into body. The body
// may be empty or missing the target path entirely; missing ancestors are
// constructed. File contents overwrite any existing leaf value; name fallback
// adds a name element under the parent's sibling "general" only when absent.
func injectClassicFileFields(body []byte, rootName string, specs []classicFileFieldSpec) ([]byte, error) {
	active := false
	for _, s := range specs {
		if s.FilePath != "" || len(s.FileBytes) > 0 {
			active = true
			break
		}
	}
	if !active {
		return body, nil
	}

	bodyStr := string(bytes.TrimSpace(body))
	if bodyStr == "" {
		bodyStr = "<" + rootName + "></" + rootName + ">"
	}

	for _, s := range specs {
		if s.FilePath == "" && len(s.FileBytes) == 0 {
			continue
		}
		var data []byte
		var nameForFallback string
		if len(s.FileBytes) > 0 {
			data = s.FileBytes
			nameForFallback = filepath.Base(s.FileNameHint)
		} else {
			var err error
			data, err = os.ReadFile(s.FilePath)
			if err != nil {
				return nil, fmt.Errorf("reading %s: %w", s.FilePath, err)
			}
			nameForFallback = filepath.Base(s.FilePath)
		}
		var inner string
		if s.Encoding == "xml-cdata" {
			if profileconvert.IsSignedProfile(data) {
				// CMS-signed mobileconfig — extract the inner plist. The
				// signature cannot survive this API anyway: the server
				// re-serialises the plist on ingest.
				if unsigned, err := profileconvert.ExtractSignedProfile(data); err == nil {
					fmt.Fprintln(os.Stderr, "note: input is a signed mobileconfig; uploading the inner profile (the Classic API cannot preserve the signature)")
					data = unsigned
				}
			}
			if bytes.HasPrefix(data, []byte("bplist0")) {
				// Binary plist — convert to XML so it can be embedded at all.
				if normalized, err := profileconvert.NormalizeXML(data); err == nil {
					data = normalized
				}
			}
			if bytes.Contains(data, []byte("]]>")) {
				// "]]>" would terminate the CDATA wrapper early (XML 1.0
				// §2.4/§2.7). Embedded CDATA sections are the one way a valid
				// plist contains it — rewrite them as escaped character data
				// (byte-faithful, no plist parsing), then entity-guard any
				// stray remainder from malformed input.
				data = stripCDATASections(data)
				data = bytes.ReplaceAll(data, []byte("]]>"), []byte("]]&gt;"))
			}
			inner = "<![CDATA[" + string(data) + "]]>"
		} else {
			inner = string(data)
		}
		wrapped := "<" + s.LeafName + ">" + inner + "</" + s.LeafName + ">"

		// Replace an existing leaf anywhere in the body. Safe for our known
		// XML shapes because "payloads"/"preferences" only appear inside their
		// expected parents.
		openTag := "<" + s.LeafName + ">"
		closeTag := "</" + s.LeafName + ">"
		if si := strings.Index(bodyStr, openTag); si >= 0 {
			if ei := strings.Index(bodyStr[si:], closeTag); ei >= 0 {
				bodyStr = bodyStr[:si] + wrapped + bodyStr[si+ei+len(closeTag):]
			} else {
				return nil, fmt.Errorf("malformed XML: %s opens without close", openTag)
			}
		} else {
			// Insert before </parent>. If the parent is missing, build the path.
			parentName := s.ParentPath[len(s.ParentPath)-1]
			parentClose := "</" + parentName + ">"
			if idx := strings.Index(bodyStr, parentClose); idx >= 0 {
				bodyStr = bodyStr[:idx] + wrapped + bodyStr[idx:]
			} else {
				build := wrapped
				for i := len(s.ParentPath) - 1; i >= 0; i-- {
					build = "<" + s.ParentPath[i] + ">" + build + "</" + s.ParentPath[i] + ">"
				}
				rootClose := "</" + rootName + ">"
				if idx := strings.LastIndex(bodyStr, rootClose); idx >= 0 {
					bodyStr = bodyStr[:idx] + build + bodyStr[idx:]
				} else {
					return nil, fmt.Errorf("root </%s> not found in body", rootName)
				}
			}
		}

		if s.NameFallback != "" && s.NameFallback != "none" {
			// Only fill a name if one isn't already present under <general>.
			// Users often provide scope/category with their own <name> elements —
			// those are distinct, so we target <general><name> specifically.
			if !hasClassicGeneralName(bodyStr) {
				nm := nameForFallback
				if s.NameFallback == "strip-ext" {
					if dot := strings.LastIndex(nm, "."); dot > 0 {
						nm = nm[:dot]
					}
				}
				nameEl := "<name>" + classicXMLEscape(nm) + "</name>"
				if gi := strings.Index(bodyStr, "</general>"); gi >= 0 {
					bodyStr = bodyStr[:gi] + nameEl + bodyStr[gi:]
				} else if ri := strings.LastIndex(bodyStr, "</"+rootName+">"); ri >= 0 {
					bodyStr = bodyStr[:ri] + "<general>" + nameEl + "</general>" + bodyStr[ri:]
				}
			}
		}
	}
	return []byte(bodyStr), nil
}

// hasClassicGeneralName returns true if <general>…<name>…</name>…</general>
// appears in the XML body.
func hasClassicGeneralName(bodyStr string) bool {
	gOpen := strings.Index(bodyStr, "<general>")
	if gOpen < 0 {
		return false
	}
	gClose := strings.Index(bodyStr[gOpen:], "</general>")
	if gClose < 0 {
		return false
	}
	inner := bodyStr[gOpen : gOpen+gClose]
	return strings.Contains(inner, "<name>")
}

// classicXMLEscape escapes reserved characters for an XML text node.
func classicXMLEscape(s string) string {
	var b strings.Builder
	_ = xml.EscapeText(&b, []byte(s))
	return b.String()
}

{{ if anyHasCustomPayload . }}
// newProfileUUID returns a random RFC 4122 v4 UUID string (uppercase, hyphenated).
func newProfileUUID() string {
	var b [16]byte
	_, _ = rand.Read(b[:])
	b[6] = (b[6] & 0x0f) | 0x40 // version 4
	b[8] = (b[8] & 0x3f) | 0x80 // variant bits
	return fmt.Sprintf("%X-%X-%X-%X-%X", b[0:4], b[4:6], b[6:8], b[8:10], b[10:16])
}

// buildCustomPayloadMobileconfig constructs a com.apple.ManagedClient.preferences
// mobileconfig plist from one or more preference plist files. Each file's parsed
// contents become the mcx_preference_settings for its preference domain. The
// domain is inferred from the filename (extension stripped) unless domain is set,
// which is only valid when len(files)==1.
func buildCustomPayloadMobileconfig(files []string, domain string) ([]byte, error) {
	if domain != "" && len(files) != 1 {
		return nil, fmt.Errorf("--custom-payload-domain requires exactly one --custom-payload-file")
	}
	var payloadContent []any
	for _, file := range files {
		raw, err := os.ReadFile(file)
		if err != nil {
			return nil, fmt.Errorf("reading %s: %w", file, err)
		}
		var settings map[string]any
		if _, err := plist.Unmarshal(raw, &settings); err != nil {
			return nil, fmt.Errorf("parsing plist %s: %w", file, err)
		}
		d := domain
		if d == "" {
			base := filepath.Base(file)
			if dot := strings.LastIndex(base, "."); dot > 0 {
				d = base[:dot]
			} else {
				d = base
			}
		}
		innerUUID := newProfileUUID()
		payloadContent = append(payloadContent, map[string]any{
			"PayloadDisplayName":  "Custom Settings",
			"PayloadIdentifier":   innerUUID,
			"PayloadOrganization": "JAMF Software",
			"PayloadType":         "com.apple.ManagedClient.preferences",
			"PayloadUUID":         innerUUID,
			"PayloadVersion":      1,
			"PayloadContent": map[string]any{
				d: map[string]any{
					"Forced": []any{
						map[string]any{"mcx_preference_settings": settings},
					},
				},
			},
		})
	}
	outerUUID := newProfileUUID()
	profile := map[string]any{
		"PayloadUUID":              outerUUID,
		"PayloadType":              "Configuration",
		"PayloadOrganization":      "JAMF Software",
		"PayloadIdentifier":        outerUUID,
		"PayloadDisplayName":       "Custom",
		"PayloadDescription":       "",
		"PayloadVersion":           1,
		"PayloadEnabled":           true,
		"PayloadRemovalDisallowed": true,
		"PayloadScope":             "System",
		"PayloadContent":           payloadContent,
	}
	return plist.MarshalIndent(profile, plist.XMLFormat, "\t")
}

// setClassicGeneralName sets or replaces the <name> element inside <general>
// in a Classic API XML body. When body is empty, a minimal root element is
// created. Used by apply --name to override the NameFallback-derived name.
func setClassicGeneralName(body []byte, rootName, name string) []byte {
	nameEl := "<name>" + classicXMLEscape(name) + "</name>"
	s := strings.TrimSpace(string(body))
	if s == "" {
		return []byte("<" + rootName + "><general>" + nameEl + "</general></" + rootName + ">")
	}
	gOpen := strings.Index(s, "<general>")
	if gOpen < 0 {
		// No <general>: insert before closing root tag.
		if ri := strings.LastIndex(s, "</"+rootName+">"); ri >= 0 {
			s = s[:ri] + "<general>" + nameEl + "</general>" + s[ri:]
		}
		return []byte(s)
	}
	gClose := strings.Index(s[gOpen:], "</general>")
	if gClose < 0 {
		return []byte(s)
	}
	gClose += gOpen
	inner := s[gOpen+len("<general>") : gClose]
	if nOpen := strings.Index(inner, "<name>"); nOpen >= 0 {
		if nClose := strings.Index(inner[nOpen:], "</name>"); nClose >= 0 {
			inner = inner[:nOpen] + nameEl + inner[nOpen+nClose+len("</name>"):]
			return []byte(s[:gOpen+len("<general>")] + inner + s[gClose:])
		}
	}
	// No existing <name>: prepend inside <general>.
	return []byte(s[:gOpen+len("<general>")] + nameEl + inner + s[gClose:])
}
{{ end }}
// fetchClassicFullXMLByName fetches a Classic resource's full XML body by name,
// returning the bytes and its ID. Used by apply for resources that need
// fetch-merge-put semantics (e.g. mac/mobile app AppConfig). Returns an error
// if the API responds with a non-2xx status so the caller doesn't PUT back an
// HTML error page as the "existing record".
func fetchClassicFullXMLByName(ctx context.Context, client registry.HTTPClient, apiPath, name string) (id string, body []byte, err error) {
	path := fmt.Sprintf("/JSSResource/%s/name/%s", apiPath, registry.EscapeClassicPathSegment(name))
	resp, err := client.Do(ctx, "GET", path, nil)
	if err != nil {
		return "", nil, err
	}
	defer func() { _ = resp.Body.Close() }()
	body, err = io.ReadAll(resp.Body)
	if err != nil {
		return "", nil, fmt.Errorf("reading GET %s: %w", path, err)
	}
	if resp.StatusCode >= 400 {
		return "", nil, fmt.Errorf("GET %s returned %d: %s", path, resp.StatusCode, string(body))
	}
	m, mapErr := xmlconv.ToMap(body)
	if mapErr == nil {
		for _, rootVal := range m {
			if root, ok := rootVal.(map[string]any); ok {
				if general, ok := root["general"].(map[string]any); ok {
					id = extractIDString(general, "id")
				}
			}
		}
	}
	return id, body, nil
}
{{ end }}
{{ if anyListSubset . }}
// sliceClassicListSubsetXML returns the <subset>...</subset> subtree from a
// combined Classic API XML response, prefixed with the XML declaration. This
// preserves the exact wire format so pretty-printed XML (and -o raw) match what
// other classic list commands emit. When the subset element is absent or
// malformed, the body is returned unchanged.
func sliceClassicListSubsetXML(body []byte, subset string) []byte {
	openTag := []byte("<" + subset + ">")
	closeTag := []byte("</" + subset + ">")
	si := bytes.Index(body, openTag)
	ei := bytes.Index(body, closeTag)
	if si < 0 || ei < 0 || ei < si {
		// Also handle self-closing <subset/>.
		if bytes.Contains(body, []byte("<"+subset+"/>")) {
			return []byte(` + "`" + `<?xml version="1.0" encoding="UTF-8"?><` + "`" + ` + subset + ` + "`" + `/>` + "`" + `)
		}
		return body
	}
	subtree := body[si : ei+len(closeTag)]
	out := make([]byte, 0, len(subtree)+64)
	out = append(out, []byte(` + "`" + `<?xml version="1.0" encoding="UTF-8"?>` + "`" + `)...)
	out = append(out, subtree...)
	return out
}

// extractClassicListSubset parses the combined Classic API XML response and
// returns the repeated items under the named subset element (e.g. "users" or
// "groups" under <accounts>). An absent or self-closing subset returns an empty
// slice — the caller can still format "No results" cleanly.
func extractClassicListSubset(body []byte, subset string) ([]map[string]any, error) {
	m, err := xmlconv.ToMap(body)
	if err != nil {
		return nil, fmt.Errorf("parsing XML: %w", err)
	}
	var rootVal any
	for _, v := range m {
		rootVal = v
		break
	}
	rootMap, ok := rootVal.(map[string]any)
	if !ok {
		return []map[string]any{}, nil
	}
	subVal, ok := rootMap[subset]
	if !ok {
		return []map[string]any{}, nil
	}
	subMap, ok := subVal.(map[string]any)
	if !ok {
		// Empty <users/> or <users></users> comes through as "" — treat as empty.
		return []map[string]any{}, nil
	}
	var items []map[string]any
	for _, v := range subMap {
		switch vv := v.(type) {
		case map[string]any:
			items = append(items, vv)
		case []any:
			for _, it := range vv {
				if im, ok := it.(map[string]any); ok {
					items = append(items, im)
				}
			}
		}
	}
	if items == nil {
		items = []map[string]any{}
	}
	return items, nil
}
{{ end }}
{{ if anyHasGroupPath . }}
// fetchClassicGroupMemberIDs resolves a Classic API group by name (or numeric ID)
// and returns the member resource IDs. groupsPath is e.g. "/JSSResource/mobiledevicegroups";
// membersKey is the XML container element ("mobile_devices"); memberKey is the XML
// singular element ("mobile_device").
func fetchClassicGroupMemberIDs(ctx context.Context, client registry.HTTPClient, groupsPath, membersKey, memberKey, nameOrID string) ([]string, error) {
	groupID := nameOrID
	if !isNumericID(nameOrID) {
		resp, err := client.Do(ctx, "GET", groupsPath, nil)
		if err != nil {
			return nil, fmt.Errorf("listing groups: %w", err)
		}
		defer func() { _ = resp.Body.Close() }()
		body, err := io.ReadAll(io.LimitReader(resp.Body, 4<<20))
		if err != nil {
			return nil, err
		}
		groupID = classicFindIDByName(body, nameOrID)
		if groupID == "" {
			return nil, fmt.Errorf("group %q not found", nameOrID)
		}
	}

	resp, err := client.Do(ctx, "GET", groupsPath+"/id/"+groupID, nil)
	if err != nil {
		return nil, fmt.Errorf("fetching group %s: %w", groupID, err)
	}
	defer func() { _ = resp.Body.Close() }()
	body, err := io.ReadAll(io.LimitReader(resp.Body, 4<<20))
	if err != nil {
		return nil, err
	}

	dec := xml.NewDecoder(bytes.NewReader(body))
	var stack []string
	var ids []string
	var curID string
	for {
		tok, err := dec.Token()
		if err != nil {
			break
		}
		switch t := tok.(type) {
		case xml.StartElement:
			stack = append(stack, t.Name.Local)
		case xml.EndElement:
			n := len(stack)
			if n >= 2 && stack[n-1] == memberKey && stack[n-2] == membersKey && curID != "" {
				ids = append(ids, curID)
				curID = ""
			}
			if n > 0 {
				stack = stack[:n-1]
			}
		case xml.CharData:
			n := len(stack)
			if n >= 3 && stack[n-1] == "id" && stack[n-2] == memberKey && stack[n-3] == membersKey {
				curID = strings.TrimSpace(string(t))
			}
		}
	}
	return ids, nil
}

// classicFindIDByName parses a Classic API XML list response and returns the
// <id> of the first item whose <name> matches (case-insensitive).
func classicFindIDByName(body []byte, name string) string {
	dec := xml.NewDecoder(bytes.NewReader(body))
	var stack []string
	var curID, curName string
	for {
		tok, err := dec.Token()
		if err != nil {
			break
		}
		switch t := tok.(type) {
		case xml.StartElement:
			stack = append(stack, t.Name.Local)
			if len(stack) == 2 {
				curID = ""
				curName = ""
			}
		case xml.EndElement:
			n := len(stack)
			if n == 2 && strings.EqualFold(curName, name) && curID != "" {
				return curID
			}
			if n > 0 {
				stack = stack[:n-1]
			}
		case xml.CharData:
			n := len(stack)
			if n == 3 {
				val := strings.TrimSpace(string(t))
				switch stack[n-1] {
				case "id":
					curID = val
				case "name":
					curName = val
				}
			}
		}
	}
	return ""
}
{{ end }}
{{ if anyHasSubsets . }}
// resolveClassicRecordID fetches a Classic record by a non-id lookup path (no
// /subset/) and returns its id, so a {lookup}/{val}/subset/... request can be
// rewritten to id/{id}/subset/... — the only form the Platform Gateway's Classic
// proxy allows (non-id + /subset/ returns 403). See
// docs/solutions/conventions/scope-put-avoid-subset-2026-07-08.md.
func resolveClassicRecordID(ctx context.Context, client registry.HTTPClient, path, singularKey string) (string, error) {
	resp, err := client.Do(ctx, "GET", path, nil)
	if err != nil {
		return "", fmt.Errorf("resolving record id: %w", err)
	}
	defer func() { _ = resp.Body.Close() }()
	body, err := io.ReadAll(resp.Body)
	if err != nil {
		return "", fmt.Errorf("reading record for id resolution: %w", err)
	}
	m, err := xmlconv.ToMap(body)
	if err != nil {
		return "", fmt.Errorf("parsing record for id resolution: %w", err)
	}
	obj, ok := m[singularKey].(map[string]any)
	if !ok {
		obj = m
	}
	if id := extractIDString(obj, "id"); id != "" {
		return id, nil
	}
	// History records nest the id under <general>.
	if general, ok := obj["general"].(map[string]any); ok {
		if id := extractIDString(general, "id"); id != "" {
			return id, nil
		}
	}
	return "", fmt.Errorf("could not resolve id from record at %s", path)
}
{{ end }}
`
