package classic

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"text/template"

	"github.com/iancoleman/strcase"
)

// Generator generates Go command files from ClassicResource definitions.
type Generator struct {
	outputDir string
}

// NewGenerator creates a new Classic API code generator.
func NewGenerator(outputDir string) *Generator {
	return &Generator{outputDir: outputDir}
}

// Generate writes a Go command file for a single Classic API resource.
func (g *Generator) Generate(resource ClassicResource) (string, error) {
	tmpl, err := template.New("classic_resource").Funcs(templateFuncs()).Parse(classicResourceTemplate)
	if err != nil {
		return "", fmt.Errorf("parsing template: %w", err)
	}

	filename := fmt.Sprintf("classic_%s.go", strings.ReplaceAll(resource.CLIName, "-", "_"))
	// strip the leading "classic_classic_" that would result from cli_name already containing "classic-"
	filename = strings.Replace(filename, "classic_classic_", "classic_", 1)
	outPath := filepath.Join(g.outputDir, filename)

	f, err := os.Create(outPath)
	if err != nil {
		return "", fmt.Errorf("creating file: %w", err)
	}
	defer func() { _ = f.Close() }()

	if err := tmpl.Execute(f, resource); err != nil {
		return "", fmt.Errorf("executing template: %w", err)
	}

	return outPath, nil
}

// GenerateRegistry writes the classic_registry.go file that registers all Classic commands.
func (g *Generator) GenerateRegistry(resources []ClassicResource) (string, error) {
	tmpl, err := template.New("classic_registry").Parse(classicRegistryTemplate)
	if err != nil {
		return "", fmt.Errorf("parsing template: %w", err)
	}

	outPath := filepath.Join(g.outputDir, "classic_registry.go")

	f, err := os.Create(outPath)
	if err != nil {
		return "", fmt.Errorf("creating file: %w", err)
	}
	defer func() { _ = f.Close() }()

	sorted := make([]ClassicResource, len(resources))
	copy(sorted, resources)
	sort.Slice(sorted, func(i, j int) bool {
		return sorted[i].CLIName < sorted[j].CLIName
	})

	if err := tmpl.Execute(f, sorted); err != nil {
		return "", fmt.Errorf("executing template: %w", err)
	}

	return outPath, nil
}

func templateFuncs() template.FuncMap {
	return template.FuncMap{
		"toCamel":      strcase.ToCamel,
		"toKebab":      strcase.ToKebab,
		"toLower":      strings.ToLower,
		"hasOp":        hasOp,
		"hasLookup":    hasLookup,
		"extraLookups": extraLookups,
		"classicExample": func(r ClassicResource, op string) string {
			bin := "jamfpro-cli"
			name := r.CLIName
			singular := r.Singular
			switch op {
			case "list":
				return fmt.Sprintf("  # List all %s\n  %s %s list\n\n  # List %s and extract IDs\n  %s %s list --field id",
					r.Name, bin, name, r.Name, bin, name)
			case "get":
				return fmt.Sprintf("  # Get a %s by ID\n  %s %s get 1\n\n  # Get a %s and output as YAML\n  %s %s get 1 -o yaml",
					singular, bin, name, singular, bin, name)
			case "create":
				return fmt.Sprintf("  # Create a %s from JSON\n  echo '{\"name\":\"Example\"}' | %s %s create\n\n  # Get a %s, modify, and create a copy\n  %s %s get 1 -o json | jq '.name = \"Copy\"' | %s %s create",
					singular, bin, name, singular, bin, name, bin, name)
			case "update":
				return fmt.Sprintf("  # Update a %s from JSON\n  echo '{\"name\":\"Updated\"}' | %s %s update 1\n\n  # Get, modify, and update a %s\n  %s %s get 1 -o json | jq '.name = \"New\"' | %s %s update 1",
					singular, bin, name, singular, bin, name, bin, name)
			case "delete":
				return fmt.Sprintf("  # Delete a %s (with confirmation)\n  %s %s delete 1\n\n  # Delete without confirmation prompt\n  %s %s delete 1 --yes",
					singular, bin, name, bin, name)
			default:
				return ""
			}
		},
		"lookupFlag": func(l string) string {
			return strcase.ToKebab(l)
		},
		"lookupCamel": func(l string) string {
			return strcase.ToCamel(l)
		},
		"needsIO": func(r ClassicResource) bool {
			// list and get use io.ReadAll for response unwrapping; create/update read from stdin
			return r.HasOperation("list") || r.HasOperation("get") || r.HasOperation("create") || r.HasOperation("update")
		},
		"needsFmt": func(r ClassicResource) bool {
			return r.HasOperation("delete") || r.HasOperation("create") || r.HasOperation("update") || r.HasOperation("get") || len(r.ExtraLookups()) > 0
		},
		"needsOS": func(r ClassicResource) bool {
			return r.HasOperation("create") || r.HasOperation("update") || r.HasOperation("delete")
		},
	}
}

func hasOp(ops []string, target string) bool {
	for _, op := range ops {
		if op == target {
			return true
		}
	}
	return false
}

func hasLookup(lookups []string, target string) bool {
	for _, l := range lookups {
		if l == target {
			return true
		}
	}
	return false
}

func extraLookups(lookups []string) []string {
	var extra []string
	for _, l := range lookups {
		if l != "id" {
			extra = append(extra, l)
		}
	}
	return extra
}

// classicResourceTemplate generates a single Go file per Classic API resource.
const classicResourceTemplate = `// Code generated by jamfpro-cli generator (classic). DO NOT EDIT.
package generated

import (
	"context"
	"encoding/json"
{{- if needsFmt . }}
	"fmt"
{{- end }}
{{- if needsIO . }}
	"io"
{{- end }}
{{- if hasOp .Operations "delete" }}
	"net/http"
{{- end }}
{{- if needsOS . }}
	"os"
{{- end }}

	"github.com/spf13/cobra"
)

// New{{ .GoName }}Cmd creates the {{ .CLIName }} command group
func New{{ .GoName }}Cmd(ctx *CLIContext) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "{{ .CLIName }}",
		Short: "{{ .Description }} (Classic API)",
		Long:  ` + "`" + `Manage {{ .Description | toLower }} via the Jamf Pro Classic API (/JSSResource/).` + "`" + `,
	}
{{ if hasOp .Operations "list" }}
	cmd.AddCommand(new{{ .GoName }}ListCmd(ctx))
{{- end }}
{{ if hasOp .Operations "get" }}
	cmd.AddCommand(new{{ .GoName }}GetCmd(ctx))
{{- end }}
{{- range extraLookups .Lookups }}
	cmd.AddCommand(new{{ $.GoName }}GetBy{{ lookupCamel . }}Cmd(ctx))
{{- end }}
{{ if hasOp .Operations "create" }}
	cmd.AddCommand(new{{ .GoName }}CreateCmd(ctx))
{{- end }}
{{ if hasOp .Operations "update" }}
	cmd.AddCommand(new{{ .GoName }}UpdateCmd(ctx))
{{- end }}
{{ if hasOp .Operations "delete" }}
	cmd.AddCommand(new{{ .GoName }}DeleteCmd(ctx))
{{- end }}

	return cmd
}
{{ if hasOp .Operations "list" }}
func new{{ .GoName }}ListCmd(ctx *CLIContext) *cobra.Command {
	return &cobra.Command{
		Use:   "list",
		Short: "List all {{ .Name }}",
		Example: ` + "`" + `{{ classicExample . "list" }}` + "`" + `,
		RunE: func(cmd *cobra.Command, args []string) error {
			reqCtx := context.Background()
			resp, err := ctx.Client.Do(reqCtx, "GET", "/JSSResource/{{ .Path }}", nil)
			if err != nil {
				return err
			}
			defer resp.Body.Close()

			// Classic API wraps list responses: {"{{ .Name }}": [...]}
			body, err := io.ReadAll(resp.Body)
			if err != nil {
				return err
			}
			var wrapper map[string]json.RawMessage
			if err := json.Unmarshal(body, &wrapper); err == nil {
				if inner, ok := wrapper["{{ .Name }}"]; ok {
					return ctx.Output.PrintRaw(inner)
				}
			}
			return ctx.Output.PrintRaw(body)
		},
	}
}
{{ end }}
{{ if hasOp .Operations "get" }}
func new{{ .GoName }}GetCmd(ctx *CLIContext) *cobra.Command {
	return &cobra.Command{
		Use:   "get <id>",
		Short: "Get a {{ .Singular }} by ID",
		Example: ` + "`" + `{{ classicExample . "get" }}` + "`" + `,
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			reqCtx := context.Background()
			path := fmt.Sprintf("/JSSResource/{{ .Path }}/id/%s", args[0])
			resp, err := ctx.Client.Do(reqCtx, "GET", path, nil)
			if err != nil {
				return err
			}
			defer resp.Body.Close()

			// Classic API wraps single-object responses: {"{{ .Singular }}": {...}}
			body, err := io.ReadAll(resp.Body)
			if err != nil {
				return err
			}
			var wrapper map[string]json.RawMessage
			if err := json.Unmarshal(body, &wrapper); err == nil {
				if inner, ok := wrapper["{{ .Singular }}"]; ok {
					return ctx.Output.PrintRaw(inner)
				}
			}
			return ctx.Output.PrintRaw(body)
		},
	}
}
{{ end }}
{{- range extraLookups .Lookups }}
func new{{ $.GoName }}GetBy{{ lookupCamel . }}Cmd(ctx *CLIContext) *cobra.Command {
	return &cobra.Command{
		Use:   "get-by-{{ lookupFlag . }} <{{ lookupFlag . }}>",
		Short: "Get a {{ $.Singular }} by {{ . }}",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			reqCtx := context.Background()
			path := fmt.Sprintf("/JSSResource/{{ $.Path }}/{{ . }}/%s", args[0])
			resp, err := ctx.Client.Do(reqCtx, "GET", path, nil)
			if err != nil {
				return err
			}
			defer resp.Body.Close()

			body, err := io.ReadAll(resp.Body)
			if err != nil {
				return err
			}
			var wrapper map[string]json.RawMessage
			if err := json.Unmarshal(body, &wrapper); err == nil {
				if inner, ok := wrapper["{{ $.Singular }}"]; ok {
					return ctx.Output.PrintRaw(inner)
				}
			}
			return ctx.Output.PrintRaw(body)
		},
	}
}
{{ end }}
{{ if hasOp .Operations "create" }}
func new{{ .GoName }}CreateCmd(ctx *CLIContext) *cobra.Command {
	return &cobra.Command{
		Use:   "create",
		Short: "Create a {{ .Singular }}",
		Long:  "Create a new {{ .Singular }}. Reads JSON body from stdin.",
		Example: ` + "`" + `{{ classicExample . "create" }}` + "`" + `,
		RunE: func(cmd *cobra.Command, args []string) error {
			reqCtx := context.Background()

			var body io.Reader
			stat, _ := os.Stdin.Stat()
			if (stat.Mode() & os.ModeCharDevice) == 0 {
				body = os.Stdin
			} else {
				return fmt.Errorf("request body required on stdin (pipe JSON input)")
			}

			resp, err := ctx.Client.Do(reqCtx, "POST", "/JSSResource/{{ .Path }}/id/0", body)
			if err != nil {
				return err
			}
			defer resp.Body.Close()

			return ctx.Output.PrintResponse(resp)
		},
	}
}
{{ end }}
{{ if hasOp .Operations "update" }}
func new{{ .GoName }}UpdateCmd(ctx *CLIContext) *cobra.Command {
	return &cobra.Command{
		Use:   "update <id>",
		Short: "Update a {{ .Singular }}",
		Long:  "Update an existing {{ .Singular }} by ID. Reads JSON body from stdin.",
		Example: ` + "`" + `{{ classicExample . "update" }}` + "`" + `,
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			reqCtx := context.Background()

			var body io.Reader
			stat, _ := os.Stdin.Stat()
			if (stat.Mode() & os.ModeCharDevice) == 0 {
				body = os.Stdin
			} else {
				return fmt.Errorf("request body required on stdin (pipe JSON input)")
			}

			path := fmt.Sprintf("/JSSResource/{{ .Path }}/id/%s", args[0])
			resp, err := ctx.Client.Do(reqCtx, "PUT", path, body)
			if err != nil {
				return err
			}
			defer resp.Body.Close()

			return ctx.Output.PrintResponse(resp)
		},
	}
}
{{ end }}
{{ if hasOp .Operations "delete" }}
func new{{ .GoName }}DeleteCmd(ctx *CLIContext) *cobra.Command {
	var (
		flagYes    bool
		flagDryRun bool
	)

	cmd := &cobra.Command{
		Use:   "delete <id>",
		Short: "Delete a {{ .Singular }}",
		Example: ` + "`" + `{{ classicExample . "delete" }}` + "`" + `,
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			reqCtx := context.Background()

			if flagDryRun {
				fmt.Fprintf(os.Stderr, "Would delete {{ .Singular }} %s\n", args[0])
				return nil
			}
			if !flagYes {
				noInput, _ := cmd.Flags().GetBool("no-input")
				if noInput {
					return fmt.Errorf("destructive operation requires --yes when --no-input is set")
				}
				fmt.Fprintf(os.Stderr, "This will delete {{ .Singular }} %s. Type 'yes' to confirm: ", args[0])
				var confirm string
				fmt.Scanln(&confirm)
				if confirm != "yes" {
					return fmt.Errorf("aborted")
				}
			}

			path := fmt.Sprintf("/JSSResource/{{ .Path }}/id/%s", args[0])
			resp, err := ctx.Client.Do(reqCtx, "DELETE", path, nil)
			if err != nil {
				return err
			}
			defer resp.Body.Close()

			if resp.StatusCode == http.StatusNoContent || resp.StatusCode == http.StatusOK {
				fmt.Fprintln(os.Stderr, "Deleted successfully")
				return nil
			}

			return ctx.Output.PrintResponse(resp)
		},
	}

	cmd.Flags().BoolVar(&flagYes, "yes", false, "Skip confirmation prompt")
	cmd.Flags().BoolVarP(&flagDryRun, "dry-run", "n", false, "Preview without executing")

	return cmd
}
{{ end }}
`

const classicRegistryTemplate = `// Code generated by jamfpro-cli generator (classic). DO NOT EDIT.
package generated

import "github.com/spf13/cobra"

// RegisterClassicCommands registers all Classic API resource commands.
func RegisterClassicCommands(root *cobra.Command, ctx *CLIContext) {
{{- range . }}
	root.AddCommand(New{{ .GoName }}Cmd(ctx))
{{- end }}
}
`
