apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: jamf-cli
  description: CLI for the Jamf platform
  tags:
  - api
  - ai
spec:
  type: research
  lifecycle: experimental
  owner: concepts
  system: jamf-concept-projects
