apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: jamfpro-cli
  description: Jamf Pro CLI
  tags:
  - api
  - ai
spec:
  type: research
  lifecycle: experimental
  owner: concepts
  system: jamf-concept-projects
