// Copyright 2026, Jamf Software LLC
// Code generated by jamf-cli generator. DO NOT EDIT.

package blueprintcomponents

// Scaffolds maps blueprint component identifiers to example JSON configurations.
// Each value is a complete, valid configuration object that can be used as the
// "configuration" field in a BlueprintComponentV1.
var Scaffolds = map[string]string{
	`com.jamf.ddm-configuration-profile`: `{}`,
	`com.jamf.ddm.app-managed`:           `{}`,
	`com.jamf.ddm.audio-accessory-settings`: `{
  "TemporaryPairing": {
    "Configuration": {
      "UnpairingTime": {
        "Hour": 0,
        "Policy": "None"
      }
    },
    "Disabled": false,
    "Included": true
  }
}`,
	`com.jamf.ddm.custom-declarations`: `{
  "declarations": [
    {
      "kind": "CONFIGURATION",
      "payload": {},
      "type": ""
    }
  ]
}`,
	`com.jamf.ddm.disk-management`: `{
  "Restrictions": {
    "ExternalStorage": {
      "Included": true,
      "Value": "Allowed"
    },
    "NetworkStorage": {
      "Included": true,
      "Value": "Allowed"
    }
  },
  "version": 2
}`,
	`com.jamf.ddm.math-settings`: `{
  "Calculator": {
    "BasicMode": {
      "AddSquareRoot": true,
      "Included": true
    },
    "InputModes": {
      "Included": true,
      "RPN": true,
      "UnitConversion": true
    },
    "MathNotesMode": {
      "Enabled": true,
      "Included": true
    },
    "ProgrammerMode": {
      "Enabled": true,
      "Included": true
    },
    "ScientificMode": {
      "Enabled": true,
      "Included": true
    }
  },
  "SystemBehavior": {
    "Included": true,
    "KeyboardSuggestions": true,
    "MathNotes": true
  }
}`,
	`com.jamf.ddm.passcode-settings`: `{
  "ChangeAtNextAuth": {
    "Included": true,
    "Value": true
  },
  "CustomRegex": {
    "Description": {
      "<key>": ""
    },
    "Included": true,
    "Regex": "[0-9]{16}"
  },
  "FailedAttemptsResetInMinutes": {
    "Included": true,
    "Value": 5
  },
  "MaximumFailedAttempts": {
    "Included": true,
    "Value": 10
  },
  "MaximumGracePeriodInMinutes": {
    "Included": true,
    "Value": 2
  },
  "MaximumInactivityInMinutes": {
    "Included": true,
    "Value": 10
  },
  "MaximumPasscodeAgeInDays": {
    "Included": true,
    "Value": 14
  },
  "MinimumComplexCharacters": {
    "Included": true,
    "Value": 1
  },
  "MinimumLength": {
    "Included": true,
    "Value": 8
  },
  "PasscodeReuseLimit": {
    "Included": true,
    "Value": 10
  },
  "RequireAlphanumericPasscode": {
    "Included": true,
    "Value": true
  },
  "RequireComplexPasscode": {
    "Included": true,
    "Value": true
  },
  "RequirePasscode": {
    "Included": true,
    "Value": true
  },
  "version": "2"
}`,
	`com.jamf.ddm.safari-bookmarks`: `{
  "ManagedBookmarks": [
    {
      "Bookmarks": [
        {
          "Folder": [
            {
              "Title": "",
              "URL": ""
            }
          ],
          "Title": "",
          "Type": ""
        }
      ],
      "GroupIdentifier": "",
      "Title": ""
    }
  ]
}`,
	`com.jamf.ddm.safari-extensions`: `{
  "ManagedExtensions": {
    "<key>": {
      "AllowedDomains": [
        {
          "Domain": ""
        }
      ],
      "DeniedDomains": [
        {
          "Domain": ""
        }
      ],
      "PrivateBrowsing": "Allowed",
      "State": "Allowed"
    }
  }
}`,
	`com.jamf.ddm.safari-settings`: `{
  "AcceptCookies": {
    "Included": true,
    "Value": "Never"
  },
  "AllowDisablingFraudWarning": {
    "Included": true,
    "Value": true
  },
  "AllowHistoryClearing": {
    "Included": true,
    "Value": true
  },
  "AllowJavaScript": {
    "Included": true,
    "Value": true
  },
  "AllowPopups": {
    "Included": true,
    "Value": true
  },
  "AllowPrivateBrowsing": {
    "Included": true,
    "Value": true
  },
  "AllowSummary": {
    "Included": true,
    "Value": true
  },
  "NewTabStartPage": {
    "ExtensionIdentifier": "com.example.extension (ABC1234567)",
    "HomepageURL": "https://example.com",
    "Included": true,
    "PageType": "Start"
  }
}`,
	`com.jamf.ddm.service-background-tasks`: `{
  "backgroundTasks": [
    {
      "ExecutableAssetReference": {
        "Authentication": {
          "Type": "MDM"
        },
        "Reference": {
          "ContentType": "",
          "DataURL": "",
          "Hash-SHA-256": "",
          "Size": 0
        }
      },
      "LaunchdConfigurations": [
        {
          "Context": "daemon",
          "FileAssetReference": {
            "Authentication": {
              "Type": "MDM"
            },
            "Reference": {
              "ContentType": "",
              "DataURL": "",
              "Hash-SHA-256": "",
              "Size": 0
            }
          }
        }
      ],
      "TaskDescription": "",
      "TaskType": ""
    }
  ]
}`,
	`com.jamf.ddm.service-configuration-files`: `{
  "serviceConfigFiles": [
    {
      "DataAssetReference": {
        "Authentication": {
          "Type": "MDM"
        },
        "Reference": {
          "ContentType": "",
          "DataURL": "",
          "Hash-SHA-256": "",
          "Size": 0
        }
      },
      "ServiceType": ""
    }
  ]
}`,
	`com.jamf.ddm.software-update-settings`: `{
  "AllowStandardUserOSUpdates": {
    "Enabled": true,
    "Included": true
  },
  "AutomaticActions": {
    "Download": {
      "Included": true,
      "Value": "Allowed"
    },
    "InstallOSUpdates": {
      "Included": true,
      "Value": "Allowed"
    },
    "InstallSecurityUpdate": {
      "Included": true,
      "Value": "Allowed"
    }
  },
  "Beta": {
    "Included": true,
    "Value": {
      "OfferPrograms": [
        {
          "Description": "",
          "Token": ""
        }
      ],
      "ProgramEnrollment": "Allowed",
      "RequireProgram": {
        "Description": "",
        "Token": ""
      }
    }
  },
  "Deferrals": {
    "CombinedPeriodInDays": {
      "Included": true,
      "Value": 1
    },
    "MajorPeriodInDays": {
      "Included": true,
      "Value": 1
    },
    "MinorPeriodInDays": {
      "Included": true,
      "Value": 1
    },
    "SystemPeriodInDays": {
      "Included": true,
      "Value": 1
    }
  },
  "Notifications": {
    "Enabled": true,
    "Included": true
  },
  "RapidSecurityResponse": {
    "Enable": {
      "Enabled": true,
      "Included": true
    },
    "EnableRollback": {
      "Enabled": true,
      "Included": true
    }
  },
  "RecommendedCadence": {
    "Included": true,
    "Value": "All"
  }
}`,
	`com.jamf.ddm.sw-updates`: `{
  "deploymentTime": "16:00",
  "detailsURL": {
    "Included": false,
    "Value": ""
  },
  "enforceAfterDays": 14,
  "enforcementType": "AUTOMATIC",
  "rules": {
    "minor": {
      "deploymentTime": "16:00",
      "enforceAfterDays": 14
    }
  },
  "strategy": "LATEST"
}`,
}

// ShortNames maps short names to full component identifiers for CLI convenience.
var ShortNames = map[string]string{
	`ddm-configuration-profile`:   `com.jamf.ddm-configuration-profile`,
	`app-managed`:                 `com.jamf.ddm.app-managed`,
	`audio-accessory-settings`:    `com.jamf.ddm.audio-accessory-settings`,
	`custom-declarations`:         `com.jamf.ddm.custom-declarations`,
	`disk-management`:             `com.jamf.ddm.disk-management`,
	`math-settings`:               `com.jamf.ddm.math-settings`,
	`passcode-settings`:           `com.jamf.ddm.passcode-settings`,
	`safari-bookmarks`:            `com.jamf.ddm.safari-bookmarks`,
	`safari-extensions`:           `com.jamf.ddm.safari-extensions`,
	`safari-settings`:             `com.jamf.ddm.safari-settings`,
	`service-background-tasks`:    `com.jamf.ddm.service-background-tasks`,
	`service-configuration-files`: `com.jamf.ddm.service-configuration-files`,
	`software-update-settings`:    `com.jamf.ddm.software-update-settings`,
	`sw-updates`:                  `com.jamf.ddm.sw-updates`,
}

// Identifiers returns all known component identifiers in sorted order.
func Identifiers() []string {
	return []string{
		`com.jamf.ddm-configuration-profile`,
		`com.jamf.ddm.app-managed`,
		`com.jamf.ddm.audio-accessory-settings`,
		`com.jamf.ddm.custom-declarations`,
		`com.jamf.ddm.disk-management`,
		`com.jamf.ddm.math-settings`,
		`com.jamf.ddm.passcode-settings`,
		`com.jamf.ddm.safari-bookmarks`,
		`com.jamf.ddm.safari-extensions`,
		`com.jamf.ddm.safari-settings`,
		`com.jamf.ddm.service-background-tasks`,
		`com.jamf.ddm.service-configuration-files`,
		`com.jamf.ddm.software-update-settings`,
		`com.jamf.ddm.sw-updates`,
	}
}
