// Copyright 2026, Jamf Software LLC

package smartgroup

func init() {
	Register(complianceGatekeeperDisabled())
	Register(complianceSIPDisabled())
	Register(complianceFirewallDisabled())
	Register(complianceNonCompliantBaseline())
}

func complianceGatekeeperDisabled() Template {
	return Template{
		Slug:        "compliance/gatekeeper-disabled",
		Category:    "compliance",
		Description: "Macs with Gatekeeper disabled",
		Build: func(_ map[string]any) (SmartGroupRequest, error) {
			return SmartGroupRequest{
				Description: "Auto-generated by jamf-cli (template: compliance/gatekeeper-disabled)",
				Criteria: []Criterion{
					{AndOr: "and", Priority: 0, Name: CriterionGatekeeper, SearchType: "is", Value: "Off"},
				},
			}, nil
		},
	}
}

func complianceSIPDisabled() Template {
	return Template{
		Slug:        "compliance/sip-disabled",
		Category:    "compliance",
		Description: "Macs with System Integrity Protection disabled",
		Build: func(_ map[string]any) (SmartGroupRequest, error) {
			return SmartGroupRequest{
				Description: "Auto-generated by jamf-cli (template: compliance/sip-disabled)",
				Criteria: []Criterion{
					{AndOr: "and", Priority: 0, Name: CriterionSIP, SearchType: "is", Value: "Disabled"},
				},
			}, nil
		},
	}
}

func complianceFirewallDisabled() Template {
	return Template{
		Slug:        "compliance/firewall-disabled",
		Category:    "compliance",
		Description: "Macs with the application firewall disabled",
		Build: func(_ map[string]any) (SmartGroupRequest, error) {
			return SmartGroupRequest{
				Description: "Auto-generated by jamf-cli (template: compliance/firewall-disabled)",
				Criteria: []Criterion{
					{AndOr: "and", Priority: 0, Name: CriterionFirewallEnabled, SearchType: "is", Value: "No"},
				},
			}, nil
		},
	}
}

func complianceNonCompliantBaseline() Template {
	return Template{
		Slug:        "compliance/non-compliant-baseline",
		Category:    "compliance",
		Description: "Composite: any of FV2 disabled, SIP disabled, Gatekeeper disabled, Firewall disabled",
		Build: func(_ map[string]any) (SmartGroupRequest, error) {
			return SmartGroupRequest{
				Description: "Auto-generated by jamf-cli (template: compliance/non-compliant-baseline). OR-composite across four security primitives.",
				Criteria: []Criterion{
					{AndOr: "and", Priority: 0, Name: CriterionFV2Enabled, SearchType: "is", Value: "Not Enabled"},
					{AndOr: "or", Priority: 1, Name: CriterionSIP, SearchType: "is", Value: "Disabled"},
					{AndOr: "or", Priority: 2, Name: CriterionGatekeeper, SearchType: "is", Value: "Off"},
					{AndOr: "or", Priority: 3, Name: CriterionFirewallEnabled, SearchType: "is", Value: "No"},
				},
			}, nil
		},
	}
}
