// Copyright 2026, Jamf Software LLC

package smartgroup

import "fmt"

func init() {
	Register(encryptionNotEncrypted())
	Register(encryptionInvalidRecoveryKey())
	Register(encryptionEscrowMissing())
	Register(encryptionIRKOnlyDeprecated())
	Register(encryptionEncryptionStalled())
	Register(encryptionFVIneligible())
}

func encryptionNotEncrypted() Template {
	return Template{
		Slug:        "encryption/not-encrypted",
		Category:    "encryption",
		Description: "Macs where FileVault 2 is not enabled",
		Build: func(_ map[string]any) (SmartGroupRequest, error) {
			return SmartGroupRequest{
				Description: "Auto-generated by jamf-cli (template: encryption/not-encrypted)",
				Criteria: []Criterion{
					{AndOr: "and", Priority: 0, Name: CriterionFV2Status, SearchType: "is", Value: "No Partitions Encrypted"},
				},
			}, nil
		},
	}
}

func encryptionInvalidRecoveryKey() Template {
	return Template{
		Slug:        "encryption/invalid-recovery-key",
		Category:    "encryption",
		Description: "Macs with an INVALID escrowed recovery key (cannot unlock)",
		Build: func(_ map[string]any) (SmartGroupRequest, error) {
			return SmartGroupRequest{
				Description: "Auto-generated by jamf-cli (template: encryption/invalid-recovery-key)",
				Criteria: []Criterion{
					{AndOr: "and", Priority: 0, Name: CriterionFV2IndividualKeyValidation, SearchType: "is", Value: "Not Valid"},
				},
			}, nil
		},
	}
}

func encryptionEscrowMissing() Template {
	return Template{
		Slug:        "encryption/escrow-missing",
		Category:    "encryption",
		Description: "Macs without any escrowed recovery key",
		Build: func(_ map[string]any) (SmartGroupRequest, error) {
			return SmartGroupRequest{
				Description: "Auto-generated by jamf-cli (template: encryption/escrow-missing)",
				Criteria: []Criterion{
					{AndOr: "and", Priority: 0, Name: CriterionFV2RecoveryKeyType, SearchType: "is", Value: ""},
				},
			}, nil
		},
	}
}

func encryptionIRKOnlyDeprecated() Template {
	return Template{
		Slug:        "encryption/irk-only-deprecated",
		Category:    "encryption",
		Description: "Macs on the deprecated Institutional Recovery Key",
		Build: func(_ map[string]any) (SmartGroupRequest, error) {
			return SmartGroupRequest{
				Description: "Auto-generated by jamf-cli (template: encryption/irk-only-deprecated). IRK is deprecated for managed Macs; migrate to Personal Recovery Key escrow.",
				Criteria: []Criterion{
					{AndOr: "and", Priority: 0, Name: CriterionFV2RecoveryKeyType, SearchType: "is", Value: "Institutional"},
				},
			}, nil
		},
	}
}

func encryptionEncryptionStalled() Template {
	return Template{
		Slug:        "encryption/encryption-stalled",
		Category:    "encryption",
		Description: "Macs stuck mid-encryption (no inventory update in N days)",
		Params: []ParamSpec{
			{Name: "stalled-after", Type: "int", Default: 7, Description: "Days since last inventory update"},
		},
		Build: func(opts map[string]any) (SmartGroupRequest, error) {
			days, ok := opts["stalled-after"].(int)
			if !ok {
				return SmartGroupRequest{}, fmt.Errorf("expected int stalled-after, got %T", opts["stalled-after"])
			}
			return SmartGroupRequest{
				Description: fmt.Sprintf("Auto-generated by jamf-cli (template: encryption/encryption-stalled, stalled-after=%d)", days),
				Criteria: []Criterion{
					{AndOr: "and", Priority: 0, Name: CriterionFV2Status, SearchType: "is not", Value: "All Partitions Encrypted"},
					{AndOr: "and", Priority: 1, Name: CriterionLastInventoryUpdate, SearchType: "more than x days ago", Value: fmt.Sprintf("%d", days)},
				},
			}, nil
		},
	}
}

func encryptionFVIneligible() Template {
	return Template{
		Slug:        "encryption/fv-ineligible",
		Category:    "encryption",
		Description: `Macs reporting FileVault 2 Status of "N/A" (ineligible hardware or never collected)`,
		Build: func(_ map[string]any) (SmartGroupRequest, error) {
			return SmartGroupRequest{
				Description: "Auto-generated by jamf-cli (template: encryption/fv-ineligible)",
				Criteria: []Criterion{
					{AndOr: "and", Priority: 0, Name: CriterionFV2Status, SearchType: "is", Value: "N/A"},
				},
			}, nil
		},
	}
}
