// Copyright 2026, Jamf Software LLC

package smartgroup

func init() {
	Register(lifecycleUnsupervised())
	Register(lifecycleADEEnrolled())
	Register(lifecycleJamfBinaryOutdated())
	Register(lifecycleFVIneligibleHardware())
}

func lifecycleUnsupervised() Template {
	return Template{
		Slug:        "lifecycle/unsupervised",
		Category:    "lifecycle",
		Description: "Macs that are not supervised",
		Build: func(_ map[string]any) (SmartGroupRequest, error) {
			return SmartGroupRequest{
				Description: "Auto-generated by jamf-cli (template: lifecycle/unsupervised)",
				Criteria: []Criterion{
					{AndOr: "and", Priority: 0, Name: CriterionSupervised, SearchType: "is", Value: "No"},
				},
			}, nil
		},
	}
}

func lifecycleADEEnrolled() Template {
	return Template{
		Slug:        "lifecycle/ade-enrolled",
		Category:    "lifecycle",
		Description: "Macs enrolled via Automated Device Enrollment (PreStage)",
		Build: func(_ map[string]any) (SmartGroupRequest, error) {
			return SmartGroupRequest{
				Description: "Auto-generated by jamf-cli (template: lifecycle/ade-enrolled)",
				Criteria: []Criterion{
					{AndOr: "and", Priority: 0, Name: CriterionEnrolledViaADE, SearchType: "is", Value: "Yes"},
				},
			}, nil
		},
	}
}

func lifecycleJamfBinaryOutdated() Template {
	return Template{
		Slug:        "lifecycle/jamf-binary-outdated",
		Category:    "lifecycle",
		Description: "Macs whose Jamf binary is not on the latest known version",
		Build: func(_ map[string]any) (SmartGroupRequest, error) {
			return SmartGroupRequest{
				Description: "Auto-generated by jamf-cli (template: lifecycle/jamf-binary-outdated). Uses Jamf Pro's 'not current' operator — matches devices below the latest known Jamf binary version.",
				Criteria: []Criterion{
					{AndOr: "and", Priority: 0, Name: CriterionJamfBinaryVersion, SearchType: "not current", Value: ""},
				},
			}, nil
		},
	}
}

func lifecycleFVIneligibleHardware() Template {
	return Template{
		Slug:        "lifecycle/fv-ineligible-hardware",
		Category:    "lifecycle",
		Description: "Intel Macs reporting FileVault 2 Status N/A (hardware-refresh candidates)",
		Build: func(_ map[string]any) (SmartGroupRequest, error) {
			return SmartGroupRequest{
				Description: "Auto-generated by jamf-cli (template: lifecycle/fv-ineligible-hardware)",
				Criteria: []Criterion{
					{AndOr: "and", Priority: 0, Name: CriterionFV2Status, SearchType: "is", Value: "N/A"},
					{AndOr: "and", Priority: 1, Name: CriterionAppleSilicon, SearchType: "is", Value: "No"},
				},
			}, nil
		},
	}
}
