// Copyright 2026, Jamf Software LLC

package smartgroup

import "fmt"

func init() {
	Register(lifecycleUnsupervised())
	Register(lifecycleADEEnrolled())
	Register(lifecycleJamfBinaryOutdated())
	Register(lifecycleFVIneligibleHardware())
}

func lifecycleUnsupervised() Template {
	return Template{
		Slug:        "lifecycle/unsupervised",
		Category:    "lifecycle",
		Description: "Macs that are not supervised",
		Build: func(_ map[string]any) (SmartGroupRequest, error) {
			return SmartGroupRequest{
				Description: "Auto-generated by jamf-cli (template: lifecycle/unsupervised)",
				Criteria: []Criterion{
					{AndOr: "and", Priority: 0, Name: CriterionSupervised, SearchType: "is", Value: "No"},
				},
			}, nil
		},
	}
}

func lifecycleADEEnrolled() Template {
	return Template{
		Slug:        "lifecycle/ade-enrolled",
		Category:    "lifecycle",
		Description: "Macs enrolled via Automated Device Enrollment (PreStage)",
		Build: func(_ map[string]any) (SmartGroupRequest, error) {
			return SmartGroupRequest{
				Description: "Auto-generated by jamf-cli (template: lifecycle/ade-enrolled)",
				Criteria: []Criterion{
					{AndOr: "and", Priority: 0, Name: CriterionEnrollmentMethodPrestage, SearchType: "is", Value: "Yes"},
				},
			}, nil
		},
	}
}

func lifecycleJamfBinaryOutdated() Template {
	return Template{
		Slug:        "lifecycle/jamf-binary-outdated",
		Category:    "lifecycle",
		Description: "Macs running an outdated Jamf binary",
		Params: []ParamSpec{
			{Name: "below-version", Type: "version", Description: "Jamf binary version threshold (e.g. 11.0.0)", Required: true},
		},
		Build: func(opts map[string]any) (SmartGroupRequest, error) {
			v, ok := opts["below-version"].(string)
			if !ok {
				return SmartGroupRequest{}, fmt.Errorf("expected string below-version, got %T", opts["below-version"])
			}
			return SmartGroupRequest{
				Description: fmt.Sprintf("Auto-generated by jamf-cli (template: lifecycle/jamf-binary-outdated, below-version=%s)", v),
				Criteria: []Criterion{
					{AndOr: "and", Priority: 0, Name: CriterionJamfBinaryVersion, SearchType: "less than", Value: v},
				},
			}, nil
		},
	}
}

func lifecycleFVIneligibleHardware() Template {
	return Template{
		Slug:        "lifecycle/fv-ineligible-hardware",
		Category:    "lifecycle",
		Description: "Intel Macs reporting FileVault 2 Status N/A (hardware-refresh candidates)",
		Build: func(_ map[string]any) (SmartGroupRequest, error) {
			return SmartGroupRequest{
				Description: "Auto-generated by jamf-cli (template: lifecycle/fv-ineligible-hardware)",
				Criteria: []Criterion{
					{AndOr: "and", Priority: 0, Name: CriterionFV2Status, SearchType: "is", Value: "N/A"},
					{AndOr: "and", Priority: 1, Name: CriterionAppleSilicon, SearchType: "is", Value: "No"},
				},
			}, nil
		},
	}
}
