// Copyright 2026, Jamf Software LLC

package smartgroup

import "fmt"

func init() {
	Register(mdmBootstrapTokenMissing())
	Register(mdmUserApprovedMDMNo())
	Register(mdmStaleCheckin())
	Register(mdmMDMCertExpiring())
	Register(mdmDDMDisabled())
}

func mdmBootstrapTokenMissing() Template {
	return Template{
		Slug:        "mdm/bootstrap-token-missing",
		Category:    "mdm",
		Description: "Macs without an escrowed bootstrap token",
		Build: func(_ map[string]any) (SmartGroupRequest, error) {
			return SmartGroupRequest{
				Description: "Auto-generated by jamf-cli (template: mdm/bootstrap-token-missing)",
				Criteria: []Criterion{
					{AndOr: "and", Priority: 0, Name: CriterionBootstrapTokenEscrowed, SearchType: "is", Value: "No"},
				},
			}, nil
		},
	}
}

func mdmUserApprovedMDMNo() Template {
	return Template{
		Slug:        "mdm/user-approved-mdm-no",
		Category:    "mdm",
		Description: "Macs without User Approved MDM",
		Build: func(_ map[string]any) (SmartGroupRequest, error) {
			return SmartGroupRequest{
				Description: "Auto-generated by jamf-cli (template: mdm/user-approved-mdm-no)",
				Criteria: []Criterion{
					{AndOr: "and", Priority: 0, Name: CriterionUserApprovedMDM, SearchType: "is", Value: "No"},
				},
			}, nil
		},
	}
}

func mdmStaleCheckin() Template {
	return Template{
		Slug:        "mdm/stale-checkin",
		Category:    "mdm",
		Description: "Macs whose last inventory update is older than N days",
		Params: []ParamSpec{
			{Name: "days", Type: "int", Default: 7, Description: "Days since last inventory update"},
		},
		Build: func(opts map[string]any) (SmartGroupRequest, error) {
			n, ok := opts["days"].(int)
			if !ok {
				return SmartGroupRequest{}, fmt.Errorf("expected int days, got %T", opts["days"])
			}
			return SmartGroupRequest{
				Description: fmt.Sprintf("Auto-generated by jamf-cli (template: mdm/stale-checkin, days=%d)", n),
				Criteria: []Criterion{
					{AndOr: "and", Priority: 0, Name: CriterionLastInventoryUpdate, SearchType: "more than x days ago", Value: fmt.Sprintf("%d", n)},
				},
			}, nil
		},
	}
}

func mdmMDMCertExpiring() Template {
	return Template{
		Slug:        "mdm/mdm-cert-expiring",
		Category:    "mdm",
		Description: "Macs whose MDM profile expires within N days",
		Params: []ParamSpec{
			{Name: "within-days", Type: "int", Default: 30, Description: "Days from now"},
		},
		Build: func(opts map[string]any) (SmartGroupRequest, error) {
			n, ok := opts["within-days"].(int)
			if !ok {
				return SmartGroupRequest{}, fmt.Errorf("expected int within-days, got %T", opts["within-days"])
			}
			return SmartGroupRequest{
				Description: fmt.Sprintf("Auto-generated by jamf-cli (template: mdm/mdm-cert-expiring, within-days=%d)", n),
				Criteria: []Criterion{
					{AndOr: "and", Priority: 0, Name: CriterionMDMProfileExpirationDate, SearchType: "in less than x days", Value: fmt.Sprintf("%d", n)},
				},
			}, nil
		},
	}
}

func mdmDDMDisabled() Template {
	return Template{
		Slug:        "mdm/declarative-management-disabled",
		Category:    "mdm",
		Description: "Macs without Declarative Device Management enabled",
		Build: func(_ map[string]any) (SmartGroupRequest, error) {
			return SmartGroupRequest{
				Description: "Auto-generated by jamf-cli (template: mdm/declarative-management-disabled)",
				Criteria: []Criterion{
					{AndOr: "and", Priority: 0, Name: CriterionDDMEnabled, SearchType: "is", Value: "No"},
				},
			}, nil
		},
	}
}
