// Copyright 2026, Jamf Software LLC

package smartgroup

import "fmt"

func init() {
	Register(updatesOSVersionBelow())
	Register(updatesMajorVersionBehind())
	Register(updatesRSRNotApplied())
	Register(updatesBetaOS())
}

func updatesOSVersionBelow() Template {
	return Template{
		Slug:        "updates/os-version-below",
		Category:    "updates",
		Description: "Macs running OS older than a specific version",
		Params: []ParamSpec{
			{Name: "below-version", Type: "version", Description: "macOS version threshold (e.g. 15.4)", Required: true},
		},
		Build: func(opts map[string]any) (SmartGroupRequest, error) {
			v, ok := opts["below-version"].(string)
			if !ok {
				return SmartGroupRequest{}, fmt.Errorf("expected string below-version, got %T", opts["below-version"])
			}
			return SmartGroupRequest{
				Description: fmt.Sprintf("Auto-generated by jamf-cli (template: updates/os-version-below, below-version=%s)", v),
				Criteria: []Criterion{
					{AndOr: "and", Priority: 0, Name: CriterionOSVersion, SearchType: "less than", Value: v},
				},
			}, nil
		},
	}
}

func updatesMajorVersionBehind() Template {
	return Template{
		Slug:        "updates/major-version-behind",
		Category:    "updates",
		Description: "Macs behind a major macOS version (e.g. all running <15.x)",
		Params: []ParamSpec{
			{Name: "major-below", Type: "int", Description: "Major macOS version threshold", Required: true},
		},
		Build: func(opts map[string]any) (SmartGroupRequest, error) {
			n, ok := opts["major-below"].(int)
			if !ok {
				return SmartGroupRequest{}, fmt.Errorf("expected int major-below, got %T", opts["major-below"])
			}
			return SmartGroupRequest{
				Description: fmt.Sprintf("Auto-generated by jamf-cli (template: updates/major-version-behind, major-below=%d)", n),
				Criteria: []Criterion{
					{AndOr: "and", Priority: 0, Name: CriterionOSVersion, SearchType: "less than", Value: fmt.Sprintf("%d.0", n)},
				},
			}, nil
		},
	}
}

func updatesRSRNotApplied() Template {
	return Template{
		Slug:        "updates/rsr-not-applied",
		Category:    "updates",
		Description: "Macs with no Rapid Security Response applied",
		Build: func(_ map[string]any) (SmartGroupRequest, error) {
			return SmartGroupRequest{
				Description: "Auto-generated by jamf-cli (template: updates/rsr-not-applied)",
				Criteria: []Criterion{
					{AndOr: "and", Priority: 0, Name: CriterionOSRapidSecurityResponse, SearchType: "is", Value: ""},
				},
			}, nil
		},
	}
}

func updatesBetaOS() Template {
	return Template{
		Slug:        "updates/beta-os",
		Category:    "updates",
		Description: `Macs whose OS version contains "Beta"`,
		Build: func(_ map[string]any) (SmartGroupRequest, error) {
			return SmartGroupRequest{
				Description: "Auto-generated by jamf-cli (template: updates/beta-os)",
				Criteria: []Criterion{
					{AndOr: "and", Priority: 0, Name: CriterionOSVersion, SearchType: "like", Value: "Beta"},
				},
			}, nil
		},
	}
}
