// Copyright 2026, Jamf Software LLC

package parser

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"text/template"

	"github.com/iancoleman/strcase"
)

// CodegenHeader is the marker line at the top of every modern API generated file.
// Must match the first line of resourceTemplate and registryTemplate.
const CodegenHeader = "// Code generated by jamf-cli generator. DO NOT EDIT."

// goosNames is the set of valid GOOS values recognised by the Go toolchain.
// Files ending in _<goos>.go are treated as OS-specific and excluded from
// builds on other platforms. We must avoid generating such filenames.
// Keep in sync with: go tool dist list | cut -d/ -f1 | sort -u
var goosNames = map[string]bool{
	"aix": true, "android": true, "darwin": true, "dragonfly": true,
	"freebsd": true, "hurd": true, "illumos": true, "ios": true,
	"js": true, "linux": true, "netbsd": true, "openbsd": true,
	"plan9": true, "solaris": true, "wasip1": true, "windows": true, "zos": true,
}

// goarchNames is the set of valid GOARCH values recognised by the Go toolchain.
// Keep in sync with: go tool dist list | cut -d/ -f2 | sort -u
var goarchNames = map[string]bool{
	"386": true, "amd64": true, "arm": true, "arm64": true, "loong64": true,
	"mips": true, "mips64": true, "mips64le": true, "mipsle": true,
	"ppc64": true, "ppc64le": true, "riscv64": true, "s390x": true,
	"sparc64": true, "wasm": true,
}

// safeFilename converts a resource name to a Go source filename that won't be
// misinterpreted as an OS/arch-specific build file. If the base name (without .go)
// ends with a known GOOS or GOARCH suffix, "_resource" is appended.
func safeFilename(resourceName string) string {
	base := strings.ReplaceAll(resourceName, "-", "_")
	// Check last underscore-separated segment
	parts := strings.Split(base, "_")
	last := parts[len(parts)-1]
	if goosNames[last] || goarchNames[last] {
		base += "_resource"
	}
	return base + ".go"
}

// Generator generates Go code from parsed resources
type Generator struct {
	outputDir string
}

// NewGenerator creates a new code generator
func NewGenerator(outputDir string) *Generator {
	return &Generator{outputDir: outputDir}
}

// Generate generates a Go command file for a resource
func (g *Generator) Generate(resource *Resource) (string, error) {
	// Deduplicate operations before template execution
	resource.Operations = dedupeOperations(resource.Operations)

	tmpl, err := template.New("resource").Funcs(template.FuncMap{
		"toCamel":          strcase.ToCamel,
		"toLowerCamel":     strcase.ToLowerCamel,
		"toSnake":          strcase.ToSnake,
		"toKebab":          strcase.ToKebab,
		"toScreamingSnake": strcase.ToScreamingSnake,
		"hasPathParam":     hasPathParam,
		"pathParams":       pathParams,
		"queryParams":      queryParams,
		"goType":           goType,
		"flagType":         flagType,
		"sortOps":          sortOperations,
		"dedupeOps":        dedupeOperations,
		"escapeQuotes":     escapeQuotes,
		"isDestructive":    func(op *Operation) bool { return op.IsDestructive },
		"exampleText": func(resourceName, nameSingular string, op *Operation) string {
			bin := "jamf-cli"
			switch op.Name {
			case "list":
				return fmt.Sprintf("  # List all %s\n  %s %s list\n\n  # List %s and extract IDs\n  %s %s list --field id",
					resourceName, bin, resourceName, resourceName, bin, resourceName)
			case "get":
				if !hasPathParam(op.Path) {
					// Singleton get — no ID argument
					return fmt.Sprintf("  # Get %s\n  %s %s get\n\n  # Get %s and output as YAML\n  %s %s get -o yaml",
						resourceName, bin, resourceName, resourceName, bin, resourceName)
				}
				return fmt.Sprintf("  # Get a %s by ID\n  %s %s get 1\n\n  # Get a %s by name\n  %s %s get-by-name \"Example\"\n\n  # Get a %s and output as YAML\n  %s %s get 1 -o yaml",
					nameSingular, bin, resourceName, nameSingular, bin, resourceName, nameSingular, bin, resourceName)
			case "create":
				if op.RequestBody != nil && op.RequestBody.IsMultipart {
					return fmt.Sprintf("  # Upload a file\n  %s pro %s create --file /path/to/file",
						bin, resourceName)
				}
				return fmt.Sprintf("  # Show the JSON template for creating a %s\n  %s %s create --scaffold\n\n  # Create a %s from JSON\n  echo '{\"name\":\"Example\"}' | %s %s create\n\n  # Get a %s, modify it, and create a copy\n  %s %s get 1 -o json | jq '.name = \"Copy\"' | %s %s create",
					nameSingular, bin, resourceName, nameSingular, bin, resourceName, nameSingular, bin, resourceName, bin, resourceName)
			case "update":
				if !hasPathParam(op.Path) {
					// Singleton update — no ID argument
					return fmt.Sprintf("  # Update %s\n  %s %s get -o json | jq '.field = \"value\"' | %s %s update\n\n  # Update from a file\n  %s %s update --from-file %s.json",
						resourceName, bin, resourceName, bin, resourceName, bin, resourceName, resourceName)
				}
				return fmt.Sprintf("  # Update a %s from JSON\n  echo '{\"name\":\"Updated\"}' | %s %s update 1\n\n  # Get a %s, modify, and update\n  %s %s get 1 -o json | jq '.name = \"New Name\"' | %s %s update 1",
					nameSingular, bin, resourceName, nameSingular, bin, resourceName, bin, resourceName)
			case "delete":
				return fmt.Sprintf("  # Delete a %s (with confirmation)\n  %s %s delete 1\n\n  # Delete without confirmation prompt\n  %s %s delete 1 --yes",
					nameSingular, bin, resourceName, bin, resourceName)
			case "delete-multiple":
				return fmt.Sprintf("  # Delete multiple %s by IDs\n  %s %s delete-multiple --ids 1,2,3 --yes",
					resourceName, bin, resourceName)
			case "history":
				return fmt.Sprintf("  # Get history for a %s\n  %s %s history 1",
					nameSingular, bin, resourceName)
			case "export":
				return fmt.Sprintf("  # Export %s to CSV\n  %s %s export --out-file %s.csv",
					resourceName, bin, resourceName, resourceName)
			default:
				if opHasBinaryResponse(op) {
					idArg := ""
					if hasPathParam(op.Path) {
						idArg = " <id>"
					}
					return fmt.Sprintf(
						"  # Save to file\n  %s pro %s %s%s -O output.bin\n\n  # Pipe to stdout\n  %s pro %s %s%s > output.bin",
						bin, resourceName, op.Name, idArg,
						bin, resourceName, op.Name, idArg)
				}
				return ""
			}
		},
		"hasPostOrPut":    hasPostOrPut,
		"hasDelete":       hasDelete,
		"hasDestructive":  hasDestructive,
		"hasApply":        func(ops []*Operation) bool { return hasApply(ops) },
		"hasDeleteByName": func(ops []*Operation) bool { return hasDeleteByName(ops) },
		"deletePath": func(ops []*Operation) string {
			for _, op := range ops {
				if op.Name == "delete" && op.Method == "DELETE" {
					return op.Path
				}
			}
			return ""
		},
		"deletePathParam": func(ops []*Operation) string {
			for _, op := range ops {
				if op.Name == "delete" && op.Method == "DELETE" {
					start := strings.LastIndex(op.Path, "{")
					end := strings.LastIndex(op.Path, "}")
					if start != -1 && end > start {
						return op.Path[start : end+1]
					}
				}
			}
			return "{id}"
		},
		"listPathFromOps": func(ops []*Operation) string {
			// Derive the list endpoint from the get path: /v1/buildings/{id} → /v1/buildings
			for _, op := range ops {
				if op.Name == "get" && op.Method == "GET" && hasPathParam(op.Path) {
					path := op.Path
					if idx := strings.LastIndex(path, "/{"); idx != -1 {
						return path[:idx]
					}
				}
			}
			return ""
		},
		"createPath": func(ops []*Operation) string {
			for _, op := range ops {
				if op.Name == "create" && op.Method == "POST" {
					return op.Path
				}
			}
			return ""
		},
		"updatePath": func(ops []*Operation) string {
			for _, op := range ops {
				if op.Name == "update" && op.Method == "PUT" {
					return op.Path
				}
			}
			return ""
		},
		"updatePathParam": func(ops []*Operation) string {
			for _, op := range ops {
				if op.Name == "update" && op.Method == "PUT" {
					start := strings.LastIndex(op.Path, "{")
					end := strings.LastIndex(op.Path, "}")
					if start != -1 && end > start {
						return op.Path[start : end+1]
					}
				}
			}
			return "{id}"
		},
		"hasScaffold":  hasScaffold,
		"scaffoldJSON": scaffoldJSON,
		"opHasScaffold": func(op *Operation) bool {
			// Multipart uploads use --file, not a JSON scaffold.
			if op.RequestBody != nil && op.RequestBody.IsMultipart {
				return false
			}
			return op.RequestBody != nil && op.RequestBody.Schema != nil &&
				len(op.RequestBody.Schema.Properties) > 0 &&
				(op.Method == "POST" || op.Method == "PUT" || op.Method == "PATCH")
		},
		"opScaffoldJSON": func(op *Operation) string {
			if op.RequestBody == nil || op.RequestBody.Schema == nil {
				return "{}"
			}
			return scaffoldJSON(op.RequestBody.Schema)
		},
		"needsFmt":             needsFmt,
		"needsURL":             needsURL,
		"needsMultipart":       needsMultipart,
		"hasAnyBinaryResponse": hasAnyBinaryResponse,
		"opIsMultipart":        func(op *Operation) bool { return op.RequestBody != nil && op.RequestBody.IsMultipart },
		"opHasBinaryResponse":  opHasBinaryResponse,
		"shouldGenerateApply":  shouldGenerateApply,
		"hasDeleteMultiple":    hasDeleteMultiple,
		"defaultVal": func(paramType string, val any) string {
			switch paramType {
			case "string":
				return fmt.Sprintf("%q", fmt.Sprintf("%v", val))
			case "integer":
				return fmt.Sprintf("%v", val)
			case "boolean":
				return fmt.Sprintf("%v", val)
			default:
				return fmt.Sprintf("%#v", val)
			}
		},
		"hasList": func(ops []*Operation) bool {
			for _, op := range ops {
				if op.IsList {
					return true
				}
			}
			return false
		},
		"isGet": func(op *Operation) bool {
			return op.Name == "get" && op.Method == "GET" && hasPathParam(op.Path)
		},
		"listPath": func(op *Operation) string {
			// Derive the list endpoint from the get path: /v1/buildings/{id} → /v1/buildings
			path := op.Path
			if idx := strings.LastIndex(path, "/{"); idx != -1 {
				path = path[:idx]
			}
			return path
		},
		"pathParamName": func(op *Operation) string {
			// Extract the path parameter name from the URL path itself,
			// so it works even when the param is defined at the path level
			// in the OpenAPI spec rather than on the individual operation.
			start := strings.LastIndex(op.Path, "{")
			end := strings.LastIndex(op.Path, "}")
			if start != -1 && end > start {
				return op.Path[start : end+1]
			}
			return "{id}"
		},
	}).Parse(resourceTemplate)
	if err != nil {
		return "", fmt.Errorf("parsing template: %w", err)
	}

	filename := safeFilename(resource.Name)
	outPath := filepath.Join(g.outputDir, filename)

	f, err := os.Create(outPath)
	if err != nil {
		return "", fmt.Errorf("creating file: %w", err)
	}

	if err := tmpl.Execute(f, resource); err != nil {
		_ = f.Close()
		_ = os.Remove(outPath)
		return "", fmt.Errorf("executing template: %w", err)
	}

	_ = f.Close()
	return outPath, nil
}

// GenerateRegistry generates the registry file that registers all commands
func (g *Generator) GenerateRegistry(resources []*Resource) (string, error) {
	tmpl, err := template.New("registry").Parse(registryTemplate)
	if err != nil {
		return "", fmt.Errorf("parsing template: %w", err)
	}

	outPath := filepath.Join(g.outputDir, "registry.go")

	f, err := os.Create(outPath)
	if err != nil {
		return "", fmt.Errorf("creating file: %w", err)
	}

	// Sort resources by name
	sort.Slice(resources, func(i, j int) bool {
		return resources[i].Name < resources[j].Name
	})

	if err := tmpl.Execute(f, resources); err != nil {
		_ = f.Close()
		_ = os.Remove(outPath)
		return "", fmt.Errorf("executing template: %w", err)
	}

	_ = f.Close()
	return outPath, nil
}

// Template helper functions
func hasPathParam(path string) bool {
	return strings.Contains(path, "{")
}

func pathParams(params []*Parameter) []*Parameter {
	var result []*Parameter
	for _, p := range params {
		if p.In == "path" {
			result = append(result, p)
		}
	}
	return result
}

func queryParams(params []*Parameter) []*Parameter {
	var result []*Parameter
	for _, p := range params {
		if p.In == "query" {
			result = append(result, p)
		}
	}
	return result
}

func goType(t string) string {
	switch t {
	case "integer":
		return "int"
	case "boolean":
		return "bool"
	case "number":
		return "float64"
	default:
		return "string"
	}
}

func flagType(t string) string {
	switch t {
	case "integer":
		return "Int"
	case "boolean":
		return "Bool"
	case "number":
		return "Float64"
	default:
		return "String"
	}
}

func escapeQuotes(s string) string {
	s = strings.ReplaceAll(s, `\`, `\\`)
	s = strings.ReplaceAll(s, `"`, `\"`)
	s = strings.ReplaceAll(s, "\n", " ")
	s = strings.ReplaceAll(s, "\r", "")
	s = strings.ReplaceAll(s, "`", "'")
	return s
}

func dedupeOperations(ops []*Operation) []*Operation {
	seen := make(map[string]bool)
	var result []*Operation
	for _, op := range ops {
		if !seen[op.Name] {
			seen[op.Name] = true
			result = append(result, op)
		} else {
			fmt.Fprintf(os.Stderr, "  Warning: duplicate operation name %q — dropping %s %s\n", op.Name, op.Method, op.Path)
		}
	}
	return result
}

func hasPostOrPut(ops []*Operation) bool {
	for _, op := range ops {
		if op.Method == "POST" || op.Method == "PUT" || op.Method == "PATCH" {
			return true
		}
	}
	return false
}

func hasDelete(ops []*Operation) bool {
	for _, op := range ops {
		if op.Method == "DELETE" {
			return true
		}
	}
	return false
}

func hasDestructive(ops []*Operation) bool {
	for _, op := range ops {
		if op.IsDestructive {
			return true
		}
	}
	return false
}

func hasQueryParams(ops []*Operation) bool {
	// Returns true for query params that use fmt.Sprintf (integer and array types).
	// String params use url.QueryEscape concatenation; boolean params use literals.
	for _, op := range ops {
		for _, p := range op.Parameters {
			if p.In == "query" && (p.Type == "integer" || p.IsArray) {
				return true
			}
		}
	}
	return false
}

func needsFmt(r *Resource) bool {
	// fmt is needed for: destructive confirmations, query param formatting,
	// delete success message, scaffold output, apply status messages, multipart error wrapping
	return hasDestructive(r.Operations) || hasQueryParams(r.Operations) || hasDelete(r.Operations) || hasScaffold(r.Operations) || shouldGenerateApply(r) || needsMultipart(r) || hasAnyBinaryResponse(r)
}

func needsMultipart(r *Resource) bool {
	for _, op := range r.Operations {
		if op.RequestBody != nil && op.RequestBody.IsMultipart {
			return true
		}
	}
	return false
}

func hasAnyBinaryResponse(r *Resource) bool {
	for _, op := range r.Operations {
		if opHasBinaryResponse(op) {
			return true
		}
	}
	return false
}

func opHasBinaryResponse(op *Operation) bool {
	for _, resp := range op.Responses {
		if resp.IsBinary && (resp.StatusCode == "200" || resp.StatusCode == "201") {
			return true
		}
	}
	return false
}

func hasDeleteMultiple(ops []*Operation) bool {
	for _, op := range ops {
		if op.Name == "delete-multiple" {
			return true
		}
	}
	return false
}

func needsURL(r *Resource) bool {
	// net/url is needed for path param encoding, query param encoding, get-by-name, and apply
	if shouldGenerateApply(r) {
		return true
	}
	for _, op := range r.Operations {
		if op.Name == "get" && op.Method == "GET" && hasPathParam(op.Path) {
			return true
		}
		for _, p := range op.Parameters {
			if p.In == "path" {
				return true
			}
			if p.In == "query" && (p.Type == "string" || p.IsArray) {
				return true
			}
		}
	}
	return false
}

// shouldGenerateApply returns true if the resource should have an apply (upsert) command.
// Singletons are excluded: they have no name-based collection to search, so upsert
// semantics don't apply.
func shouldGenerateApply(r *Resource) bool {
	return !r.IsSingleton && hasApply(r.Operations)
}

// scaffoldJSON generates a JSON template string from a schema, skipping read-only fields.
func scaffoldJSON(s *Schema) string {
	if s == nil || len(s.Properties) == 0 {
		return "{}"
	}

	// Sort property names for deterministic output
	names := make([]string, 0, len(s.Properties))
	for name := range s.Properties {
		names = append(names, name)
	}
	sort.Strings(names)

	obj := make(map[string]any)
	for _, name := range names {
		prop := s.Properties[name]
		if prop.ReadOnly {
			continue
		}
		if prop.Example != nil {
			obj[name] = prop.Example
		} else {
			switch prop.Type {
			case "string":
				obj[name] = ""
			case "integer", "number":
				obj[name] = 0
			case "boolean":
				obj[name] = false
			case "array":
				obj[name] = []any{}
			case "object":
				obj[name] = map[string]any{}
			default:
				obj[name] = ""
			}
		}
	}

	data, err := json.MarshalIndent(obj, "", "  ")
	if err != nil {
		return "{}"
	}
	return string(data)
}

// hasDeleteByName returns true if the resource has a delete operation and a
// get operation with a path parameter (needed for name-to-ID resolution).
func hasDeleteByName(ops []*Operation) bool {
	hasDeleteOp := false
	hasGetWithParam := false
	for _, op := range ops {
		if op.Method == "DELETE" && op.Name == "delete" {
			hasDeleteOp = true
		}
		if op.Name == "get" && op.Method == "GET" && hasPathParam(op.Path) {
			hasGetWithParam = true
		}
	}
	return hasDeleteOp && hasGetWithParam
}

// hasApply returns true if the resource has both create and update operations.
func hasApply(ops []*Operation) bool {
	hasCreate := false
	hasUpdate := false
	for _, op := range ops {
		if op.Name == "create" && op.Method == "POST" {
			hasCreate = true
		}
		if op.Name == "update" && op.Method == "PUT" {
			hasUpdate = true
		}
	}
	return hasCreate && hasUpdate
}

// hasScaffold returns true if any operation has a request body with a schema.
func hasScaffold(ops []*Operation) bool {
	for _, op := range ops {
		if op.RequestBody != nil && op.RequestBody.Schema != nil && len(op.RequestBody.Schema.Properties) > 0 {
			if op.Method == "POST" || op.Method == "PUT" || op.Method == "PATCH" {
				return true
			}
		}
	}
	return false
}

func sortOperations(ops []*Operation) []*Operation {
	// Define order: list, get, create, update, delete, then others
	order := map[string]int{
		"list":             1,
		"get":              2,
		"create":           3,
		"update":           4,
		"delete":           5,
		"delete-multiple":  6,
		"history":          7,
		"add-history-note": 8,
		"export":           9,
		"history-export":   10,
	}

	sorted := make([]*Operation, len(ops))
	copy(sorted, ops)

	sort.Slice(sorted, func(i, j int) bool {
		oi, oki := order[sorted[i].Name]
		oj, okj := order[sorted[j].Name]
		if !oki {
			oi = 100
		}
		if !okj {
			oj = 100
		}
		return oi < oj
	})

	return sorted
}

const resourceTemplate = `// Copyright 2026, Jamf Software LLC
// Code generated by jamf-cli generator. DO NOT EDIT.
package generated

import (
{{- if or (shouldGenerateApply .) (needsMultipart .) }}
	"bytes"
{{- end }}
{{- if or (hasList .Operations) (hasDeleteMultiple .Operations) }}
	"encoding/json"
{{- end }}
{{- if or (needsFmt .) (hasList .Operations) }}
	"fmt"
{{- end }}
{{- if or (hasPostOrPut .Operations) (hasList .Operations) (hasAnyBinaryResponse .) }}
	"io"
{{- end }}
{{- if needsMultipart . }}
	"mime/multipart"
{{- end }}
{{- if hasDelete .Operations }}
	"net/http"
{{- end }}
{{- if needsURL . }}
	"net/url"
{{- end }}
{{- if or (hasPostOrPut .Operations) (hasDestructive .Operations) (hasDelete .Operations) (shouldGenerateApply .) (hasAnyBinaryResponse .) }}
	"os"
{{- end }}
{{- if needsMultipart . }}
	"path/filepath"
{{- end }}
	"strings"

	"github.com/spf13/cobra"

	"github.com/Jamf-Concepts/jamf-cli/internal/registry"
)

// New{{ .GoName }}Cmd creates the {{ .Name }} command group
func New{{ .GoName }}Cmd(ctx *registry.CLIContext) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "{{ .Name }}",
		Short: "Manage {{ .Name }}",
		Long:  ` + "`" + `Manage {{ .Name }} in Jamf Pro.` + "`" + `,
	}
{{ range dedupeOps (sortOps .Operations) }}
	cmd.AddCommand(new{{ $.GoName }}{{ toCamel .Name }}Cmd(ctx))
{{- end }}
{{- range dedupeOps (sortOps .Operations) }}{{ if isGet . }}
	cmd.AddCommand(new{{ $.GoName }}GetByNameCmd(ctx))
{{- end }}{{ end }}
{{- if shouldGenerateApply . }}
	cmd.AddCommand(new{{ .GoName }}ApplyCmd(ctx))
{{- end }}
{{- if hasDeleteByName .Operations }}
	cmd.AddCommand(new{{ .GoName }}DeleteByNameCmd(ctx))
{{- end }}

	return cmd
}
{{ range dedupeOps (sortOps .Operations) }}
func new{{ $.GoName }}{{ toCamel .Name }}Cmd(ctx *registry.CLIContext) *cobra.Command {
	var (
{{- range queryParams .Parameters }}
{{- if .IsArray }}
		flag{{ toCamel .Name }} []{{ goType .Type }}
{{- else }}
		flag{{ toCamel .Name }} {{ goType .Type }}
{{- end }}
{{- end }}
{{- if .IsList }}
		flagAll  bool
		flagLimit int
{{- end }}
{{- if .IsDestructive }}
		flagYes bool
		flagDryRun bool
{{- end }}
{{- if eq .Name "delete-multiple" }}
		flagIds []string
{{- end }}
{{- if opHasScaffold . }}
		flagScaffold bool
{{- end }}
{{- if opIsMultipart . }}
		flagFile string
{{- end }}
{{- if opHasBinaryResponse . }}
		flagSaveTo string
{{- end }}
	)

	cmd := &cobra.Command{
		Use:   "{{ .Name }}{{ if hasPathParam .Path }} <id>{{ end }}",
		Short: "{{ escapeQuotes .Summary }}",
{{- if .Description }}
		Long:  "{{ escapeQuotes .Description }}",
{{- end }}
{{- $ex := exampleText $.Name $.NameSingular . }}{{ if $ex }}
		Example: ` + "`" + `{{ $ex }}` + "`" + `,
{{- end }}
{{- if hasPathParam .Path }}
		Args:  cobra.ExactArgs(1),
{{- end }}
		RunE: func(cmd *cobra.Command, args []string) error {
			reqCtx := cmd.Context()
{{- if opHasBinaryResponse . }}
			reqCtx = registry.WithAccept(reqCtx, "*/*")
{{- end }}
{{- if opHasScaffold . }}

			if flagScaffold {
				fmt.Println(` + "`" + `{{ opScaffoldJSON . }}` + "`" + `)
				return nil
			}
{{- end }}
{{- if .IsDestructive }}

			// Confirmation for destructive action
			if flagDryRun {
				fmt.Fprintf(os.Stderr, "Would {{ .Name }}{{ if hasPathParam .Path }} resource %s{{ end }}\n"{{ if hasPathParam .Path }}, args[0]{{ end }})
				return nil
			}
			if !flagYes {
				noInput, _ := cmd.Flags().GetBool("no-input")
				if noInput {
					return fmt.Errorf("destructive operation requires --yes when --no-input is set")
				}
				fmt.Fprintf(os.Stderr, "⚠️  This will {{ .Name }}{{ if hasPathParam .Path }} resource %s{{ end }}. Type 'yes' to confirm: "{{ if hasPathParam .Path }}, args[0]{{ end }})
				var confirm string
				fmt.Scanln(&confirm)
				if confirm != "yes" {
					return fmt.Errorf("aborted")
				}
			}
{{- end }}


			// Build request path
			path := "{{ .Path }}"
{{- range pathParams .Parameters }}
			path = strings.Replace(path, "{{"{"}}{{ .Name }}{{"}"}}", url.PathEscape(args[0]), 1)
{{- end }}

			// Build query string
			var queryParts []string
{{- range queryParams .Parameters }}
{{- if .IsArray }}
			if len(flag{{ toCamel .Name }}) > 0 {
				for _, v := range flag{{ toCamel .Name }} {
					queryParts = append(queryParts, "{{ .Name }}=" + url.QueryEscape(fmt.Sprintf("%v", v)))
				}
			}
{{- else if eq .Type "string" }}
			if flag{{ toCamel .Name }} != "" {
				queryParts = append(queryParts, "{{ .Name }}=" + url.QueryEscape(flag{{ toCamel .Name }}))
			}
{{- else if eq .Type "integer" }}
			if flag{{ toCamel .Name }} != 0 {
				queryParts = append(queryParts, fmt.Sprintf("{{ .Name }}=%d", flag{{ toCamel .Name }}))
			}
{{- else if eq .Type "boolean" }}
			if flag{{ toCamel .Name }} {
				queryParts = append(queryParts, "{{ .Name }}=true")
			}
{{- end }}
{{- end }}
			if len(queryParts) > 0 {
				path = path + "?" + strings.Join(queryParts, "&")
			}
{{- if .IsList }}

			// Auto-pagination: fetch all pages when --all is set and --page was not manually specified
			if flagAll && flagPage == 0 {
				var allResults []json.RawMessage
				pageNum := 0
				pageSize := 100

				for {
					// Build page-specific query
					pagePath := "{{ .Path }}"
{{- range pathParams .Parameters }}
					pagePath = strings.Replace(pagePath, "{{"{"}}{{ .Name }}{{"}"}}", url.PathEscape(args[0]), 1)
{{- end }}
					var pageQuery []string
					// Carry forward non-pagination query params
					for _, qp := range queryParts {
						if !strings.HasPrefix(qp, "page=") && !strings.HasPrefix(qp, "page-size=") && !strings.HasPrefix(qp, "pagesize=") {
							pageQuery = append(pageQuery, qp)
						}
					}
					pageQuery = append(pageQuery, fmt.Sprintf("page=%d", pageNum))
					pageQuery = append(pageQuery, fmt.Sprintf("page-size=%d", pageSize))
					pagePath = pagePath + "?" + strings.Join(pageQuery, "&")

					resp, err := ctx.Client.Do(reqCtx, "GET", pagePath, nil)
					if err != nil {
						return err
					}

					body, err := io.ReadAll(resp.Body)
					resp.Body.Close()
					if err != nil {
						return err
					}

					// Parse pagination response: {"totalCount": N, "results": [...]}
					var pageResp struct {
						TotalCount int               ` + "`" + `json:"totalCount"` + "`" + `
						Results    []json.RawMessage  ` + "`" + `json:"results"` + "`" + `
					}
					if err := json.Unmarshal(body, &pageResp); err != nil {
						// Not a paginated response; output as-is
						return ctx.Output.PrintRaw(body)
					}

					allResults = append(allResults, pageResp.Results...)

					// Check limit
					if flagLimit > 0 && len(allResults) >= flagLimit {
						allResults = allResults[:flagLimit]
						break
					}

					// Check if we've fetched everything
					if len(pageResp.Results) < pageSize || len(allResults) >= pageResp.TotalCount {
						break
					}

					pageNum++
				}

				// Output combined results as JSON array
				combined, err := json.MarshalIndent(allResults, "", "  ")
				if err != nil {
					return err
				}
				return ctx.Output.PrintRaw(combined)
			}
{{- end }}

			// Make request
{{- if opIsMultipart . }}
			if ctx.Uploader == nil {
				return fmt.Errorf("file upload not supported in this context")
			}
			f, err := os.Open(flagFile)
			if err != nil {
				return fmt.Errorf("opening %s: %w", flagFile, err)
			}
			defer f.Close()
			var buf bytes.Buffer
			mw := multipart.NewWriter(&buf)
			fw, err := mw.CreateFormFile("{{ .RequestBody.FileField }}", filepath.Base(flagFile))
			if err != nil {
				return fmt.Errorf("creating form file: %w", err)
			}
			if _, err := io.Copy(fw, f); err != nil {
				return fmt.Errorf("writing file: %w", err)
			}
			mw.Close()
			resp, err := ctx.Uploader.Upload(reqCtx, path, &buf, mw.FormDataContentType(), int64(buf.Len()))
{{- else if eq .Method "GET" "DELETE" }}
			resp, err := ctx.Client.Do(reqCtx, "{{ .Method }}", path, nil)
{{- else }}
			// Read body from stdin if available
			var body io.Reader
{{- if eq .Name "delete-multiple" }}
			// Handle --ids flag for bulk operations
			if len(flagIds) > 0 {
				payload := struct {
					IDs []string ` + "`" + `json:"ids"` + "`" + `
				}{IDs: flagIds}
				idsJSON, err := json.Marshal(payload)
				if err != nil {
					return fmt.Errorf("encoding ids: %w", err)
				}
				body = strings.NewReader(string(idsJSON))
			} else {
				stat, _ := os.Stdin.Stat()
				if (stat.Mode() & os.ModeCharDevice) == 0 {
					body = os.Stdin
				}
			}
{{- else }}
			stat, _ := os.Stdin.Stat()
			if (stat.Mode() & os.ModeCharDevice) == 0 {
				body = os.Stdin
			}
{{- end }}
			resp, err := ctx.Client.Do(reqCtx, "{{ .Method }}", path, body)
{{- end }}
			if err != nil {
				return err
			}
			defer resp.Body.Close()

{{ if eq .Method "DELETE" }}
			if resp.StatusCode == http.StatusNoContent {
				fmt.Fprintln(os.Stderr, "Deleted successfully")
				return nil
			}
{{ end }}
{{- if opHasBinaryResponse . }}
			if flagSaveTo != "" {
				f, err := os.Create(flagSaveTo)
				if err != nil {
					return fmt.Errorf("opening output file: %w", err)
				}
				defer f.Close()
				n, err := io.Copy(f, resp.Body)
				if err != nil {
					return err
				}
				fmt.Fprintf(os.Stderr, "Saved to %s (%d bytes)\n", flagSaveTo, n)
				return nil
			}
			_, err = io.Copy(os.Stdout, resp.Body)
			return err
{{- else }}
			return ctx.Output.PrintResponse(resp)
{{- end }}
		},
	}
{{ range queryParams .Parameters }}
{{- if .IsArray }}
	cmd.Flags().{{ flagType .Type }}SliceVar(&flag{{ toCamel .Name }}, "{{ toKebab .Name }}", nil, "{{ escapeQuotes .Description }}")
{{- else }}
	cmd.Flags().{{ flagType .Type }}Var(&flag{{ toCamel .Name }}, "{{ toKebab .Name }}", {{ if .Default }}{{ defaultVal .Type .Default }}{{ else if eq .Type "string" }}""{{ else if eq .Type "integer" }}0{{ else if eq .Type "boolean" }}false{{ else }}0{{ end }}, "{{ escapeQuotes .Description }}")
{{- end }}
{{- end }}
{{- if .IsList }}
	cmd.Flags().BoolVar(&flagAll, "all", true, "Fetch all pages (set --all=false for single page)")
	cmd.Flags().IntVar(&flagLimit, "limit", 0, "Maximum total results to return (0 = unlimited)")
{{- end }}
{{- if .IsDestructive }}
	cmd.Flags().BoolVar(&flagYes, "yes", false, "Skip confirmation prompt")
	cmd.Flags().BoolVarP(&flagDryRun, "dry-run", "n", false, "Preview without executing")
{{- end }}
{{- if eq .Name "delete-multiple" }}
	cmd.Flags().StringSliceVar(&flagIds, "ids", nil, "IDs to delete (comma-separated)")
{{- end }}
{{- if opHasScaffold . }}
	cmd.Flags().BoolVar(&flagScaffold, "scaffold", false, "Print a JSON template for the request body and exit")
{{- end }}
{{- if opIsMultipart . }}
	cmd.Flags().StringVar(&flagFile, "file", "", "Path to file to upload (required)")
	_ = cmd.MarkFlagRequired("file")
{{- end }}
{{- if opHasBinaryResponse . }}
	cmd.Flags().StringVarP(&flagSaveTo, "save-to", "O", "", "Save output to file instead of stdout")
{{- end }}

	return cmd
}
{{ end }}
{{ range dedupeOps (sortOps .Operations) }}{{ if isGet . }}
func new{{ $.GoName }}GetByNameCmd(ctx *registry.CLIContext) *cobra.Command {
	return &cobra.Command{
		Use:   "get-by-name <name>",
		Short: "Get a {{ $.NameSingular }} by name",
		Example: ` + "`" + `  # Get a {{ $.NameSingular }} by name
  jamf-cli {{ $.Name }} get-by-name "Example"

  # Get by name and output as YAML
  jamf-cli {{ $.Name }} get-by-name "Example" -o yaml` + "`" + `,
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			reqCtx := cmd.Context()
			id, err := resolveNameToID(reqCtx, ctx.Client, "{{ listPath . }}", "{{ $.NameField }}", args[0])
			if err != nil {
				return err
			}
			path := strings.Replace("{{ .Path }}", "{{ pathParamName . }}", url.PathEscape(id), 1)
			resp, err := ctx.Client.Do(reqCtx, "GET", path, nil)
			if err != nil {
				return err
			}
			defer resp.Body.Close()
			return ctx.Output.PrintResponse(resp)
		},
	}
}
{{ end }}{{ end }}
{{ if hasDeleteByName .Operations }}
func new{{ .GoName }}DeleteByNameCmd(ctx *registry.CLIContext) *cobra.Command {
	var (
		flagYes    bool
		flagDryRun bool
	)

	cmd := &cobra.Command{
		Use:   "delete-by-name <name>",
		Short: "Delete a {{ .NameSingular }} by name",
		Example: ` + "`" + `  # Delete a {{ .NameSingular }} by name (with confirmation)
  jamf-cli {{ .Name }} delete-by-name "Example"

  # Delete without confirmation prompt
  jamf-cli {{ .Name }} delete-by-name "Example" --yes` + "`" + `,
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			reqCtx := cmd.Context()
			name := args[0]

			// Resolve name to ID (collision-aware)
			noInput, _ := cmd.Flags().GetBool("no-input")
			id, err := resolveNameToIDForApply(reqCtx, ctx.Client, "{{ listPathFromOps .Operations }}", "{{ .NameField }}", name, noInput)
			if err != nil {
				return err
			}
			if id == "" {
				return fmt.Errorf("no {{ .NameSingular }} found with {{ .NameField }} %q", name)
			}

			if flagDryRun {
				fmt.Fprintf(os.Stderr, "[dry-run] Would delete {{ .NameSingular }} %q (id: %s)\n", name, id)
				return nil
			}
			if !flagYes {
				if noInput {
					return fmt.Errorf("destructive operation requires --yes when --no-input is set")
				}
				fmt.Fprintf(os.Stderr, "This will delete {{ .NameSingular }} %q (id: %s). Type 'yes' to confirm: ", name, id)
				var confirm string
				fmt.Scanln(&confirm)
				if confirm != "yes" {
					return fmt.Errorf("aborted")
				}
			}

			path := strings.Replace("{{ deletePath .Operations }}", "{{ deletePathParam .Operations }}", url.PathEscape(id), 1)
			resp, err := ctx.Client.Do(reqCtx, "DELETE", path, nil)
			if err != nil {
				return err
			}
			defer resp.Body.Close()

			if resp.StatusCode == http.StatusNoContent {
				fmt.Fprintf(os.Stderr, "Deleted {{ .NameSingular }} %q (id: %s)\n", name, id)
				return nil
			}
			return ctx.Output.PrintResponse(resp)
		},
	}

	cmd.Flags().BoolVar(&flagYes, "yes", false, "Skip confirmation prompt")
	cmd.Flags().BoolVarP(&flagDryRun, "dry-run", "n", false, "Preview without executing")

	return cmd
}
{{ end }}
{{ if shouldGenerateApply . }}
func new{{ .GoName }}ApplyCmd(ctx *registry.CLIContext) *cobra.Command {
	var (
		fromFile   string
		flagYes    bool
		flagDryRun bool
	)

	cmd := &cobra.Command{
		Use:   "apply",
		Short: "Create or replace a {{ .NameSingular }} by name",
		Long: ` + "`" + `Create or replace a {{ .NameSingular }}. Reads JSON from --from-file or stdin.

The {{ .NameField }} field in the input is used to check if the resource
already exists. If it does, the resource is replaced (with confirmation).
If not, a new resource is created.` + "`" + `,
		Example: ` + "`" + `  # Apply a {{ .NameSingular }} from a file
  jamf-cli {{ .Name }} apply --from-file {{ .NameSingular }}.json

  # Apply from stdin
  cat {{ .NameSingular }}.json | jamf-cli {{ .Name }} apply

  # Apply without replacement confirmation
  jamf-cli {{ .Name }} apply --from-file {{ .NameSingular }}.json --yes

  # Preview what would happen
  jamf-cli {{ .Name }} apply --from-file {{ .NameSingular }}.json --dry-run` + "`" + `,
		RunE: func(cmd *cobra.Command, _ []string) error {
			reqCtx := cmd.Context()

			// Read input
			data, err := readApplyInput(fromFile)
			if err != nil {
				return err
			}

			// Extract name from JSON input
			name, err := extractJSONField(data, "{{ .NameField }}")
			if err != nil {
				return fmt.Errorf("input must include a %q field: %w", "{{ .NameField }}", err)
			}

			// Check if resource exists by name (read-only, runs even in dry-run)
			noInput, _ := cmd.Flags().GetBool("no-input")
			id, err := resolveNameToIDForApply(reqCtx, ctx.Client, "{{ listPathFromOps .Operations }}", "{{ .NameField }}", name, noInput)
			if err != nil {
				return err
			}

			if id == "" {
				// Not found — create
				if flagDryRun {
					fmt.Fprintf(os.Stderr, "[dry-run] Would create {{ .NameSingular }} %q\n", name)
					return nil
				}
				resp, err := ctx.Client.Do(reqCtx, "POST", "{{ createPath .Operations }}", bytes.NewReader(data))
				if err != nil {
					return err
				}
				defer resp.Body.Close()
				fmt.Fprintf(os.Stderr, "Created {{ .NameSingular }} %q\n", name)
				return ctx.Output.PrintResponse(resp)
			}

			// Found — replace
			if flagDryRun {
				fmt.Fprintf(os.Stderr, "[dry-run] Would replace {{ .NameSingular }} %q (id: %s)\n", name, id)
				return nil
			}
			if !flagYes {
				if noInput {
					return fmt.Errorf("{{ .NameSingular }} %q already exists (id: %s); use --yes to replace when --no-input is set", name, id)
				}
				fmt.Fprintf(os.Stderr, "{{ .NameSingular }} %q already exists (id: %s) and will be replaced. Type 'yes' to confirm: ", name, id)
				var confirm string
				fmt.Scanln(&confirm)
				if confirm != "yes" {
					return fmt.Errorf("aborted")
				}
			}

			updatePath := strings.Replace("{{ updatePath .Operations }}", "{{ updatePathParam .Operations }}", url.PathEscape(id), 1)
			resp, err := ctx.Client.Do(reqCtx, "PUT", updatePath, bytes.NewReader(data))
			if err != nil {
				return err
			}
			defer resp.Body.Close()
			fmt.Fprintf(os.Stderr, "Replaced {{ .NameSingular }} %q (id: %s)\n", name, id)
			return ctx.Output.PrintResponse(resp)
		},
	}

	cmd.Flags().StringVar(&fromFile, "from-file", "", "Path to JSON input file (or pipe JSON to stdin)")
	cmd.Flags().BoolVar(&flagYes, "yes", false, "Skip confirmation prompt when replacing")
	cmd.Flags().BoolVarP(&flagDryRun, "dry-run", "n", false, "Preview without executing")

	return cmd
}
{{ end }}
`

const registryTemplate = `// Copyright 2026, Jamf Software LLC
// Code generated by jamf-cli generator. DO NOT EDIT.
package generated

import (
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/url"
	"os"
	"strings"

	"github.com/spf13/cobra"

	"github.com/Jamf-Concepts/jamf-cli/internal/registry"
)

// RegisterCommands registers all generated resource commands
func RegisterCommands(root *cobra.Command, ctx *registry.CLIContext) {
{{- range . }}
	root.AddCommand(New{{ .GoName }}Cmd(ctx))
{{- end }}
}

// resolveNameToID looks up a resource by name using a filtered list call and
// returns its ID. This enables --name as an alternative to positional ID args
// on get commands. The nameField parameter specifies the filter field
// (usually "name", but some resources use "displayName").
func resolveNameToID(ctx context.Context, client registry.HTTPClient, listPath, nameField, name string) (string, error) {
	filterPath := fmt.Sprintf("%s?filter=%s&page-size=1",
		listPath, url.QueryEscape(fmt.Sprintf(` + "`" + `%s=="%s"` + "`" + `, nameField, name)))

	resp, err := client.Do(ctx, "GET", filterPath, nil)
	if err != nil {
		return "", fmt.Errorf("looking up %q: %w", name, err)
	}
	defer func() { _ = resp.Body.Close() }()

	body, err := io.ReadAll(io.LimitReader(resp.Body, 1<<20))
	if err != nil {
		return "", fmt.Errorf("reading lookup response: %w", err)
	}

	// Paginated response: {"totalCount": N, "results": [{...}]}
	var data struct {
		TotalCount int               ` + "`" + `json:"totalCount"` + "`" + `
		Results    []json.RawMessage ` + "`" + `json:"results"` + "`" + `
	}
	if err := json.Unmarshal(body, &data); err != nil {
		// Some endpoints return plain arrays instead of paginated objects
		var arr []json.RawMessage
		if jsonErr := json.Unmarshal(body, &arr); jsonErr != nil {
			return "", fmt.Errorf("parsing lookup response: %w", err)
		}
		data.Results = arr
		data.TotalCount = len(arr)
	}

	if data.TotalCount == 0 || len(data.Results) == 0 {
		return "", fmt.Errorf("no resource found with name %q", name)
	}

	var first map[string]any
	if err := json.Unmarshal(data.Results[0], &first); err != nil {
		return "", fmt.Errorf("parsing lookup result: %w", err)
	}

	// Extract ID — could be string or number
	switch v := first["id"].(type) {
	case string:
		if v == "" {
			return "", fmt.Errorf("resource %q has no ID", name)
		}
		return v, nil
	case float64:
		return fmt.Sprintf("%d", int(v)), nil
	default:
		return "", fmt.Errorf("resource %q has unexpected ID type", name)
	}
}

// extractIDString extracts the "id" field from a JSON object as a string.
// NOTE: Also used by classic_registry.go helpers (same generated package).
func extractIDString(obj map[string]any) string {
	switch v := obj["id"].(type) {
	case string:
		return v
	case float64:
		return fmt.Sprintf("%d", int(v))
	default:
		return ""
	}
}

// readApplyInput reads input from --from-file or stdin for apply commands.
// NOTE: Also used by classic_registry.go helpers (same generated package).
func readApplyInput(fromFile string) ([]byte, error) {
	if fromFile != "" {
		data, err := os.ReadFile(fromFile)
		if err != nil {
			return nil, fmt.Errorf("reading input file: %w", err)
		}
		return data, nil
	}

	stat, _ := os.Stdin.Stat()
	if (stat.Mode() & os.ModeCharDevice) == 0 {
		data, err := io.ReadAll(io.LimitReader(os.Stdin, 10<<20))
		if err != nil {
			return nil, fmt.Errorf("reading stdin: %w", err)
		}
		if len(data) > 0 {
			return data, nil
		}
	}

	return nil, fmt.Errorf("input required: use --from-file or pipe data to stdin")
}

// extractJSONField extracts a string field from a JSON object.
func extractJSONField(data []byte, field string) (string, error) {
	var obj map[string]any
	if err := json.Unmarshal(data, &obj); err != nil {
		return "", fmt.Errorf("parsing JSON: %w", err)
	}
	val, ok := obj[field]
	if !ok {
		return "", fmt.Errorf("field %q not found", field)
	}
	s, ok := val.(string)
	if !ok || s == "" {
		return "", fmt.Errorf("field %q must be a non-empty string", field)
	}
	return s, nil
}

// resolveNameToIDForApply looks up a resource by name and returns its ID.
// Unlike resolveNameToID, it fetches enough results to detect collisions.
// Returns ("", nil) when no resource is found (caller should create).
// Returns (id, nil) when exactly one match is found.
// Returns ("", error) when multiple matches or lookup fails.
func resolveNameToIDForApply(ctx context.Context, client registry.HTTPClient, listPath, nameField, name string, noInput bool) (string, error) {
	// Escape double quotes in name to prevent RSQL injection
	escapedName := strings.ReplaceAll(name, ` + "`" + `"` + "`" + `, ` + "`" + `\"` + "`" + `)
	filterPath := fmt.Sprintf("%s?filter=%s&page-size=100",
		listPath, url.QueryEscape(fmt.Sprintf(` + "`" + `%s=="%s"` + "`" + `, nameField, escapedName)))

	resp, err := client.Do(ctx, "GET", filterPath, nil)
	if err != nil {
		return "", fmt.Errorf("looking up %q: %w", name, err)
	}
	defer func() { _ = resp.Body.Close() }()

	body, err := io.ReadAll(io.LimitReader(resp.Body, 1<<20))
	if err != nil {
		return "", fmt.Errorf("reading lookup response: %w", err)
	}

	var data struct {
		TotalCount int               ` + "`" + `json:"totalCount"` + "`" + `
		Results    []json.RawMessage ` + "`" + `json:"results"` + "`" + `
	}
	if err := json.Unmarshal(body, &data); err != nil {
		var arr []json.RawMessage
		if jsonErr := json.Unmarshal(body, &arr); jsonErr != nil {
			return "", fmt.Errorf("parsing lookup response: %w", err)
		}
		data.Results = arr
		data.TotalCount = len(arr)
	}

	if data.TotalCount == 0 || len(data.Results) == 0 {
		return "", nil // Not found — caller should create
	}

	// Parse results to extract IDs
	type applyMatch struct {
		id string
	}
	var matches []applyMatch
	for _, raw := range data.Results {
		var obj map[string]any
		if err := json.Unmarshal(raw, &obj); err != nil {
			continue
		}
		if id := extractIDString(obj); id != "" {
			matches = append(matches, applyMatch{id: id})
		}
	}

	if len(matches) == 0 {
		return "", nil
	}

	if len(matches) == 1 {
		return matches[0].id, nil
	}

	// Collision: multiple resources with the same name
	if noInput {
		ids := make([]string, len(matches))
		for i, m := range matches {
			ids[i] = m.id
		}
		return "", fmt.Errorf("multiple resources found with name %q (IDs: %s); resolve duplicates or use update with a specific ID", name, strings.Join(ids, ", "))
	}

	// Interactive: prompt user to pick
	fmt.Fprintf(os.Stderr, "Multiple resources found with name %q:\n", name)
	for i, m := range matches {
		fmt.Fprintf(os.Stderr, "  [%d] ID: %s\n", i+1, m.id)
	}
	fmt.Fprintf(os.Stderr, "Enter number to replace (or 0 to cancel): ")
	var choice int
	if _, err := fmt.Fscan(os.Stdin, &choice); err != nil || choice < 1 || choice > len(matches) {
		return "", fmt.Errorf("aborted")
	}
	return matches[choice-1].id, nil
}
`
