// Copyright 2026, Jamf Software LLC

package parser

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"text/template"

	"github.com/iancoleman/strcase"
)

// CodegenHeader is the marker line at the top of every modern API generated file.
// Must match the first line of resourceTemplate and registryTemplate.
const CodegenHeader = "// Code generated by jamf-cli generator. DO NOT EDIT."

// goosNames is the set of valid GOOS values recognised by the Go toolchain.
// Files ending in _<goos>.go are treated as OS-specific and excluded from
// builds on other platforms. We must avoid generating such filenames.
// Keep in sync with: go tool dist list | cut -d/ -f1 | sort -u
var goosNames = map[string]bool{
	"aix": true, "android": true, "darwin": true, "dragonfly": true,
	"freebsd": true, "hurd": true, "illumos": true, "ios": true,
	"js": true, "linux": true, "netbsd": true, "openbsd": true,
	"plan9": true, "solaris": true, "wasip1": true, "windows": true, "zos": true,
}

// goarchNames is the set of valid GOARCH values recognised by the Go toolchain.
// Keep in sync with: go tool dist list | cut -d/ -f2 | sort -u
var goarchNames = map[string]bool{
	"386": true, "amd64": true, "arm": true, "arm64": true, "loong64": true,
	"mips": true, "mips64": true, "mips64le": true, "mipsle": true,
	"ppc64": true, "ppc64le": true, "riscv64": true, "s390x": true,
	"sparc64": true, "wasm": true,
}

// safeFilename converts a resource name to a Go source filename that won't be
// misinterpreted as an OS/arch-specific build file. If the base name (without .go)
// ends with a known GOOS or GOARCH suffix, "_resource" is appended.
func safeFilename(resourceName string) string {
	base := strings.ReplaceAll(resourceName, "-", "_")
	// Check last underscore-separated segment
	parts := strings.Split(base, "_")
	last := parts[len(parts)-1]
	if goosNames[last] || goarchNames[last] {
		base += "_resource"
	}
	return base + ".go"
}

// Generator generates Go code from parsed resources
type Generator struct {
	outputDir string
}

// NewGenerator creates a new code generator
func NewGenerator(outputDir string) *Generator {
	return &Generator{outputDir: outputDir}
}

// Generate generates a Go command file for a resource
func (g *Generator) Generate(resource *Resource) (string, error) {
	// Deduplicate operations before template execution
	resource.Operations = dedupeOperations(resource.Operations)

	tmpl, err := template.New("resource").Funcs(template.FuncMap{
		"toCamel":           strcase.ToCamel,
		"toLowerCamel":      strcase.ToLowerCamel,
		"toSnake":           strcase.ToSnake,
		"toKebab":           strcase.ToKebab,
		"toScreamingSnake":  strcase.ToScreamingSnake,
		"hasPathParam":      hasPathParam,
		"pathParams":        pathParams,
		"indexedPathParams": indexedPathParams,
		"pathParamCount": func(params []*Parameter) int {
			return len(pathParams(params))
		},
		"pathParamUsage": func(params []*Parameter) string {
			pp := pathParams(params)
			if len(pp) == 0 {
				return ""
			}
			if len(pp) == 1 {
				return " <id>"
			}
			var parts []string
			for _, p := range pp {
				parts = append(parts, "<"+p.Name+">")
			}
			return " " + strings.Join(parts, " ")
		},
		"queryParams":   queryParams,
		"goType":        goType,
		"flagType":      flagType,
		"sortOps":       sortOperations,
		"dedupeOps":     dedupeOperations,
		"escapeQuotes":  escapeQuotes,
		"isDestructive": func(op *Operation) bool { return op.IsDestructive },
		"exampleText": func(r *Resource, op *Operation) string {
			bin := "jamf-cli"
			resourceName := r.Name
			nameSingular := r.NameSingular
			switch op.Name {
			case "list":
				return fmt.Sprintf("  # List all %s\n  %s %s list\n\n  # List %s and extract IDs\n  %s %s list --field id",
					resourceName, bin, resourceName, resourceName, bin, resourceName)
			case "get":
				if !hasPathParam(op.Path) {
					// Singleton get — no ID argument
					return fmt.Sprintf("  # Get %s\n  %s %s get\n\n  # Get %s and output as YAML\n  %s %s get -o yaml",
						resourceName, bin, resourceName, resourceName, bin, resourceName)
				}
				if pp := pathParams(op.Parameters); len(pp) > 1 {
					// Multi-param sub-resource: no --name lookup; use "1 2 ..." as example args
					var argNums []string
					for i := range pp {
						argNums = append(argNums, fmt.Sprintf("%d", i+1))
					}
					idStr := strings.Join(argNums, " ")
					return fmt.Sprintf("  # Get a %s by ID\n  %s %s get %s\n\n  # Get a %s and output as YAML\n  %s %s get %s -o yaml",
						nameSingular, bin, resourceName, idStr, nameSingular, bin, resourceName, idStr)
				}
				if opHasNameLookup(op, r) {
					return fmt.Sprintf("  # Get a %s by ID\n  %s %s get 1\n\n  # Get a %s by name\n  %s %s get --name \"Example\"\n\n  # Get a %s and output as YAML\n  %s %s get 1 -o yaml",
						nameSingular, bin, resourceName, nameSingular, bin, resourceName, nameSingular, bin, resourceName)
				}
				return fmt.Sprintf("  # Get a %s by ID\n  %s %s get 1\n\n  # Get a %s and output as YAML\n  %s %s get 1 -o yaml",
					nameSingular, bin, resourceName, nameSingular, bin, resourceName)
			case "create":
				if op.RequestBody != nil && op.RequestBody.IsMultipart {
					return fmt.Sprintf("  # Upload a file\n  %s pro %s create --file /path/to/file",
						bin, resourceName)
				}
				return fmt.Sprintf("  # Show the JSON template for creating a %s\n  %s %s create --scaffold\n\n  # Create a %s from JSON\n  echo '{\"name\":\"Example\"}' | %s %s create\n\n  # Get a %s, modify it, and create a copy\n  %s %s get 1 -o json | jq '.name = \"Copy\"' | %s %s create",
					nameSingular, bin, resourceName, nameSingular, bin, resourceName, nameSingular, bin, resourceName, bin, resourceName)
			case "update":
				if !hasPathParam(op.Path) {
					// Singleton update — no ID argument
					return fmt.Sprintf("  # Update %s\n  %s %s get -o json | jq '.field = \"value\"' | %s %s update\n\n  # Update from a file\n  %s %s update --from-file %s.json",
						resourceName, bin, resourceName, bin, resourceName, bin, resourceName, resourceName)
				}
				if pp := pathParams(op.Parameters); len(pp) > 1 {
					var argNums []string
					for i := range pp {
						argNums = append(argNums, fmt.Sprintf("%d", i+1))
					}
					idStr := strings.Join(argNums, " ")
					return fmt.Sprintf("  # Update a %s from JSON\n  echo '{\"name\":\"Updated\"}' | %s %s update %s\n\n  # Get a %s, modify, and update\n  %s %s get %s -o json | jq '.name = \"New Name\"' | %s %s update %s",
						nameSingular, bin, resourceName, idStr, nameSingular, bin, resourceName, idStr, bin, resourceName, idStr)
				}
				if opHasNameLookup(op, r) {
					return fmt.Sprintf("  # Update a %s from JSON\n  echo '{\"name\":\"Updated\"}' | %s %s update 1\n\n  # Update by name\n  %s %s get --name \"Example\" -o json | jq '.field = \"value\"' | %s %s update --name \"Example\"\n\n  # Get a %s, modify, and update\n  %s %s get 1 -o json | jq '.name = \"New Name\"' | %s %s update 1",
						nameSingular, bin, resourceName, bin, resourceName, bin, resourceName, nameSingular, bin, resourceName, bin, resourceName)
				}
				return fmt.Sprintf("  # Update a %s from JSON\n  echo '{\"name\":\"Updated\"}' | %s %s update 1\n\n  # Get a %s, modify, and update\n  %s %s get 1 -o json | jq '.name = \"New Name\"' | %s %s update 1",
					nameSingular, bin, resourceName, nameSingular, bin, resourceName, bin, resourceName)
			case "delete":
				if pp := pathParams(op.Parameters); len(pp) > 1 {
					var argNums []string
					for i := range pp {
						argNums = append(argNums, fmt.Sprintf("%d", i+1))
					}
					idStr := strings.Join(argNums, " ")
					return fmt.Sprintf("  # Delete a %s (with confirmation)\n  %s %s delete %s\n\n  # Delete without confirmation prompt\n  %s %s delete %s --yes",
						nameSingular, bin, resourceName, idStr, bin, resourceName, idStr)
				}
				if opHasNameLookup(op, r) {
					return fmt.Sprintf("  # Delete a %s (with confirmation)\n  %s %s delete 1\n\n  # Delete by name\n  %s %s delete --name \"Example\" --yes\n\n  # Delete without confirmation prompt\n  %s %s delete 1 --yes",
						nameSingular, bin, resourceName, bin, resourceName, bin, resourceName)
				}
				return fmt.Sprintf("  # Delete a %s (with confirmation)\n  %s %s delete 1\n\n  # Delete without confirmation prompt\n  %s %s delete 1 --yes",
					nameSingular, bin, resourceName, bin, resourceName)
			case "delete-multiple":
				return fmt.Sprintf("  # Delete multiple %s by IDs\n  %s %s delete-multiple --ids 1,2,3 --yes",
					resourceName, bin, resourceName)
			case "history":
				if pp := pathParams(op.Parameters); len(pp) > 1 {
					var argNums []string
					for i := range pp {
						argNums = append(argNums, fmt.Sprintf("%d", i+1))
					}
					return fmt.Sprintf("  # Get history for a %s\n  %s %s history %s",
						nameSingular, bin, resourceName, strings.Join(argNums, " "))
				}
				if opHasNameLookup(op, r) {
					return fmt.Sprintf("  # Get history for a %s by ID\n  %s %s history 1\n\n  # Get history by name\n  %s %s history --name \"Example\"",
						nameSingular, bin, resourceName, bin, resourceName)
				}
				return fmt.Sprintf("  # Get history for a %s\n  %s %s history 1",
					nameSingular, bin, resourceName)
			case "patch":
				if !hasPathParam(op.Path) {
					return fmt.Sprintf("  # Update a field on %s\n  %s %s patch --set field=value\n\n  # Update using JSON\n  %s %s get -o json | jq '.field = \"value\"' | %s %s patch",
						resourceName, bin, resourceName, bin, resourceName, bin, resourceName)
				}
				return fmt.Sprintf("  # Update a field by ID\n  %s %s patch 1 --set general.managed=true\n\n  # Update multiple fields\n  %s %s patch 1 --set field1=value1 --set field2=value2\n\n  # Patch from a file\n  %s %s patch 1 --from-file changes.json",
					bin, resourceName, bin, resourceName, bin, resourceName)
			case "export":
				return fmt.Sprintf("  # Export %s to CSV\n  %s %s export --out-file %s.csv",
					resourceName, bin, resourceName, resourceName)
			default:
				if opHasBinaryResponse(op) {
					idArg := ""
					if hasPathParam(op.Path) {
						idArg = " <id>"
					}
					return fmt.Sprintf(
						"  # Save to file\n  %s pro %s %s%s -O output.bin\n\n  # Pipe to stdout\n  %s pro %s %s%s > output.bin",
						bin, resourceName, op.Name, idArg,
						bin, resourceName, op.Name, idArg)
				}
				return ""
			}
		},
		"hasPostOrPut":   hasPostOrPut,
		"hasDelete":      hasDelete,
		"hasDestructive": hasDestructive,
		"hasApply":       func(ops []*Operation) bool { return hasApply(ops) },
		"deletePath": func(ops []*Operation) string {
			for _, op := range ops {
				if op.Name == "delete" && op.Method == "DELETE" {
					return op.Path
				}
			}
			return ""
		},
		"deletePathParam": func(ops []*Operation) string {
			for _, op := range ops {
				if op.Name == "delete" && op.Method == "DELETE" {
					start := strings.LastIndex(op.Path, "{")
					end := strings.LastIndex(op.Path, "}")
					if start != -1 && end > start {
						return op.Path[start : end+1]
					}
				}
			}
			return "{id}"
		},
		"listPathFromOps": func(ops []*Operation) string {
			return collectionPath(ops)
		},
		"createPath": func(ops []*Operation) string {
			for _, op := range ops {
				if op.Name == "create" && op.Method == "POST" {
					return op.Path
				}
			}
			return ""
		},
		"updatePath": func(ops []*Operation) string {
			for _, op := range ops {
				if op.Name == "update" && op.Method == "PUT" {
					return op.Path
				}
			}
			return ""
		},
		"updatePathParam": func(ops []*Operation) string {
			for _, op := range ops {
				if op.Name == "update" && op.Method == "PUT" {
					start := strings.LastIndex(op.Path, "{")
					end := strings.LastIndex(op.Path, "}")
					if start != -1 && end > start {
						return op.Path[start : end+1]
					}
				}
			}
			return "{id}"
		},
		"isPatchOp":       isPatchOp,
		"hasPatchOp":      hasPatchOp,
		"patchHasLookup":  func(r *Resource) bool { return patchHasLookup(r) },
		"opHasNameLookup": func(op *Operation, r *Resource) bool { return opHasNameLookup(op, r) },
		"nameLookupPath": func(r *Resource) string {
			if r.NameLookupPath != "" {
				return r.NameLookupPath
			}
			return collectionPath(r.Operations)
		},
		// lookupIDField returns the ID field to extract from nameLookupPath responses.
		// Falls back to IDField when no separate lookup ID field is configured.
		"lookupIDField": func(r *Resource) string {
			if r.NameLookupIDField != "" {
				return r.NameLookupIDField
			}
			return r.IDField
		},
		"patchExampleText": func(r *Resource, op *Operation) string { return patchExampleText(r, op) },
		"patchPath":        func(ops []*Operation) string { return patchPath(ops) },
		"patchPathParam":   func(ops []*Operation) string { return patchPathParam(ops) },
		"patchSetCompletions": func(op *Operation, schemas map[string]*Schema) []string {
			return patchSetCompletions(op, schemas)
		},
		"patchLongDesc": func(op *Operation, schemas map[string]*Schema, r *Resource) string {
			return patchLongDesc(op, schemas, r)
		},
		"hasScaffold":  hasScaffold,
		"scaffoldJSON": scaffoldJSON,
		"opHasScaffold": func(op *Operation) bool {
			// Multipart uploads use --file, not a JSON scaffold.
			if op.RequestBody != nil && op.RequestBody.IsMultipart {
				return false
			}
			return op.RequestBody != nil && op.RequestBody.Schema != nil &&
				len(op.RequestBody.Schema.Properties) > 0 &&
				(op.Method == "POST" || op.Method == "PUT" || op.Method == "PATCH")
		},
		"opScaffoldJSON": func(op *Operation) string {
			if op.RequestBody == nil || op.RequestBody.Schema == nil {
				return "{}"
			}
			return scaffoldJSON(op.RequestBody.Schema)
		},
		"needsFmt":             needsFmt,
		"needsURL":             needsURL,
		"needsMultipart":       needsMultipart,
		"hasAnyBinaryResponse": hasAnyBinaryResponse,
		"opIsMultipart":        func(op *Operation) bool { return op.RequestBody != nil && op.RequestBody.IsMultipart },
		"opHasBinaryResponse":  opHasBinaryResponse,
		"shouldGenerateApply":  shouldGenerateApply,
		"hasResolvableID":      hasResolvableID,
		"hasDeleteMultiple":    hasDeleteMultiple,
		"defaultVal": func(paramType string, val any) string {
			switch paramType {
			case "string":
				return fmt.Sprintf("%q", fmt.Sprintf("%v", val))
			case "integer":
				return fmt.Sprintf("%v", val)
			case "boolean":
				return fmt.Sprintf("%v", val)
			default:
				return fmt.Sprintf("%#v", val)
			}
		},
		"hasList": func(ops []*Operation) bool {
			for _, op := range ops {
				if op.IsList {
					return true
				}
			}
			return false
		},
		"isGet": func(op *Operation) bool {
			return op.Name == "get" && op.Method == "GET" && hasPathParam(op.Path)
		},
		"listPath": func(op *Operation) string {
			// Derive the list endpoint from the get path: /v1/buildings/{id} → /v1/buildings
			path := op.Path
			if idx := strings.LastIndex(path, "/{"); idx != -1 {
				path = path[:idx]
			}
			return path
		},
		"pathParamName": func(op *Operation) string {
			// Extract the path parameter name from the URL path itself,
			// so it works even when the param is defined at the path level
			// in the OpenAPI spec rather than on the individual operation.
			start := strings.LastIndex(op.Path, "{")
			end := strings.LastIndex(op.Path, "}")
			if start != -1 && end > start {
				return op.Path[start : end+1]
			}
			return "{id}"
		},
	}).Parse(resourceTemplate)
	if err != nil {
		return "", fmt.Errorf("parsing template: %w", err)
	}

	filename := safeFilename(resource.Name)
	outPath := filepath.Join(g.outputDir, filename)

	f, err := os.Create(outPath)
	if err != nil {
		return "", fmt.Errorf("creating file: %w", err)
	}

	if err := tmpl.Execute(f, resource); err != nil {
		_ = f.Close()
		_ = os.Remove(outPath)
		return "", fmt.Errorf("executing template: %w", err)
	}

	_ = f.Close()
	return outPath, nil
}

// GenerateRegistry generates the registry file that registers all commands
func (g *Generator) GenerateRegistry(resources []*Resource) (string, error) {
	tmpl, err := template.New("registry").Parse(registryTemplate)
	if err != nil {
		return "", fmt.Errorf("parsing template: %w", err)
	}

	outPath := filepath.Join(g.outputDir, "registry.go")

	f, err := os.Create(outPath)
	if err != nil {
		return "", fmt.Errorf("creating file: %w", err)
	}

	// Sort resources by name
	sort.Slice(resources, func(i, j int) bool {
		return resources[i].Name < resources[j].Name
	})

	if err := tmpl.Execute(f, resources); err != nil {
		_ = f.Close()
		_ = os.Remove(outPath)
		return "", fmt.Errorf("executing template: %w", err)
	}

	_ = f.Close()
	return outPath, nil
}

// Template helper functions
func hasPathParam(path string) bool {
	return strings.Contains(path, "{")
}

func pathParams(params []*Parameter) []*Parameter {
	var result []*Parameter
	for _, p := range params {
		if p.In == "path" {
			result = append(result, p)
		}
	}
	return result
}

// indexedParam pairs a path parameter with its positional index for template use.
type indexedParam struct {
	Index int
	Param *Parameter
}

func indexedPathParams(params []*Parameter) []indexedParam {
	var result []indexedParam
	for _, p := range params {
		if p.In == "path" {
			result = append(result, indexedParam{Index: len(result), Param: p})
		}
	}
	return result
}

func queryParams(params []*Parameter) []*Parameter {
	var result []*Parameter
	for _, p := range params {
		if p.In == "query" {
			result = append(result, p)
		}
	}
	return result
}

func goType(t string) string {
	switch t {
	case "integer":
		return "int"
	case "boolean":
		return "bool"
	case "number":
		return "float64"
	default:
		return "string"
	}
}

func flagType(t string) string {
	switch t {
	case "integer":
		return "Int"
	case "boolean":
		return "Bool"
	case "number":
		return "Float64"
	default:
		return "String"
	}
}

func escapeQuotes(s string) string {
	s = strings.ReplaceAll(s, `\`, `\\`)
	s = strings.ReplaceAll(s, `"`, `\"`)
	s = strings.ReplaceAll(s, "\n", " ")
	s = strings.ReplaceAll(s, "\r", "")
	s = strings.ReplaceAll(s, "`", "'")
	return s
}

// collectionPath returns the canonical collection/list path for a resource's operations.
// Priority:
//  1. "list" GET without path param that also has a direct /{param} child — this confirms
//     it is a true CRUD collection and not a utility endpoint (e.g. feature-toggle).
//  2. "create" POST without path param AND with a direct /{param} child — same safety
//     check; excludes utility POSTs like parse-markdown or tasks/retry.
//  3. Derive from "get" (GET with path param) by stripping the last /{param} segment —
//     only accepted when the result itself has no path params (avoids paths like
//     /foo/{id}/bar/{subId}). This is the original fallback and most common case.
//  4. Derive from "update" (PUT) by stripping the last /{param} — same constraint:
//     result must be param-free.
func collectionPath(ops []*Operation) string {
	hasDirectChild := func(path string) bool {
		for _, other := range ops {
			if strings.HasPrefix(other.Path, path+"/") {
				if strings.HasPrefix(other.Path[len(path):], "/{") {
					return true
				}
			}
		}
		return false
	}

	for _, op := range ops {
		if op.Name == "list" && op.Method == "GET" && !hasPathParam(op.Path) && hasDirectChild(op.Path) {
			return op.Path
		}
	}
	for _, op := range ops {
		if op.Name == "create" && op.Method == "POST" && !hasPathParam(op.Path) && hasDirectChild(op.Path) {
			return op.Path
		}
	}
	for _, op := range ops {
		if op.Name == "get" && op.Method == "GET" && hasPathParam(op.Path) {
			if idx := strings.LastIndex(op.Path, "/{"); idx != -1 {
				if stripped := op.Path[:idx]; !hasPathParam(stripped) {
					return stripped
				}
			}
		}
	}
	for _, op := range ops {
		if op.Name == "update" && op.Method == "PUT" && hasPathParam(op.Path) {
			if idx := strings.LastIndex(op.Path, "/{"); idx != -1 {
				if stripped := op.Path[:idx]; !hasPathParam(stripped) {
					return stripped
				}
			}
		}
	}
	return ""
}

func dedupeOperations(ops []*Operation) []*Operation {
	// Pre-compute the collection path so we can prefer "get" ops that match it.
	// This avoids keeping a secondary GET/{id} (e.g. /images/{id}, /smart-group-membership/{id})
	// over the primary CRUD GET/{id} when both exist in the same resource.
	cp := collectionPath(ops)

	seen := make(map[string]*Operation) // name → kept op
	var result []*Operation
	for _, op := range ops {
		if prev, exists := seen[op.Name]; !exists {
			seen[op.Name] = op
			result = append(result, op)
		} else if op.Name == "get" && cp != "" && hasPathParam(op.Path) {
			// Check whether this duplicate "get" is a better match for the collection path.
			prevParent := ""
			if idx := strings.LastIndex(prev.Path, "/{"); idx != -1 {
				prevParent = prev.Path[:idx]
			}
			opParent := ""
			if idx := strings.LastIndex(op.Path, "/{"); idx != -1 {
				opParent = op.Path[:idx]
			}
			if opParent == cp && prevParent != cp {
				// Replace the previously kept op with this better match.
				for i, r := range result {
					if r == prev {
						result[i] = op
						break
					}
				}
				seen[op.Name] = op
				fmt.Fprintf(os.Stderr, "  Warning: duplicate operation name %q — replacing %s %s with %s %s (matches collection path)\n",
					op.Name, prev.Method, prev.Path, op.Method, op.Path)
			} else {
				fmt.Fprintf(os.Stderr, "  Warning: duplicate operation name %q — dropping %s %s\n", op.Name, op.Method, op.Path)
			}
		} else {
			fmt.Fprintf(os.Stderr, "  Warning: duplicate operation name %q — dropping %s %s\n", op.Name, op.Method, op.Path)
		}
	}
	return result
}

func hasPostOrPut(ops []*Operation) bool {
	for _, op := range ops {
		if op.Method == "POST" || op.Method == "PUT" || op.Method == "PATCH" {
			return true
		}
	}
	return false
}

func hasDelete(ops []*Operation) bool {
	for _, op := range ops {
		if op.Method == "DELETE" {
			return true
		}
	}
	return false
}

func hasDestructive(ops []*Operation) bool {
	for _, op := range ops {
		if op.IsDestructive {
			return true
		}
	}
	return false
}

func hasQueryParams(ops []*Operation) bool {
	// Returns true for query params that use fmt.Sprintf (integer and array types).
	// String params use url.QueryEscape concatenation; boolean params use literals.
	for _, op := range ops {
		for _, p := range op.Parameters {
			if p.In == "query" && (p.Type == "integer" || p.IsArray) {
				return true
			}
		}
	}
	return false
}

func needsFmt(r *Resource) bool {
	// fmt is needed for: destructive confirmations, query param formatting,
	// delete success message, scaffold output, apply status messages, multipart error wrapping,
	// patch-by-name error messages, --set parse errors, name-lookup error messages
	if hasDestructive(r.Operations) || hasQueryParams(r.Operations) || hasDelete(r.Operations) || hasScaffold(r.Operations) || shouldGenerateApply(r) || needsMultipart(r) || hasAnyBinaryResponse(r) || patchHasLookup(r) || hasPatchOp(r.Operations) {
		return true
	}
	for _, op := range r.Operations {
		if opHasNameLookup(op, r) {
			return true
		}
	}
	return false
}

func needsMultipart(r *Resource) bool {
	for _, op := range r.Operations {
		if op.RequestBody != nil && op.RequestBody.IsMultipart {
			return true
		}
	}
	return false
}

func hasAnyBinaryResponse(r *Resource) bool {
	for _, op := range r.Operations {
		if opHasBinaryResponse(op) {
			return true
		}
	}
	return false
}

func opHasBinaryResponse(op *Operation) bool {
	for _, resp := range op.Responses {
		if resp.IsBinary && (resp.StatusCode == "200" || resp.StatusCode == "201") {
			return true
		}
	}
	return false
}

func hasDeleteMultiple(ops []*Operation) bool {
	for _, op := range ops {
		if op.Name == "delete-multiple" {
			return true
		}
	}
	return false
}

func needsURL(r *Resource) bool {
	// net/url is needed for path param encoding, query param encoding, name lookup, apply, and patch lookup
	if shouldGenerateApply(r) || patchHasLookup(r) {
		return true
	}
	for _, op := range r.Operations {
		if opHasNameLookup(op, r) {
			return true
		}
		if op.Name == "get" && op.Method == "GET" && hasPathParam(op.Path) {
			return true
		}
		for _, p := range op.Parameters {
			if p.In == "path" {
				return true
			}
			if p.In == "query" && (p.Type == "string" || p.IsArray) {
				return true
			}
		}
	}
	return false
}

// shouldGenerateApply returns true if the resource should have an apply (upsert) command.
// Singletons are excluded: they have no name-based collection to search, so upsert
// semantics don't apply. Sub-resources (where collectionPath returns empty) are also
// excluded: without a flat collection there is no way to resolve a name to an ID.
func shouldGenerateApply(r *Resource) bool {
	return !r.IsSingleton && hasApply(r.Operations) && collectionPath(r.Operations) != "" && hasResolvableID(r)
}

// hasResolvableID returns true when the detected ID field exists in at least one
// response schema (or is the standard "id"). When false, name-resolution (--name
// lookup flags, apply) is not generated because extracting the identifier from
// list responses would fail at runtime.
func hasResolvableID(r *Resource) bool {
	if r.IDField == "" || r.IDField == "id" {
		return true
	}
	return schemaHasProperty(r.Schemas, r.IDField)
}

// ScalarField represents a patchable scalar field in dot-notation (e.g. "general.managed").
type ScalarField struct {
	Path string // dot-notation path, e.g. "general.managed"
	Type string // scalar type: "string", "integer", "boolean", "number"
}

// flattenSchemaToScalarFields walks a PATCH request body schema and returns all
// non-read-only scalar fields in dot notation. Top-level scalars are included
// directly; object properties are expanded one level using their SchemaRef.
// Arrays are intentionally excluded — they require --from-file.
func flattenSchemaToScalarFields(schema *Schema, schemas map[string]*Schema) []ScalarField {
	if schema == nil {
		return nil
	}

	isScalar := func(t string) bool {
		return t == "string" || t == "integer" || t == "boolean" || t == "number"
	}

	topNames := make([]string, 0, len(schema.Properties))
	for name := range schema.Properties {
		topNames = append(topNames, name)
	}
	sort.Strings(topNames)

	var fields []ScalarField
	for _, propName := range topNames {
		prop := schema.Properties[propName]
		if prop.ReadOnly {
			continue
		}
		switch {
		case isScalar(prop.Type):
			fields = append(fields, ScalarField{Path: propName, Type: prop.Type})
		case prop.Type == "object" || (prop.Type == "" && prop.Nested != nil):
			// Prefer the inline-resolved Nested schema (always populated by parseSchema
			// for cross-file $ref objects). Fall back to component schemas map.
			var nested *Schema
			if prop.Nested != nil {
				nested = prop.Nested
			} else if prop.SchemaRef != "" {
				nested = schemas[prop.SchemaRef]
			}
			if nested == nil {
				continue
			}
			nestedNames := make([]string, 0, len(nested.Properties))
			for n := range nested.Properties {
				nestedNames = append(nestedNames, n)
			}
			sort.Strings(nestedNames)
			for _, nestedName := range nestedNames {
				nestedProp := nested.Properties[nestedName]
				if nestedProp.ReadOnly || !isScalar(nestedProp.Type) {
					continue
				}
				fields = append(fields, ScalarField{
					Path: propName + "." + nestedName,
					Type: nestedProp.Type,
				})
			}
		}
	}
	return fields
}

// isPatchOp reports whether an operation is a PATCH with a JSON request body schema.
func isPatchOp(op *Operation) bool {
	return op.Method == "PATCH" && op.Name == "patch" &&
		op.RequestBody != nil && !op.RequestBody.IsMultipart
}

// hasPatchOp reports whether any operation in the slice satisfies isPatchOp.
func hasPatchOp(ops []*Operation) bool {
	for _, op := range ops {
		if isPatchOp(op) {
			return true
		}
	}
	return false
}

// patchHasLookup returns true when the resource's patch command should support
// name/serial/UDID lookup in addition to a direct ID argument.
// Requires: non-singleton, resolvable ID, a list endpoint for RSQL, and a PATCH with path param.
func patchHasLookup(r *Resource) bool {
	if r.IsSingleton || !hasResolvableID(r) || collectionPath(r.Operations) == "" {
		return false
	}
	for _, op := range r.Operations {
		if isPatchOp(op) && hasPathParam(op.Path) {
			return true
		}
	}
	return false
}

// opHasNameLookup returns true when an operation should get --name/--serial/--udid
// lookup flags as alternatives to the positional ID argument.
// Covers get, update, delete, binary download, and multipart upload operations
// that have a path parameter on a non-singleton, listable resource with resolvable ID.
func opHasNameLookup(op *Operation, r *Resource) bool {
	if r.IsSingleton || !hasResolvableID(r) || collectionPath(r.Operations) == "" {
		return false
	}
	return hasPathParam(op.Path)
}

// patchExampleText builds the Example string for a unified patch command.
func patchExampleText(r *Resource, op *Operation) string {
	bin := "jamf-cli"
	if !hasPathParam(op.Path) {
		// Singleton PATCH — no ID
		return fmt.Sprintf("  # Update a field\n  %s %s patch --set field=value\n\n  # Update using JSON\n  %s %s get -o json | jq '.field = \"value\"' | %s %s patch",
			bin, r.Name, bin, r.Name, bin, r.Name)
	}
	base := fmt.Sprintf("  # Update a field by ID\n  %s %s patch 1 --set general.managed=true\n\n  # Update multiple fields\n  %s %s patch 1 --set field1=value1 --set field2=value2",
		bin, r.Name, bin, r.Name)
	if patchHasLookup(r) {
		base += fmt.Sprintf("\n\n  # Update by name\n  %s %s patch --name \"Example\" --set general.managed=true",
			bin, r.Name)
		for _, lf := range r.LookupFields {
			base += fmt.Sprintf("\n\n  # Update by %s\n  %s %s patch --%s <value> --set general.managed=true",
				lf.Flag, bin, r.Name, lf.Flag)
		}
	}
	base += fmt.Sprintf("\n\n  # Patch from a file\n  %s %s patch 1 --from-file changes.json", bin, r.Name)
	return base
}

// patchPath returns the path of the first PATCH operation.
func patchPath(ops []*Operation) string {
	for _, op := range ops {
		if isPatchOp(op) {
			return op.Path
		}
	}
	return ""
}

// patchPathParam returns the last path parameter placeholder of the PATCH path.
func patchPathParam(ops []*Operation) string {
	for _, op := range ops {
		if isPatchOp(op) {
			start := strings.LastIndex(op.Path, "{")
			end := strings.LastIndex(op.Path, "}")
			if start != -1 && end > start {
				return op.Path[start : end+1]
			}
		}
	}
	return "{id}"
}

// patchSetCompletions returns the list of "--set" completion candidates for a
// PATCH operation: each scalar field path with "=" appended.
func patchSetCompletions(op *Operation, schemas map[string]*Schema) []string {
	if op.RequestBody == nil {
		return nil
	}
	fields := flattenSchemaToScalarFields(op.RequestBody.Schema, schemas)
	result := make([]string, len(fields))
	for i, f := range fields {
		result[i] = f.Path + "="
	}
	return result
}

// patchLongDesc builds the Long description string (as a Go double-quoted literal)
// for a PATCH command, embedding the list of patchable scalar fields and lookup info.
func patchLongDesc(op *Operation, schemas map[string]*Schema, r *Resource) string {
	fields := flattenSchemaToScalarFields(op.RequestBody.Schema, schemas)

	goEscape := func(s string) string {
		s = strings.ReplaceAll(s, `\`, `\\`)
		s = strings.ReplaceAll(s, `"`, `\"`)
		s = strings.ReplaceAll(s, "\r", "")
		s = strings.ReplaceAll(s, "\n", `\n`)
		s = strings.ReplaceAll(s, "`", "'")
		return s
	}

	desc := strings.TrimSpace(op.Description)
	if desc == "" {
		desc = strings.TrimSpace(op.Summary)
	}

	var sb strings.Builder
	sb.WriteString(`"`)
	sb.WriteString(goEscape(desc))

	if patchHasLookup(r) {
		sb.WriteString(`\n\nIdentify the resource by ID (positional arg), --name, `)
		for i, lf := range r.LookupFields {
			if i > 0 {
				sb.WriteString(`, `)
			}
			sb.WriteString(`--` + lf.Flag)
		}
		sb.WriteString(`. Omit ID to use a lookup flag.`)
	}

	if len(fields) > 0 {
		sb.WriteString(`\n\nUse --set KEY=VALUE to update scalar fields (repeatable). Omitted fields are unchanged.\n\nAvailable fields:\n`)
		for _, f := range fields {
			fmt.Fprintf(&sb, `  %-44s %s\n`, f.Path, f.Type)
		}
		sb.WriteString(`\nUse --from-file or pipe JSON to stdin for complex updates (arrays, bulk changes).`)
	}

	sb.WriteString(`"`)
	return sb.String()
}

// scaffoldJSON generates a JSON template string from a schema, skipping read-only fields.
func scaffoldJSON(s *Schema) string {
	if s == nil || len(s.Properties) == 0 {
		return "{}"
	}

	// Sort property names for deterministic output
	names := make([]string, 0, len(s.Properties))
	for name := range s.Properties {
		names = append(names, name)
	}
	sort.Strings(names)

	obj := make(map[string]any)
	for _, name := range names {
		prop := s.Properties[name]
		if prop.ReadOnly {
			continue
		}
		if prop.Example != nil {
			obj[name] = prop.Example
		} else {
			switch prop.Type {
			case "string":
				obj[name] = ""
			case "integer", "number":
				obj[name] = 0
			case "boolean":
				obj[name] = false
			case "array":
				obj[name] = []any{}
			case "object":
				obj[name] = map[string]any{}
			default:
				obj[name] = ""
			}
		}
	}

	data, err := json.MarshalIndent(obj, "", "  ")
	if err != nil {
		return "{}"
	}
	return string(data)
}

// hasApply returns true if the resource has both create and update operations.
func hasApply(ops []*Operation) bool {
	hasCreate := false
	hasUpdate := false
	for _, op := range ops {
		if op.Name == "create" && op.Method == "POST" {
			hasCreate = true
		}
		if op.Name == "update" && op.Method == "PUT" {
			hasUpdate = true
		}
	}
	return hasCreate && hasUpdate
}

// hasScaffold returns true if any operation has a request body with a schema.
func hasScaffold(ops []*Operation) bool {
	for _, op := range ops {
		if op.RequestBody != nil && op.RequestBody.Schema != nil && len(op.RequestBody.Schema.Properties) > 0 {
			if op.Method == "POST" || op.Method == "PUT" || op.Method == "PATCH" {
				return true
			}
		}
	}
	return false
}

func sortOperations(ops []*Operation) []*Operation {
	// Define order: list, get, create, update, delete, then others
	order := map[string]int{
		"list":             1,
		"get":              2,
		"create":           3,
		"update":           4,
		"delete":           5,
		"delete-multiple":  6,
		"history":          7,
		"add-history-note": 8,
		"export":           9,
		"history-export":   10,
	}

	sorted := make([]*Operation, len(ops))
	copy(sorted, ops)

	sort.Slice(sorted, func(i, j int) bool {
		oi, oki := order[sorted[i].Name]
		oj, okj := order[sorted[j].Name]
		if !oki {
			oi = 100
		}
		if !okj {
			oj = 100
		}
		return oi < oj
	})

	return sorted
}

const resourceTemplate = `// Copyright 2026, Jamf Software LLC
// Code generated by jamf-cli generator. DO NOT EDIT.
package generated

import (
{{- if or (shouldGenerateApply .) (needsMultipart .) (hasPatchOp .Operations) }}
	"bytes"
{{- end }}
{{- if or (hasList .Operations) (hasDeleteMultiple .Operations) }}
	"encoding/json"
{{- end }}
{{- if or (needsFmt .) (hasList .Operations) }}
	"fmt"
{{- end }}
{{- if or (hasPostOrPut .Operations) (hasList .Operations) (hasAnyBinaryResponse .) }}
	"io"
{{- end }}
{{- if needsMultipart . }}
	"mime/multipart"
{{- end }}
{{- if hasDelete .Operations }}
	"net/http"
{{- end }}
{{- if needsURL . }}
	"net/url"
{{- end }}
{{- if or (hasPostOrPut .Operations) (hasDestructive .Operations) (hasDelete .Operations) (shouldGenerateApply .) (hasAnyBinaryResponse .) }}
	"os"
{{- end }}
{{- if needsMultipart . }}
	"path/filepath"
{{- end }}
	"strings"

	"github.com/spf13/cobra"

	"github.com/Jamf-Concepts/jamf-cli/internal/registry"
)

// New{{ .GoName }}Cmd creates the {{ .Name }} command group
func New{{ .GoName }}Cmd(ctx *registry.CLIContext) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "{{ .Name }}",
		Short: "Manage {{ .Name }}",
		Long:  ` + "`" + `Manage {{ .Name }} in Jamf Pro.` + "`" + `,
	}
{{ range dedupeOps (sortOps .Operations) }}
	cmd.AddCommand(new{{ $.GoName }}{{ toCamel .Name }}Cmd(ctx))
{{- end }}
{{- if shouldGenerateApply . }}
	cmd.AddCommand(new{{ .GoName }}ApplyCmd(ctx))
{{- end }}

	return cmd
}
{{ range dedupeOps (sortOps .Operations) }}
func new{{ $.GoName }}{{ toCamel .Name }}Cmd(ctx *registry.CLIContext) *cobra.Command {
	var (
{{- range queryParams .Parameters }}
{{- if .IsArray }}
		flag{{ toCamel .Name }} []{{ goType .Type }}
{{- else }}
		flag{{ toCamel .Name }} {{ goType .Type }}
{{- end }}
{{- end }}
{{- if .IsList }}
		flagAll  bool
		flagLimit int
{{- end }}
{{- if .IsDestructive }}
		flagYes bool
		flagDryRun bool
{{- end }}
{{- if eq .Name "delete-multiple" }}
		flagIds []string
{{- end }}
{{- if opHasScaffold . }}
		flagScaffold bool
{{- end }}
{{- if opIsMultipart . }}
		flagFile string
{{- end }}
{{- if opHasBinaryResponse . }}
		flagSaveTo string
{{- end }}
{{- if isPatchOp . }}
		flagSet  []string
		fromFile string
{{- if patchHasLookup $ }}
		flagName string
{{ range $.LookupFields }}		flag{{ toCamel .Flag }} string
{{ end }}{{- end }}
{{- end }}
{{- if and (not (isPatchOp .)) (opHasNameLookup . $) }}
		flagName string
{{ range $.LookupFields }}		flag{{ toCamel .Flag }} string
{{ end }}{{- end }}
	)

	cmd := &cobra.Command{
{{- if or (and (isPatchOp .) (patchHasLookup $)) (and (not (isPatchOp .)) (opHasNameLookup . $)) }}
		Use:   "{{ .Name }} [<id>]",
{{- else }}
		Use:   "{{ .Name }}{{ pathParamUsage .Parameters }}",
{{- end }}
		Short: "{{ escapeQuotes .Summary }}",
{{- if isPatchOp . }}
		Long: {{ patchLongDesc . $.Schemas $ }},
{{- else if .Description }}
		Long:  "{{ escapeQuotes .Description }}",
{{- end }}
{{- if isPatchOp . }}
		Example: ` + "`" + `{{ patchExampleText $ . }}` + "`" + `,
{{- else }}
{{- $ex := exampleText $ . }}{{ if $ex }}
		Example: ` + "`" + `{{ $ex }}` + "`" + `,
{{- end }}
{{- end }}
{{- if hasPathParam .Path }}
{{- if or (and (isPatchOp .) (patchHasLookup $)) (and (not (isPatchOp .)) (opHasNameLookup . $)) }}
		Args:  cobra.MaximumNArgs(1),
{{- else }}
		Args:  cobra.ExactArgs({{ pathParamCount .Parameters }}),
{{- end }}
{{- end }}
		RunE: func(cmd *cobra.Command, args []string) error {
			reqCtx := cmd.Context()
{{- if opHasBinaryResponse . }}
			reqCtx = registry.WithAccept(reqCtx, "*/*")
{{- end }}
{{- if opHasScaffold . }}

			if flagScaffold {
				fmt.Println(` + "`" + `{{ opScaffoldJSON . }}` + "`" + `)
				return nil
			}
{{- end }}
{{- if and .IsDestructive (not (opHasNameLookup . $)) }}

			// Confirmation for destructive action
			if flagDryRun {
				fmt.Fprintf(os.Stderr, "Would {{ .Name }}{{ if hasPathParam .Path }} resource %s{{ end }}\n"{{ if hasPathParam .Path }}, args[0]{{ end }})
				return nil
			}
			if !flagYes {
				noInput, _ := cmd.Flags().GetBool("no-input")
				if noInput {
					return fmt.Errorf("destructive operation requires --yes when --no-input is set")
				}
				fmt.Fprintf(os.Stderr, "⚠️  This will {{ .Name }}{{ if hasPathParam .Path }} resource %s{{ end }}. Type 'yes' to confirm: "{{ if hasPathParam .Path }}, args[0]{{ end }})
				var confirm string
				fmt.Scanln(&confirm)
				if confirm != "yes" {
					return fmt.Errorf("aborted")
				}
			}
{{- end }}


{{- if and (isPatchOp .) (patchHasLookup $) }}

			// Resolve resource ID from positional arg, --name, or lookup flags
			var resolvedPatchID string
{{ range $.LookupFields }}
			if flag{{ toCamel .Flag }} != "" {
				rid, err := resolveNameToID(reqCtx, ctx.Client, "{{ nameLookupPath $ }}", "{{ .RSQLField }}", "{{ lookupIDField $ }}", flag{{ toCamel .Flag }})
				if err != nil {
					return fmt.Errorf("looking up --{{ .Flag }} %q: %w", flag{{ toCamel .Flag }}, err)
				}
				resolvedPatchID = rid
			} else {{ end }}if flagName != "" {
				rid, err := resolveNameToID(reqCtx, ctx.Client, "{{ nameLookupPath $ }}", "{{ $.NameField }}", "{{ lookupIDField $ }}", flagName)
				if err != nil {
					return err
				}
				resolvedPatchID = rid
			} else if len(args) > 0 {
				resolvedPatchID = args[0]
			} else {
				return fmt.Errorf("provide an <id> argument, --name{{ range $.LookupFields }}, --{{ .Flag }}{{ end }}")
			}
{{- end }}
{{- if and (not (isPatchOp .)) (opHasNameLookup . $) }}

			// Resolve resource ID from positional arg, --name, or lookup flags
			var resolvedID string
{{- if .IsDestructive }}
			var resolvedByName string
{{- end }}
{{- $opIsDestructive := .IsDestructive }}
{{ range $.LookupFields }}
			if flag{{ toCamel .Flag }} != "" {
{{- if $opIsDestructive }}
				noInputLookup, _ := cmd.Flags().GetBool("no-input")
				rid, err := resolveNameToIDForApply(reqCtx, ctx.Client, "{{ nameLookupPath $ }}", "{{ .RSQLField }}", "{{ lookupIDField $ }}", flag{{ toCamel .Flag }}, noInputLookup)
				if err != nil {
					return fmt.Errorf("looking up --{{ .Flag }} %q: %w", flag{{ toCamel .Flag }}, err)
				}
				if rid == "" {
					return fmt.Errorf("no {{ $.NameSingular }} found with --{{ .Flag }} %q", flag{{ toCamel .Flag }})
				}
{{- else }}
				rid, err := resolveNameToID(reqCtx, ctx.Client, "{{ nameLookupPath $ }}", "{{ .RSQLField }}", "{{ lookupIDField $ }}", flag{{ toCamel .Flag }})
				if err != nil {
					return fmt.Errorf("looking up --{{ .Flag }} %q: %w", flag{{ toCamel .Flag }}, err)
				}
{{- end }}
				resolvedID = rid
{{- if $opIsDestructive }}
				resolvedByName = flag{{ toCamel .Flag }}
{{- end }}
			} else {{ end }}if flagName != "" {
{{- if .IsDestructive }}
				noInput, _ := cmd.Flags().GetBool("no-input")
				rid, err := resolveNameToIDForApply(reqCtx, ctx.Client, "{{ nameLookupPath $ }}", "{{ $.NameField }}", "{{ lookupIDField $ }}", flagName, noInput)
				if err != nil {
					return err
				}
				if rid == "" {
					return fmt.Errorf("no {{ $.NameSingular }} found with {{ $.NameField }} %q", flagName)
				}
{{- else }}
				rid, err := resolveNameToID(reqCtx, ctx.Client, "{{ nameLookupPath $ }}", "{{ $.NameField }}", "{{ lookupIDField $ }}", flagName)
				if err != nil {
					return err
				}
{{- end }}
				resolvedID = rid
{{- if .IsDestructive }}
				resolvedByName = flagName
{{- end }}
			} else if len(args) > 0 {
				resolvedID = args[0]
			} else {
				return fmt.Errorf("provide an <id> argument, --name{{ range $.LookupFields }}, --{{ .Flag }}{{ end }}")
			}
{{- end }}
{{- if and .IsDestructive (opHasNameLookup . $) }}

			// Confirmation for destructive action (after name lookup)
			if flagDryRun {
				if resolvedByName != "" {
					fmt.Fprintf(os.Stderr, "[dry-run] Would {{ .Name }} {{ $.NameSingular }} %q (id: %s)\n", resolvedByName, resolvedID)
				} else {
					fmt.Fprintf(os.Stderr, "[dry-run] Would {{ .Name }} {{ $.NameSingular }} %s\n", resolvedID)
				}
				return nil
			}
			if !flagYes {
				noInput, _ := cmd.Flags().GetBool("no-input")
				if noInput {
					return fmt.Errorf("destructive operation requires --yes when --no-input is set")
				}
				if resolvedByName != "" {
					fmt.Fprintf(os.Stderr, "⚠️  This will {{ .Name }} {{ $.NameSingular }} %q (id: %s). Type 'yes' to confirm: ", resolvedByName, resolvedID)
				} else {
					fmt.Fprintf(os.Stderr, "⚠️  This will {{ .Name }} {{ $.NameSingular }} %s. Type 'yes' to confirm: ", resolvedID)
				}
				var confirm string
				fmt.Scanln(&confirm)
				if confirm != "yes" {
					return fmt.Errorf("aborted")
				}
			}
{{- end }}

			// Build request path
			path := "{{ .Path }}"
{{- if and (isPatchOp .) (patchHasLookup $) }}
			path = strings.Replace(path, "{{ patchPathParam $.Operations }}", url.PathEscape(resolvedPatchID), 1)
{{- else if and (not (isPatchOp .)) (opHasNameLookup . $) }}
			path = strings.Replace(path, "{{ pathParamName . }}", url.PathEscape(resolvedID), 1)
{{- else }}
{{- range indexedPathParams .Parameters }}
			path = strings.Replace(path, "{{"{"}}{{ .Param.Name }}{{"}"}}", url.PathEscape(args[{{ .Index }}]), 1)
{{- end }}
{{- end }}

			// Build query string
			var queryParts []string
{{- range queryParams .Parameters }}
{{- if .IsArray }}
			if len(flag{{ toCamel .Name }}) > 0 {
				for _, v := range flag{{ toCamel .Name }} {
					queryParts = append(queryParts, "{{ .Name }}=" + url.QueryEscape(fmt.Sprintf("%v", v)))
				}
			}
{{- else if eq .Type "string" }}
			if flag{{ toCamel .Name }} != "" {
				queryParts = append(queryParts, "{{ .Name }}=" + url.QueryEscape(flag{{ toCamel .Name }}))
			}
{{- else if eq .Type "integer" }}
			if flag{{ toCamel .Name }} != 0 {
				queryParts = append(queryParts, fmt.Sprintf("{{ .Name }}=%d", flag{{ toCamel .Name }}))
			}
{{- else if eq .Type "boolean" }}
			if flag{{ toCamel .Name }} {
				queryParts = append(queryParts, "{{ .Name }}=true")
			}
{{- end }}
{{- end }}
			if len(queryParts) > 0 {
				path = path + "?" + strings.Join(queryParts, "&")
			}
{{- if .IsList }}

			// Auto-pagination: fetch all pages when --all is set and --page was not manually specified
			if flagAll && flagPage == 0 {
				var allResults []json.RawMessage
				pageNum := 0
				pageSize := 100

				for {
					// Build page-specific query
					pagePath := "{{ .Path }}"
{{- if and (not (isPatchOp .)) (opHasNameLookup . $) }}
					pagePath = strings.Replace(pagePath, "{{ pathParamName . }}", url.PathEscape(resolvedID), 1)
{{- else if and (isPatchOp .) (patchHasLookup $) }}
					pagePath = strings.Replace(pagePath, "{{ patchPathParam $.Operations }}", url.PathEscape(resolvedPatchID), 1)
{{- else }}
{{- range indexedPathParams .Parameters }}
					pagePath = strings.Replace(pagePath, "{{"{"}}{{ .Param.Name }}{{"}"}}", url.PathEscape(args[{{ .Index }}]), 1)
{{- end }}
{{- end }}
					var pageQuery []string
					// Carry forward non-pagination query params
					for _, qp := range queryParts {
						if !strings.HasPrefix(qp, "page=") && !strings.HasPrefix(qp, "page-size=") && !strings.HasPrefix(qp, "pagesize=") {
							pageQuery = append(pageQuery, qp)
						}
					}
					pageQuery = append(pageQuery, fmt.Sprintf("page=%d", pageNum))
					pageQuery = append(pageQuery, fmt.Sprintf("page-size=%d", pageSize))
					pagePath = pagePath + "?" + strings.Join(pageQuery, "&")

					resp, err := ctx.Client.Do(reqCtx, "GET", pagePath, nil)
					if err != nil {
						return err
					}

					body, err := io.ReadAll(resp.Body)
					resp.Body.Close()
					if err != nil {
						return err
					}

					// Parse pagination response: {"totalCount": N, "results": [...]}
					var pageResp struct {
						TotalCount int               ` + "`" + `json:"totalCount"` + "`" + `
						Results    []json.RawMessage  ` + "`" + `json:"results"` + "`" + `
					}
					if err := json.Unmarshal(body, &pageResp); err != nil {
						// Not a paginated response; output as-is
						return ctx.Output.PrintRaw(body)
					}

					allResults = append(allResults, pageResp.Results...)

					// Check limit
					if flagLimit > 0 && len(allResults) >= flagLimit {
						allResults = allResults[:flagLimit]
						break
					}

					// Check if we've fetched everything
					if len(pageResp.Results) < pageSize || len(allResults) >= pageResp.TotalCount {
						break
					}

					pageNum++
				}

				// Output combined results as JSON array
				combined, err := json.MarshalIndent(allResults, "", "  ")
				if err != nil {
					return err
				}
				return ctx.Output.PrintRaw(combined)
			}
{{- end }}

			// Make request
{{- if opIsMultipart . }}
			if ctx.Uploader == nil {
				return fmt.Errorf("file upload not supported in this context")
			}
			f, err := os.Open(flagFile)
			if err != nil {
				return fmt.Errorf("opening %s: %w", flagFile, err)
			}
			defer f.Close()
			var buf bytes.Buffer
			mw := multipart.NewWriter(&buf)
			fw, err := mw.CreateFormFile("{{ .RequestBody.FileField }}", filepath.Base(flagFile))
			if err != nil {
				return fmt.Errorf("creating form file: %w", err)
			}
			if _, err := io.Copy(fw, f); err != nil {
				return fmt.Errorf("writing file: %w", err)
			}
			mw.Close()
			resp, err := ctx.Uploader.Upload(reqCtx, path, &buf, mw.FormDataContentType(), int64(buf.Len()))
{{- else if eq .Method "GET" "DELETE" }}
			resp, err := ctx.Client.Do(reqCtx, "{{ .Method }}", path, nil)
{{- else }}
			// Read body from stdin if available
			var body io.Reader
{{- if isPatchOp . }}
			// PATCH: --set flags take priority; fall back to --from-file or stdin
			reqCtx = registry.WithContentType(reqCtx, "application/merge-patch+json")
			switch {
			case len(flagSet) > 0:
				data, err := buildMergePatchFromSet(flagSet)
				if err != nil {
					return err
				}
				body = bytes.NewReader(data)
			case fromFile != "":
				data, err := os.ReadFile(fromFile)
				if err != nil {
					return fmt.Errorf("reading input file: %w", err)
				}
				body = bytes.NewReader(data)
			default:
				stat, _ := os.Stdin.Stat()
				if (stat.Mode() & os.ModeCharDevice) == 0 {
					body = os.Stdin
				}
			}
{{- else if eq .Name "delete-multiple" }}
			// Handle --ids flag for bulk operations
			if len(flagIds) > 0 {
				payload := struct {
					IDs []string ` + "`" + `json:"ids"` + "`" + `
				}{IDs: flagIds}
				idsJSON, err := json.Marshal(payload)
				if err != nil {
					return fmt.Errorf("encoding ids: %w", err)
				}
				body = strings.NewReader(string(idsJSON))
			} else {
				stat, _ := os.Stdin.Stat()
				if (stat.Mode() & os.ModeCharDevice) == 0 {
					body = os.Stdin
				}
			}
{{- else }}
			stat, _ := os.Stdin.Stat()
			if (stat.Mode() & os.ModeCharDevice) == 0 {
				body = os.Stdin
			}
{{- end }}
			resp, err := ctx.Client.Do(reqCtx, "{{ .Method }}", path, body)
{{- end }}
			if err != nil {
				return err
			}
			defer resp.Body.Close()

{{ if eq .Method "DELETE" }}
			if resp.StatusCode == http.StatusNoContent {
				fmt.Fprintln(os.Stderr, "Deleted successfully")
				return nil
			}
{{ end }}
{{- if opHasBinaryResponse . }}
			if flagSaveTo != "" {
				f, err := os.Create(flagSaveTo)
				if err != nil {
					return fmt.Errorf("opening output file: %w", err)
				}
				defer f.Close()
				n, err := io.Copy(f, resp.Body)
				if err != nil {
					return err
				}
				fmt.Fprintf(os.Stderr, "Saved to %s (%d bytes)\n", flagSaveTo, n)
				return nil
			}
			_, err = io.Copy(os.Stdout, resp.Body)
			return err
{{- else }}
			return ctx.Output.PrintResponse(resp)
{{- end }}
		},
	}
{{ range queryParams .Parameters }}
{{- if .IsArray }}
	cmd.Flags().{{ flagType .Type }}SliceVar(&flag{{ toCamel .Name }}, "{{ toKebab .Name }}", nil, "{{ escapeQuotes .Description }}")
{{- else }}
	cmd.Flags().{{ flagType .Type }}Var(&flag{{ toCamel .Name }}, "{{ toKebab .Name }}", {{ if .Default }}{{ defaultVal .Type .Default }}{{ else if eq .Type "string" }}""{{ else if eq .Type "integer" }}0{{ else if eq .Type "boolean" }}false{{ else }}0{{ end }}, "{{ escapeQuotes .Description }}")
{{- end }}
{{- end }}
{{- if .IsList }}
	cmd.Flags().BoolVar(&flagAll, "all", true, "Fetch all pages (set --all=false for single page)")
	cmd.Flags().IntVar(&flagLimit, "limit", 0, "Maximum total results to return (0 = unlimited)")
{{- end }}
{{- if .IsDestructive }}
	cmd.Flags().BoolVar(&flagYes, "yes", false, "Skip confirmation prompt")
	cmd.Flags().BoolVarP(&flagDryRun, "dry-run", "n", false, "Preview without executing")
{{- end }}
{{- if eq .Name "delete-multiple" }}
	cmd.Flags().StringSliceVar(&flagIds, "ids", nil, "IDs to delete (comma-separated)")
{{- end }}
{{- if opHasScaffold . }}
	cmd.Flags().BoolVar(&flagScaffold, "scaffold", false, "Print a JSON template for the request body and exit")
{{- end }}
{{- if opIsMultipart . }}
	cmd.Flags().StringVar(&flagFile, "file", "", "Path to file to upload (required)")
	_ = cmd.MarkFlagRequired("file")
{{- end }}
{{- if opHasBinaryResponse . }}
	cmd.Flags().StringVarP(&flagSaveTo, "save-to", "O", "", "Save output to file instead of stdout")
{{- end }}
{{- if isPatchOp . }}
	cmd.Flags().StringArrayVar(&flagSet, "set", nil, "Set a field value in dot notation (key=value, repeatable)")
	cmd.Flags().StringVar(&fromFile, "from-file", "", "Path to JSON merge-patch file (or pipe to stdin)")
	_ = cmd.RegisterFlagCompletionFunc("set", func(_ *cobra.Command, _ []string, _ string) ([]string, cobra.ShellCompDirective) {
		return []string{
			{{ range patchSetCompletions . $.Schemas }}"{{ . }}",{{ end }}
		}, cobra.ShellCompDirectiveNoSpace
	})
{{- if patchHasLookup $ }}
	cmd.Flags().StringVar(&flagName, "name", "", "Look up {{ $.NameSingular }} by name")
{{ range $.LookupFields }}	cmd.Flags().StringVar(&flag{{ toCamel .Flag }}, "{{ .Flag }}", "", "{{ escapeQuotes .Desc }}")
{{ end }}{{- end }}
{{- end }}
{{- if and (not (isPatchOp .)) (opHasNameLookup . $) }}
	cmd.Flags().StringVar(&flagName, "name", "", "Look up {{ $.NameSingular }} by name")
{{ range $.LookupFields }}	cmd.Flags().StringVar(&flag{{ toCamel .Flag }}, "{{ .Flag }}", "", "{{ escapeQuotes .Desc }}")
{{ end }}{{- end }}

	return cmd
}
{{ end }}
{{ if shouldGenerateApply . }}
func new{{ .GoName }}ApplyCmd(ctx *registry.CLIContext) *cobra.Command {
	var (
		fromFile   string
		flagYes    bool
		flagDryRun bool
	)

	cmd := &cobra.Command{
		Use:   "apply",
		Short: "Create or replace a {{ .NameSingular }} by name",
		Long: ` + "`" + `Create or replace a {{ .NameSingular }}. Reads JSON from --from-file or stdin.

The {{ .NameField }} field in the input is used to check if the resource
already exists. If it does, the resource is replaced (with confirmation).
If not, a new resource is created.` + "`" + `,
		Example: ` + "`" + `  # Apply a {{ .NameSingular }} from a file
  jamf-cli {{ .Name }} apply --from-file {{ .NameSingular }}.json

  # Apply from stdin
  cat {{ .NameSingular }}.json | jamf-cli {{ .Name }} apply

  # Apply without replacement confirmation
  jamf-cli {{ .Name }} apply --from-file {{ .NameSingular }}.json --yes

  # Preview what would happen
  jamf-cli {{ .Name }} apply --from-file {{ .NameSingular }}.json --dry-run` + "`" + `,
		RunE: func(cmd *cobra.Command, _ []string) error {
			reqCtx := cmd.Context()

			// Read input
			data, err := readApplyInput(fromFile)
			if err != nil {
				return err
			}

			// Extract name from JSON input
			name, err := extractJSONField(data, "{{ .NameField }}")
			if err != nil {
				return fmt.Errorf("input must include a %q field: %w", "{{ .NameField }}", err)
			}

			// Check if resource exists by name (read-only, runs even in dry-run)
			noInput, _ := cmd.Flags().GetBool("no-input")
			id, err := resolveNameToIDForApply(reqCtx, ctx.Client, "{{ listPathFromOps .Operations }}", "{{ .NameField }}", "{{ .IDField }}", name, noInput)
			if err != nil {
				return err
			}

			if id == "" {
				// Not found — create
				if flagDryRun {
					fmt.Fprintf(os.Stderr, "[dry-run] Would create {{ .NameSingular }} %q\n", name)
					return nil
				}
				resp, err := ctx.Client.Do(reqCtx, "POST", "{{ createPath .Operations }}", bytes.NewReader(data))
				if err != nil {
					return err
				}
				defer resp.Body.Close()
				fmt.Fprintf(os.Stderr, "Created {{ .NameSingular }} %q\n", name)
				return ctx.Output.PrintResponse(resp)
			}

			// Found — replace
			if flagDryRun {
				fmt.Fprintf(os.Stderr, "[dry-run] Would replace {{ .NameSingular }} %q (id: %s)\n", name, id)
				return nil
			}
			if !flagYes {
				if noInput {
					return fmt.Errorf("{{ .NameSingular }} %q already exists (id: %s); use --yes to replace when --no-input is set", name, id)
				}
				fmt.Fprintf(os.Stderr, "{{ .NameSingular }} %q already exists (id: %s) and will be replaced. Type 'yes' to confirm: ", name, id)
				var confirm string
				fmt.Scanln(&confirm)
				if confirm != "yes" {
					return fmt.Errorf("aborted")
				}
			}

			updatePath := strings.Replace("{{ updatePath .Operations }}", "{{ updatePathParam .Operations }}", url.PathEscape(id), 1)
			resp, err := ctx.Client.Do(reqCtx, "PUT", updatePath, bytes.NewReader(data))
			if err != nil {
				return err
			}
			defer resp.Body.Close()
			fmt.Fprintf(os.Stderr, "Replaced {{ .NameSingular }} %q (id: %s)\n", name, id)
			return ctx.Output.PrintResponse(resp)
		},
	}

	cmd.Flags().StringVar(&fromFile, "from-file", "", "Path to JSON input file (or pipe JSON to stdin)")
	cmd.Flags().BoolVar(&flagYes, "yes", false, "Skip confirmation prompt when replacing")
	cmd.Flags().BoolVarP(&flagDryRun, "dry-run", "n", false, "Preview without executing")

	return cmd
}
{{ end }}
`

const registryTemplate = `// Copyright 2026, Jamf Software LLC
// Code generated by jamf-cli generator. DO NOT EDIT.
package generated

import (
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/url"
	"os"
	"strconv"
	"strings"

	"github.com/spf13/cobra"

	"github.com/Jamf-Concepts/jamf-cli/internal/registry"
)

// RegisterCommands registers all generated resource commands
func RegisterCommands(root *cobra.Command, ctx *registry.CLIContext) {
{{- range . }}
	root.AddCommand(New{{ .GoName }}Cmd(ctx))
{{- end }}
}

// resolveNameToID looks up a resource by name using a filtered list call and
// returns its ID. This enables --name as an alternative to positional ID args
// on get commands. The nameField parameter specifies the filter field
// (usually "name", but some resources use "displayName"). The idField parameter
// specifies which response property holds the identifier (usually "id", but some
// resources use "templateId", "groupId", etc.).
func resolveNameToID(ctx context.Context, client registry.HTTPClient, listPath, nameField, idField, name string) (string, error) {
	filterPath := fmt.Sprintf("%s?filter=%s&page-size=1",
		listPath, url.QueryEscape(fmt.Sprintf(` + "`" + `%s=="%s"` + "`" + `, nameField, name)))

	resp, err := client.Do(ctx, "GET", filterPath, nil)
	if err != nil {
		return "", fmt.Errorf("looking up %q: %w", name, err)
	}
	defer func() { _ = resp.Body.Close() }()

	body, err := io.ReadAll(io.LimitReader(resp.Body, 1<<20))
	if err != nil {
		return "", fmt.Errorf("reading lookup response: %w", err)
	}

	// Paginated response: {"totalCount": N, "results": [{...}]}
	var data struct {
		TotalCount int               ` + "`" + `json:"totalCount"` + "`" + `
		Results    []json.RawMessage ` + "`" + `json:"results"` + "`" + `
	}
	if err := json.Unmarshal(body, &data); err != nil {
		// Some endpoints return plain arrays instead of paginated objects
		var arr []json.RawMessage
		if jsonErr := json.Unmarshal(body, &arr); jsonErr != nil {
			return "", fmt.Errorf("parsing lookup response: %w", err)
		}
		data.Results = arr
		data.TotalCount = len(arr)
	}

	if data.TotalCount == 0 || len(data.Results) == 0 {
		return "", fmt.Errorf("no resource found with name %q", name)
	}

	var first map[string]any
	if err := json.Unmarshal(data.Results[0], &first); err != nil {
		return "", fmt.Errorf("parsing lookup result: %w", err)
	}

	if id := extractIDString(first, idField); id != "" {
		return id, nil
	}
	return "", fmt.Errorf("resource %q has no %s field", name, idField)
}

// extractIDString extracts the named identifier field from a JSON object as a string.
// NOTE: Also used by classic_registry.go helpers (same generated package).
func extractIDString(obj map[string]any, field string) string {
	switch v := obj[field].(type) {
	case string:
		return v
	case float64:
		return fmt.Sprintf("%d", int(v))
	default:
		return ""
	}
}

// readApplyInput reads input from --from-file or stdin for apply commands.
// NOTE: Also used by classic_registry.go helpers (same generated package).
func readApplyInput(fromFile string) ([]byte, error) {
	if fromFile != "" {
		data, err := os.ReadFile(fromFile)
		if err != nil {
			return nil, fmt.Errorf("reading input file: %w", err)
		}
		return data, nil
	}

	stat, _ := os.Stdin.Stat()
	if (stat.Mode() & os.ModeCharDevice) == 0 {
		data, err := io.ReadAll(io.LimitReader(os.Stdin, 10<<20))
		if err != nil {
			return nil, fmt.Errorf("reading stdin: %w", err)
		}
		if len(data) > 0 {
			return data, nil
		}
	}

	return nil, fmt.Errorf("input required: use --from-file or pipe data to stdin")
}

// extractJSONField extracts a string field from a JSON object.
func extractJSONField(data []byte, field string) (string, error) {
	var obj map[string]any
	if err := json.Unmarshal(data, &obj); err != nil {
		return "", fmt.Errorf("parsing JSON: %w", err)
	}
	val, ok := obj[field]
	if !ok {
		return "", fmt.Errorf("field %q not found", field)
	}
	s, ok := val.(string)
	if !ok || s == "" {
		return "", fmt.Errorf("field %q must be a non-empty string", field)
	}
	return s, nil
}

// resolveNameToIDForApply looks up a resource by name and returns its ID.
// Unlike resolveNameToID, it fetches enough results to detect collisions.
// Returns ("", nil) when no resource is found (caller should create).
// Returns (id, nil) when exactly one match is found.
// Returns ("", error) when multiple matches or lookup fails.
func resolveNameToIDForApply(ctx context.Context, client registry.HTTPClient, listPath, nameField, idField, name string, noInput bool) (string, error) {
	// Escape double quotes in name to prevent RSQL injection
	escapedName := strings.ReplaceAll(name, ` + "`" + `"` + "`" + `, ` + "`" + `\"` + "`" + `)
	filterPath := fmt.Sprintf("%s?filter=%s&page-size=100",
		listPath, url.QueryEscape(fmt.Sprintf(` + "`" + `%s=="%s"` + "`" + `, nameField, escapedName)))

	resp, err := client.Do(ctx, "GET", filterPath, nil)
	if err != nil {
		return "", fmt.Errorf("looking up %q: %w", name, err)
	}
	defer func() { _ = resp.Body.Close() }()

	body, err := io.ReadAll(io.LimitReader(resp.Body, 1<<20))
	if err != nil {
		return "", fmt.Errorf("reading lookup response: %w", err)
	}

	var data struct {
		TotalCount int               ` + "`" + `json:"totalCount"` + "`" + `
		Results    []json.RawMessage ` + "`" + `json:"results"` + "`" + `
	}
	if err := json.Unmarshal(body, &data); err != nil {
		var arr []json.RawMessage
		if jsonErr := json.Unmarshal(body, &arr); jsonErr != nil {
			return "", fmt.Errorf("parsing lookup response: %w", err)
		}
		data.Results = arr
		data.TotalCount = len(arr)
	}

	if data.TotalCount == 0 || len(data.Results) == 0 {
		return "", nil // Not found — caller should create
	}

	// Parse results to extract IDs
	type applyMatch struct {
		id string
	}
	var matches []applyMatch
	for _, raw := range data.Results {
		var obj map[string]any
		if err := json.Unmarshal(raw, &obj); err != nil {
			continue
		}
		if id := extractIDString(obj, idField); id != "" {
			matches = append(matches, applyMatch{id: id})
		}
	}

	if len(matches) == 0 {
		return "", nil
	}

	if len(matches) == 1 {
		return matches[0].id, nil
	}

	// Collision: multiple resources with the same name
	if noInput {
		ids := make([]string, len(matches))
		for i, m := range matches {
			ids[i] = m.id
		}
		return "", fmt.Errorf("multiple resources found with name %q (IDs: %s); resolve duplicates or use update with a specific ID", name, strings.Join(ids, ", "))
	}

	// Interactive: prompt user to pick
	fmt.Fprintf(os.Stderr, "Multiple resources found with name %q:\n", name)
	for i, m := range matches {
		fmt.Fprintf(os.Stderr, "  [%d] ID: %s\n", i+1, m.id)
	}
	fmt.Fprintf(os.Stderr, "Enter number to replace (or 0 to cancel): ")
	var choice int
	if _, err := fmt.Fscan(os.Stdin, &choice); err != nil || choice < 1 || choice > len(matches) {
		return "", fmt.Errorf("aborted")
	}
	return matches[choice-1].id, nil
}



// buildMergePatchFromSet converts a slice of "key.path=value" strings into a
// JSON merge-patch document. Dot notation is expanded into nested objects.
// Value inference: "true"/"false" → bool, "null" → null, integers → int64, else string.
func buildMergePatchFromSet(pairs []string) ([]byte, error) {
	result := make(map[string]any)
	for _, pair := range pairs {
		eq := strings.Index(pair, "=")
		if eq < 1 {
			return nil, fmt.Errorf("invalid --set value %q: expected key=value", pair)
		}
		key := pair[:eq]
		val := pair[eq+1:]
		if err := setNestedValue(result, strings.Split(key, "."), parsePatchValue(val)); err != nil {
			return nil, fmt.Errorf("setting %q: %w", key, err)
		}
	}
	return json.Marshal(result)
}

// setNestedValue sets a value at a dot-notation path within a nested map.
func setNestedValue(m map[string]any, keys []string, value any) error {
	if len(keys) == 1 {
		m[keys[0]] = value
		return nil
	}
	sub, ok := m[keys[0]]
	if !ok {
		sub = make(map[string]any)
		m[keys[0]] = sub
	}
	subMap, ok := sub.(map[string]any)
	if !ok {
		return fmt.Errorf("cannot set nested key under non-object field %q", keys[0])
	}
	return setNestedValue(subMap, keys[1:], value)
}

// parsePatchValue converts a string to the most appropriate scalar type for
// JSON merge-patch: "true"/"false" → bool, "null" → nil, integers → int64, else string.
func parsePatchValue(s string) any {
	switch s {
	case "true":
		return true
	case "false":
		return false
	case "null":
		return nil
	}
	if i, err := strconv.ParseInt(s, 10, 64); err == nil {
		return i
	}
	return s
}
`
