// Copyright 2026, Jamf Software LLC

package security

// resourceTemplate emits one Go file per Security Cloud resource. Generated
// commands take *security.Client from CLIContext.SecurityClient and call
// .DoExpect{Risk,Lifecycle,SSE}() — chosen per-resource by .Scope — for every
// API request; the client handles the scoped Basic-login-for-JWT auth and
// non-2xx error mapping.
//
// Current scope (deliberately narrower than the Pro/Platform templates —
// Security's 12 total operations never need path params, name-based lookup,
// or PATCH/merge-patch):
//   - GET (no body)
//   - PUT/POST/DELETE actions, with or without a JSON body via --file/--set
//     (+ --scaffold), and --yes confirmation for destructive ones
//   - The one paginated op (risk list) always fetches every page and prints
//     the aggregated array — no --all flag, mirroring the Platform
//     generator's simpler "just fetch everything" pagination
//   - Device Lifecycle's {customerId} path placeholder is filled from
//     SecurityClient.LifecycleCustomerID at request time, never user-facing
const resourceTemplate = `// Copyright 2026, Jamf Software LLC
// Code generated by jamf-cli generator. DO NOT EDIT.

package generated

import (
	"encoding/json"
	"fmt"
	"net/url"
	"strings"

	"github.com/spf13/cobra"

	"github.com/Jamf-Concepts/jamf-cli/internal/registry"
	"github.com/Jamf-Concepts/jamf-cli/internal/security"
)

// New{{.GoName}}Cmd returns the cobra command tree for the {{.Name}} Jamf
// Security Cloud resource. Wire it into the "security" product command via AddCommand.
func New{{.GoName}}Cmd(cliCtx *registry.CLIContext) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "{{.Name}}",
		Short: "Manage {{.Name}} (Jamf Security Cloud)",
	}
{{- range .Operations }}
	cmd.AddCommand(new{{$.GoName}}{{.GoName}}Cmd(cliCtx))
{{- end }}
	return cmd
}
{{ range .Operations }}
func new{{$.GoName}}{{.GoName}}Cmd(cliCtx *registry.CLIContext) *cobra.Command {
{{- if .HasBody }}
	var bodyFile string
	var setFlags []string
	var scaffoldFlag bool
{{- end }}
{{- if .IsDestructive }}
	var yes bool
{{- end }}
{{- if .Paginate }}
{{- range .QueryParams }}
{{- if eq .GoType "bool" }}
	var {{.Var}} bool
{{- else if eq .GoType "[]string" }}
	var {{.Var}} []string
{{- else }}
	var {{.Var}} string
{{- end }}
{{- end }}
{{- end }}
	cmd := &cobra.Command{
		Use:   "{{.Name}}",
		Short: {{printf "%q" .Short}},
{{- $ann := opAnnotations . }}{{ if $ann }}
		Annotations: {{ $ann }},
{{- end }}
		RunE: func(cmd *cobra.Command, args []string) error {
{{- if .HasBody }}
			if scaffoldFlag {
				// Scaffold prints raw JSON regardless of -o, so the output
				// can be piped straight back into --file.
				fmt.Println({{printf "%q" .Scaffold}})
				return nil
			}
{{- end }}
{{- if .IsDestructive }}
			if err := security.ConfirmAction({{printf "%q" .Name}}, {{printf "%q" $.Name}}, yes); err != nil {
				return err
			}
{{- end }}
			path := {{printf "%q" .Path}}
{{- if .NeedsCustomerID }}
			customerID, err := cliCtx.SecurityClient.LifecycleCustomerID(cmd.Context())
			if err != nil {
				return err
			}
			path = strings.Replace(path, "{{"{customerId}"}}", url.PathEscape(customerID), 1)
{{- end }}
{{- if .HasBody }}
			body, err := security.ReadBody(bodyFile, setFlags)
			if err != nil {
				return err
			}
{{- else }}
			var body any
{{- end }}
{{- if .Paginate }}
			const pageSize = 100
			var aggregated []json.RawMessage
			for page := 0; ; page++ {
				q := url.Values{}
				q.Set("page", fmt.Sprintf("%d", page))
				q.Set("pageSize", fmt.Sprintf("%d", pageSize))
{{- range .QueryParams }}
{{- if eq .GoType "bool" }}
				if {{.Var}} {
					q.Set("{{.Name}}", "true")
				}
{{- else if eq .GoType "[]string" }}
				for _, v := range {{.Var}} {
					q.Add("{{.Name}}", v)
				}
{{- else }}
				if {{.Var}} != "" {
					q.Set("{{.Name}}", {{.Var}})
				}
{{- end }}
{{- end }}
				var pageResult struct {
					Items []json.RawMessage ` + "`json:\"{{.UnwrapArrayKey}}\"`" + `
				}
				if err := cliCtx.SecurityClient.DoExpect{{$.Scope}}(cmd.Context(), {{printf "%q" .Method}}, path+"?"+q.Encode(), body, &pageResult); err != nil {
					return fmt.Errorf("{{.Name}}: %w", err)
				}
				aggregated = append(aggregated, pageResult.Items...)
				if len(pageResult.Items) < pageSize {
					break
				}
			}
			b, err := json.MarshalIndent(aggregated, "", "  ")
			if err != nil {
				return err
			}
			return cliCtx.Output.PrintRaw(b)
{{- else }}
			var result any
			if err := cliCtx.SecurityClient.DoExpect{{$.Scope}}(cmd.Context(), {{printf "%q" .Method}}, path, body, &result); err != nil {
				return fmt.Errorf("{{.Name}}: %w", err)
			}
			if result == nil {
				return nil
			}
			b, err := json.MarshalIndent(result, "", "  ")
			if err != nil {
				return err
			}
			return cliCtx.Output.PrintRaw(b)
{{- end }}
		},
	}
{{- if .HasBody }}
	cmd.Flags().StringVar(&bodyFile, "file", "", "Path to JSON file containing the request body")
	cmd.Flags().StringArrayVar(&setFlags, "set", nil, "Override body values (key=value, repeatable, supports nested.keys)")
	cmd.Flags().BoolVar(&scaffoldFlag, "scaffold", false, "Print an example request body and exit")
{{- end }}
{{- if .IsDestructive }}
	cmd.Flags().BoolVar(&yes, "yes", false, "Skip confirmation prompt")
{{- end }}
{{- if .Paginate }}
{{- range .QueryParams }}
{{- if eq .GoType "bool" }}
	cmd.Flags().BoolVar(&{{.Var}}, "{{.FlagName}}", false, {{printf "%q" .Description}})
{{- else if eq .GoType "[]string" }}
	cmd.Flags().StringArrayVar(&{{.Var}}, "{{.FlagName}}", nil, {{printf "%q" .Description}})
{{- else }}
	cmd.Flags().StringVar(&{{.Var}}, "{{.FlagName}}", "", {{printf "%q" .Description}})
{{- end }}
{{- end }}
{{- end }}
	return cmd
}
{{ end }}
// guards against unused-import errors when a given resource's operations
// don't happen to exercise every helper (e.g. a resource with no paginated
// op never calls url.Values, one with no {customerId} substitution never
// calls strings.Replace, and a resource with only bodyless/non-destructive
// GETs — well-known, jwks — never calls into the security package at all).
var (
	_ = strings.Replace
	_ = url.Values{}
	_ = json.Marshal
	_ = security.ConfirmAction
	_ = security.ReadBody
)
`
