// Copyright 2026, Jamf Software LLC

// Code generated by generator/gateway. DO NOT EDIT.
//
// Which Jamf Pro and Classic operations this CLI can send that the Jamf
// Platform gateway does not publish, derived from jamfplatform-go-sdk's
// api/pro_api.json and api/classic_api_resource_documentation.json via
// specs/gateway/coverage.json. Regenerate with:
//
//	make sync-gateway-coverage-from-sdk JAMFPLATFORM_SDK_PATH=/path/to/jamfplatform-go-sdk
//
// Only the operations this CLI actually sends are listed, so the table is the
// intersection of "the gateway omits it" and "a command exists for it" — not a
// mirror of the gateway's spec.

package gateway

// Provenance of the manifest this table was derived from. Empty when the tree
// held no manifest at generate time, which is the "unknown" case: Lookup then
// finds nothing and no command is refused.
const (
	ProAPIVersion     = "11.31.0"
	ClassicAPIVersion = "11.28.0"
	SDKCommit         = "adb8d7b"
)

// unserved is sorted by path then method. Paths are gateway-form with every
// path parameter rendered as {}, matched segment-wise by Lookup. Every entry is
// refused before a request is sent on a gateway profile; Basis selects the
// wording, not the behaviour.
var unserved = []Finding{
	{Method: "POST", Path: "/pro/auth/current", Level: Unserved, Basis: BasisUnpublished, Detail: "not declared by the gateway's Jamf Pro API 11.31.0"},
	{Method: "POST", Path: "/pro/auth/invalidateToken", Level: Unserved, Basis: BasisUnpublished, Detail: "not declared by the gateway's Jamf Pro API 11.31.0"},
	{Method: "POST", Path: "/pro/auth/keepAlive", Level: Unserved, Basis: BasisUnpublished, Detail: "not declared by the gateway's Jamf Pro API 11.31.0"},
	{Method: "GET", Path: "/pro/v1/api-integrations", Level: Unserved, Basis: BasisUnpublished, Detail: "not declared by the gateway's Jamf Pro API 11.31.0"},
	{Method: "POST", Path: "/pro/v1/api-integrations", Level: Unserved, Basis: BasisUnpublished, Detail: "not declared by the gateway's Jamf Pro API 11.31.0"},
	{Method: "DELETE", Path: "/pro/v1/api-integrations/{}", Level: Unserved, Basis: BasisUnpublished, Detail: "not declared by the gateway's Jamf Pro API 11.31.0"},
	{Method: "GET", Path: "/pro/v1/api-integrations/{}", Level: Unserved, Basis: BasisUnpublished, Detail: "not declared by the gateway's Jamf Pro API 11.31.0"},
	{Method: "PUT", Path: "/pro/v1/api-integrations/{}", Level: Unserved, Basis: BasisUnpublished, Detail: "not declared by the gateway's Jamf Pro API 11.31.0"},
	{Method: "POST", Path: "/pro/v1/api-integrations/{}/client-credentials", Level: Unserved, Basis: BasisUnpublished, Detail: "not declared by the gateway's Jamf Pro API 11.31.0"},
	{Method: "GET", Path: "/pro/v1/api-role-privileges", Level: Unserved, Basis: BasisUnpublished, Detail: "not declared by the gateway's Jamf Pro API 11.31.0"},
	{Method: "GET", Path: "/pro/v1/api-role-privileges/search", Level: Unserved, Basis: BasisUnpublished, Detail: "not declared by the gateway's Jamf Pro API 11.31.0"},
	{Method: "GET", Path: "/pro/v1/api-roles", Level: Unserved, Basis: BasisUnpublished, Detail: "not declared by the gateway's Jamf Pro API 11.31.0"},
	{Method: "POST", Path: "/pro/v1/api-roles", Level: Unserved, Basis: BasisUnpublished, Detail: "not declared by the gateway's Jamf Pro API 11.31.0"},
	{Method: "DELETE", Path: "/pro/v1/api-roles/{}", Level: Unserved, Basis: BasisUnpublished, Detail: "not declared by the gateway's Jamf Pro API 11.31.0"},
	{Method: "GET", Path: "/pro/v1/api-roles/{}", Level: Unserved, Basis: BasisUnpublished, Detail: "not declared by the gateway's Jamf Pro API 11.31.0"},
	{Method: "PUT", Path: "/pro/v1/api-roles/{}", Level: Unserved, Basis: BasisUnpublished, Detail: "not declared by the gateway's Jamf Pro API 11.31.0"},
	{Method: "GET", Path: "/pro/v1/app-installers/deployments", Level: Unserved, Basis: BasisProbe, Detail: "wire-confirmed unserved on EU and US, 2026-08-28, re-confirmed 2026-08-31"},
	{Method: "POST", Path: "/pro/v1/app-installers/deployments", Level: Unserved, Basis: BasisProbe, Detail: "wire-confirmed unserved on EU and US, 2026-08-28, re-confirmed 2026-08-31"},
	{Method: "POST", Path: "/pro/v1/app-installers/deployments/export", Level: Unserved, Basis: BasisProbe, Detail: "wire-confirmed unserved on EU and US, 2026-08-28, re-confirmed 2026-08-31"},
	{Method: "DELETE", Path: "/pro/v1/app-installers/deployments/{}", Level: Unserved, Basis: BasisProbe, Detail: "wire-confirmed unserved on EU and US, 2026-08-28, re-confirmed 2026-08-31"},
	{Method: "GET", Path: "/pro/v1/app-installers/deployments/{}", Level: Unserved, Basis: BasisProbe, Detail: "wire-confirmed unserved on EU and US, 2026-08-28, re-confirmed 2026-08-31"},
	{Method: "PUT", Path: "/pro/v1/app-installers/deployments/{}", Level: Unserved, Basis: BasisProbe, Detail: "wire-confirmed unserved on EU and US, 2026-08-28, re-confirmed 2026-08-31"},
	{Method: "GET", Path: "/pro/v1/app-installers/deployments/{}/computers", Level: Unserved, Basis: BasisProbe, Detail: "wire-confirmed unserved on EU and US, 2026-08-28, re-confirmed 2026-08-31"},
	{Method: "POST", Path: "/pro/v1/app-installers/deployments/{}/computers/installation-retry", Level: Unserved, Basis: BasisProbe, Detail: "wire-confirmed unserved on EU and US, 2026-08-28, re-confirmed 2026-08-31"},
	{Method: "POST", Path: "/pro/v1/app-installers/deployments/{}/computers/{}/installation-retry", Level: Unserved, Basis: BasisProbe, Detail: "wire-confirmed unserved on EU and US, 2026-08-28, re-confirmed 2026-08-31"},
	{Method: "GET", Path: "/pro/v1/app-installers/deployments/{}/history", Level: Unserved, Basis: BasisProbe, Detail: "wire-confirmed unserved on EU and US, 2026-08-28, re-confirmed 2026-08-31"},
	{Method: "POST", Path: "/pro/v1/app-installers/deployments/{}/history", Level: Unserved, Basis: BasisProbe, Detail: "wire-confirmed unserved on EU and US, 2026-08-28, re-confirmed 2026-08-31"},
	{Method: "GET", Path: "/pro/v1/app-installers/deployments/{}/installation-summary", Level: Unserved, Basis: BasisProbe, Detail: "wire-confirmed unserved on EU and US, 2026-08-28, re-confirmed 2026-08-31"},
	{Method: "POST", Path: "/pro/v1/app-installers/deployments/{}/version-update", Level: Unserved, Basis: BasisProbe, Detail: "wire-confirmed unserved on EU and US, 2026-08-28, re-confirmed 2026-08-31"},
	{Method: "GET", Path: "/pro/v1/app-installers/global-settings", Level: Unserved, Basis: BasisProbe, Detail: "wire-confirmed unserved on EU and US, 2026-08-28, re-confirmed 2026-08-31"},
	{Method: "PUT", Path: "/pro/v1/app-installers/global-settings", Level: Unserved, Basis: BasisProbe, Detail: "wire-confirmed unserved on EU and US, 2026-08-28, re-confirmed 2026-08-31"},
	{Method: "GET", Path: "/pro/v1/app-installers/titles", Level: Unserved, Basis: BasisProbe, Detail: "wire-confirmed unserved on EU and US, 2026-08-28, re-confirmed 2026-08-31"},
	{Method: "GET", Path: "/pro/v1/app-installers/titles/{}", Level: Unserved, Basis: BasisProbe, Detail: "wire-confirmed unserved on EU and US, 2026-08-28, re-confirmed 2026-08-31"},
	{Method: "GET", Path: "/pro/v1/auth", Level: Unserved, Basis: BasisUnpublished, Detail: "not declared by the gateway's Jamf Pro API 11.31.0"},
	{Method: "POST", Path: "/pro/v1/auth/invalidate-token", Level: Unserved, Basis: BasisUnpublished, Detail: "not declared by the gateway's Jamf Pro API 11.31.0"},
	{Method: "POST", Path: "/pro/v1/auth/keep-alive", Level: Unserved, Basis: BasisUnpublished, Detail: "not declared by the gateway's Jamf Pro API 11.31.0"},
	{Method: "POST", Path: "/pro/v1/auth/token", Level: Unserved, Basis: BasisUnpublished, Detail: "not declared by the gateway's Jamf Pro API 11.31.0"},
	{Method: "GET", Path: "/pro/v1/macos-managed-software-updates/available-updates", Level: Unserved, Basis: BasisUnpublished, Detail: "not declared by the gateway's Jamf Pro API 11.31.0"},
	{Method: "POST", Path: "/pro/v1/oauth/token", Level: Unserved, Basis: BasisUnpublished, Detail: "not declared by the gateway's Jamf Pro API 11.31.0"},
	{Method: "GET", Path: "/pro/v1/oauth2/session-tokens", Level: Unserved, Basis: BasisUnpublished, Detail: "not declared by the gateway's Jamf Pro API 11.31.0"},
	{Method: "POST", Path: "/pro/v1/system/initialize-database-connection", Level: Unserved, Basis: BasisUnpublished, Detail: "not declared by the gateway's Jamf Pro API 11.31.0"},
	{Method: "GET", Path: "/pro/v2/environment-type", Level: Unserved, Basis: BasisUnpublished, Detail: "not declared by the gateway's Jamf Pro API 11.31.0"},
	{Method: "POST", Path: "/pro/v2/mdm/commands", Level: Unserved, Basis: BasisUnpublished, Detail: "the gateway's Jamf Pro API 11.31.0 declares GET on this path but not POST"},
	{Method: "*", Path: "/proclassic/computerconfigurations/**", Level: Unserved, Basis: BasisUnpublished, Detail: "not declared by the gateway's Classic API 11.28.0, which trails the Pro API's version"},
}
