openapi: 3.0.1
info:
  title: Jamf Pro API - Account Driven User Enrollment Session Token Setting
  version: 0.0.1

paths:
  /v1/adue-session-token-settings:
    get:
      tags:
        - enrollment
      summary: |
        Retrieve the Account Driven User Enrollment Session Token Settings
      description: |
        Retrieve the Account Driven User Enrollment Session Token Settings
      responses:
        200:
          description: Successful response
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/AccountDrivenUserEnrollmentSessionTokenSettings'
      x-required-privileges:
        - Read User-Initiated Enrollment
    put:
      tags:
        - enrollment
      summary: |
        Update Account Driven User Enrollment Session Token Settings.
      description: |
        Update the Account Driven User Enrollment Session Token Settings object.
      requestBody:
        description: Update Account Driven User Enrollment Session Token Settings.
        content:
          'application/json':
            schema:
              $ref: '#/components/schemas/AccountDrivenUserEnrollmentSessionTokenSettings'
        required: true
      responses:
        200:
          description: Successfully updated Account Driven User Enrollment Session Token Settings object
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/AccountDrivenUserEnrollmentSessionTokenSettings'
        400:
          description: Invalid data response
          content:
            'application/json':
              schema:
                $ref: 'DefinitionsLibrary.yaml#/components/schemas/ApiError'
      x-required-privileges:
        - Update User-Initiated Enrollment

components:
  schemas:
    AccountDrivenUserEnrollmentSessionTokenSettings:
      type: object
      description: Settings for Account Driven User Enrollment. Only 1 of expirationIntervalDays or expirationIntervalSeconds can be supplied.
      properties:
        enabled:
          type: boolean
          example: false
        expirationIntervalDays:
          type: integer
          example: 1
        expirationIntervalSeconds:
          type: integer
          example: 86400



