components:
  schemas:
    ActivationCode:
      properties:
        activationCode:
          description: Activation Code for Jamf Pro. Hyphens are optional.
          example: A1A1-B2B2-C3C3-D4D4-E5E5-F6F6-G7G7-H8H8
          maxLength: 39
          minLength: 32
          type: string
      required:
        - activationCode
      type: object
    OrganizationName:
      properties:
        organizationName:
          description: The Organization Name for Jamf Pro.
          example: Your Organization Name
          nullable: false
          type: string
      required:
        - organizationName
      type: object
info:
  title: Jamf Pro API - ActivationCode
  version: 0.0.1
openapi: 3.0.1
paths:
  /v1/activation-code:
    put:
      description: Updates Activation Code in Jamf Pro.
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ActivationCode'
      responses:
        202:
          description: Update successful.
      summary: Updates Activation Code
      tags:
        - activation-code
      x-required-privileges:
        - Update Activation Code
  /v1/activation-code/history:
    get:
      description: Get Activation Code history object
      parameters:
        - $ref: _MonolithLibrary.yaml#/components/parameters/page
        - $ref: _MonolithLibrary.yaml#/components/parameters/page-size
        - description: 'Sorting criteria in the format: property:asc/desc. Default sort is date:desc. Fields allowed in the query: id, username, date, note, details Multiple sort criteria are supported and must be separated with a comma. Example: sort=date:desc,note:asc '
          explode: true
          in: query
          name: sort
          required: false
          schema:
            default:
              - date:desc
            items:
              type: string
            type: array
          style: form
        - description: 'Query in the RSQL format, allowing to filter history notes collection. Default filter is empty query - returning all results for the requested page. Fields allowed in the query: id, username, date, note, details. This param can be combined with paging and sorting. Example: filter=username!=admin and details==*disabled* and date<2019-12-15'
          explode: true
          in: query
          name: filter
          required: false
          schema:
            default: ""
            type: string
          style: form
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: _MonolithLibrary.yaml#/components/schemas/HistorySearchResults
          description: Details of Activation Code history was found.
        404:
          content:
            application/json:
              schema:
                $ref: _MonolithLibrary.yaml#/components/schemas/ApiError
          description: Activation Code object does not exist.
      summary: Get Activation Code history object
      tags:
        - activation-code
      x-required-privileges:
        - Read Activation Code
    post:
      description: |
        Adds Activation Code object note.
      requestBody:
        content:
          application/json:
            schema:
              $ref: _MonolithLibrary.yaml#/components/schemas/ObjectHistoryNote
        description: Activation Code history notes to create.
        required: true
      responses:
        201:
          content:
            application/json:
              schema:
                $ref: _MonolithLibrary.yaml#/components/schemas/ObjectHistory
          description: Notes of Activation Code history were added.
        503:
          content:
            application/json:
              schema:
                $ref: _MonolithLibrary.yaml#/components/schemas/ApiError
          description: Activation Code history cannot be saved.
      summary: |
        Add Activation Code object note
      tags:
        - activation-code
      x-required-privileges:
        - Update Activation Code
  /v1/activation-code/history/export:
    post:
      description: |
        Export history object collection in specified format for Activation Code
      parameters:
        - $ref: _MonolithLibrary.yaml#/components/parameters/export-fields
        - $ref: _MonolithLibrary.yaml#/components/parameters/export-labels
        - $ref: _MonolithLibrary.yaml#/components/parameters/page
        - $ref: _MonolithLibrary.yaml#/components/parameters/page-size
        - description: 'Sorting criteria in the format: property:asc/desc. Default sort is date:desc. Multiple sort criteria are supported and must be separated with a comma. Example: sort=date:desc,name:asc '
          explode: true
          in: query
          name: sort
          required: false
          schema:
            default:
              - date:desc
            items:
              type: string
            type: array
          style: form
        - description: 'Query in the RSQL format, allowing to filter history notes collection. Default filter is empty query - returning all results for the requested page. Fields allowed in the query: username, date, note, details. This param can be combined with paging and sorting. Example: filter=username!=admin and details==*disabled* and date<2019-12-15'
          explode: true
          in: query
          name: filter
          required: false
          schema:
            default: ""
            type: string
          style: form
      requestBody:
        content:
          application/json:
            schema:
              $ref: _MonolithLibrary.yaml#/components/schemas/ExportParameters
        description: Optional. Override query parameters since they can make URI exceed 2,000 character limit.
        required: false
      responses:
        200:
          content:
            text/csv:
              schema:
                example: |
                  id,username,date,note,details
                  1,admin,2019-02-04 21:09:31,Buildings update,Some details
                format: binary
          description: Export successful
        400:
          content:
            application/json:
              schema:
                $ref: _MonolithLibrary.yaml#/components/schemas/ApiError
          description: Export fields specified incorrectly - non-existing column or duplicate on the list.
        503:
          content:
            application/json:
              schema:
                $ref: _MonolithLibrary.yaml#/components/schemas/ApiError
          description: Export currently unavailable, all export-related resources are in use. Try again later.
      summary: |
        Export history object collection in specified format for Activation Code
      tags:
        - activation-code
      x-action: true
      x-required-privileges:
        - Read Activation Code
  /v1/activation-code/organization-name:
    patch:
      description: Updates Organization Name in Jamf Pro.
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/OrganizationName'
      responses:
        202:
          description: Update successful.
      summary: Updates Organization Name
      tags:
        - activation-code
      x-required-privileges:
        - Update Activation Code
servers:
  - url: /api
