components:
  schemas:
    AdvancedSearch:
      properties:
        criteria:
          items:
            $ref: _MonolithLibrary.yaml#/components/schemas/SmartSearchCriterion
          type: array
        displayFields:
          example:
            - AirPlay Password
            - App Analytics Enabled
          items:
            type: string
          type: array
        id:
          example: "1"
          minLength: 1
          readOnly: true
          type: string
        name:
          example: Andy's Search
          type: string
        siteId:
          example: "-1"
          nullable: true
          type: string
      required:
        - name
      type: object
    AdvancedSearchCriteriaChoices:
      properties:
        choices:
          example:
            - Option 1
            - Option 2
          items:
            type: string
          type: array
      type: object
    AdvancedSearchSearchResults:
      properties:
        results:
          items:
            $ref: '#/components/schemas/AdvancedSearch'
          minItems: 0
          type: array
        totalCount:
          example: 3
          minimum: 0
          type: integer
      type: object
info:
  title: Jamf Pro API - AdvancedMobileDeviceSearch
  version: 0.0.1
openapi: 3.0.1
paths:
  /v1/advanced-mobile-device-searches:
    get:
      description: |
        Gets Advanced Search Objects
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AdvancedSearchSearchResults'
          description: Successful response - Advanced searches retrieved
      summary: |
        Get Advanced Search objects
      tags:
        - advanced-mobile-device-searches
      x-required-privileges:
        - Read Advanced Mobile Device Searches
    post:
      description: |
        Creates Advanced Search Object
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AdvancedSearch'
        required: true
      responses:
        201:
          content:
            application/json:
              schema:
                $ref: _MonolithLibrary.yaml#/components/schemas/HrefResponse
          description: Successful response - Advanced search created
      summary: |
        Create Advanced Search object
      tags:
        - advanced-mobile-device-searches
      x-required-privileges:
        - Create Advanced Mobile Device Searches
  /v1/advanced-mobile-device-searches/choices:
    get:
      description: |
        Gets Mobile Device Advanced Search criteria choices. A list of potentially valid choices can be found by navigating to the Criteria page of the Advanced Mobile Device Search creation process. A few are "App Name", "Building", and "Display Name".
      parameters:
        - explode: true
          in: query
          name: criteria
          required: true
          schema:
            type: string
          style: form
        - explode: true
          in: query
          name: site
          required: false
          schema:
            default: "-1"
            type: string
          style: form
        - explode: true
          in: query
          name: contains
          required: false
          schema:
            default: "null"
            type: string
          style: form
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AdvancedSearchCriteriaChoices'
          description: Successful response - Criteria choices retrieved
      summary: |
        Get Mobile Device Advanced Search criteria choices
      tags:
        - advanced-mobile-device-searches
      x-required-privileges:
        - Read Advanced Mobile Device Searches
  /v1/advanced-mobile-device-searches/delete-multiple:
    post:
      description: |
        Removes specified Advanced Search Objects
      requestBody:
        content:
          application/json:
            schema:
              $ref: _MonolithLibrary.yaml#/components/schemas/Ids
        description: ids of the building to be deleted
        required: true
      responses:
        204:
          description: Successful response - Advanced searches deleted
        400:
          content:
            application/json:
              schema:
                $ref: _MonolithLibrary.yaml#/components/schemas/ApiError
          description: At least one target Advanced Search does not exist
      summary: |
        Remove specified Advanced Search objects
      tags:
        - advanced-mobile-device-searches
      x-action: true
      x-required-privileges:
        - Delete Advanced Mobile Device Searches
  /v1/advanced-mobile-device-searches/{id}:
    delete:
      description: |
        Removes specified Advanced Search Object
      parameters:
        - description: instance id of advanced search record
          explode: false
          in: path
          name: id
          required: true
          schema:
            type: string
          style: simple
      responses:
        204:
          description: Successful response - Advanced search deleted
        404:
          content:
            application/json:
              schema:
                $ref: _MonolithLibrary.yaml#/components/schemas/ApiError
          description: Target Advanced Search does not exist
      summary: |
        Remove specified Advanced Search object
      tags:
        - advanced-mobile-device-searches
      x-required-privileges:
        - Delete Advanced Mobile Device Searches
    get:
      description: |
        Gets Specified Advanced Search Object
      parameters:
        - description: id of target Advanced Search
          explode: false
          in: path
          name: id
          required: true
          schema:
            type: string
          style: simple
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AdvancedSearch'
          description: Successful response - Advanced Search retrieved
        404:
          content:
            application/json:
              schema:
                $ref: _MonolithLibrary.yaml#/components/schemas/ApiError
          description: Target Advanced Search does not exist
      summary: |
        Get specified Advanced Search object
      tags:
        - advanced-mobile-device-searches
      x-required-privileges:
        - Read Advanced Mobile Device Searches
    put:
      description: |
        Gets Specified Advanced Search Object
      parameters:
        - description: id of target Advanced Search
          explode: false
          in: path
          name: id
          required: true
          schema:
            type: string
          style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AdvancedSearch'
        required: true
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AdvancedSearch'
          description: Successful response - Advanced Search updated
        404:
          content:
            application/json:
              schema:
                $ref: _MonolithLibrary.yaml#/components/schemas/ApiError
          description: Target Advanced Search does not exist
      summary: |
        Get specified Advanced Search object
      tags:
        - advanced-mobile-device-searches
      x-required-privileges:
        - Update Advanced Mobile Device Searches
servers:
  - url: /api
