components:
  schemas:
    ApiIntegrationRequest:
      properties:
        accessTokenLifetimeSeconds:
          example: 300
          type: integer
        authorizationScopes:
          description: |
            API Role display names.
          example:
            - Tootsie Roal
            - Jamf Reset
          items:
            type: string
          type: array
        displayName:
          example: My API Integration
          type: string
        enabled:
          example: true
          type: boolean
      required:
        - authorizationScopes
        - displayName
      type: object
    ApiIntegrationResponse:
      properties:
        accessTokenLifetimeSeconds:
          example: 300
          type: integer
        appType:
          description: |
            Type of API Client:
                * `CLIENT_CREDENTIALS` - A client ID and secret have been generated for this integration.
                * `NATIVE_APP_OAUTH` - A native app (i.e., Jamf Reset) has been linked to this integration for auth code grant type via Managed App Config.
                * `NONE` - No client is currently associated with this integration.
          enum:
            - CLIENT_CREDENTIALS
            - NATIVE_APP_OAUTH
            - NONE
          example: CLIENT_CREDENTIALS
          readOnly: true
          type: string
        authorizationScopes:
          example:
            - Tootsie Roal
            - Jamf Reset
          items:
            type: string
          type: array
        clientId:
          example: 538878d4-9744-43ed-8732-3df99d502bd6
          readOnly: true
          type: string
        displayName:
          example: My API Integration
          type: string
        enabled:
          example: true
          type: boolean
        id:
          example: 1
          type: integer
      required:
        - appType
        - authorizationScopes
        - clientId
        - displayName
        - enabled
        - id
      type: object
    ApiIntegrationSearchResult:
      properties:
        results:
          items:
            $ref: '#/components/schemas/ApiIntegrationResponse'
          minItems: 0
          type: array
        totalCount:
          example: 1
          minimum: 0
          readOnly: true
          type: integer
      required:
        - results
        - totalCount
      type: object
    OAuthClientCredentials:
      properties:
        clientId:
          example: admin
          type: string
        clientSecret:
          example: "12345"
          type: string
      required:
        - clientId
        - clientSecret
      type: object
info:
  title: Jamf Pro API - ApiIntegrations
  version: 0.0.1
openapi: 3.0.1
paths:
  /v1/api-integrations:
    get:
      description: Get Jamf|Pro API Integrations with Search Criteria
      parameters:
        - $ref: _MonolithLibrary.yaml#/components/parameters/page
        - $ref: _MonolithLibrary.yaml#/components/parameters/page-size
        - description: 'Sorting criteria in the format: property:asc/desc. Default sort is id:asc. Multiple sort criteria are supported and must be separated with a comma. Fields allowed in the query: id, displayName. Example: sort=displayName:desc'
          explode: true
          in: query
          name: sort
          required: false
          schema:
            default:
              - id:asc
            items:
              type: string
            type: array
          style: form
        - description: 'Query in the RSQL format, allowing to filter app titles collection. Default filter is empty query - returning all results for the requested page. Fields allowed in the query: id, displayName. Example: displayName=="*IntegrationName*"'
          explode: true
          in: query
          name: filter
          required: false
          schema:
            default: ""
            type: string
          style: form
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiIntegrationSearchResult'
          description: A list of the current Jamf API Integrations
      summary: Get the current API Integrations
      tags:
        - api-integrations
      x-required-privileges:
        - Read API Integrations
    post:
      description: Create API integration object
      operationId: postCreateApiIntegration
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ApiIntegrationRequest'
        description: api integration object to create
        required: true
      responses:
        201:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiIntegrationResponse'
          description: Api Integration object was created
      summary: Create API integration object
      tags:
        - api-integrations
      x-required-privileges:
        - Create API Integrations
  /v1/api-integrations/{id}:
    delete:
      description: Removes specified API integration
      operationId: deleteApiIntegration
      parameters:
        - description: instance id of api integration object
          explode: false
          in: path
          name: id
          required: true
          schema:
            type: string
          style: simple
      responses:
        204:
          description: Api Integration was deleted
        404:
          content:
            application/json:
              schema:
                $ref: _MonolithLibrary.yaml#/components/schemas/ApiError
          description: Specified api integration object does not exist.
      summary: Remove specified API integration
      tags:
        - api-integrations
      x-required-privileges:
        - Delete API Integrations
    get:
      description: Gets specified API integration object
      operationId: getOneApiIntegration
      parameters:
        - description: instance id of api integration object
          explode: false
          in: path
          name: id
          required: true
          schema:
            type: string
          style: simple
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiIntegrationResponse'
          description: Details of api integration object were found.
        404:
          content:
            application/json:
              schema:
                $ref: _MonolithLibrary.yaml#/components/schemas/ApiError
          description: Specified api integration object does not exist.
      summary: Get specified API integration object
      tags:
        - api-integrations
      x-required-privileges:
        - Read API Integrations
    put:
      description: Update specified API integration object
      operationId: putUpdateApiIntegration
      parameters:
        - description: instance id of api integration object
          explode: false
          in: path
          name: id
          required: true
          schema:
            type: string
          style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ApiIntegrationRequest'
        description: api object to update
        required: true
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiIntegrationResponse'
          description: Api Integration updated
        400:
          content:
            application/json:
              schema:
                $ref: _MonolithLibrary.yaml#/components/schemas/ApiError
          description: Api Integration could not be updated.
        404:
          content:
            application/json:
              schema:
                $ref: _MonolithLibrary.yaml#/components/schemas/ApiError
          description: Specified api integration object does not exist.
      summary: Update specified API integration object
      tags:
        - api-integrations
      x-required-privileges:
        - Update API Integrations
  /v1/api-integrations/{id}/client-credentials:
    post:
      description: Create client credentials for specified API integration
      operationId: postCreateClientCredentials
      parameters:
        - description: instance id of api integration object
          explode: false
          in: path
          name: id
          required: true
          schema:
            type: string
          style: simple
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OAuthClientCredentials'
          description: Client credentials have been created
        400:
          content:
            application/json:
              schema:
                $ref: _MonolithLibrary.yaml#/components/schemas/ApiError
          description: Client credentials could not be created for this api integration
        404:
          content:
            application/json:
              schema:
                $ref: _MonolithLibrary.yaml#/components/schemas/ApiError
          description: Specified api integration object does not exist.
      summary: Create client credentials for specified API integration
      tags:
        - api-integrations
      x-action: true
      x-required-privileges:
        - Create API Integrations
servers:
  - url: /api
