components:
  schemas:
    ApiRole:
      properties:
        displayName:
          example: One Role to Rule them all
          type: string
        id:
          example: "1"
          readOnly: true
          type: string
        privileges:
          items:
            example: View License Serial Numbers
            type: string
          minItems: 0
          type: array
      required:
        - displayName
        - id
        - privileges
      type: object
    ApiRoleRequest:
      properties:
        displayName:
          example: One Role to Rule them all
          type: string
        privileges:
          items:
            example: View License Serial Numbers
            type: string
          minItems: 0
          type: array
      required:
        - displayName
        - privileges
      type: object
    ApiRoleResult:
      properties:
        results:
          items:
            $ref: '#/components/schemas/ApiRole'
          minItems: 0
          type: array
        totalCount:
          example: 1
          minimum: 0
          readOnly: true
          type: integer
      required:
        - results
        - totalCount
      type: object
info:
  title: Jamf Pro API - ApiRoles
  version: 0.0.1
openapi: 3.0.1
paths:
  /v1/api-roles:
    get:
      description: Get roles with Search Criteria
      operationId: getAllApiRoles
      parameters:
        - $ref: _MonolithLibrary.yaml#/components/parameters/page
        - $ref: _MonolithLibrary.yaml#/components/parameters/page-size
        - description: 'Sorting criteria in the format: property:asc/desc. Default sort is id:asc. Multiple sort criteria are supported and must be separated with a comma. Fields allowed in the query: id, displayName. Example: sort=displayName:desc'
          explode: true
          in: query
          name: sort
          required: false
          schema:
            default:
              - id:asc
            items:
              type: string
            type: array
          style: form
        - description: 'Query in the RSQL format, allowing to filter app titles collection. Default filter is empty query - returning all results for the requested page. Fields allowed in the query: id, displayName. Example: displayName=="*myRole*"'
          explode: true
          in: query
          name: filter
          required: false
          schema:
            default: ""
            type: string
          style: form
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiRoleResult'
          description: A list of the current Jamf API Roles
      summary: Get the current Jamf API Roles
      tags:
        - api-roles
      x-required-privileges:
        - Read API Roles
    post:
      description: Post to create new Role
      operationId: postCreateApiRole
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ApiRoleRequest'
        description: API Integrations Role to create
        required: true
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiRole'
          description: The created Role
        400:
          content:
            application/json:
              schema:
                $ref: _MonolithLibrary.yaml#/components/schemas/ApiError
          description: Bad Request
      summary: Create a new API role
      tags:
        - api-roles
      x-action: true
      x-required-privileges:
        - Create API Roles
  /v1/api-roles/{id}:
    delete:
      description: Delete specific Role
      operationId: deleteApiRole
      parameters:
        - description: instance id of API role
          explode: false
          in: path
          name: id
          required: true
          schema:
            type: string
          style: simple
      responses:
        204:
          description: Jamf API Integrations Role deleted
        404:
          content:
            application/json:
              schema:
                $ref: _MonolithLibrary.yaml#/components/schemas/ApiError
          description: Role not found.
        409:
          content:
            application/json:
              schema:
                $ref: _MonolithLibrary.yaml#/components/schemas/ApiError
          description: Role in use by an Integration/Client
      summary: Delete API Integrations Role
      tags:
        - api-roles
      x-required-privileges:
        - Delete API Roles
    get:
      description: Get specific Role
      operationId: getOneApiRole
      parameters:
        - description: instance id of API role
          explode: false
          in: path
          name: id
          required: true
          schema:
            type: string
          style: simple
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiRole'
          description: The requested Jamf API Role
        404:
          content:
            application/json:
              schema:
                $ref: _MonolithLibrary.yaml#/components/schemas/ApiError
          description: Role not found
      summary: Get the specific Jamf API Role
      tags:
        - api-roles
      x-required-privileges:
        - Read API Roles
    put:
      description: Update specific Role
      operationId: putUpdateApiRole
      parameters:
        - description: instance id of API role
          explode: false
          in: path
          name: id
          required: true
          schema:
            type: string
          style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ApiRoleRequest'
        description: API Integrations Role to update
        required: true
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiRole'
          description: Jamf API Integrations Role updated
        400:
          content:
            application/json:
              schema:
                $ref: _MonolithLibrary.yaml#/components/schemas/ApiError
          description: Bad Request, could not parse input.
        404:
          content:
            application/json:
              schema:
                $ref: _MonolithLibrary.yaml#/components/schemas/ApiError
          description: Role not found
      summary: Update API Integrations Role
      tags:
        - api-roles
      x-required-privileges:
        - Update API Roles
servers:
  - url: /api
