components:
  schemas:
    ApiRolePrivileges:
      properties:
        privileges:
          items:
            example: Flush MDM Commands
            type: string
          minItems: 0
          type: array
      required:
        - privileges
      type: object
info:
  title: Jamf Pro API - ApiRolesPrivileges
  version: 0.0.1
openapi: 3.0.1
paths:
  /v1/api-role-privileges:
    get:
      description: Get role privileges
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiRolePrivileges'
          description: A sorted list of the current Jamf API Roles Privileges
      summary: Get the current Jamf API Role Privileges
      tags:
        - api-role-privileges
      x-required-privileges:
        - Read API Roles
  /v1/api-role-privileges/search:
    get:
      description: Search role privileges
      parameters:
        - description: The partial or complete privilege name we are searching for
          explode: true
          in: query
          name: name
          required: true
          schema:
            example: Flush
            type: string
          style: form
        - description: Limit the query results, defaults to 15
          explode: true
          in: query
          name: limit
          required: false
          schema:
            default: "15"
            example: "50"
            type: string
          style: form
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiRolePrivileges'
          description: A list of matches Jamf API Roles Privileges
      summary: Search the current Jamf API Role Privileges
      tags:
        - api-role-privileges
      x-required-privileges:
        - Read API Roles
servers:
  - url: /api
