components:
  schemas:
    AccountGroup:
      properties:
        accessLevel:
          enum:
            - FullAccess
            - SiteAccess
            - GroupBasedAccess
          example: FullAccess
          type: string
        memberUserIds:
          example:
            - 1
            - 3
          items:
            type: integer
          type: array
        privilegeSet:
          enum:
            - ADMINISTRATOR
            - AUDITOR
            - ENROLLMENT
            - CUSTOM
          example: CUSTOM
          type: string
        privileges:
          example: Read SSO Settings
          items:
            type: string
          type: array
        siteId:
          example: 1
          type: integer
      type: object
    AccountPreferences:
      properties:
        dateFormat:
          example: MM/dd/yyyy
          type: string
        isDisableRelativeDates:
          example: false
          type: boolean
        language:
          example: en
          type: string
        region:
          example: Europe
          type: string
        timezone:
          example: Etc/GMT
          type: string
      type: object
    AccountPreferencesV1:
      properties:
        dateFormat:
          example: MM/dd/yyyy
          type: string
        disableRelativeDates:
          example: false
          type: boolean
        language:
          example: en
          type: string
        region:
          example: Europe
          type: string
        timezone:
          example: Etc/GMT
          type: string
      type: object
    AuthAccount:
      properties:
        accessLevel:
          enum:
            - FullAccess
            - SiteAccess
            - GroupBasedAccess
          example: FullAccess
          type: string
        currentSiteId:
          example: 1
          type: integer
        email:
          example: ITBob@Jamf.com
          type: string
        groupIds:
          example:
            - 1
            - 3
          items:
            type: integer
          type: array
        id:
          example: 1
          minimum: 1
          type: integer
        isMultiSiteAdmin:
          example: true
          type: boolean
        preferences:
          $ref: '#/components/schemas/AccountPreferences'
        privilegeSet:
          enum:
            - ADMINISTRATOR
            - AUDITOR
            - ENROLLMENT
            - CUSTOM
          example: CUSTOM
          type: string
        privilegesBySite:
          additionalProperties:
            items:
              type: string
            type: array
          example:
            1:
              - Read SSO Settings
              - Delete eBooks
          type: object
        realName:
          example: IT Bob
          type: string
        username:
          example: admin
          type: string
      type: object
    AuthAccountV1:
      properties:
        accessLevel:
          enum:
            - FullAccess
            - SiteAccess
            - GroupBasedAccess
          example: FullAccess
          type: string
        currentSiteId:
          example: "1"
          type: string
        email:
          example: ITBob@Jamf.com
          type: string
        groupIds:
          example:
            - 1
            - 3
          items:
            type: string
          type: array
        id:
          example: "1"
          minLength: 1
          type: string
        multiSiteAdmin:
          example: true
          type: boolean
        preferences:
          $ref: '#/components/schemas/AccountPreferencesV1'
        privilegeSet:
          enum:
            - ADMINISTRATOR
            - AUDITOR
            - ENROLLMENT
            - CUSTOM
          example: CUSTOM
          type: string
        privilegesBySite:
          additionalProperties:
            items:
              type: string
            type: array
          example:
            1:
              - Read SSO Settings
              - Delete eBooks
          type: object
        realName:
          example: IT Bob
          type: string
        username:
          example: admin
          type: string
      type: object
    AuthToken:
      properties:
        expires:
          example: 1539619348124
          type: integer
        token:
          example: eyJhbGciOiJIUzUxMiJ9.eyJhdXRoZW50aWNhdGVkLWFwcCI6IkdFTkVSSUMiLCJhdXRoZW50aWNhdGlvbi10eXBlIjoiSlNTIiwiZ3JvdXBzIjpbXSwic3ViamVjdC10eXBlIjoiSlNTX1VTRVJfSUQiLCJ0b2tlbi11dWlkIjoiNzc0YWY3MGYtYWQ0Yy00N2QzLTk2MzktZjEwMjBhMTIwYzExIiwibGRhcC1zZXJ2ZXItaWQiOi0xLCJzdWIiOiIxIiwiZXhwIjoxNTM5NjE5MzQ4fQ.0t7sgYyIyA7kTTmrM8tMGE7fnXcJ1ZzQODAJp0pzg92-cBMQS0Cv8S9oWjkJD7VJS-CHA1dOppr0G_2dCPOfng
          nullable: false
          type: string
      type: object
    AuthTokenV1:
      properties:
        expires:
          example: "2020-04-21T21:09:31.626Z"
          type: string
        token:
          example: eyJhbGciOiJIUzUxMiJ9.eyJhdXRoZW50aWNhdGVkLWFwcCI6IkdFTkVSSUMiLCJhdXRoZW50aWNhdGlvbi10eXBlIjoiSlNTIiwiZ3JvdXBzIjpbXSwic3ViamVjdC10eXBlIjoiSlNTX1VTRVJfSUQiLCJ0b2tlbi11dWlkIjoiNzc0YWY3MGYtYWQ0Yy00N2QzLTk2MzktZjEwMjBhMTIwYzExIiwibGRhcC1zZXJ2ZXItaWQiOi0xLCJzdWIiOiIxIiwiZXhwIjoxNTM5NjE5MzQ4fQ.0t7sgYyIyA7kTTmrM8tMGE7fnXcJ1ZzQODAJp0pzg92-cBMQS0Cv8S9oWjkJD7VJS-CHA1dOppr0G_2dCPOfng
          nullable: false
          type: string
      type: object
    AuthenticationType:
      enum:
        - JSS
        - LDAP
        - SAML
        - INVITE
        - NATIVE_APP_API_INTEGRATION
        - DEVICE_SIGNATURE
        - CLOUD_CONNECTOR
        - SYSTEM_ACCOUNT
        - USER_ENROLLMENT
        - CLIENT_CREDENTIALS
        - OIDC
        - M2M
      example: JSS
      type: string
    Authorization:
      properties:
        account:
          $ref: '#/components/schemas/AuthAccount'
        accountGroups:
          items:
            $ref: '#/components/schemas/AccountGroup'
          type: array
        authenticationType:
          $ref: '#/components/schemas/AuthenticationType'
        sites:
          items:
            $ref: '#/components/schemas/Site'
          type: array
      type: object
    AuthorizationV1:
      properties:
        account:
          $ref: '#/components/schemas/AuthAccountV1'
        accountGroups:
          items:
            $ref: '#/components/schemas/AccountGroup'
          type: array
        authenticationType:
          $ref: '#/components/schemas/AuthenticationType'
        sites:
          items:
            $ref: _MonolithLibrary.yaml#/components/schemas/V1SiteBase
          type: array
      type: object
    CurrentAccount:
      properties:
        accessLevel:
          enum:
            - FullAccess
            - SiteAccess
            - GroupBasedAccess
          example: FullAccess
          type: string
        currentSiteId:
          example: 1
          type: integer
        email:
          example: ITBob@Jamf.com
          type: string
        groupIds:
          example:
            - 1
            - 3
          items:
            type: integer
          type: array
        id:
          example: 1
          minimum: 1
          type: integer
        isMultiSiteAdmin:
          example: true
          type: boolean
        preferences:
          $ref: '#/components/schemas/AccountPreferences'
        privilegeSet:
          enum:
            - ADMINISTRATOR
            - AUDITOR
            - ENROLLMENT
            - CUSTOM
          example: CUSTOM
          type: string
        privileges:
          example:
            - Read SSO Settings
            - Delete eBooks
          items:
            type: string
          type: array
        realName:
          example: IT Bob
          type: string
        username:
          example: admin
          type: string
      type: object
    CurrentAuthorization:
      properties:
        account:
          $ref: '#/components/schemas/CurrentAccount'
        authenticationType:
          $ref: '#/components/schemas/AuthenticationType'
        sites:
          items:
            $ref: '#/components/schemas/Site'
          type: array
      type: object
    OAuthTokenEndpointErrorResponse:
      properties:
        error:
          example: invalid_client
          type: string
        error_description:
          example: 'OAuth 2.0 Parameter: grant_type'
          type: string
        error_uri:
          example: https://datatracker.ietf.org/doc/html/rfc6749#section-5.2
          type: string
      required:
        - error
      type: object
    OAuthTokenRequest:
      properties:
        client_id:
          description: Client ID from your API Client
          example: 1979ca82-1337-c0de-1012-82a008a3bf70
          type: string
        client_secret:
          description: Client secret from your API Client
          example: -j1o7Ery2fQG9IrBsUoTjN-AdcgFvj9zgXpSN_JdNjR6jYzTrU-K1ngshmzo3RuG
          format: password
          type: string
          writeOnly: true
        grant_type:
          description: OAuth2 grant type. For Jamf Pro API Clients, use `client_credentials`
          example: client_credentials
          type: string
        scope:
          description: "Optional. Provide a space-delimited list of roles that are within the configuration for \nthis API Client. Omitting this field will grant an access token that includes all of this client's \nallowed roles. Specifying a subset of them will limit the privileges for this access token to\nthat subset of roles. Specifying a role that is not assigned to this client will result in \nan `invalid_scope` error. The format matches what is returned from the OAuth token\nendpoint response's `scope` field.\n"
          example: api-role:1 api-role:2
          type: string
      required:
        - client_id
        - client_secret
        - grant_type
      type: object
    OAuthTokenResponse:
      properties:
        access_token:
          example: eyJhbGciOiJIUzI1NiJ9.RXJpayBTYXRpZSBzYWlkIHlvdSBoYWQgdG8gcGxhbiBWZXhhdGlvbnMgODQwIHRpbWVzIGluIGEgcm93Li4uZG8geW91IHRoaW5rIGhlIHJlYWxseSBtZWFudCBpdD8.bGlF3raOEwNgcbV52yVJClNixVlwrJy2RECVFrH_GQg
          type: string
        expires_in:
          description: Seconds until this access token is expired. This will reflect the `accessTokenLifetimeSeconds` value configured on your API Client.
          example: 60
          type: integer
        scope:
          description: Space-delimited list of API Roles, formatted and identified by ID like `api-role:{apiRoleId}`.
          example: api-role:1 api-role:2
          type: string
        token_type:
          example: Bearer
          type: string
      required:
        - access_token
        - expires_in
        - scope
        - token_type
      type: object
    Site:
      properties:
        id:
          example: 1
          type: integer
        name:
          example: Eau Claire
          type: string
      type: object
info:
  title: Jamf Pro API - Authentication
  version: 0.0.1
openapi: 3.0.1
paths:
  /auth:
    get:
      deprecated: true
      description: Get all the authorization details associated with the current api token
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Authorization'
          description: Current authorization details.
      security:
        - Bearer: []
      summary: |
        Get all the Authorization details associated with the current api
      tags:
        - api-authentication
      x-authentication-required: true
      x-deprecation-date: "2020-06-01"
  /auth/current:
    post:
      deprecated: true
      description: Get the authorization details associated with the current API token for the users current site
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CurrentAuthorization'
          description: Authorization details for users current site.
      security:
        - Bearer: []
      summary: |
        Get the authorization details associated with the current API token
      tags:
        - api-authentication
      x-action: true
      x-authentication-required: true
      x-deprecation-date: "2020-06-01"
  /auth/invalidateToken:
    post:
      deprecated: true
      description: Invalidates current token
      responses:
        204:
          description: token invalidated
      security:
        - Bearer: []
      summary: |
        Invalidate current token
      tags:
        - api-authentication
      x-action: true
      x-authentication-required: true
      x-deprecation-date: "2020-06-01"
  /auth/keepAlive:
    post:
      deprecated: true
      description: Invalidates existing token and generates new token with extended expiration based on existing token credentials.
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthToken'
          description: Updated token.
      security:
        - Bearer: []
      summary: |
        Invalidate existing token and generates new token
      tags:
        - api-authentication
      x-action: true
      x-authentication-required: true
      x-deprecation-date: "2020-06-01"
  /v1/auth:
    get:
      description: Get all the authorization details associated with the current api token
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthorizationV1'
          description: Current authorization details.
      security:
        - Bearer: []
      summary: |
        Get all the Authorization details associated with the current api
      tags:
        - api-authentication
      x-authentication-required: true
  /v1/auth/invalidate-token:
    post:
      description: Invalidates current token
      responses:
        204:
          description: token invalidated
      security:
        - Bearer: []
      summary: |
        Invalidate current token
      tags:
        - api-authentication
      x-action: true
      x-authentication-required: true
  /v1/auth/keep-alive:
    post:
      description: Invalidates existing token and generates new token with extended expiration based on existing token credentials.
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthTokenV1'
          description: Updated token.
      security:
        - Bearer: []
      summary: |
        Invalidate existing token and generates new token
      tags:
        - api-authentication
      x-action: true
      x-authentication-required: true
  /v1/auth/token:
    post:
      description: |
        Create a token based on other authentication details (basic, etc.).
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthTokenV1'
          description: New auth token generated.
        401:
          content:
            application/json:
              schema:
                $ref: _MonolithLibrary.yaml#/components/schemas/ApiError
          description: Authentication failed. If the admin has forced the user to change their password before next user login, or the non-SSO account's password has expired, an ApiError with USER_EXPIRED_PASSWORD will be returned.
      security:
        - BasicAuth: []
      summary: Create a token based on other authentication details (basic, etc.)
      tags:
        - api-authentication
      x-action: true
      x-authentication-required: false
  /v1/oauth/token:
    post:
      description: Obtain an access token using the OAuth2 client credentials flow
      operationId: postOAuthToken
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/OAuthTokenRequest'
        description: Client credential token request
        required: true
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OAuthTokenResponse'
          description: OAuth2 token obtained successfully
        400:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OAuthTokenEndpointErrorResponse'
          description: |
            Bad request. These differ from standard Jamf Pro API error response for better compatability
            with a wide variety of standard clients. See https://datatracker.ietf.org/doc/html/rfc6749#section-5.2
            for additional details.
      summary: Obtain an access token using an API Client
      tags:
        - api-authentication
      x-action: true
      x-authentication-required: false
servers:
  - url: /api
