openapi: 3.0.1
info:
  title: Jamf Pro API - buildings
  version: 0.0.1
paths:
  /v1/buildings:
    get:
      tags:
      - buildings
      summary: |
         Search for sorted and paged Buildings
      description: Search for sorted and paged buildings
      parameters:
      - $ref: 'DefinitionsLibrary.yaml#/components/parameters/page'
      - $ref: 'DefinitionsLibrary.yaml#/components/parameters/page-size'
      - name: sort
        in: query
        description: 'Sorting criteria in the format: property:asc/desc. Default sort
          is id:asc. Multiple sort criteria are supported and must be separated with
          a comma. Example: sort=date:desc,name:asc '
        explode: true
        schema:
          type: array
          items:
            type: string
          default: [id:asc]
      - name: filter
        in: query
        description: 'Query in the RSQL format, allowing to filter buildings collection.
                      Default filter is empty query - returning all results for the requested page.
                      Fields allowed in the query: name, streetAddress1, streetAddress2, city, stateProvince, zipPostalCode, country.
                      This param can be combined with paging and sorting.
                      Example: filter=city=="Chicago" and name=="*build*"'
        schema:
          type: string
          default: ''
      responses:
        200:
          description: Successful response
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/BuildingSearchResults'
      x-required-privileges:
      - Read Buildings
    post:
      tags:
      - buildings
      summary: |
        Create Building record
      description: |
        Create building record
      requestBody:
        description: building object to create. ids defined in this body will be ignored
        content:
          'application/json':
            schema:
              $ref: '#/components/schemas/Building'
        required: true
      responses:
        201:
          description: Building record was created
          content:
            'application/json':
              schema:
                $ref: 'DefinitionsLibrary.yaml#/components/schemas/HrefResponse'
      x-required-privileges:
      - Create Buildings
  /v1/buildings/{id}:
    get:
      tags:
      - buildings
      summary: |
        Get specified Building object
      description: |
        Gets specified Building object
      parameters:
      - name: id
        in: path
        description: instance id of building record
        required: true
        schema:
          type: string
      responses:
        200:
          description: Details of building were found
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/Building'
        404:
          description: Specified building object does not exist.
          content:
            'application/json':
              schema:
                $ref: 'DefinitionsLibrary.yaml#/components/schemas/ApiError'
      x-required-privileges:
      - Read Buildings
    put:
      tags:
      - buildings
      summary: |
        Update specified Building object
      description: |
        Update specified building object
      parameters:
      - name: id
        in: path
        description: instance id of building record
        required: true
        schema:
          type: string
      requestBody:
        description: building object to update. ids defined in this body will be ignored
        content:
          'application/json':
            schema:
              $ref: '#/components/schemas/Building'
        required: true
      responses:
        200:
          description: Building update
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/Building'
      x-required-privileges:
      - Update Buildings
    delete:
      tags:
      - buildings
      summary: |
        Remove specified Building record
      description: |
        Removes specified building record
      parameters:
      - name: id
        in: path
        description: instance id of building record
        required: true
        schema:
          type: string
      responses:
        204:
          description: Building record was deleted
      x-required-privileges:
      - Delete Buildings
  /v1/buildings/delete-multiple:
    post:
      tags:
        - buildings
      summary: |
        Delete multiple Buildings by their ids
      description: multiple many Buildings by their ids
      requestBody:
        description: ids of the building to be deleted
        content:
          'application/json':
            schema:
              $ref: 'DefinitionsLibrary.yaml#/components/schemas/Ids'
        required: true
      responses:
        204:
          description: All building ids passed in request sucessfully deleted.
        400:
          description: 'Request processed.  Returns ids and error codes of any buildings
                unable to be deleted.  Expected error codes: INVALID_ID - id does not
                exist SYSTEM_EXCEPTION - a system exception occurred trying to delete
                the building.'
          content:
            'application/json':
              schema:
                $ref: 'DefinitionsLibrary.yaml#/components/schemas/ApiError'
      x-required-privileges:
        - Delete Buildings
      x-action: true
  /v1/buildings/{id}/history:
    get:
      tags:
      - buildings
      summary: |
        Get specified Building History object
      description: |
        Gets specified Building history object
      parameters:
      - name: id
        in: path
        description: instance id of building history record
        required: true
        schema:
          type: string
      - $ref: 'DefinitionsLibrary.yaml#/components/parameters/page'
      - $ref: 'DefinitionsLibrary.yaml#/components/parameters/page-size'
      - name: sort
        in: query
        description: 'Sorting criteria in the format: property:asc/desc. Default sort
          is date:desc. Multiple sort criteria are supported and must be separated
          with a comma. Example: sort=date:desc,name:asc '
        explode: true
        schema:
          type: array
          items:
            type: string
          default: [date:desc]
      - name: filter
        in: query
        description: 'Query in the RSQL format, allowing to filter history notes collection.
          Default filter is empty query - returning all results for the requested page.
          Fields allowed in the query: username, date, note, details.
          This param can be combined with paging and sorting.
          Example: filter=username!=admin and details==*disabled* and date<2019-12-15'
        schema:
          type: string
          default: ''
      responses:
        200:
          description: Details of building history were found
          content:
            'application/json':
              schema:
                $ref: 'DefinitionsLibrary.yaml#/components/schemas/HistorySearchResults'
        404:
          description: Specified building object does not exist.
          content:
            'application/json':
              schema:
                $ref: 'DefinitionsLibrary.yaml#/components/schemas/ApiError'
      x-required-privileges:
      - Read Buildings
    post:
      tags:
      - buildings
      summary: |
        Add specified Building history object notes
      description: |
        Adds specified Building history object notes
      parameters:
      - name: id
        in: path
        description: instance id of building history record
        required: true
        schema:
          type: string
      requestBody:
        description: history notes to create
        content:
          'application/json':
            schema:
              $ref: 'DefinitionsLibrary.yaml#/components/schemas/ObjectHistoryNote'
        required: true
      responses:
        201:
          description: Notes of building history were added
          content:
            'application/json':
              schema:
                $ref: 'DefinitionsLibrary.yaml#/components/schemas/ObjectHistory'
        404:
          description: Specified building object does not exist.
          content:
            'application/json':
              schema:
                $ref: 'DefinitionsLibrary.yaml#/components/schemas/ApiError'
        503:
          description: Building history can not be saved
          content:
            'application/json':
              schema:
                $ref: 'DefinitionsLibrary.yaml#/components/schemas/ApiError'
      x-required-privileges:
      - Update Buildings
  /v1/buildings/{id}/history/export:
    post:
      tags:
        - buildings
      summary: |
        Export history object collection in specified format for specified Buildings
      description: |
        Export history object collection in specified format for specified Buildings
      parameters:
        - $ref: 'DefinitionsLibrary.yaml#/components/parameters/export-fields'
        - $ref: 'DefinitionsLibrary.yaml#/components/parameters/export-labels'
        - name: id
          in: path
          description: instance id of buildings
          required: true
          schema:
            type: string
        - $ref: 'DefinitionsLibrary.yaml#/components/parameters/page'
        - $ref: 'DefinitionsLibrary.yaml#/components/parameters/page-size'
        - name: sort
          in: query
          description: 'Sorting criteria in the format: property:asc/desc. Default sort
             is date:desc. Multiple sort criteria are supported and must be separated
             with a comma. Example: sort=date:desc,name:asc '
          explode: true
          schema:
            type: array
            items:
              type: string
            default: [ date:desc ]
        - name: filter
          in: query
          description: 'Query in the RSQL format, allowing to filter history notes collection.
             Default filter is empty query - returning all results for the requested page.
             Fields allowed in the query: username, date, note, details.
             This param can be combined with paging and sorting.
             Example: filter=username!=admin and details==*disabled* and date<2019-12-15'
          schema:
            type: string
            default: ''
      requestBody:
        description: Optional. Override query parameters since they can make URI exceed 2,000 character limit.
        content:
          'application/json':
            schema:
              $ref: 'DefinitionsLibrary.yaml#/components/schemas/ExportParameters'
        required: false
      responses:
        200:
          description: Export successful
          content:
            text/csv:
              schema:
                format: binary
                example: |
                  id,username,date,note,details
                  1,admin,2019-02-04 21:09:31,Buildings update,Some details
        400:
          description: Export fields specified incorrectly - non-existing column or duplicate on the list.
          content:
            application/json:
              schema:
                $ref: 'DefinitionsLibrary.yaml#/components/schemas/ApiError'
        503:
          description: Export currently unavailable, all export-related resources are in use. Try again later.
          content:
            application/json:
              schema:
                $ref: 'DefinitionsLibrary.yaml#/components/schemas/ApiError'
      x-required-privileges:
        - Read Buildings
      x-action: true
  /v1/buildings/export:
    post:
      tags:
        - buildings
      summary: |
        Export Buildings collection
      description: |
        Export Buildings collection
      parameters:
        - $ref: 'DefinitionsLibrary.yaml#/components/parameters/export-fields'
        - $ref: 'DefinitionsLibrary.yaml#/components/parameters/export-labels'
        - $ref: 'DefinitionsLibrary.yaml#/components/parameters/page'
        - $ref: 'DefinitionsLibrary.yaml#/components/parameters/page-size'
        - name: sort
          in: query
          description: 'Sorting criteria in the format: property:asc/desc. Default sort
              is id:desc. Multiple sort criteria are supported and must be separated
              with a comma. Example: sort=id:desc,name:asc '
          explode: true
          schema:
            type: array
            items:
              type: string
            default: [ id:asc ]
        - name: filter
          in: query
          description: 'Query in the RSQL format, allowing to filter history notes collection.
              Default filter is empty query - returning all results for the requested page.
              Fields allowed in the query: id, name.
              This param can be combined with paging and sorting.
              Example: name=="*buildings*"'
          schema:
            type: string
            default: ''
      requestBody:
        description: Optional. Override query parameters since they can make URI exceed 2,000 character limit.
        content:
          'application/json':
            schema:
              $ref: 'DefinitionsLibrary.yaml#/components/schemas/ExportParameters'
        required: false
      responses:
        200:
          description: Export successful
          content:
            text/csv:
              schema:
                format: binary
                example: |
                  id,name
                  1,Marketing
                  2,Accounting
        400:
          description: Export fields specified incorrectly - non-existing column or duplicate on the list.
          content:
            application/json:
              schema:
                $ref: 'DefinitionsLibrary.yaml#/components/schemas/ApiError'
        503:
          description: Export currently unavailable, all export-related resources are in use. Try again later.
          content:
            application/json:
              schema:
                $ref: 'DefinitionsLibrary.yaml#/components/schemas/ApiError'
      x-required-privileges:
        - Read Buildings
      x-action: true
components:
  schemas:
    Building:
      required:
      - name
      type: object
      properties:
        id:
          type: string
          example: 1
          readOnly: true
        name:
          type: string
          example: Apple Park
        streetAddress1:
          type: string
          nullable: true
          example: The McIntosh Tree
        streetAddress2:
          type: string
          nullable: true
          example: One Apple Park Way
        city:
          type: string
          nullable: true
          example: Cupertino
        stateProvince:
          type: string
          nullable: true
          example: California
        zipPostalCode:
          type: string
          nullable: true
          example: 95014
        country:
          type: string
          nullable: true
          example: The United States of America
    BuildingSearchResults:
      type: object
      properties:
        totalCount:
          minimum: 0
          type: integer
          example: 3
        results:
          type: array
          items:
            $ref: '#/components/schemas/Building'
