components:
  schemas:
    CacheSettings:
      properties:
        cacheType:
          example: ehcache
          type: string
        cacheUniqueId:
          description: The default is for Jamf Pro to generate a UUID, so we can only give an example instead.
          example: 24864549-94ea-4cc1-bb80-d7fb392c6556
          type: string
        directoryTimeToLiveSeconds:
          example: 120
          format: int32
          type: integer
        ehcacheMaxBytesLocalHeap:
          default: "null"
          type: string
        elasticache:
          default: false
          type: boolean
        id:
          default: "0"
          minLength: 1
          readOnly: true
          type: string
        memcachedEndpoints:
          example: []
          items:
            $ref: '#/components/schemas/MemcachedEndpoints'
          type: array
        name:
          default: cache configuration
          type: string
        timeToIdleSeconds:
          example: 120
          format: int32
          type: integer
        timeToLiveSeconds:
          example: 120
          format: int32
          type: integer
      required:
        - cacheType
        - cacheUniqueId
        - memcachedEndpoints
        - timeToLiveSeconds
      type: object
    MemcachedEndpoints:
      properties:
        enabled:
          example: true
          type: boolean
        hostName:
          example: https://memcache.jamf.com
          type: string
        id:
          example: "1"
          minLength: 1
          readOnly: true
          type: string
        jssCacheConfigurationId:
          example: 1
          type: integer
        name:
          example: Jamf Fake Example Memcache
          type: string
        port:
          example: 9001
          type: integer
      type: object
info:
  title: Jamf Pro API - Cache
  version: 0.0.1
openapi: 3.0.1
paths:
  /v1/cache-settings:
    get:
      description: gets cache settings
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CacheSettings'
          description: cache settings
      summary: |
        Get Cache Settings
      tags:
        - cache-settings
      x-required-privileges:
        - Read Cache
    put:
      description: |
        updates cache settings
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CacheSettings'
        required: true
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CacheSettings'
          description: cache has been updated
        403:
          content:
            application/json:
              schema:
                $ref: _MonolithLibrary.yaml#/components/schemas/ApiError
          description: |
            The following code is returned by this call:
            HOSTED_ENVIRONMENT - PUT command is not available in hosted environments.
      summary: |
        Update Cache Settings
      tags:
        - cache-settings
      x-required-privileges:
        - Update Cache
servers:
  - url: /api
