components:
  schemas:
    CategoriesSearchResults:
      properties:
        results:
          items:
            $ref: '#/components/schemas/Category'
          minItems: 0
          type: array
        totalCount:
          example: 3
          minimum: 0
          type: integer
      type: object
    Category:
      properties:
        id:
          example: "1"
          minLength: 1
          readOnly: true
          type: string
        name:
          example: The Best
          type: string
        priority:
          example: 9
          format: int32
          type: integer
      required:
        - name
        - priority
      type: object
info:
  title: Jamf Pro API - Category
  version: 0.0.1
openapi: 3.0.1
paths:
  /v1/categories:
    get:
      description: |
        Gets `Category` objects.
      parameters:
        - $ref: _MonolithLibrary.yaml#/components/parameters/page
        - $ref: _MonolithLibrary.yaml#/components/parameters/page-size
        - description: 'Sorting criteria in the format: property:asc/desc. Default sort is id:asc. Multiple sort criteria are supported and must be separated with a comma. Example: sort=date:desc,name:asc '
          explode: true
          in: query
          name: sort
          required: false
          schema:
            default:
              - id:asc
            items:
              type: string
            type: array
          style: form
        - description: 'Query in the RSQL format, allowing to filter categories collection. Default filter is empty query - returning all results for the requested page. Fields allowed in the query: name, priority. This param can be combined with paging and sorting. Example: filter=name=="Apps*" and priority>=5'
          explode: true
          in: query
          name: filter
          required: false
          schema:
            default: ""
            type: string
          style: form
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CategoriesSearchResults'
          description: Successful response
      summary: |
        Get Category objects
      tags:
        - categories
      x-required-privileges:
        - Read Categories
        - Read Self Service
    post:
      description: |
        Create category record
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Category'
        description: category object to create. IDs defined in this body will be ignored
        required: true
      responses:
        201:
          content:
            application/json:
              schema:
                $ref: _MonolithLibrary.yaml#/components/schemas/HrefResponse
          description: Category record was created
      summary: |
        Create Category record
      tags:
        - categories
      x-required-privileges:
        - Create Categories
  /v1/categories/delete-multiple:
    post:
      description: Delete multiple Categories by their IDs
      requestBody:
        content:
          application/json:
            schema:
              $ref: _MonolithLibrary.yaml#/components/schemas/Ids
        description: IDs of the categories to be deleted
        required: true
      responses:
        204:
          description: All Category IDs passed in request sucessfully deleted.
        400:
          content:
            application/json:
              schema:
                $ref: _MonolithLibrary.yaml#/components/schemas/ApiError
          description: 'Request processed.  Returns IDs and error codes of any categories unable to be deleted.  Expected error codes: INVALID_ID - id does not exist SYSTEM_EXCEPTION - a system exception occurred trying to delete the category.'
      summary: |
        Delete multiple Categories by their IDs
      tags:
        - categories
      x-action: true
      x-required-privileges:
        - Delete Categories
  /v1/categories/{id}:
    delete:
      description: |
        Removes specified category record
      parameters:
        - description: instance id of category record
          explode: false
          in: path
          name: id
          required: true
          schema:
            type: string
          style: simple
      responses:
        204:
          description: Category record was deleted
      summary: |
        Remove specified Category record
      tags:
        - categories
      x-required-privileges:
        - Delete Categories
    get:
      description: |
        Gets specified Category object
      parameters:
        - description: instance id of category record
          explode: false
          in: path
          name: id
          required: true
          schema:
            type: string
          style: simple
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Category'
          description: Details of category were found
        404:
          content:
            application/json:
              schema:
                $ref: _MonolithLibrary.yaml#/components/schemas/ApiError
          description: Specified category object does not exist.
      summary: |
        Get specified Category object
      tags:
        - categories
      x-required-privileges:
        - Read Categories
    put:
      description: |
        Update specified category object
      parameters:
        - description: instance id of category record
          explode: false
          in: path
          name: id
          required: true
          schema:
            type: string
          style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Category'
        description: category object to create. id defined in this body will be ignored
        required: true
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Category'
          description: Category record was updated
      summary: |
        Update specified Category object
      tags:
        - categories
      x-required-privileges:
        - Update Categories
  /v1/categories/{id}/history:
    get:
      description: |
        Gets specified Category history object
      parameters:
        - description: instance id of category history record
          explode: false
          in: path
          name: id
          required: true
          schema:
            type: string
          style: simple
        - $ref: _MonolithLibrary.yaml#/components/parameters/page
        - $ref: _MonolithLibrary.yaml#/components/parameters/page-size
        - description: 'Sorting criteria in the format: property:asc/desc. Default sort is id:asc. Multiple sort criteria are supported and must be separated with a comma. Example: sort=date:desc,name:asc '
          explode: true
          in: query
          name: sort
          required: false
          schema:
            default:
              - date:desc
            items:
              type: string
            type: array
          style: form
        - description: 'Query in the RSQL format, allowing to filter history notes collection. Default filter is empty query - returning all results for the requested page. Fields allowed in the query: username, date, note, details. This param can be combined with paging and sorting. Example: filter=username!=admin and details==*disabled* and date<2019-12-15'
          explode: true
          in: query
          name: filter
          required: false
          schema:
            default: ""
            type: string
          style: form
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: _MonolithLibrary.yaml#/components/schemas/HistorySearchResults
          description: Details of category history were found
        404:
          content:
            application/json:
              schema:
                $ref: _MonolithLibrary.yaml#/components/schemas/ApiError
          description: Specified category object does not exist.
      summary: |
        Get specified Category history object
      tags:
        - categories
      x-required-privileges:
        - Read Categories
    post:
      description: |
        Adds specified Category history object notes
      parameters:
        - description: instance id of category history record
          explode: false
          in: path
          name: id
          required: true
          schema:
            type: string
          style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: _MonolithLibrary.yaml#/components/schemas/ObjectHistoryNote
        description: history notes to create
        required: true
      responses:
        201:
          content:
            application/json:
              schema:
                $ref: _MonolithLibrary.yaml#/components/schemas/ObjectHistory
          description: Notes of category history were added
        404:
          content:
            application/json:
              schema:
                $ref: _MonolithLibrary.yaml#/components/schemas/ApiError
          description: Specified category object does not exist.
        503:
          content:
            application/json:
              schema:
                $ref: _MonolithLibrary.yaml#/components/schemas/ApiError
          description: Category history can not be saved
      summary: |
        Add specified Category history object notes
      tags:
        - categories
      x-required-privileges:
        - Update Categories
servers:
  - url: /api
