components:
  schemas:
    CertificateRecord:
      properties:
        issuerX500Principal:
          example: CN=Jamf JSS Built-in Certificate Authority
          type: string
        keyUsage:
          example:
            - digitalSignature
            - keyEncipherment
            - keyCertSign
            - cRLSign
          items:
            type: string
          type: array
        keyUsageExtended:
          example:
            - 1.3.6.1.5.5.7.3.1
          items:
            type: string
          type: array
        notAfter:
          example: 1927739379
          type: integer
        notBefore:
          example: 1612120179
          type: integer
        serialNumber:
          example: 00bc43bea0
          type: string
        sha1Fingerprint:
          example: 448a7cc4d899d6a1821258133c24c023a5f558d9
          type: string
        sha256Fingerprint:
          example: 660958e14891c67491822687d9ac0e3574562664458111ad875b680995ca472b
          type: string
        signature:
          $ref: '#/components/schemas/Signature'
        subjectX500Principal:
          example: CN=Jamf JSS Built-in Certificate Authority
          type: string
        version:
          example: 3
          type: integer
      type: object
    Signature:
      properties:
        algorithm:
          example: SHA256withRSA
          type: string
        algorithmOid:
          example: 1.2.840.113549.1.1.11
          type: string
        value:
          example: 6874f9b8c60a46c25b6b270c14b9a2949c87b25524868394309b20349f95edd624588ada274e5678a921199d26d0fe5b231fc794eb6e020b7a6c4790cf91ec5d9a5bd4da126f141a657cf4af78df6303327964c57721d82b85af1d46379ac7ec45a24ae3418576688f05fd075a1c9c3d137d0fd8831f4c88ce7698af9c747db983a40fb0480ebfb293bf4889e34a949d4a53251b1abef19d895bcea8e0ce590b22244ad1623624319e6a8b7e7d11aea3d94b77be1a94d28fda58e8df2e398c45e2e9c13473dcc81db01acac8f2c6d21cb5c44371c9ebfba632dcb46838a91808d4e82a35500f370dc71f4156528fbce93137c94eb33d83d41d49483d4dcca5e1
          type: string
      type: object
info:
  title: Jamf Pro API - CertificateAuthority
  version: 0.0.1
openapi: 3.0.1
paths:
  /v1/pki/certificate-authority/active:
    get:
      description: Returns X.509 details of the active Certificate Authority (CA)
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CertificateRecord'
          description: Successful response displays the details of the active Certificate Authority (CA)
      summary: Returns X.509 details of the active Certificate Authority (CA)
      tags:
        - certificate-authority
      x-authentication-required: false
  /v1/pki/certificate-authority/active/der:
    get:
      description: Returns X.509 of active Certificate Authority (CA) in DER format
      responses:
        200:
          content:
            application/pkix-cert:
              schema:
                format: binary
                type: string
          description: Successful response returns certificate in DER format
      summary: Returns X.509 of active Certificate Authority (CA) in DER format
      tags:
        - certificate-authority
      x-authentication-required: false
  /v1/pki/certificate-authority/active/pem:
    get:
      description: Returns active Certificate Authority (CA) in PEM format
      responses:
        200:
          content:
            application/pem-certificate-chain:
              schema:
                format: binary
                type: string
          description: Successful response returns certificate in PEM format.
      summary: Returns active Certificate Authority (CA) in PEM format
      tags:
        - certificate-authority
      x-authentication-required: false
  /v1/pki/certificate-authority/{id}:
    get:
      description: Returns X.509 details of Certificate Authority (CA) with provided ID
      parameters:
        - description: UUID of the Certificate Authority (CA)
          explode: false
          in: path
          name: id
          required: true
          schema:
            type: string
          style: simple
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CertificateRecord'
          description: Successful response displays the details of the Certificate Authority (CA) with provided ID
        400:
          content:
            application/json:
              schema:
                $ref: _MonolithLibrary.yaml#/components/schemas/ApiError
          description: Invalid ID parameter
        404:
          content:
            application/json:
              schema:
                $ref: _MonolithLibrary.yaml#/components/schemas/ApiError
          description: Certificate with that ID does not exist
      summary: Returns X.509 details of Certificate Authority (CA) with provided ID
      tags:
        - certificate-authority
      x-required-privileges:
        - Read PKI
  /v1/pki/certificate-authority/{id}/der:
    get:
      description: Returns X.509 current Certificate Authority (CA) with provided ID in DER format
      parameters:
        - description: UUID of the Certificate Authority (CA)
          explode: false
          in: path
          name: id
          required: true
          schema:
            type: string
          style: simple
      responses:
        200:
          content:
            application/pkix-cert:
              schema:
                format: binary
                type: string
          description: Successful response returns certificate in DER format
        400:
          content:
            application/json:
              schema:
                $ref: _MonolithLibrary.yaml#/components/schemas/ApiError
          description: Invalid ID parameter
        404:
          content:
            application/json:
              schema:
                $ref: _MonolithLibrary.yaml#/components/schemas/ApiError
          description: Certificate with that ID does not exist
      summary: Returns X.509 current Certificate Authority (CA) with provided ID in DER format
      tags:
        - certificate-authority
      x-required-privileges:
        - Read PKI
  /v1/pki/certificate-authority/{id}/pem:
    get:
      description: Returns current Certificate Authority (CA) with provided ID in PEM format
      parameters:
        - description: UUID of the Certificate Authority (CA)
          explode: false
          in: path
          name: id
          required: true
          schema:
            type: string
          style: simple
      responses:
        200:
          content:
            application/pem-certificate-chain:
              schema:
                format: binary
                type: string
          description: Successful response returns certificate in PEM format
        400:
          content:
            application/json:
              schema:
                $ref: _MonolithLibrary.yaml#/components/schemas/ApiError
          description: Invalid ID parameter
        404:
          content:
            application/json:
              schema:
                $ref: _MonolithLibrary.yaml#/components/schemas/ApiError
          description: Certificate with that ID does not exist
      summary: Returns current Certificate Authority (CA) with provided ID in PEM format
      tags:
        - certificate-authority
      x-required-privileges:
        - Read PKI
servers:
  - url: /api
