openapi: 3.0.1
info:
    title: Jamf Pro API - Change Password
    version: 0.0.1
paths:
    /v1/user/change-password:
        post:
            tags:
                - user
            summary: |
                Changes the user account password.
            description: |
                Changes the account password for a currently authenticated user.
            requestBody:
                description: Current account password and new password.
                content:
                    'application/json':
                        schema:
                            $ref: '#/components/schemas/ChangePassword'
                required: true
            responses:
                202:
                    description: Password for user successfully changed.
                400:
                    description: Bad Request
                    content:
                        'application/json':
                            schema:
                                $ref: 'DefinitionsLibrary.yaml#/components/schemas/ApiError'
                429:
                    description: Rate limit exceeded
            x-required-privileges:
                - Change Password
            x-authentication-required: true
            x-action: true
            x-rate-limit: true
components:
    schemas:
        ChangePassword:
            required:
                - currentPassword
                - newPassword
            type: object
            properties:
                currentPassword:
                    type: string
                    format: password
                    writeOnly: true
                    example: oldPassword
                    nullable: false
                newPassword:
                    type: string
                    format: password
                    writeOnly: true
                    example: updatedPassword
                    nullable: false

