components:
  schemas:
    ChangePassword:
      properties:
        currentPassword:
          example: oldPassword
          format: password
          nullable: false
          type: string
          writeOnly: true
        newPassword:
          example: updatedPassword
          format: password
          nullable: false
          type: string
          writeOnly: true
      required:
        - currentPassword
        - newPassword
      type: object
info:
  title: Jamf Pro API - ChangePassword
  version: 0.0.1
openapi: 3.0.1
paths:
  /v1/user/change-password:
    post:
      description: |
        Changes the account password for a currently authenticated user.
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ChangePassword'
        description: Current account password and new password.
        required: true
      responses:
        202:
          description: Password for user successfully changed.
        400:
          content:
            application/json:
              schema:
                $ref: _MonolithLibrary.yaml#/components/schemas/ApiError
          description: Bad Request
        429:
          description: Rate limit exceeded
      summary: |
        Changes the user account password.
      tags:
        - user
      x-action: true
      x-authentication-required: true
      x-rate-limit: true
      x-required-privileges:
        - Change Password
servers:
  - url: /api
