info:
  title: Jamf Pro API - CloudAzureDefaults
  version: 0.0.1
openapi: 3.0.1
paths:
  /v1/cloud-azure/defaults/mappings:
    get:
      deprecated: true
      description: This is the default set of attributes that allows you to return the data you need from Azure AD. Some fields may be empty and may be edited when creating a new configuration.
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: _MonolithLibrary.yaml#/components/schemas/AzureMappings
          description: Default mappings returned.
        400:
          content:
            application/json:
              schema:
                $ref: _MonolithLibrary.yaml#/components/schemas/ApiError
          description: Files cannot be loaded.
        404:
          content:
            application/json:
              schema:
                $ref: _MonolithLibrary.yaml#/components/schemas/ApiError
          description: This endpoint is not available for your environment.
      summary: Get default mappings
      tags:
        - cloud-azure
      x-deprecation-date: "2025-05-21"
      x-required-privileges:
        - Read LDAP Servers
  /v1/cloud-azure/defaults/server-configuration:
    get:
      description: This is the default set of attributes that allows you to return the data you need from Azure AD. Some fields may be empty and may be edited when creating a new configuration.
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: _MonolithLibrary.yaml#/components/schemas/AzureServerConfiguration
          description: Default server configuration returned.
        400:
          content:
            application/json:
              schema:
                $ref: _MonolithLibrary.yaml#/components/schemas/ApiError
          description: Default server configuration cannot be loaded.
        404:
          content:
            application/json:
              schema:
                $ref: _MonolithLibrary.yaml#/components/schemas/ApiError
          description: This endpoint is not available for your environment.
      summary: Get default server configuration
      tags:
        - cloud-azure
      x-required-privileges:
        - Read LDAP Servers
servers:
  - url: /api
