info:
  title: Jamf Pro API - CloudLdapDefaults
  version: 0.0.1
openapi: 3.0.1
paths:
  /v2/cloud-ldaps/defaults/{provider}/mappings:
    get:
      description: Get default mappings for Cloud Identity Provider Provider.
      parameters:
        - description: Cloud Identity Provider name
          example: google
          explode: false
          in: path
          name: provider
          required: true
          schema:
            type: string
          style: simple
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: _MonolithLibrary.yaml#/components/schemas/CloudLdapMappingsResponse
          description: Default mappings returned.
        400:
          content:
            application/json:
              schema:
                $ref: _MonolithLibrary.yaml#/components/schemas/ApiError
          description: Files cannot be loaded.
        404:
          content:
            application/json:
              schema:
                $ref: _MonolithLibrary.yaml#/components/schemas/ApiError
          description: The provider name in the URL is invalid or not supported.
      summary: Get default mappings
      tags:
        - cloud-ldap
      x-required-privileges:
        - Read LDAP Servers
  /v2/cloud-ldaps/defaults/{provider}/server-configuration:
    get:
      description: Get default server configuration for Cloud Identity Provider Identity Provider.
      parameters:
        - description: Cloud Identity Provider name
          example: google
          explode: false
          in: path
          name: provider
          required: true
          schema:
            type: string
          style: simple
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: _MonolithLibrary.yaml#/components/schemas/CloudLdapServerResponse
          description: Default server configuration returned.
        400:
          content:
            application/json:
              schema:
                $ref: _MonolithLibrary.yaml#/components/schemas/ApiError
          description: Default server configuration cannot be loaded.
        404:
          content:
            application/json:
              schema:
                $ref: _MonolithLibrary.yaml#/components/schemas/ApiError
          description: The provider name in the URL is invalid or not supported.
      summary: Get default server configuration
      tags:
        - cloud-ldap
      x-required-privileges:
        - Read LDAP Servers
servers:
  - url: /api
