openapi: 3.0.1
info:
  title: Jamf Pro API - Cloud Identity Provider
  version: 0.0.1
paths:
  /v2/cloud-ldaps:
    post:
      tags:
        - cloud-ldap
      summary: Create Cloud Identity Provider configuration
      description: Create new Cloud Identity Provider configuration with unique display
        name. If mappings not provided, then defaults will be generated instead.
      requestBody:
        description: Cloud Identity Provider configuration to create
        content:
          'application/json':
            schema:
              $ref: '#/components/schemas/LdapConfigurationRequest'
        required: true
      responses:
        201:
          description: Cloud Identity Provider configuration created
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/HrefResponse'
        400:
          description: Cloud Identity Provider configuration cannot be saved.
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/ApiError'
      x-required-privileges:
        - Create LDAP Servers
  /v2/cloud-ldaps/{id}:
    get:
      tags:
        - cloud-ldap
      summary: Get Cloud Identity Provider configuration with given id.
      description: Get Cloud Identity Provider configuration with given id.
      parameters:
        - name: id
          in: path
          description: Cloud Identity Provider identifier
          required: true
          schema:
            type: string
      responses:
        200:
          description: Cloud Identity Provider configuration returned.
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/LdapConfigurationResponse'
        400:
          description: Id can only be a number.
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/ApiError'
        404:
          description: Specified Cloud Identity Provider configuration does not exist.
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/ApiError'
      x-required-privileges:
        - Read LDAP Servers
    put:
      tags:
        - cloud-ldap
      summary: Update Cloud Identity Provider configuration
      description: Update Cloud Identity Provider configuration. Cannot be used for
        partial updates, all content body must be sent.
      parameters:
        - name: id
          in: path
          required: true
          description: Cloud Identity Provider identifier
          schema:
            type: string
      requestBody:
        description: Cloud Identity Provider configuration to update
        content:
          'application/json':
            schema:
              $ref: '#/components/schemas/LdapConfigurationUpdate'
        required: true
      responses:
        200:
          description: Cloud Identity Provider configuration updated
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/LdapConfigurationResponse'
        400:
          description: One or more parameters were invalid.
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/ApiError'
        404:
          description: Cloud Identity Provider configuration does not exist.
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/ApiError'
        409:
          description: The request URL configuration id value does not match the id value in the request body.
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/ApiError'
      x-required-privileges:
        - Update LDAP Servers
    delete:
      tags:
        - cloud-ldap
      summary: Delete Cloud Identity Provider configuration.
      description: Delete Cloud Identity Provider configuration.
      parameters:
        - name: id
          in: path
          required: true
          description: Cloud Identity Provider identifier
          schema:
            type: string
      responses:
        204:
          description: Cloud Identity Provider configuration deleted.
        400:
          description: Id can only be a number.
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/ApiError'
        404:
          description: Cloud Identity Provider configuration does not exist.
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/ApiError'
      x-required-privileges:
        - Delete LDAP Servers
components: {}
