openapi: 3.0.1
info:
  title: Jamf Pro API - Defaults for Azure Identity Provider
  version: 0.0.1
paths:
  /v1/cloud-azure/defaults/mappings:
    get:
      deprecated: true
      x-deprecation-date: 2025-05-21
      tags:
        - cloud-azure
      summary: Get default mappings
      description: This is the default set of attributes that allows you to return the data you need from Azure AD. Some fields may be empty and may be edited when creating a new configuration.
      responses:
        200:
          description: Default mappings returned.
          content:
            'application/json':
              schema:
                $ref: 'CloudLdapDefinitionsLibrary.yaml#/components/schemas/AzureMappings'
        400:
          description: Files cannot be loaded.
          content:
            'application/json':
              schema:
                $ref: 'DefinitionsLibrary.yaml#/components/schemas/ApiError'
        404:
          description: This endpoint is not available for your environment.
          content:
            'application/json':
              schema:
                $ref: 'DefinitionsLibrary.yaml#/components/schemas/ApiError'
      x-required-privileges:
        - Read LDAP Servers
  /v1/cloud-azure/defaults/server-configuration:
    get:
      tags:
        - cloud-azure
      summary: Get default server configuration
      description: This is the default set of attributes that allows you to return the data you need from Azure AD. Some fields may be empty and may be edited when creating a new configuration.
      responses:
        200:
          description: Default server configuration returned.
          content:
            'application/json':
              schema:
                $ref: 'CloudLdapDefinitionsLibrary.yaml#/components/schemas/AzureServerConfiguration'
        400:
          description: Default server configuration cannot be loaded.
          content:
            'application/json':
              schema:
                $ref: 'DefinitionsLibrary.yaml#/components/schemas/ApiError'
        404:
          description: This endpoint is not available for your environment.
          content:
            'application/json':
              schema:
                $ref: 'DefinitionsLibrary.yaml#/components/schemas/ApiError'
      x-required-privileges:
        - Read LDAP Servers
components:
  schemas: {}
