info:
  title: Jamf Pro API - CloudLdapKeyStore
  version: 0.0.1
openapi: 3.0.1
paths:
  /v1/ldap-keystore/verify:
    post:
      description: Validate keystore for Cloud Identity Provider secure connection
      requestBody:
        content:
          application/json:
            schema:
              $ref: _MonolithLibrary.yaml#/components/schemas/CloudLdapKeystoreFile
        required: true
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: _MonolithLibrary.yaml#/components/schemas/CloudLdapKeystore
          description: Keystore verified.
        400:
          content:
            application/json:
              schema:
                $ref: _MonolithLibrary.yaml#/components/schemas/ApiError
          description: One or more invalid parameters
      summary: Validate keystore for Cloud Identity Provider secure connection
      tags:
        - cloud-ldap
      x-action: true
      x-required-privileges:
        - Create LDAP Servers
servers:
  - url: /api
