openapi: 3.0.1
info:
  title: Jamf Pro API - Cloud information endpoints
  version: 1.0.0
paths:
  /v1/cloud-information:
    get:
      tags:
        - cloud-information
      summary: |
        Retrieve information related to cloud setup.
      description: |
        Retrieve information related to cloud setup.
        Retrieves information related to cloud setup. Provides details about cloud instance configuration.
      responses:
        200:
          description: Result of verification for being cloud-based instance
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CloudResponse'
      x-authentication-required: false
components:
  schemas:
    CloudResponse:
      type: object
      properties:
        cloudInstance:
          type: boolean
          example: true
          nullable: false
        rampInstance:
          type: boolean
          example: true
          nullable: false
        govCloudInstance:
          type: boolean
          example: true
          nullable: false
        managedServiceProviderInstance:
          type: boolean
          example: true
          nullable: false
          description: Information whether this instance is managed by managed service provider