info:
  title: Jamf Pro API - CloudIdPHistory
  version: 0.0.1
openapi: 3.0.1
paths:
  /v1/cloud-idp/{id}/history:
    get:
      description: Gets specified Cloud Identity Provider object history
      parameters:
        - description: Cloud Identity Provider identifier
          explode: false
          in: path
          name: id
          required: true
          schema:
            type: string
          style: simple
        - $ref: _MonolithLibrary.yaml#/components/parameters/page
        - $ref: _MonolithLibrary.yaml#/components/parameters/page-size
        - description: 'Sorting criteria in the format: property:asc/desc. Default sort is date:desc. Multiple sort criteria are supported and must be separated with a comma. Example: sort=date:desc,name:asc '
          explode: true
          in: query
          name: sort
          required: false
          schema:
            default:
              - date:desc
            items:
              type: string
            type: array
          style: form
        - description: 'Query in the RSQL format, allowing to filter history notes collection. Default filter is empty query - returning all results for the requested page. Fields allowed in the query: username, date, note, details. This param can be combined with paging and sorting. Example: filter=username!=admin and details==*disabled* and date<2019-12-15'
          explode: true
          in: query
          name: filter
          required: false
          schema:
            default: ""
            type: string
          style: form
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: _MonolithLibrary.yaml#/components/schemas/HistorySearchResults
          description: Details of Cloud Identity Provider history were found
        400:
          content:
            application/json:
              schema:
                $ref: _MonolithLibrary.yaml#/components/schemas/ApiError
          description: Id can only be a number.
        404:
          content:
            application/json:
              schema:
                $ref: _MonolithLibrary.yaml#/components/schemas/ApiError
          description: Specified Cloud Identity Provider object does not exist.
      summary: Get Cloud Identity Provider history
      tags:
        - cloud-idp
      x-required-privileges:
        - Read LDAP Servers
    post:
      description: |
        Adds specified Cloud Identity Provider object history notes
      parameters:
        - description: Cloud Identity Provider identifier
          explode: false
          in: path
          name: id
          required: true
          schema:
            type: string
          style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: _MonolithLibrary.yaml#/components/schemas/ObjectHistoryNote
        description: history notes to create
        required: true
      responses:
        201:
          content:
            application/json:
              schema:
                $ref: _MonolithLibrary.yaml#/components/schemas/ObjectHistory
          description: Notes of Cloud Identity Provider history were added
        404:
          content:
            application/json:
              schema:
                $ref: _MonolithLibrary.yaml#/components/schemas/ApiError
          description: Specified Cloud Identity Provider object does not exist.
        503:
          content:
            application/json:
              schema:
                $ref: _MonolithLibrary.yaml#/components/schemas/ApiError
          description: Notes of Cloud Identity Provider can not be saved
      summary: Add Cloud Identity Provider history note
      tags:
        - cloud-idp
      x-required-privileges:
        - Update LDAP Servers
servers:
  - url: /api
