openapi: 3.0.1
info:
  title: Jamf Pro API - smart-computer-groups
  version: 0.0.1
paths:
  /v1/computers/{id}/recalculate-smart-groups:
    post:
      tags:
      - smart-computer-groups-preview
      summary: |
        Recalculate a smart group for the given id
      description: |
        Recalculates a smart group for the given id and then
        returns the count of smart groups the computer falls into
      parameters:
      - name: id
        in: path
        description: id of computer
        required: true
        schema:
          type: integer
      responses:
        200:
          description: Successful response
          content:
            'application/json':
              schema:
                $ref: 'DefinitionsLibrary.yaml#/components/schemas/RecalculationResults'
        400:
          description: smart group not found
          content:
            'application/json':
              schema:
                $ref: 'DefinitionsLibrary.yaml#/components/schemas/ApiError'
      x-action: true
      x-required-privileges:
      - Update Smart Computer Groups
  /v1/smart-computer-groups/{id}/recalculate:
    post:
      tags:
      - smart-computer-groups-preview
      summary: |
        Recalculate the smart group for the given id
      description: |
        Recalculates the smart group for the given id and then
        returns the ids for the computers in the smart group
      parameters:
      - name: id
        in: path
        description: instance id of smart group
        required: true
        schema:
          type: integer
      responses:
        200:
          description: Successful response
          content:
            'application/json':
              schema:
                $ref: 'DefinitionsLibrary.yaml#/components/schemas/RecalculationResults'
        400:
          description: smart group not found
          content:
            'application/json':
              schema:
                $ref: 'DefinitionsLibrary.yaml#/components/schemas/ApiError'
      x-action: true
      x-required-privileges:
      - Update Smart Computer Groups
