openapi: 3.0.1
info:
  title: Jamf Pro API - computer-groups
  version: 1.0.0
paths:
  /v1/computer-groups:
    get:
      tags:
        - computer-groups
      summary: |
        Returns the list of all computer groups
      description: |
        Use it to get the list of all computer groups.
      responses:
        200:
          description: Success
          content:
            'application/json':
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ComputerGroup'
      x-required-privileges:
        - Read Smart Computer Groups
        - Read Static Computer Groups
components:
  schemas:
    ComputerGroup:
      type: object
      properties:
        id:
          type: string
          minLength: 1
          example: 1
        name:
          type: string
          example: All Managed Computers
        description:
          type: string
          example: A group containing all managed computers
        smartGroup:
          type: boolean
          example: true
