components:
  schemas:
    AppPath:
      properties:
        id:
          description: A "-1" id indicates a built-in path that cannot be deleted or modified.
          example: "1"
          type: string
        path:
          example: /Example/Path/To/App/
          type: string
      required:
        - id
        - path
      type: object
    ComputerInventoryCollectionPreferences:
      properties:
        allowChangingUserAndLocation:
          default: true
          example: true
          type: boolean
        calculateSizes:
          default: false
          example: false
          type: boolean
        collectSyncedMobileDeviceInfo:
          default: false
          example: false
          type: boolean
        collectUnmanagedCertificates:
          default: true
          example: true
          type: boolean
        includeAccounts:
          default: false
          example: true
          type: boolean
        includeFonts:
          default: false
          example: true
          readOnly: true
          type: boolean
        includeHiddenAccounts:
          default: false
          example: true
          type: boolean
        includePackages:
          default: false
          example: true
          type: boolean
        includePlugins:
          default: false
          example: true
          type: boolean
        includePrinters:
          default: false
          example: true
          type: boolean
        includeServices:
          default: false
          example: true
          type: boolean
        includeSoftwareId:
          default: false
          example: true
          type: boolean
        includeSoftwareUpdates:
          default: false
          example: true
          type: boolean
        monitorApplicationUsage:
          default: false
          example: true
          type: boolean
        monitorBeacons:
          default: false
          example: true
          type: boolean
        updateLdapInfoOnComputerInventorySubmissions:
          default: false
          example: false
          type: boolean
        useUnixUserPaths:
          default: true
          example: true
          type: boolean
      type: object
    ComputerInventoryCollectionPreferencesV2:
      properties:
        allowChangingUserAndLocation:
          default: true
          example: true
          type: boolean
        calculateSizes:
          default: false
          example: false
          type: boolean
        collectSyncedMobileDeviceInfo:
          default: false
          example: false
          type: boolean
        collectUnmanagedCertificates:
          default: true
          example: true
          type: boolean
        includeAccounts:
          default: false
          example: true
          type: boolean
        includeHiddenAccounts:
          default: false
          example: true
          type: boolean
        includePackages:
          default: false
          example: true
          type: boolean
        includePrinters:
          default: false
          example: true
          type: boolean
        includeServices:
          default: false
          example: true
          type: boolean
        includeSoftwareId:
          default: false
          example: true
          type: boolean
        includeSoftwareUpdates:
          default: false
          example: true
          type: boolean
        monitorApplicationUsage:
          default: false
          example: true
          nullable: false
          type: boolean
        monitorBeacons:
          default: false
          example: true
          type: boolean
        updateLdapInfoOnComputerInventorySubmissions:
          default: false
          example: false
          type: boolean
        useUnixUserPaths:
          default: true
          example: true
          type: boolean
      type: object
    ComputerInventoryCollectionSettings:
      properties:
        applicationPaths:
          items:
            $ref: '#/components/schemas/AppPath'
          type: array
        computerInventoryCollectionPreferences:
          $ref: '#/components/schemas/ComputerInventoryCollectionPreferences'
        fontPaths:
          items:
            $ref: '#/components/schemas/FontPath'
          readOnly: true
          type: array
        pluginPaths:
          items:
            $ref: '#/components/schemas/PluginPath'
          readOnly: true
          type: array
      type: object
    ComputerInventoryCollectionSettingsV2:
      properties:
        applicationPaths:
          items:
            $ref: '#/components/schemas/AppPath'
          nullable: false
          type: array
        computerInventoryCollectionPreferences:
          $ref: '#/components/schemas/ComputerInventoryCollectionPreferencesV2'
      type: object
    CreatePath:
      properties:
        path:
          example: /Example/Path/
          type: string
        scope:
          enum:
            - APP
            - FONT
            - PLUGIN
          example: APP
          type: string
      required:
        - path
        - scope
      type: object
    CreatePathV2:
      properties:
        path:
          example: /Example/Path/
          type: string
        scope:
          enum:
            - APP
          example: APP
          type: string
      required:
        - path
        - scope
      type: object
    FontPath:
      properties:
        id:
          description: A "-1" id indicates a built-in path that cannot be deleted or modified.
          example: "2"
          type: string
        path:
          example: /Example/Path/To/Font/
          type: string
      required:
        - id
        - path
      type: object
    PluginPath:
      properties:
        id:
          description: A "-1" id indicates a built-in path that cannot be deleted or modified.
          example: "3"
          type: string
        path:
          example: /Example/Path/To/Plugin/
          type: string
      required:
        - id
        - path
      type: object
info:
  title: Jamf Pro API - ComputerInventoryCollectionSettings
  version: 0.0.1
openapi: 3.0.1
paths:
  /v1/computer-inventory-collection-settings:
    get:
      deprecated: true
      description: Returns computer inventory settings
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ComputerInventoryCollectionSettings'
          description: Successful response returns the computer inventory settings
      summary: Returns computer inventory settings
      tags:
        - computer-inventory-collection-settings
      x-deprecation-date: "2025-06-30"
      x-required-privileges:
        - Read Computer Inventory Collection Settings
    patch:
      deprecated: true
      description: Update computer inventory settings
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ComputerInventoryCollectionSettings'
        description: Computer inventory settings to update
        required: true
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ComputerInventoryCollectionSettings'
          description: Computer inventory settings updated
      summary: Update computer inventory settings
      tags:
        - computer-inventory-collection-settings
      x-deprecation-date: "2025-06-30"
      x-required-privileges:
        - Update Computer Inventory Collection Settings
  /v1/computer-inventory-collection-settings/custom-path:
    post:
      deprecated: true
      description: Creates a custom search path to use when collecting applications, fonts, and plug-ins.
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreatePath'
        description: Computer inventory settings to update
        required: true
      responses:
        201:
          content:
            application/json:
              schema:
                $ref: _MonolithLibrary.yaml#/components/schemas/HrefResponse
          description: Custom path created
        400:
          content:
            application/json:
              schema:
                $ref: _MonolithLibrary.yaml#/components/schemas/ApiError
          description: Invalid data response
      summary: Create Computer Inventory Collection Settings Custom Path
      tags:
        - computer-inventory-collection-settings
      x-deprecation-date: "2025-06-30"
      x-required-privileges:
        - Create Custom Paths
  /v1/computer-inventory-collection-settings/custom-path/{id}:
    delete:
      deprecated: true
      description: Delete Custom Path from Computer Inventory Collection Settings
      parameters:
        - description: id of Custom Path
          explode: false
          in: path
          name: id
          required: true
          schema:
            type: string
          style: simple
      responses:
        204:
          description: Custom path deleted
        404:
          content:
            application/json:
              schema:
                $ref: _MonolithLibrary.yaml#/components/schemas/ApiError
          description: Invalid data response
      summary: Delete Custom Path from Computer Inventory Collection Settings
      tags:
        - computer-inventory-collection-settings
      x-deprecation-date: "2025-06-30"
      x-required-privileges:
        - Delete Custom Paths
  /v2/computer-inventory-collection-settings:
    get:
      description: Returns computer inventory settings
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ComputerInventoryCollectionSettingsV2'
          description: Successful response returns the computer inventory settings
      summary: Returns computer inventory settings
      tags:
        - computer-inventory-collection-settings
      x-required-privileges:
        - Read Computer Inventory Collection Settings
    patch:
      description: Update computer inventory settings
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ComputerInventoryCollectionSettingsV2'
        description: Computer inventory settings to update
        required: true
      responses:
        204:
          description: Computer inventory settings updated
      summary: Update computer inventory settings
      tags:
        - computer-inventory-collection-settings
      x-required-privileges:
        - Update Computer Inventory Collection Settings
  /v2/computer-inventory-collection-settings/custom-path:
    post:
      description: Creates a custom search path to use when collecting applications.
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreatePathV2'
        description: Computer inventory settings to update
        required: true
      responses:
        201:
          content:
            application/json:
              schema:
                $ref: _MonolithLibrary.yaml#/components/schemas/HrefResponse
          description: Custom path created
        400:
          content:
            application/json:
              schema:
                $ref: _MonolithLibrary.yaml#/components/schemas/ApiError
          description: Invalid data response
      summary: Create Computer Inventory Collection Settings Custom Path
      tags:
        - computer-inventory-collection-settings
      x-required-privileges:
        - Create Custom Paths
  /v2/computer-inventory-collection-settings/custom-path/{id}:
    delete:
      description: Delete Custom Path from Computer Inventory Collection Settings
      parameters:
        - description: id of Custom Path
          explode: false
          in: path
          name: id
          required: true
          schema:
            type: string
          style: simple
      responses:
        204:
          description: Custom path deleted
        404:
          content:
            application/json:
              schema:
                $ref: _MonolithLibrary.yaml#/components/schemas/ApiError
          description: Invalid data response
      summary: Delete Custom Path from Computer Inventory Collection Settings
      tags:
        - computer-inventory-collection-settings
      x-required-privileges:
        - Delete Custom Paths
servers:
  - url: /api
