components:
  schemas:
    AccountSettingsRequest:
      properties:
        adminPassword:
          default: ""
          example: password
          minLength: 0
          nullable: false
          type: string
          writeOnly: true
        adminUsername:
          default: ""
          example: admin
          minLength: 0
          nullable: false
          type: string
        hiddenAdminAccount:
          default: false
          example: false
          nullable: false
          type: boolean
        id:
          description: id of Account Settings
          example: "1"
          nullable: false
          type: string
        localAdminAccountEnabled:
          default: false
          example: true
          nullable: false
          type: boolean
        localUserManaged:
          default: false
          example: true
          nullable: false
          type: boolean
        payloadConfigured:
          default: false
          example: true
          nullable: false
          type: boolean
        prefillAccountFullName:
          default: ""
          example: TestUser FullName
          minLength: 0
          nullable: false
          type: string
        prefillAccountUserName:
          default: ""
          example: UserName
          minLength: 0
          nullable: false
          type: string
        prefillPrimaryAccountInfoFeatureEnabled:
          default: false
          example: true
          nullable: false
          type: boolean
        prefillType:
          default: CUSTOM
          description: Values accepted are only CUSTOM and DEVICE_OWNER
          example: DEVICE_OWNER
          nullable: false
          type: string
        preventPrefillInfoFromModification:
          default: false
          example: false
          nullable: false
          type: boolean
        userAccountType:
          default: STANDARD
          enum:
            - ADMINISTRATOR
            - STANDARD
            - SKIP
          nullable: false
          type: string
        versionLock:
          default: 0
          example: 4
          nullable: false
          type: integer
      type: object
    AccountSettingsResponse:
      properties:
        adminUsername:
          default: ""
          example: admin
          minLength: 0
          nullable: false
          type: string
        hiddenAdminAccount:
          default: false
          example: false
          nullable: false
          type: boolean
        id:
          description: id of Account Settings
          example: "1"
          nullable: false
          type: string
        localAdminAccountEnabled:
          default: false
          example: true
          nullable: false
          type: boolean
        localUserManaged:
          default: false
          example: true
          nullable: false
          type: boolean
        payloadConfigured:
          default: false
          example: true
          nullable: false
          type: boolean
        prefillAccountFullName:
          default: ""
          example: TestUser FullName
          minLength: 0
          nullable: false
          type: string
        prefillAccountUserName:
          default: ""
          example: UserName
          minLength: 0
          nullable: false
          type: string
        prefillPrimaryAccountInfoFeatureEnabled:
          default: false
          example: true
          nullable: false
          type: boolean
        prefillType:
          default: CUSTOM
          description: Values accepted are only CUSTOM and DEVICE_OWNER
          example: DEVICE_OWNER
          nullable: false
          type: string
        preventPrefillInfoFromModification:
          default: false
          example: false
          nullable: false
          type: boolean
        userAccountType:
          default: STANDARD
          enum:
            - ADMINISTRATOR
            - STANDARD
            - SKIP
          nullable: false
          type: string
        versionLock:
          default: 0
          example: 4
          minimum: 0
          nullable: false
          type: integer
      type: object
    ComputerPrestageSearchResultsV3:
      properties:
        results:
          items:
            $ref: '#/components/schemas/GetComputerPrestageV3'
          minItems: 0
          type: array
        totalCount:
          example: 1
          minimum: 0
          type: integer
      type: object
    ComputerPrestageV3:
      allOf:
        - $ref: _MonolithLibrary.yaml#/components/schemas/DeviceEnrollmentPrestageV2
        - properties:
            customPackageDistributionPointId:
              example: "1"
              type: string
            customPackageIds:
              items:
                example: "1"
                type: string
              type: array
            enableRecoveryLock:
              example: true
              nullable: false
              type: boolean
            installProfilesDuringSetup:
              example: true
              nullable: false
              type: boolean
            manifestUrl:
              description: The URL to the manifest file for the Platform SSO (PSSO) application 403 workflow. This URL is used when deploying the PSSO app to devices during the setup process.
              example: https://mdmserver.example.com/psso-app.plist
              nullable: true
              type: string
            minimumOsSpecificVersion:
              example: "17.1"
              minLength: 0
              nullable: false
              type: string
            platformSsoAppBundleId:
              description: The bundle identifier for the Platform SSO (PSSO) application unattended workflow. This identifier is used to specify which PSSO app should be deployed to devices during the setup process.
              example: com.okta.mobile
              type: string
            prestageInstalledProfileIds:
              items:
                example: "1"
                type: string
              type: array
            prestageMinimumOsTargetVersionType:
              enum:
                - NO_ENFORCEMENT
                - MINIMUM_OS_LATEST_VERSION
                - MINIMUM_OS_LATEST_MAJOR_VERSION
                - MINIMUM_OS_LATEST_MINOR_VERSION
                - MINIMUM_OS_SPECIFIC_VERSION
              example: MINIMUM_OS_LATEST_VERSION
              nullable: false
              type: string
            profileUrl:
              description: The URL to the configuration profile for the Platform SSO (PSSO) application 403 workflow. This URL is used when deploying the PSSO app to devices during the setup process. Users should use either profileUrl or populate pssoConfigProfileId, but not both.
              example: https://mdmserver.example.com/psso.mobileconfig
              nullable: true
              type: string
            pssoConfigProfileId:
              description: The identifier for the configuration profile associated with the Platform SSO (PSSO) application 403 workflow. This ID is used to specify which configuration profile should be applied to devices during the setup process when PSSO is enabled. Users should use either pssoConfigProfileId or populate profileUrl, but not both.
              example: "1"
              nullable: true
              type: string
            pssoEnabled:
              default: false
              description: Indicates whether Platform SSO (PSSO) is enabled for this computer prestage, regardless of unattended or 403 workflows. When enabled, the PSSO application will be deployed to devices during the setup process to facilitate single sign-on (SSO) for users.
              example: true
              type: boolean
            recoveryLockPasswordType:
              enum:
                - MANUAL
                - RANDOM
              example: MANUAL
              nullable: false
              type: string
            rotateRecoveryLockPassword:
              example: true
              nullable: false
              type: boolean
          required:
            - customPackageDistributionPointId
            - customPackageIds
            - installProfilesDuringSetup
            - prestageInstalledProfileIds
          type: object
    GetComputerPrestageV3:
      allOf:
        - $ref: '#/components/schemas/ComputerPrestageV3'
        - properties:
            accountSettings:
              $ref: '#/components/schemas/AccountSettingsResponse'
            id:
              example: "1"
              minLength: 1
              readOnly: true
              type: string
            profileUuid:
              example: 29d-a8d8f-b8sdjndf-dsa9
              type: string
            siteId:
              example: "5"
              type: string
            versionLock:
              example: 0
              minimum: 0
              type: integer
          type: object
    PostComputerPrestageV3:
      allOf:
        - $ref: '#/components/schemas/ComputerPrestageV3'
        - properties:
            accountSettings:
              $ref: '#/components/schemas/AccountSettingsRequest'
            recoveryLockPassword:
              example: password123
              format: password
              minLength: 1
              type: string
              writeOnly: true
          type: object
    PutComputerPrestageV3:
      allOf:
        - $ref: '#/components/schemas/ComputerPrestageV3'
        - properties:
            accountSettings:
              $ref: '#/components/schemas/AccountSettingsRequest'
            recoveryLockPassword:
              example: password123
              format: password
              minLength: 1
              type: string
              writeOnly: true
            versionLock:
              example: 0
              minimum: 0
              type: integer
          type: object
info:
  title: Jamf Pro API - ComputerPrestagesV3
  version: 0.0.1
openapi: 3.0.1
paths:
  /v3/computer-prestages:
    get:
      description: Gets sorted and paged computer prestages
      parameters:
        - $ref: _MonolithLibrary.yaml#/components/parameters/page
        - $ref: _MonolithLibrary.yaml#/components/parameters/page-size
        - description: 'Sorting criteria in the format: property:asc/desc. Multiple sort criteria are supported and must be separated with a comma. Example: sort=date:desc,name:asc '
          explode: true
          in: query
          name: sort
          required: false
          schema:
            default:
              - id:desc
            items:
              type: string
            type: array
          style: form
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ComputerPrestageSearchResultsV3'
          description: Successful response
      summary: |
        Get sorted and paged Computer Prestages
      tags:
        - computer-prestages
      x-required-privileges:
        - Read Computer PreStage Enrollments
    post:
      description: Create a computer prestage
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PostComputerPrestageV3'
        description: Computer Prestage to create. ids defined in this body will be ignored
        required: true
      responses:
        201:
          content:
            application/json:
              schema:
                $ref: _MonolithLibrary.yaml#/components/schemas/HrefResponse
          description: Computer Prestage was created
        400:
          content:
            application/json:
              schema:
                $ref: _MonolithLibrary.yaml#/components/schemas/ApiError
          description: Bad Request
      summary: |
        Create a Computer Prestage
      tags:
        - computer-prestages
      x-required-privileges:
        - Create Computer PreStage Enrollments
  /v3/computer-prestages/{id}:
    delete:
      description: Deletes a Computer Prestage with the supplied id
      parameters:
        - description: Computer Prestage identifier
          explode: false
          in: path
          name: id
          required: true
          schema:
            type: string
          style: simple
      responses:
        204:
          description: Success
      summary: |
        Delete a Computer Prestage with the supplied id
      tags:
        - computer-prestages
      x-required-privileges:
        - Delete Computer PreStage Enrollments
    get:
      description: Retrieves a Computer Prestage with the supplied id
      parameters:
        - description: Computer Prestage identifier
          explode: false
          in: path
          name: id
          required: true
          schema:
            type: string
          style: simple
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetComputerPrestageV3'
          description: Success
        404:
          content:
            application/json:
              schema:
                $ref: _MonolithLibrary.yaml#/components/schemas/ApiError
          description: Computer Prestage with that id does not exist
      summary: |
        Retrieve a Computer Prestage with the supplied id
      tags:
        - computer-prestages
      x-required-privileges:
        - Read Computer PreStage Enrollments
    put:
      description: Updates a Computer Prestage
      parameters:
        - description: Computer Prestage identifier
          explode: false
          in: path
          name: id
          required: true
          schema:
            type: string
          style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PutComputerPrestageV3'
        description: Computer Prestage to update
        required: true
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetComputerPrestageV3'
          description: Success
        400:
          content:
            application/json:
              schema:
                $ref: _MonolithLibrary.yaml#/components/schemas/ApiError
          description: Bad Request
        404:
          content:
            application/json:
              schema:
                $ref: _MonolithLibrary.yaml#/components/schemas/ApiError
          description: Computer Prestage with that id does not exist
        409:
          content:
            application/json:
              schema:
                $ref: _MonolithLibrary.yaml#/components/schemas/ApiError
          description: The Computer Prestage was modified by another process. Read the Computer Prestage again for updated changes.
      summary: |
        Update a Computer Prestage
      tags:
        - computer-prestages
      x-required-privileges:
        - Update Computer PreStage Enrollments
servers:
  - url: /api
