components:
  schemas:
    ComputerGroup:
      properties:
        description:
          example: A group containing all managed computers
          type: string
        id:
          example: "1"
          minLength: 1
          type: string
        name:
          example: All Managed Computers
          type: string
        smartGroup:
          example: true
          type: boolean
      type: object
info:
  title: Jamf Pro API - ComputerGroups
  version: 0.0.1
openapi: 3.0.1
paths:
  /v1/computer-groups:
    get:
      description: |
        Use it to get the list of all computer groups.
      responses:
        200:
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/ComputerGroup'
                type: array
          description: Success
      summary: |
        Returns the list of all computer groups
      tags:
        - computer-groups
      x-required-privileges:
        - Read Smart Computer Groups
        - Read Static Computer Groups
servers:
  - url: /api
