components:
  schemas:
    Country:
      properties:
        code:
          example: US
          type: string
        name:
          example: United States
          type: string
      type: object
    CountryCodes:
      properties:
        countryCodes:
          items:
            $ref: '#/components/schemas/Country'
          type: array
      type: object
info:
  title: Jamf Pro API - CountryCodes
  version: 0.0.1
openapi: 3.0.1
paths:
  /v1/app-store-country-codes:
    get:
      description: |
        Returns a list of countries and the associated codes that can be use for the App Store locale
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CountryCodes'
          description: Successful response
      summary: |
        Return a list of Countries and the associated Codes
      tags:
        - app-store-country-codes-preview
      x-authentication-required: false
servers:
  - url: /api
