components:
  schemas:
    DatabasePassword:
      properties:
        password:
          example: "12345"
          format: password
          minLength: 1
          type: string
          writeOnly: true
      required:
        - password
      type: object
info:
  title: Jamf Pro API - DatabaseConnection
  version: 0.0.1
openapi: 3.0.1
paths:
  /v1/system/initialize-database-connection:
    post:
      description: Provide database password during startup. Endpoint is accessible when database password was not configured and Jamf Pro server has not been initialized yet.
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DatabasePassword'
        required: true
      responses:
        202:
          description: OK
        400:
          content:
            application/json:
              schema:
                $ref: _MonolithLibrary.yaml#/components/schemas/ApiError
          description: Incorrect database password.
        429:
          content:
            application/json:
              schema:
                $ref: _MonolithLibrary.yaml#/components/schemas/ApiError
          description: Limit of requests per second was exceeded
      summary: |
        Provide Database Password during startup
      tags:
        - jamf-pro-initialization
      x-action: true
      x-authentication-required: false
servers:
  - url: /api
