info:
  title: Jamf Pro API - DdmSync
  version: 0.0.1
openapi: 3.0.1
paths:
  /v1/ddm/{clientManagementId}/sync:
    post:
      description: Force a device to sync by queuing a new DeclarativeManagementCommand
      parameters:
        - description: The client management id of the target device.
          explode: false
          in: path
          name: clientManagementId
          required: true
          schema:
            type: string
          style: simple
      responses:
        204:
          description: The device was successfully synced.
        403:
          description: Insufficient privileges to perform this action.
        500:
          content:
            application/json:
              schema:
                $ref: _MonolithLibrary.yaml#/components/schemas/ApiError
          description: Failure, unable to complete sync request.
      summary: Force a device DDM sync
      tags:
        - declarative-device-management
      x-action: true
      x-required-privileges:
        - Send Declarative Management Command
servers:
  - url: /api
