components:
  schemas:
    StatusItem:
      properties:
        key:
          description: The StatusItem key
          example: device.identifier.udid
          nullable: false
          type: string
        lastUpdateTime:
          description: The local server time when the StatusItem was last updated
          example: 2024-08-25T21:09:31
          nullable: false
          type: string
        value:
          description: The StatusItem value
          example: 00008103-000C51E402E2001E
          nullable: false
          type: string
      type: object
    StatusItems:
      properties:
        statusItems:
          default: []
          items:
            $ref: '#/components/schemas/StatusItem'
          nullable: false
          type: array
      type: object
info:
  title: Jamf Pro API - DdmStatus
  version: 0.0.1
openapi: 3.0.1
paths:
  /v1/ddm/{clientManagementId}/status-items:
    get:
      description: Retrieves the Status Items from the latest Status Report for a device
      parameters:
        - description: client management id of the target device.
          explode: false
          in: path
          name: clientManagementId
          required: true
          schema:
            type: string
          style: simple
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StatusItems'
          description: Success
        400:
          content:
            application/json:
              schema:
                $ref: _MonolithLibrary.yaml#/components/schemas/ApiError
          description: Bad Request
        404:
          content:
            application/json:
              schema:
                $ref: _MonolithLibrary.yaml#/components/schemas/ApiError
          description: The client could not be found
      summary: Retrieve the Status Items from the latest Status Report for a device
      tags:
        - declarative-device-management
      x-required-privileges:
        - Read Mobile Devices
        - Read Computers
  /v1/ddm/{clientManagementId}/status-items/{key}:
    get:
      description: Retrieves a Status Item from the latest Status Report for a device
      parameters:
        - description: client management id of the target device.
          explode: false
          in: path
          name: clientManagementId
          required: true
          schema:
            type: string
          style: simple
        - description: the status item key to retrieve.
          explode: false
          in: path
          name: key
          required: true
          schema:
            type: string
          style: simple
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StatusItem'
          description: Success
        400:
          content:
            application/json:
              schema:
                $ref: _MonolithLibrary.yaml#/components/schemas/ApiError
          description: Bad Request
        404:
          content:
            application/json:
              schema:
                $ref: _MonolithLibrary.yaml#/components/schemas/ApiError
          description: The client or specified key could not be found
      summary: Retrieve a Status Item from the latest Status Report for a device
      tags:
        - declarative-device-management
      x-required-privileges:
        - Read Mobile Devices
        - Read Computers
servers:
  - url: /api
