openapi: 3.0.1
info:
  title: Jamf Pro API - Declarative Management Command Definition
  description: This MDM commands exist to be re-used by multiple other Swagger files.
  version: 0.0.1
paths: {}
components:
  schemas:
    DeclarativeManagementCommand:
      allOf:
        - $ref: 'MdmDefinitionsLibrary.yaml#/components/schemas/MdmCommandBase'
        - type: object
          required:
            - data
          properties:
            data:
              type: string
              example: TWFkZSB5YSBsb29r
              description: Base64 encoded data to be sent with the command