openapi: 3.0.1
info:
  title: Jamf Pro API - Conditional Access Device Compliance Information
  version: 1.0.0
paths:
  /v1/conditional-access/device-compliance-information/mobile/{deviceId}:
    get:
      tags:
        - conditional-access
      summary: Get compliance information for a single mobile device
      description: Return basic compliance information for the given mobile device
      parameters:
        - name: deviceId
          description: ID of the device the query pertains
          in: path
          required: true
          schema:
            type: string
      responses:
        200:
          description: Array of device compliance information records
          content:
            'application/json':
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/DeviceComplianceInformation'
                example:
                  - deviceId: '1'
                    applicable: true
                    complianceState: 'COMPLIANT'
                    complianceVendor: 'Vendor A'
                    complianceVendorDeviceInformation:
                      - deviceIds: ['device-id-1', 'device-id-2']
                  - deviceId: '1'
                    applicable: false
                    complianceState: 'NON_COMPLIANT'
                    complianceVendor: 'Vendor B'
                    complianceVendorDeviceInformation:
                      - deviceIds: []
      x-required-privileges:
        - Read Device Compliance Information

  /v1/conditional-access/device-compliance-information/computer/{deviceId}:
    get:
      tags:
        - conditional-access
      summary: Get compliance information for a single computer device
      description: Return basic compliance information for the given computer device
      parameters:
        - name: deviceId
          description: ID of the device the query pertains
          in: path
          required: true
          schema:
            type: string
      responses:
        200:
          description: Array of device compliance information records
          content:
            'application/json':
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/DeviceComplianceInformation'
                example:
                  - deviceId: '1'
                    applicable: true
                    complianceState: 'COMPLIANT'
                    complianceVendor: 'Vendor A'
                    complianceVendorDeviceInformation:
                      - deviceIds: [ 'device-id-1', 'device-id-2' ]
                  - deviceId: '1'
                    applicable: false
                    complianceState: 'NON_COMPLIANT'
                    complianceVendor: 'Vendor B'
                    complianceVendorDeviceInformation:
                      - deviceIds: []
      x-required-privileges:
        - Read Device Compliance Information
  /v1/conditional-access/device-compliance/feature-toggle:
      get:
          tags:
              - conditional-access
          summary: Retrieves Status of the Feature Toggle
          description: Retrieves Status of the Feature Toggle
          responses:
              200:
                  description: Success
                  content:
                      'application/json':
                          schema:
                              $ref: '#/components/schemas/SharedDeviceComplianceFeatureToggle'
          x-required-privileges:
              - Read Conditional Access

components:
  schemas:
    DeviceComplianceInformation:
      type: object
      description: Device compliance information record
      properties:
        deviceId:
          type: string
          description: ID of the device
          example: '1'
        applicable:
          type: boolean
          description: If device is applicable for compliance calculation
          example: true
        complianceState:
          type: string
          enum:
            - 'UNKNOWN'
            - 'NON_COMPLIANT'
            - 'COMPLIANT'
          description: |
            Device compliance state. Possible values are:
            * `UNKNOWN` for unknow compliance state, this usually means that the compliance state is being calculated,
            * `NON_COMPLIANT` for non compliant state,
            * `COMPLIANT` for compliant state
          example: 'COMPLIANT'
        complianceVendor:
          type: string
          description: Name of the compliance vendor
          example: 'Vendor A'
        complianceVendorDeviceInformation:
          $ref: '#/components/schemas/ComplianceVendorDeviceInformation'

    ComplianceVendorDeviceInformation:
      type: object
      description: Additional, compliance vendor specific device details.
      properties:
        deviceIds:
          type: array
          items:
            type: string
          description: Vendor's device IDs. Currently provided only for Intune.
          example:
            - 'device-id-1'
            - 'device-id-2'

    SharedDeviceComplianceFeatureToggle:
        type: object
        nullable: false
        required:
            - sharedDeviceFeatureEnabled
        properties:
            sharedDeviceFeatureEnabled:
                type: boolean
                example: false
                nullable: false
