components:
  schemas:
    DeviceCommunicationSettings:
      properties:
        autoRenewComputerMdmProfileWhenCaRenewed:
          example: true
          type: boolean
        autoRenewComputerMdmProfileWhenDeviceIdentityCertExpiring:
          example: true
          type: boolean
        autoRenewMobileDeviceMdmProfileWhenCaRenewed:
          example: true
          type: boolean
        autoRenewMobileDeviceMdmProfileWhenDeviceIdentityCertExpiring:
          example: true
          type: boolean
        mdmProfileComputerExpirationLimitInDays:
          default: 180
          enum:
            - 90
            - 120
            - 180
          type: integer
        mdmProfileMobileDeviceExpirationLimitInDays:
          default: 180
          enum:
            - 90
            - 120
            - 180
          type: integer
      type: object
info:
  title: Jamf Pro API - DeviceCommunicationSettings
  version: 0.0.1
openapi: 3.0.1
paths:
  /v1/device-communication-settings:
    get:
      description: |
        Retrieves all device communication settings, including automatic renewal of the MDM profile.
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DeviceCommunicationSettings'
          description: Successful response - Device Communication Settings retrieved
      summary: |
        Retrieves all settings for device communication
      tags:
        - device-communication-settings
      x-required-privileges:
        - Read Automatically Renew MDM Profile Settings
    put:
      description: |
        Update device communication settings
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DeviceCommunicationSettings'
        required: true
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DeviceCommunicationSettings'
          description: Successful response - Device communication Settings updated
      summary: |
        Update device communication settings
      tags:
        - device-communication-settings
      x-required-privileges:
        - Update Automatically Renew MDM Profile Settings
  /v1/device-communication-settings/history:
    get:
      description: |
        Gets Device Communication settings history
      parameters:
        - $ref: _MonolithLibrary.yaml#/components/parameters/page
        - $ref: _MonolithLibrary.yaml#/components/parameters/page-size
        - description: 'Sorting criteria in the format: property:asc/desc. Default sort is date:desc. Multiple sort criteria are supported and must be separated with a comma. Example: sort=date:desc,name:asc '
          explode: true
          in: query
          name: sort
          required: false
          schema:
            default:
              - date:desc
            items:
              type: string
            type: array
          style: form
        - description: 'Query in the RSQL format, allowing to filter history notes collection. Default filter is empty query - returning all results for the requested page. Fields allowed in the query: username, date, note, details. This param can be combined with paging and sorting. Example: filter=username!=admin and details==*disabled* and date<2019-12-15'
          explode: true
          in: query
          name: filter
          required: false
          schema:
            default: ""
            type: string
          style: form
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: _MonolithLibrary.yaml#/components/schemas/HistorySearchResults
          description: Details of Device Communication Settings history were found
      summary: |
        Get Device Communication settings history
      tags:
        - device-communication-settings
      x-required-privileges:
        - Read Automatically Renew MDM Profile Settings
    post:
      description: |
        Adds Device Communication Settings history notes
      requestBody:
        content:
          application/json:
            schema:
              $ref: _MonolithLibrary.yaml#/components/schemas/ObjectHistoryNote
        description: history notes to create
        required: true
      responses:
        201:
          content:
            application/json:
              schema:
                $ref: _MonolithLibrary.yaml#/components/schemas/ObjectHistory
          description: Notes to Device Communication Settings history were added
        503:
          content:
            application/json:
              schema:
                $ref: _MonolithLibrary.yaml#/components/schemas/ApiError
          description: Device Communication Settings history can not be saved
      summary: |
        Add Device Communication Settings history notes
      tags:
        - device-communication-settings
      x-required-privileges:
        - Update Automatically Renew MDM Profile Settings
servers:
  - url: /api
