components:
  schemas:
    DistributionPoint:
      properties:
        backupDistributionPointId:
          default: "-1"
          type: string
        enableLoadBalancing:
          default: false
          description: This is used to configure load balancing on the backup distribution point. Cannot be enabled when the backup distribution point configured is cloud.
          type: boolean
        fileSharingConnectionType:
          default: NONE
          description: Specify the type of connection , Either of  fileSharingConnectionType (or) https connection type needs to be enabled using httpsEnabled for a distribution point to be created.
          enum:
            - AFP
            - SMB
            - NONE
          example: AFP
          type: string
        httpsContext:
          description: Path to the share (e.g. if the share is accessible at http://192.168.10.10/JamfShare, the context is "JamfShare") - required if HTTPS enabled
          example: JamfShare
          type: string
        httpsEnabled:
          default: false
          description: Allow downloads over HTTPS - requires installation of a valid SSL certificate
          type: boolean
        httpsPassword:
          description: Required if httpsSecurityType is USERNAME_PASSWORD
          example: password
          format: password
          type: string
          writeOnly: true
        httpsPort:
          default: 443
          description: Port number of the server - required if HTTPS enabled
          type: integer
        httpsSecurityType:
          default: NONE
          description: Type of authentication required to download files from the distribution point - required if HTTPS enabled
          enum:
            - USERNAME_PASSWORD
            - NONE
          type: string
        httpsUsername:
          description: Required if httpsSecurityType is USERNAME_PASSWORD
          example: admin
          type: string
        id:
          example: "1"
          readOnly: true
          type: string
        localPathToShare:
          example: /
          type: string
        name:
          example: My distribution point
          type: string
        port:
          default: 139
          description: Required if fileSharingConnectionType is either AFP (or) SMB
          type: integer
        principal:
          default: false
          type: boolean
        readOnlyPassword:
          description: Required if fileSharingConnectionType is either AFP (or) SMB
          example: password
          format: password
          type: string
          writeOnly: true
        readOnlyUsername:
          description: Required if fileSharingConnectionType is either AFP (or) SMB
          example: john.doe
          type: string
        readWritePassword:
          description: Required if fileSharingConnectionType is either AFP (or) SMB
          example: password
          format: password
          type: string
          writeOnly: true
        readWriteUsername:
          description: Required if fileSharingConnectionType is either AFP (or) SMB
          example: john.doe
          type: string
        serverName:
          example: My Server
          type: string
        shareName:
          description: Required if fileSharingConnectionType is either AFP (or) SMB
          example: My Share
          type: string
        sshPassword:
          example: password
          format: password
          type: string
          writeOnly: true
        sshUsername:
          example: john.doe
          type: string
        workgroup:
          example: WORKGROUP1
          type: string
      required:
        - fileSharingConnectionType
        - name
        - serverName
      type: object
    DistributionPointSearchResults:
      properties:
        results:
          items:
            $ref: '#/components/schemas/DistributionPoint'
          minItems: 0
          type: array
        totalCount:
          example: 1
          type: integer
      type: object
info:
  title: Jamf Pro API - DistributionPoint
  version: 0.0.1
openapi: 3.0.1
paths:
  /v1/distribution-points:
    get:
      description: Finds all Distribution Points
      parameters:
        - $ref: _MonolithLibrary.yaml#/components/parameters/page
        - $ref: _MonolithLibrary.yaml#/components/parameters/page-size
        - description: Sorts results by one or more criteria, following the format property:asc/desc. Default sort is id:asc. If using multiple criteria, separate with commas. Allows fields such as - name, serverName
          explode: true
          in: query
          name: sort
          required: false
          schema:
            default:
              - id:asc
            items:
              type: string
            type: array
          style: form
        - description: Filters results. Use RSQL format for query. Allows fields such as - name, serverName, principal, fileSharingConnectionType, and httpsEnabled Can be combined with paging and sorting. Default filter is an empty query and returns all results from the requested page.
          explode: true
          in: query
          name: filter
          required: false
          schema:
            default: ""
            type: string
          style: form
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DistributionPointSearchResults'
          description: Success
      summary: Finds all Distribution Points
      tags:
        - distribution-point
      x-required-privileges:
        - Read Distribution Points
    post:
      description: Create distribution point
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DistributionPoint'
        description: distribution point to be created
        required: true
      responses:
        201:
          content:
            application/json:
              schema:
                $ref: _MonolithLibrary.yaml#/components/schemas/HrefResponse
          description: distribution point was created
      summary: Create distribution point
      tags:
        - distribution-point
      x-required-privileges:
        - Create Distribution Points
  /v1/distribution-points/delete-multiple:
    post:
      description: Delete multiple distribution points at once
      requestBody:
        content:
          application/json:
            schema:
              $ref: _MonolithLibrary.yaml#/components/schemas/Ids
        description: ids of the distribution points to be deleted
        required: true
      responses:
        204:
          description: All specified distribution points deleted successfully
        400:
          content:
            application/json:
              schema:
                $ref: _MonolithLibrary.yaml#/components/schemas/ApiError
          description: Returns error codes and ids for any distribution points that were unable to be deleted. Possible error codes include INVALID_ID (distribution point id does not exist) and SYSTEM_EXCEPTION (a system exception occurred while attempting to delete the distribution point).
      summary: Delete multiple distribution points at once
      tags:
        - distribution-point
      x-action: true
      x-required-privileges:
        - Delete Distribution Points
  /v1/distribution-points/{id}:
    delete:
      description: |
        Removes specified distribution point
      parameters:
        - description: Instance id of distribution point
          explode: false
          in: path
          name: id
          required: true
          schema:
            type: string
          style: simple
      responses:
        204:
          description: distribution point deleted successfully
      summary: |
        Remove specified distribution point
      tags:
        - distribution-point
      x-required-privileges:
        - Delete Distribution Points
    get:
      description: |
        Get specified distribution point
      parameters:
        - description: instance id of distribution point
          explode: false
          in: path
          name: id
          required: true
          schema:
            type: string
          style: simple
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DistributionPoint'
          description: distribution point found
        404:
          content:
            application/json:
              schema:
                $ref: _MonolithLibrary.yaml#/components/schemas/ApiError
          description: Specified distribution point could not be found
      summary: |
        Get specified distribution point
      tags:
        - distribution-point
      x-required-privileges:
        - Read Distribution Points
    patch:
      description: |
        Updates the specified object configuration of a File Share Distribution Point in Jamf Pro. ID path parameter is mandatory and other fields can be updated as a whole or with minimal object.
      parameters:
        - description: Instance id of distribution point
          explode: false
          in: path
          name: id
          required: true
          schema:
            type: string
          style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DistributionPoint'
        description: distribution point object to update.
        required: true
      responses:
        202:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DistributionPoint'
          description: distribution point updated
        400:
          content:
            application/json:
              schema:
                $ref: _MonolithLibrary.yaml#/components/schemas/ApiError
          description: Bad Request
        404:
          content:
            application/json:
              schema:
                $ref: _MonolithLibrary.yaml#/components/schemas/ApiError
          description: The specified distribution point id doesn't exist in database or invalid.
      summary: |
        Update specified distribution point object
      tags:
        - distribution-point
      x-required-privileges:
        - Read Distribution Points
        - Update Distribution Points
    put:
      description: |
        Update specified distribution point object
      parameters:
        - description: Instance id of distribution point
          explode: false
          in: path
          name: id
          required: true
          schema:
            type: string
          style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DistributionPoint'
        description: distribution point object to update. ids defined in this body will be ignored
        required: true
      responses:
        202:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DistributionPoint'
          description: distribution point updated
      summary: |
        Update specified distribution point object
      tags:
        - distribution-point
      x-required-privileges:
        - Read Distribution Points
        - Update Distribution Points
  /v1/distribution-points/{id}/history:
    get:
      description: |
        Gets specified distribution point history object
      parameters:
        - description: Instance id of distribution point history
          explode: false
          in: path
          name: id
          required: true
          schema:
            type: string
          style: simple
        - $ref: _MonolithLibrary.yaml#/components/parameters/page
        - $ref: _MonolithLibrary.yaml#/components/parameters/page-size
        - description: Sorts results by one or more criteria, following the format property:asc/desc. Default sort is id:asc. If using multiple criteria, separate with commas.
          explode: true
          in: query
          name: sort
          required: false
          schema:
            default:
              - date:desc
            items:
              type: string
            type: array
          style: form
        - description: Filters results. Use RSQL format for query. Allows for many fields, including id, name, etc. Can be combined with paging and sorting. Default filter is an empty query and returns all results from the requested page.
          explode: true
          in: query
          name: filter
          required: false
          schema:
            default: ""
            type: string
          style: form
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: _MonolithLibrary.yaml#/components/schemas/HistorySearchResults
          description: Details of distribution point history were found
        404:
          content:
            application/json:
              schema:
                $ref: _MonolithLibrary.yaml#/components/schemas/ApiError
          description: Specified distribution point history object could not be found
      summary: |
        Get specified distribution point History object
      tags:
        - distribution-point
      x-required-privileges:
        - Read Distribution Points
    post:
      description: |
        Adds specified distribution point History object notes
      parameters:
        - description: Instance id of distribution point history
          explode: false
          in: path
          name: id
          required: true
          schema:
            type: string
          style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: _MonolithLibrary.yaml#/components/schemas/ObjectHistoryNote
        description: History note to be created
        required: true
      responses:
        201:
          content:
            application/json:
              schema:
                $ref: _MonolithLibrary.yaml#/components/schemas/ObjectHistory
          description: distribution point History note created successfully
        404:
          content:
            application/json:
              schema:
                $ref: _MonolithLibrary.yaml#/components/schemas/ApiError
          description: distribution point History note could not be found
        503:
          content:
            application/json:
              schema:
                $ref: _MonolithLibrary.yaml#/components/schemas/ApiError
          description: distribution point History note could not be saved
      summary: |
        Add specified distribution point History object notes
      tags:
        - distribution-point
      x-required-privileges:
        - Update Distribution Points
servers:
  - url: /api
