components:
  schemas:
    DockItem:
      properties:
        contents:
          example: <dict><key>GUID</key><integer>-91117049</integer><key>tile-data</key><dict><key>file-data</key><dict><key>_CFURLString</key><string>file://localhost/Applications/iTunes.app</string><key>_CFURLStringType</key><integer>15</integer></dict><key>file-label</key><string>MyDockItem2</string></dict><key>tile-type</key><string>directory-tile</string></dict>
          readOnly: true
          type: string
        id:
          example: "1"
          minimum: 1
          readOnly: true
          type: string
        name:
          example: DockItem Name
          type: string
        path:
          example: file://localhost/Applications/iTunes.app
          type: string
        type:
          enum:
            - APP
            - FILE
            - FOLDER
          example: FILE
          type: string
      required:
        - name
        - path
        - type
      type: object
info:
  title: Jamf Pro API - DockItem
  version: 0.0.1
openapi: 3.0.1
paths:
  /v1/dock-items:
    post:
      description: Creates a DockItem
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DockItem'
        description: new DockItem to create. ids defined in this body will be ignored
        required: true
      responses:
        201:
          content:
            application/json:
              schema:
                $ref: _MonolithLibrary.yaml#/components/schemas/HrefResponse
          description: DockItem created successfully
        409:
          content:
            application/json:
              schema:
                $ref: _MonolithLibrary.yaml#/components/schemas/ApiError
          description: Duplicate
      summary: |
        Create a DockItem
      tags:
        - dock-items
      x-required-privileges:
        - Create Dock Items
  /v1/dock-items/{id}:
    delete:
      description: Deletes a dockItem at the specified id
      parameters:
        - description: DockItem object identifier
          explode: false
          in: path
          name: id
          required: true
          schema:
            type: string
          style: simple
      responses:
        204:
          description: Successful response
        404:
          content:
            application/json:
              schema:
                $ref: _MonolithLibrary.yaml#/components/schemas/ApiError
          description: DockItem with that id does not exist
      summary: |
        Delete a DockItem at the specified id
      tags:
        - dock-items
      x-required-privileges:
        - Delete Dock Items
    get:
      description: Retrieves a full dockItem object
      parameters:
        - description: DockItem object identifier
          explode: false
          in: path
          name: id
          required: true
          schema:
            type: string
          style: simple
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DockItem'
          description: Success
        404:
          content:
            application/json:
              schema:
                $ref: _MonolithLibrary.yaml#/components/schemas/ApiError
          description: Dockitem with that ID does not exist
      summary: |
        Retrieve a full dockItem object
      tags:
        - dock-items
      x-required-privileges:
        - Read Dock Items
    put:
      description: Replaces the dockItem at the id with the supplied information
      parameters:
        - description: DockItem object identifier
          explode: false
          in: path
          name: id
          required: true
          schema:
            type: string
          style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DockItem'
        description: new dockItem to upload to existing id. ids defined in this body will be ignored
        required: true
      responses:
        200:
          content:
            text/plain:
              schema:
                type: string
          description: DockItem at id was updated
        404:
          content:
            application/json:
              schema:
                $ref: _MonolithLibrary.yaml#/components/schemas/ApiError
          description: DockItem with that id does not exist
        409:
          content:
            application/json:
              schema:
                $ref: _MonolithLibrary.yaml#/components/schemas/ApiError
          description: Duplicate
      summary: |
        Replace the dockItem at the id with the supplied information
      tags:
        - dock-items
      x-required-privileges:
        - Update Dock Items
servers:
  - url: /api
