openapi: 3.0.1
info:
  title: Jamf Pro API - Declarative Device Management Declarations
  version: 0.0.2
paths:
  /v1/dss-declarations/{declarationId}:
    get:
      tags:
        - declarative-device-management
      summary: Retrieve an existing declaration
      description:
        Retrieves a stored declaration based on the provided declaration id
      x-required-privileges:
        - Read Mobile Devices
        - Read Computers
      parameters:
        -   name: declarationId
            in: path
            required: true
            description: Declaration UUID
            example: 538F90D7-9383-4A2B-B1C8-81E845A9CFD7
            schema:
              type: string
      responses:
        200:
          description: The Declaration request was sent successfully.
          content:
            'application/json':
              schema:
                $ref: 'DefinitionsLibrary.yaml#/components/schemas/DssDeclarations'
        403:
          description: Insufficient privileges to perform this action.
          content:
            'application/json':
              schema:
                $ref: 'DefinitionsLibrary.yaml#/components/schemas/ApiError'
        404:
          description: Existing declaration not found.
          content:
            'application/json':
              schema:
                $ref: 'DefinitionsLibrary.yaml#/components/schemas/ApiError'
        500:
          description: Server Error, unable to complete Declaration request.
          content:
            'application/json':
              schema:
                $ref: 'DefinitionsLibrary.yaml#/components/schemas/ApiError'