components:
  schemas:
    Ebook:
      properties:
        author:
          example: IT Bob
          type: string
        categoryId:
          example: "-1"
          type: string
        deployAsManaged:
          description: If true, it will be automatically installed
          example: false
          type: boolean
        free:
          example: true
          type: boolean
        id:
          example: "1"
          type: string
        installAutomatically:
          example: false
          type: boolean
        kind:
          enum:
            - UNKNOWN
            - PDF
            - EPUB
            - IBOOKS
          example: IBOOKS
          type: string
        name:
          example: The Neverending API
          type: string
        siteId:
          example: "-1"
          type: string
        url:
          example: https://jamf.com/ibooks/the_neverending_api.just_kidding
          type: string
        version:
          example: 10.9.0
          type: string
      type: object
    EbookExclusions:
      properties:
        buildingIds:
          items:
            example: "-1"
            type: string
          type: array
        computerGroupIds:
          items:
            example: "-1"
            type: string
          type: array
        computerIds:
          items:
            example: "-1"
            type: string
          type: array
        departmentIds:
          items:
            example: "-1"
            type: string
          type: array
        limitations:
          $ref: '#/components/schemas/EbookLimitations'
        mobileDeviceGroupIds:
          items:
            example: "-1"
            type: string
          type: array
        mobileDeviceIds:
          items:
            example: "-1"
            type: string
          type: array
        userGroupIds:
          items:
            example: "-1"
            type: string
          type: array
        userIds:
          items:
            example: "-1"
            type: string
          type: array
      type: object
    EbookLimitations:
      properties:
        networkSegments:
          items:
            example: "1"
            type: string
          type: array
        userGroups:
          items:
            example: "1"
            type: string
          type: array
        users:
          items:
            properties:
              name:
                example: admin
                type: string
            type: object
          type: array
      type: object
    EbookScope:
      properties:
        allComputers:
          example: false
          type: boolean
        allMobileDevices:
          example: false
          type: boolean
        allUsers:
          example: false
          type: boolean
        buildingIds:
          items:
            example: "-1"
            type: string
          type: array
        classroomIds:
          items:
            example: "-1"
            type: string
          type: array
        computerGroupIds:
          items:
            example: "-1"
            type: string
          type: array
        computerIds:
          items:
            example: "-1"
            type: string
          type: array
        departmentIds:
          items:
            example: "-1"
            type: string
          type: array
        exclusions:
          $ref: '#/components/schemas/EbookExclusions'
        limitations:
          $ref: '#/components/schemas/EbookLimitations'
        mobileDeviceGroupIds:
          items:
            example: "-1"
            type: string
          type: array
        mobileDeviceIds:
          items:
            example: "-1"
            type: string
          type: array
        userGroupIds:
          items:
            example: "-1"
            type: string
          type: array
        userIds:
          items:
            example: "-1"
            type: string
          type: array
      type: object
    EbookSearchResults:
      properties:
        results:
          items:
            $ref: '#/components/schemas/Ebook'
          type: array
        totalCount:
          example: 3
          minimum: 0
          type: integer
      type: object
info:
  title: Jamf Pro API - Ebook
  version: 0.0.1
openapi: 3.0.1
paths:
  /v1/ebooks:
    get:
      description: Gets ebook object
      parameters:
        - $ref: _MonolithLibrary.yaml#/components/parameters/page
        - $ref: _MonolithLibrary.yaml#/components/parameters/page-size
        - description: 'Sorting criteria in the format: property:asc/desc. Default sort is name:asc. Multiple sort criteria are supported and must be separated with a comma. Example: sort=date:desc,name:asc '
          explode: true
          in: query
          name: sort
          required: false
          schema:
            default:
              - name:asc
            items:
              type: string
            type: array
          style: form
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EbookSearchResults'
          description: Successful response
      summary: |
        Get Ebook object
      tags:
        - ebooks
      x-required-privileges:
        - Read eBooks
  /v1/ebooks/{id}:
    get:
      description: |
        Gets specified Ebook object
      parameters:
        - description: instance id of ebook record
          explode: false
          in: path
          name: id
          required: true
          schema:
            type: string
          style: simple
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Ebook'
          description: Details about ebook were found for given id
        404:
          content:
            application/json:
              schema:
                $ref: _MonolithLibrary.yaml#/components/schemas/ApiError
          description: Specified ebook object does not exist.
      summary: |
        Get specified Ebook object
      tags:
        - ebooks
      x-required-privileges:
        - Read eBooks
  /v1/ebooks/{id}/scope:
    get:
      description: |
        Gets specified scope of Ebook object
      parameters:
        - description: instance id of ebook record
          explode: false
          in: path
          name: id
          required: true
          schema:
            type: string
          style: simple
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EbookScope'
          description: Details of scope for ebook were found
        404:
          content:
            application/json:
              schema:
                $ref: _MonolithLibrary.yaml#/components/schemas/ApiError
          description: Specified scope for ebook object does not exist.
      summary: |
        Get specified scope of Ebook object
      tags:
        - ebooks
      x-required-privileges:
        - Read eBooks
servers:
  - url: /api
