components:
  schemas:
    EnrollmentCustomizationBrandingSettings:
      properties:
        backgroundColor:
          example: 0000FF
          type: string
        buttonColor:
          example: 0000FF
          type: string
        buttonTextColor:
          example: 0000FF
          type: string
        iconUrl:
          example: https://jamfUrl/api/v2/enrollment-customizations/images/1
          type: string
        textColor:
          example: 0000FF
          type: string
      required:
        - backgroundColor
        - buttonColor
        - buttonTextColor
        - iconUrl
        - textColor
      type: object
    EnrollmentCustomizationSearchResultsV2:
      properties:
        results:
          items:
            $ref: '#/components/schemas/EnrollmentCustomizationV2'
          type: array
        totalCount:
          example: 1
          minimum: 0
          type: integer
      type: object
    EnrollmentCustomizationV2:
      properties:
        description:
          example: Example description
          type: string
        displayName:
          example: Example
          type: string
        enrollmentCustomizationBrandingSettings:
          $ref: '#/components/schemas/EnrollmentCustomizationBrandingSettings'
        id:
          example: "1"
          readOnly: true
          type: string
        siteId:
          example: "2"
          type: string
      required:
        - description
        - displayName
        - enrollmentCustomizationBrandingSettings
        - siteId
      type: object
    PrestageDependencies:
      properties:
        dependencies:
          items:
            $ref: '#/components/schemas/PrestageDependency'
          type: array
      type: object
    PrestageDependency:
      properties:
        humanReadableName:
          example: Computer PreStage
          type: string
        hyperlink:
          example: /mobile-prestage/id
          type: string
        name:
          example: Name
          type: string
      type: object
info:
  title: Jamf Pro API - EnrollmentCustomizationV2
  version: 0.0.1
openapi: 3.0.1
paths:
  /v2/enrollment-customizations:
    get:
      description: Retrieves sorted and paged Enrollment Customizations
      parameters:
        - $ref: _MonolithLibrary.yaml#/components/parameters/page
        - $ref: _MonolithLibrary.yaml#/components/parameters/page-size
        - description: 'Sorting criteria in the format: property:asc/desc. Multiple sort criteria are supported and must be separated with a comma. Example: sort=date:desc,name:asc '
          explode: true
          in: query
          name: sort
          required: false
          schema:
            default:
              - id:asc
            items:
              type: string
            type: array
          style: form
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EnrollmentCustomizationSearchResultsV2'
          description: Success
      summary: |
        Retrieve sorted and paged Enrollment Customizations
      tags:
        - enrollment-customization
      x-required-privileges:
        - Read Enrollment Customizations
    post:
      description: Create an enrollment customization
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EnrollmentCustomizationV2'
        description: Enrollment customization to create.
        required: true
      responses:
        201:
          content:
            application/json:
              schema:
                $ref: _MonolithLibrary.yaml#/components/schemas/HrefResponse
          description: Enrollment customization was created
      summary: |
        Create an Enrollment Customization
      tags:
        - enrollment-customization
      x-required-privileges:
        - Create Enrollment Customizations
  /v2/enrollment-customizations/images:
    post:
      description: Uploads an image
      requestBody:
        content:
          multipart/form-data:
            schema:
              properties:
                file:
                  description: The file to upload
                  format: binary
                  type: string
              required:
                - file
              type: object
        required: true
      responses:
        201:
          content:
            application/json:
              schema:
                $ref: _MonolithLibrary.yaml#/components/schemas/BrandingImageUrl
          description: Image successfully uploaded
      summary: Upload an image
      tags:
        - enrollment-customization
      x-required-privileges:
        - Update Enrollment Customizations
  /v2/enrollment-customizations/images/{id}:
    get:
      description: Download an enrollment customization image
      parameters:
        - description: id of the enrollment customization image
          explode: false
          in: path
          name: id
          required: true
          schema:
            type: string
          style: simple
      responses:
        200:
          content:
            image/*:
              schema:
                format: binary
                type: string
          description: Successful response
      summary: |
        Download an enrollment customization image
      tags:
        - enrollment-customization
      x-authentication-required: false
  /v2/enrollment-customizations/{id}:
    delete:
      description: Deletes an Enrollment Customization with the supplied id
      parameters:
        - description: Enrollment Customization identifier
          explode: false
          in: path
          name: id
          required: true
          schema:
            type: string
          style: simple
      responses:
        204:
          description: Success
      summary: |
        Delete an Enrollment Customization with the supplied id
      tags:
        - enrollment-customization
      x-required-privileges:
        - Delete Enrollment Customizations
        - Read Enrollment Customizations
    get:
      description: Retrieves an Enrollment Customization with the supplied id
      parameters:
        - description: Enrollment Customization identifier
          explode: false
          in: path
          name: id
          required: true
          schema:
            type: string
          style: simple
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EnrollmentCustomizationV2'
          description: Success
        404:
          content:
            application/json:
              schema:
                $ref: _MonolithLibrary.yaml#/components/schemas/ApiError
          description: Enrollment Customization with that id does not exist
      summary: |
        Retrieve an Enrollment Customization with the supplied id
      tags:
        - enrollment-customization
      x-required-privileges:
        - Read Enrollment Customizations
    put:
      description: Updates an Enrollment Customization
      parameters:
        - description: Enrollment Customization identifier
          explode: false
          in: path
          name: id
          required: true
          schema:
            type: string
          style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EnrollmentCustomizationV2'
        description: Enrollment Customization to update
        required: true
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EnrollmentCustomizationV2'
          description: Success
        404:
          content:
            application/json:
              schema:
                $ref: _MonolithLibrary.yaml#/components/schemas/ApiError
          description: Enrollment Customization with that id does not exist
      summary: |
        Update an Enrollment Customization
      tags:
        - enrollment-customization
      x-required-privileges:
        - Update Enrollment Customizations
  /v2/enrollment-customizations/{id}/history:
    get:
      description: Gets sorted and paged enrollment customization history objects
      parameters:
        - description: Enrollment Customization identifier
          explode: false
          in: path
          name: id
          required: true
          schema:
            type: string
          style: simple
        - $ref: _MonolithLibrary.yaml#/components/parameters/page
        - $ref: _MonolithLibrary.yaml#/components/parameters/page-size
        - description: 'Sorting criteria in the format: property,asc/desc. Default sort order is descending. Multiple sort criteria are supported and must be entered on separate lines in Swagger UI. In the URI the ''sort'' query param is duplicated for each sort criterion, e.g., ...&sort=name%2Casc&sort=date%2Cdesc'
          explode: true
          in: query
          name: sort
          required: false
          schema:
            default:
              - date:desc
            items:
              type: string
            type: array
          style: form
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: _MonolithLibrary.yaml#/components/schemas/HistorySearchResults
          description: Details of enrollment customization history were found
      summary: |
        Get sorted and paged Enrollment Customization history objects
      tags:
        - enrollment-customization
      x-required-privileges:
        - Read Enrollment Customizations
    post:
      description: Adds enrollment customization history object notes
      parameters:
        - description: Enrollment Customization identifier
          explode: false
          in: path
          name: id
          required: true
          schema:
            type: string
          style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: _MonolithLibrary.yaml#/components/schemas/ObjectHistoryNote
        description: History notes to create
        required: true
      responses:
        201:
          content:
            application/json:
              schema:
                $ref: _MonolithLibrary.yaml#/components/schemas/ObjectHistory
          description: Notes of enrollment customization history were added
        503:
          content:
            application/json:
              schema:
                $ref: _MonolithLibrary.yaml#/components/schemas/ApiError
          description: Enrollment customization history can not be saved
      summary: |
        Add Enrollment Customization history object notes
      tags:
        - enrollment-customization
      x-required-privileges:
        - Update Enrollment Customizations
  /v2/enrollment-customizations/{id}/prestages:
    get:
      description: Retrieves the list of Prestages using this Enrollment Customization
      parameters:
        - description: Enrollment Customization identifier
          explode: false
          in: path
          name: id
          required: true
          schema:
            type: string
          style: simple
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PrestageDependencies'
          description: Success
        404:
          content:
            application/json:
              schema:
                $ref: _MonolithLibrary.yaml#/components/schemas/ApiError
          description: Enrollment Customization with that id does not exist
      summary: |
        Retrieve the list of Prestages using this Enrollment Customization
      tags:
        - enrollment-customization
      x-required-privileges:
        - Read Enrollment Customizations
servers:
  - url: /api
