components:
  schemas:
    EraseDeviceComputerRequest:
      properties:
        pin:
          description: The six-character PIN for Find My.
          example: "123456"
          maximum: 6
          minimum: 6
          nullable: true
          type: string
      type: object
    EraseDeviceComputerResponse:
      properties:
        commandUuid:
          description: Uuid of the queued eraseDevice command
          example: 1234-5678-90ab-cdef-1234567890ab
          type: string
        deviceId:
          description: Id of the computer for which eraseDevice command was queued
          example: "1234"
          type: string
      required:
        - commandUuid
        - deviceId
      type: object
info:
  title: Jamf Pro API - EraseDeviceComputer
  version: 0.0.1
openapi: 3.0.1
paths:
  /v1/computer-inventory/{id}/erase:
    post:
      description: Erase a computer
      parameters:
        - description: Id of the computer to erase
          explode: false
          in: path
          name: id
          required: true
          schema:
            type: string
          style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EraseDeviceComputerRequest'
        description: Options for eraseDevice command
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EraseDeviceComputerResponse'
          description: Erase command was queued for this device.
        403:
          description: Insufficient privileges to perform this action.
        404:
          description: Computer not found.
        500:
          content:
            application/json:
              schema:
                $ref: _MonolithLibrary.yaml#/components/schemas/ApiError
          description: Failure, unable to queue command.
      summary: |
        Erase a computer
      tags:
        - computer-inventory
      x-action: true
      x-required-privileges:
        - Send Computer Remote Wipe Command
servers:
  - url: /api
