components:
  schemas:
    EraseDeviceMobileDeviceRequest:
      properties:
        clearActivationLock:
          default: false
          description: Clear the activation lock on the device.
          example: true
          nullable: false
          type: boolean
        disallowProximitySetup:
          default: false
          description: If 'true', disable Proximity Setup on the next reboot and skip the pane in Setup Assistant.
          example: true
          nullable: false
          type: boolean
        preserveDataPlan:
          default: false
          description: If 'true', preserve the data plan on an iPhone or iPad with eSIM functionality, if one exists.
          example: true
          nullable: false
          type: boolean
        returnToService:
          default: false
          description: If 'true', the device will be returned to service after the erase is complete.
          example: true
          nullable: false
          type: boolean
      type: object
    EraseDeviceMobileDeviceResponse:
      properties:
        commandUuid:
          description: Uuid of the queued eraseDevice command
          example: 1234-5678-90ab-cdef-1234567890ab
          type: string
        deviceId:
          description: Id of the mobile device for which eraseDevice command was queued
          example: "1234"
          type: string
      required:
        - commandUuid
        - deviceId
      type: object
info:
  title: Jamf Pro API - EraseDeviceMobile
  version: 0.0.1
openapi: 3.0.1
paths:
  /v2/mobile-devices/{id}/erase:
    post:
      description: Erase a Mobile Device
      parameters:
        - description: Id of the Mobile Device to erase
          explode: false
          in: path
          name: id
          required: true
          schema:
            type: string
          style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EraseDeviceMobileDeviceRequest'
        description: Options for eraseDevice command
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EraseDeviceMobileDeviceResponse'
          description: Erase command was queued for this device.
        400:
          content:
            application/json:
              schema:
                $ref: _MonolithLibrary.yaml#/components/schemas/ApiError
          description: Return to service requirements not met.
        403:
          description: Insufficient privileges to perform this action.
        404:
          description: Mobile device not found.
        500:
          content:
            application/json:
              schema:
                $ref: _MonolithLibrary.yaml#/components/schemas/ApiError
          description: Failure, unable to queue command.
      summary: |
        Erase a Mobile Device
      tags:
        - mobile-devices
      x-action: true
      x-required-privileges:
        - Send Mobile Device Remote Wipe Command
servers:
  - url: /api
