components:
  schemas:
    GsxConnection:
      properties:
        enabled:
          default: false
          example: true
          type: boolean
        gsxKeystore:
          $ref: '#/components/schemas/GsxKeystore'
        serviceAccountNo:
          example: "0000012345"
          maxLength: 10
          type: string
        shipToNo:
          example: "0000012345"
          maxLength: 10
          type: string
        token:
          example: 34dsg23-5dsgs-3sdg-4ffs-435sdgs
          type: string
          writeOnly: true
        username:
          default: ' '
          example: exampleEmail@example.com
          type: string
      required:
        - enabled
        - gsxKeystore
        - serviceAccountNo
        - token
        - username
      type: object
    GsxConnectionUpdate:
      properties:
        enabled:
          default: false
          example: true
          type: boolean
        gsxKeystore:
          $ref: '#/components/schemas/GsxKeystore'
        serviceAccountNo:
          example: "0000012345"
          maxLength: 10
          type: string
        shipToNo:
          example: "0000012345"
          maxLength: 10
          type: string
        token:
          example: 34dsg23-5dsgs-3sdg-4ffs-435sdgs
          type: string
          writeOnly: true
        username:
          default: ' '
          example: exampleEmail@example.com
          type: string
      type: object
    GsxKeystore:
      properties:
        errorMessage:
          example: Certificate error
          readOnly: true
          type: string
        expirationEpoch:
          example: 169195490000
          format: int64
          readOnly: true
          type: integer
        keystoreBytes:
          description: The base 64 encoded of the GSX Connection keystore.
          example: WlhoaGJYQnNaU0J2WmlCaElHSmhjMlUyTkNCbGJtTnZaR1ZrSUhaaGJHbGtJSEF4TWk0Z2EyVjVjM1J2Y21VZ1ptbHNaUT09
          format: byte
          pattern: ^(?:[A-Za-z0-9+/]{4})*(?:[A-Za-z0-9+/]{2}==|[A-Za-z0-9+/]{3}=)?$
          type: string
          writeOnly: true
        keystorePassword:
          example: test1234
          format: password
          type: string
          writeOnly: true
        name:
          default: ' '
          example: certificate.p12
          type: string
      required:
        - keystore
        - keystorePassword
        - name
      type: object
    GsxTestResponse:
      properties:
        message:
          example: Unable to authenticate to GSX server
          type: string
        request:
          example: '[Accept: application/json, Content-Type: application/json, X-Apple-SoldTo: 0000012345, X-Apple-ShipTo: 0000012345] GET https://api-partner-connect.apple.com/api/authenticate/check HTTP/1.1'
          type: string
        response:
          example: OK
          type: string
      required:
        - message
        - request
        - response
      type: object
info:
  title: Jamf Pro API - GsxConnection
  version: 0.0.1
openapi: 3.0.1
paths:
  /v1/gsx-connection:
    get:
      description: |
        Finds the Jamf Pro GSX Connection information
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GsxConnection'
          description: Success
      summary: |
        Finds the Jamf Pro GSX Connection information
      tags:
        - gsx-connection
      x-required-privileges:
        - Read GSX Connection
        - Read Push Certificates
    patch:
      description: |
        Updates Jamf Pro GSX Connection information
      requestBody:
        content:
          application/merge-patch+json:
            schema:
              $ref: '#/components/schemas/GsxConnectionUpdate'
        description: GSX Connection to update
        required: true
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GsxConnection'
          description: Success
        400:
          content:
            application/json:
              schema:
                $ref: _MonolithLibrary.yaml#/components/schemas/ApiError
          description: Bad Request
        422:
          content:
            application/json:
              schema:
                $ref: _MonolithLibrary.yaml#/components/schemas/ApiError
          description: There was an error applying the put
      summary: |
        Updates Jamf Pro GSX Connection information
      tags:
        - gsx-connection
      x-required-privileges:
        - Update GSX Connection
        - Update Push Certificates
    put:
      description: |
        Updates Jamf Pro GSX Connection information
      requestBody:
        content:
          application/merge-patch+json:
            schema:
              $ref: '#/components/schemas/GsxConnection'
        description: GSX Connection to update
        required: true
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GsxConnection'
          description: Success
        400:
          content:
            application/json:
              schema:
                $ref: _MonolithLibrary.yaml#/components/schemas/ApiError
          description: Bad Request
        422:
          content:
            application/json:
              schema:
                $ref: _MonolithLibrary.yaml#/components/schemas/ApiError
          description: There was an error applying the put
      summary: |
        Updates Jamf Pro GSX Connection information
      tags:
        - gsx-connection
      x-required-privileges:
        - Update GSX Connection
        - Update Push Certificates
  /v1/gsx-connection/history:
    get:
      description: |
        Gets specified GSX Connection history object
      parameters:
        - $ref: _MonolithLibrary.yaml#/components/parameters/page
        - $ref: _MonolithLibrary.yaml#/components/parameters/page-size
        - description: 'Sorting criteria in the format: property:asc/desc. Default sort is date:desc. Multiple sort criteria are supported and must be separated with a comma. Example: sort=date:desc,name:asc '
          explode: true
          in: query
          name: sort
          required: false
          schema:
            default:
              - date:desc
            items:
              type: string
            type: array
          style: form
        - description: 'Query in the RSQL format, allowing to filter history notes collection. Default filter is empty query - returning all results for the requested page. Fields allowed in the query: username, date, note, details. This param can be combined with paging and sorting. Example: filter=username!=admin and details==*disabled* and date<2019-12-15'
          explode: true
          in: query
          name: filter
          required: false
          schema:
            default: ""
            type: string
          style: form
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: _MonolithLibrary.yaml#/components/schemas/HistorySearchResultsV1
          description: Details of GSX Connection history were found
        404:
          content:
            application/json:
              schema:
                $ref: _MonolithLibrary.yaml#/components/schemas/ApiError
          description: Specified GSX Connection object does not exist.
      summary: |
        Get specified GSX Connection History object
      tags:
        - gsx-connection
      x-required-privileges:
        - Read GSX Connection
    post:
      description: |
        Adds specified GSX Connection history object notes
      requestBody:
        content:
          application/json:
            schema:
              $ref: _MonolithLibrary.yaml#/components/schemas/ObjectHistoryNote
        description: history notes to create
        required: true
      responses:
        201:
          content:
            application/json:
              schema:
                $ref: _MonolithLibrary.yaml#/components/schemas/HrefResponse
          description: Notes of GSX Connection history were added
        503:
          content:
            application/json:
              schema:
                $ref: _MonolithLibrary.yaml#/components/schemas/ApiError
          description: GSX Connection history can not be saved
      summary: |
        Add specified GSX Connection history object notes
      tags:
        - gsx-connection
      x-required-privileges:
        - Update GSX Connection
  /v1/gsx-connection/test:
    post:
      description: Test functionality of an GSX Connection
      responses:
        202:
          description: Success
        400:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GsxTestResponse'
          description: Bad Request
      summary: Test functionality of an GSX Connection
      tags:
        - gsx-connection
      x-action: true
      x-required-privileges:
        - Read GSX Connection
servers:
  - url: /api
