components:
  schemas:
    InventoryInformation:
      description: Jamf Pro Inventory statistics object. Aggregates managed/unmanaged devices and computers counters
      properties:
        managedComputers:
          description: Number of managed computers in inventory.
          example: 1200
          minimum: 0
          readOnly: true
          type: integer
        managedDevices:
          description: Number of managed devices in inventory.
          example: 1200
          minimum: 0
          readOnly: true
          type: integer
        unmanagedComputers:
          description: Number of unmanaged computers in inventory.
          example: 1100
          minimum: 0
          readOnly: true
          type: integer
        unmanagedDevices:
          description: Number of unmanaged devices in inventory.
          example: 1100
          minimum: 0
          readOnly: true
          type: integer
      type: object
info:
  title: Jamf Pro API - InventoryInformation
  version: 0.0.1
openapi: 3.0.1
paths:
  /v1/inventory-information:
    get:
      description: |
        Gets statistics about managed/unmanaged devices and computers in the inventory.
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InventoryInformation'
          description: Successful response
      summary: |
        Get statistics about managed/unmanaged devices and computers in the inventory
      tags:
        - inventory-information
      x-authentication-required: true
servers:
  - url: /api
