openapi: 3.0.1
info:
  title: Jamf Pro API - Jamf Protect Deployment Tasks
  version: 0.0.1
paths:
  /v1/jamf-protect/deployments/{id}/tasks:
    get:
      tags:
        - jamf-protect
      summary: |
        Search for deployment tasks for a config profile linked to Jamf Protect
      description: Search for config profiles linked to Jamf Protect
      parameters:
        - name: id
          in: path
          required: true
          description: the UUID of the Jamf Protect deployment
          example: 24a7bb2a-9871-4895-9009-d1be07ed31b1
          schema:
            type: string
        - $ref: 'DefinitionsLibrary.yaml#/components/parameters/page'
        - $ref: 'DefinitionsLibrary.yaml#/components/parameters/page-size'
        - $ref: 'DefinitionsLibrary.yaml#/components/parameters/sort'
        - $ref: 'DefinitionsLibrary.yaml#/components/parameters/filter'
      responses:
        200:
          description: Success.
          content:
            'application/json':
              schema:
                $ref: 'DefinitionsLibrary.yaml#/components/schemas/DeploymentTaskSearchResults'
      x-required-privileges:
        - Read Jamf Protect Deployments

  /v1/jamf-protect/deployments/{id}/tasks/retry:
    post:
      tags:
        - jamf-protect
      summary: |
        Request a retry of Protect install tasks
      description: |
        Request a retry of Protect install tasks
      parameters:
        - name: id
          in: path
          required: true
          description: the UUID of the deployment associated with the retry
          example: 24a7bb2a-9871-4895-9009-d1be07ed31b1
          schema:
            type: string
      requestBody:
        description: task IDs to retry
        content:
          'application/json':
            schema:
              $ref: 'DefinitionsLibrary.yaml#/components/schemas/Ids'
        required: true
      responses:
        204:
          description: Success, no content.
        400:
          description: Cloud Services Connection has not been established.
          content:
            'application/json':
              schema:
                $ref: 'DefinitionsLibrary.yaml#/components/schemas/ApiError'
        500:
          description: Jamf Protect tasks to retry failed
          content:
            'application/json':
              schema:
                $ref: 'DefinitionsLibrary.yaml#/components/schemas/ApiError'
      x-required-privileges:
        - Jamf Protect Deployment Retry
      x-action: true
