openapi: 3.0.1
info:
  title: Jamf Pro API - Jamf App Shared Objects
  version: 0.0.1
paths: {}
components:
  schemas:
    ProtectSettingsResponse:
      type: object
      properties:
        id:
          type: string
          example: 1
          nullable: false
        apiClientId:
          type: string
          example: esgzYzYBqN7wCImwyusbQcXob2qalGMN
        apiClientName:
          type: string
          example: Jamf Pro integration
          description: display name used when creating the API Client in the Jamf Protect web console
        registrationId:
          type: string
          example: 6f250316-2cfb-4521-8cb7-bfaf46497bc5
          description: ID used when making requests to identify this particular Protect registration.
        protectUrl:
          type: string
          example: https://examplejamfprotect.jamfcloud.com/graphql
        platformPlanSync:
          type: boolean
          example: true
          description: determines whether Protect Platform Plan syncing is enabled
        lastSyncTime:
          type: string
          example: 2003-01-05T18:00:14.885Z
        syncStatus:
          type: string
          enum:
            - IN_PROGRESS
            - COMPLETED
            - ERROR
            - UNKNOWN
          example: COMPLETED
        autoInstall:
          type: boolean
          example: true
          description: determines whether the Jamf Protect agent will be automatically installed on client computers
    DeploymentTaskSearchResults:
      type: object
      properties:
        totalCount:
          type: integer
          example: 13
        results:
          type: array
          items:
            $ref: '#/components/schemas/DeploymentTask'
    DeploymentTask:
      type: object
      properties:
        id:
          readOnly: true
          type: string
          example: 82
        computerId:
          readOnly: true
          type: string
          example: 111
        computerName:
          readOnly: true
          type: string
          example: Polka dot Stratocaster
        version:
          readOnly: true
          type: string
          example: 2.3.4
        updated:
          readOnly: true
          type: string
          format: date-time
          example: 2021-05-07T21:20:34.350Z
        status:
          type: string
          enum:
            - COMMAND_QUEUED
            - NO_COMMAND
            - PENDING_MANIFEST
            - COMPLETE
            - GAVE_UP
            - UNKNOWN
          description: >
            Status of this Jamf Connect deployment task. "Command" below refers to an `InstallEnterpriseApplication` command.
            Tasks that are not finished (i.e., `COMPLETE` or `GAVE_UP`) are evaluated once every thirty minutes, so the status
            value for a device may lag behind a successful Jamf Connect package install up to thirty minutes.
            * `COMMAND_QUEUED` - command has been queued
            * `NO_COMMAND` - command has not yet been queued
            * `PENDING_MANIFEST` - task is waiting to obtain a valid package manifest before a command can be queued
            * `COMPLETE` - command has been completed successfully
            * `GAVE_UP` - the command failed with an error or the device did not process it in a reasonable amount of time
            * `UNKNOWN` - unknown; tasks in this state will be evaluated
          example: COMPLETE
    PlanSearchResults:
      type: object
      properties:
        totalCount:
          type: integer
          example: 3
          nullable: false
        results:
          type: array
          items:
            $ref: '#/components/schemas/JamfProtectPlan'
    JamfProtectPlan:
      type: object
      properties:
        uuid:
          type: string
          example: b999dfd3-8fde-4bf2-aa56-b167c8b68071
          readOnly: true
          nullable: false
        id:
          type: string
          example: d265dfd3-8fde-4bf2-aa56-b167c8b68069
          readOnly: true
        name:
          type: string
          example: Main Plan
          readOnly: true
        description:
          type: string
          example: Plan for the majority of the company's computers
          readOnly: true
        profileId:
          type: integer
          example: 12
          readOnly: true
        profileName:
          type: string
          example: Main Plan (Jamf Protect)
          readOnly: true
        profileVersion:
          type: integer
          example: 1
          readOnly: true
        scopeDescription:
          type: string
          example: All Computers
          readOnly: true
        siteId:
          type: string
          example: "-1"
          readOnly: true
  parameters:
    sort:
      name: sort
      in: query
      description: 'Sorting criteria in the format: property:asc/desc. Default sort
        order is descending. Multiple sort criteria are supported and must be entered
        on separate lines in Swagger UI. In the URI the ''sort'' query param is not
        duplicated for each sort criterion, e.g., ...&sort=name:asc,date:desc.
        Fields that can be sorted: status, updated'
      style: form
      explode: true
      schema:
        type: array
        items:
          type: string
        default: []
    filter:
      name: filter
      in: query
      description: 'Query in the RSQL format, allowing to filter results.
        Default filter is empty query - returning all results for the requested page.
        Fields allowed in the query: status, updated, version
        This param can be combined with paging and sorting.
        Example: filter=username!=admin and details==*disabled* and date<2019-12-15'
      schema:
        type: string
        default: ''
