openapi: 3.0.1
info:
    title: Jamf Pro API - Jamf Remote Assist Definitions Library
    description: These Jamf Remote Assist definitions exist to be re-used by multiple other Swagger files.
    version: 0.0.1
paths: { }
components:
    schemas:
        SessionHistoryItem:
            type: object
            properties:
                tenantId:
                    nullable: false
                    type: string
                    example: "ee5d0ffae49e675d32ba5bdb2ce25182e958b979afc8d210c924d725bbf45f8b"
                sessionId:
                    nullable: false
                    type: string
                    example: 'c4087bc8-cb48-4452-9bec-a3c50088a485'
                deviceId:
                    type: string
                    example: 'aeafd2ff95c7e0b937a8dbf3121a8dcab7a70161cd4493af038fa9c784b61866'
                sessionStartedTimestamp:
                    type: string
                    format: date-time
                    example: '2023-11-07T10:25:27.490Z'
                sessionEndedTimestamp:
                    type: string
                    format: date-time
                    example: '2023-11-07T10:25:27.490Z'
                sessionType:
                    type: string
                    enum:
                        - ATTENDED
                        - UNATTENDED
                    example: ATTENDED
                statusType:
                    type: string
                    enum:
                        - STARTED
                        - FINISHED
                        - ERROR
                    example: STARTED
                sessionAdminId:
                    type: string
                    example: 'sessionAdminId1'
                comment:
                    type: string
                    example: 'Example comment'

        SessionHistoryItemWithDetails:
            type: object
            properties:
                tenantId:
                    nullable: false
                    type: string
                    example: "ee5d0ffae49e675d32ba5bdb2ce25182e958b979afc8d210c924d725bbf45f8b"
                sessionId:
                    nullable: false
                    type: string
                    example: 'c4087bc8-cb48-4452-9bec-a3c50088a485'
                deviceId:
                    type: string
                    example: 'aeafd2ff95c7e0b937a8dbf3121a8dcab7a70161cd4493af038fa9c784b61866'
                sessionStartedTimestamp:
                    type: string
                    format: date-time
                    example: '2023-11-07T10:25:27.490Z'
                sessionEndedTimestamp:
                    type: string
                    format: date-time
                    example: '2023-11-07T10:25:27.490Z'
                sessionType:
                    type: string
                    enum:
                        - ATTENDED
                        - UNATTENDED
                    example: ATTENDED
                statusType:
                    type: string
                    enum:
                        - STARTED
                        - FINISHED
                        - ERROR
                    example: STARTED
                sessionAdminId:
                    type: string
                    example: 'sessionAdminId1'
                comment:
                    type: string
                    example: 'Example comment'
                details:
                    $ref: '#/components/schemas/SessionHistoryItemDetails'

        SessionHistoryItemDetails:
            type: object
            properties:
                fileTransferItemList:
                    nullable: false
                    type: array
                    items:
                        $ref: '#/components/schemas/FileTransferItem'

        FileTransferItem:
            type: object
            properties:
                filePath:
                    nullable: false
                    type: string
                    example: '/SomeFilePath/ToFile.xml'
                transferTimestamp:
                    nullable: false
                    type: string
                    format: date-time
                    example: '2023-11-07T10:25:27.490Z'
                fileTransferType:
                    nullable: false
                    type: string
                    enum:
                        - DOWNLOAD
                        - UPLOAD
                    example: DOWNLOAD
