info:
  title: Jamf Pro API - JamfProtectDeploymentTasks
  version: 0.0.1
openapi: 3.0.1
paths:
  /v1/jamf-protect/deployments/{id}/tasks:
    get:
      description: Search for config profiles linked to Jamf Protect
      parameters:
        - description: the UUID of the Jamf Protect deployment
          example: 24a7bb2a-9871-4895-9009-d1be07ed31b1
          explode: false
          in: path
          name: id
          required: true
          schema:
            type: string
          style: simple
        - $ref: _MonolithLibrary.yaml#/components/parameters/page
        - $ref: _MonolithLibrary.yaml#/components/parameters/page-size
        - $ref: _MonolithLibrary.yaml#/components/parameters/sort
        - $ref: _MonolithLibrary.yaml#/components/parameters/filter
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: _MonolithLibrary.yaml#/components/schemas/DeploymentTaskSearchResults
          description: Success.
      summary: |
        Search for deployment tasks for a config profile linked to Jamf Protect
      tags:
        - jamf-protect
      x-required-privileges:
        - Read Jamf Protect Deployments
  /v1/jamf-protect/deployments/{id}/tasks/retry:
    post:
      description: |
        Request a retry of Protect install tasks
      parameters:
        - description: the UUID of the deployment associated with the retry
          example: 24a7bb2a-9871-4895-9009-d1be07ed31b1
          explode: false
          in: path
          name: id
          required: true
          schema:
            type: string
          style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: _MonolithLibrary.yaml#/components/schemas/Ids
        description: task IDs to retry
        required: true
      responses:
        204:
          description: Success, no content.
        400:
          content:
            application/json:
              schema:
                $ref: _MonolithLibrary.yaml#/components/schemas/ApiError
          description: Cloud Services Connection has not been established.
        500:
          content:
            application/json:
              schema:
                $ref: _MonolithLibrary.yaml#/components/schemas/ApiError
          description: Jamf Protect tasks to retry failed
      summary: |
        Request a retry of Protect install tasks
      tags:
        - jamf-protect
      x-action: true
      x-required-privileges:
        - Jamf Protect Deployment Retry
servers:
  - url: /api
