components:
  schemas:
    SessionHistorySearchResults:
      properties:
        results:
          items:
            $ref: _MonolithLibrary.yaml#/components/schemas/SessionHistoryItem
          type: array
        totalCount:
          example: 100
          type: integer
      required:
        - results
        - totalCount
      type: object
info:
  title: Jamf Pro API - JamfRemoteAssistSessionHistoryV2
  version: 0.0.1
openapi: 3.0.1
paths:
  /v2/jamf-remote-assist/session:
    get:
      description: |
        Returns tenants sessions history.
      parameters:
        - $ref: _MonolithLibrary.yaml#/components/parameters/page
        - $ref: _MonolithLibrary.yaml#/components/parameters/page-size
        - description: 'Sorting criteria in the format: property:asc/desc. Default sort is sessionId:desc. Multiple sort criteria are supported and must be separated with a comma. Example: sort=sessionId:desc,deviceId:asc '
          explode: true
          in: query
          name: sort
          required: false
          schema:
            default:
              - sessionId:desc
            items:
              type: string
            type: array
          style: form
        - description: 'Query in the RSQL format, allowing to filter session history items collection. Default filter is empty query - returning all results for the requested page. Fields allowed in the query: sessionId, deviceId, sessionAdminId. This param can be combined with paging and sorting. Example: sessionAdminId=="*Andrzej*"'
          explode: true
          in: query
          name: filter
          required: false
          schema:
            default: ""
            type: string
          style: form
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SessionHistorySearchResults'
          description: Up to 100 latest session history items
        403:
          content:
            application/json:
              schema:
                $ref: _MonolithLibrary.yaml#/components/schemas/ApiError
          description: Jamf Remote Assist is not available on this instance.
      summary: |
        Gets session history items.
      tags:
        - jamf-remote-assist
      x-required-privileges:
        - Read Remote Assist
  /v2/jamf-remote-assist/session/export:
    post:
      description: |
        Export Jamf Remote Assist sessions history
      requestBody:
        content:
          application/json:
            schema:
              $ref: _MonolithLibrary.yaml#/components/schemas/ExportParameters
        description: Optional. Override query parameters since they can make URI exceed 2,000 character limit.
        required: false
      responses:
        200:
          content:
            text/csv:
              schema:
                example: |
                  sessionId,deviceId
                  c4087bc8-cb48-4452-9bec-a3c50088a485,aeafd2ff95c7e0b937a8dbf3121a8dcab7a70161cd4493af038fa9c784b61866
                  c4087bc8-cb48-4452-9bec-a3c50088a486,aeafd2ff95c7e0b937a8dbf3121a8dcab7a70161cd4493af038fa9c784b61867
                  c4087bc8-cb48-4452-9bec-a3c50088a487,aeafd2ff95c7e0b937a8dbf3121a8dcab7a70161cd4493af038fa9c784b61868
                format: binary
          description: Export successful
        400:
          content:
            application/json:
              schema:
                $ref: _MonolithLibrary.yaml#/components/schemas/ApiError
          description: Export fields specified incorrectly - non-existing column or duplicate on the list.
        403:
          content:
            application/json:
              schema:
                $ref: _MonolithLibrary.yaml#/components/schemas/ApiError
          description: Jamf Remote Assist is not available on this instance.
        503:
          content:
            application/json:
              schema:
                $ref: _MonolithLibrary.yaml#/components/schemas/ApiError
          description: Export currently unavailable, all export-related resources are in use. Try again later.
      summary: |
        Export Jamf Remote Assist sessions history
      tags:
        - jamf-remote-assist
      x-action: true
      x-required-privileges:
        - Read Remote Assist
  /v2/jamf-remote-assist/session/{id}:
    get:
      description: |
        Returns tenants session history for specific session.
      parameters:
        - description: instance id of session
          explode: false
          in: path
          name: id
          required: true
          schema:
            type: string
          style: simple
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: _MonolithLibrary.yaml#/components/schemas/SessionHistoryItemWithDetails
          description: Single session history item
        403:
          content:
            application/json:
              schema:
                $ref: _MonolithLibrary.yaml#/components/schemas/ApiError
          description: Jamf Remote Assist is not available on this instance.
        404:
          content:
            application/json:
              schema:
                $ref: _MonolithLibrary.yaml#/components/schemas/ApiError
          description: Session history item not found. This may occur when the session with the given id does not exist.
      summary: |
        Gets single session history item.
      tags:
        - jamf-remote-assist
      x-required-privileges:
        - Read Remote Assist
servers:
  - url: /api
