components:
  schemas:
    JamfProVersion:
      properties:
        version:
          example: 10.9.0
          type: string
      type: object
info:
  title: Jamf Pro API - JamfProVersion
  version: 0.0.1
openapi: 3.0.1
paths:
  /v1/jamf-pro-version:
    get:
      description: |
        Returns information about the Jamf Pro including the current version.
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/JamfProVersion'
          description: Successful response
      summary: |
        Return information about the Jamf Pro including the current version
      tags:
        - jamf-pro-version
      x-authentication-required: true
servers:
  - url: /api
