components:
  schemas:
    JamfProInformationV2:
      properties:
        byodEnabled:
          default: false
          deprecated: true
          description: |
            **Deprecated as of 11.25.** This field always returns false.
          readOnly: true
          type: boolean
        cloudDeploymentsEnabled:
          example: false
          type: boolean
        depAccountEnabled:
          example: false
          type: boolean
        patchEnabled:
          example: false
          type: boolean
        smtpEnabled:
          example: false
          type: boolean
        ssoSamlEnabled:
          example: false
          type: boolean
        userMigrationEnabled:
          example: false
          type: boolean
        vppTokenEnabled:
          example: false
          type: boolean
      type: object
info:
  title: Jamf Pro API - JamfProInformation
  version: 0.0.1
openapi: 3.0.1
paths:
  /v2/jamf-pro-information:
    get:
      description: |
        Get basic information about the Jamf Pro Server
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/JamfProInformationV2'
          description: Successful response
      summary: |
        Get basic information about the Jamf Pro Server
      tags:
        - jamf-pro-information
      x-authentication-required: true
servers:
  - url: /api
