components:
  schemas:
    JamfProServerUrl:
      properties:
        url:
          example: https://example.com:8443
          type: string
      required:
        - url
      type: object
info:
  title: Jamf Pro API - JamfProServerUrl
  version: 0.0.1
openapi: 3.0.1
paths:
  /v1/jamf-pro-server-url:
    get:
      description: Get Jamf Pro Server URL settings
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/JamfProServerUrl'
          description: Successful response
      summary: |
        Get Jamf Pro Server URL settings
      tags:
        - jamf-pro-server-url-preview
      x-required-privileges:
        - Read JSS URL
    put:
      description: Update Jamf Pro Server URL settings
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/JamfProServerUrl'
        description: Jamf Pro Server URL settings object
        required: true
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/JamfProServerUrl'
          description: Jamf Pro Server URL settings updated
        403:
          content:
            application/json:
              schema:
                $ref: _MonolithLibrary.yaml#/components/schemas/ApiError
          description: Jamf Pro Server URL is managed by Jamf Cloud
      summary: |
        Update Jamf Pro Server URL settings
      tags:
        - jamf-pro-server-url-preview
      x-required-privileges:
        - Update JSS URL
  /v1/jamf-pro-server-url/history:
    get:
      description: Gets Jamf Pro Server URL settings history
      parameters:
        - $ref: _MonolithLibrary.yaml#/components/parameters/page
        - $ref: _MonolithLibrary.yaml#/components/parameters/size
        - $ref: _MonolithLibrary.yaml#/components/parameters/pagesize
        - $ref: _MonolithLibrary.yaml#/components/parameters/page-size
        - description: 'Sorting criteria in the format: property:asc/desc. Default sort is date:desc. Multiple sort criteria are supported and must be separated with a comma. Example: sort=date:desc,name:asc '
          explode: true
          in: query
          name: sort
          required: false
          schema:
            default: date:desc
            type: string
          style: form
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: _MonolithLibrary.yaml#/components/schemas/HistorySearchResults
          description: Details of Jamf Pro Server URL settings history were found
      summary: |
        Get Jamf Pro Server URL settings history
      tags:
        - jamf-pro-server-url-preview
      x-required-privileges:
        - Read JSS URL
    post:
      description: Adds Jamf Pro Server URL settings history notes
      requestBody:
        content:
          application/json:
            schema:
              $ref: _MonolithLibrary.yaml#/components/schemas/ObjectHistoryNote
        description: History notes to create
        required: true
      responses:
        201:
          content:
            application/json:
              schema:
                $ref: _MonolithLibrary.yaml#/components/schemas/ObjectHistory
          description: Notes to Jamf Pro Server URL settings history were added
        403:
          content:
            application/json:
              schema:
                $ref: _MonolithLibrary.yaml#/components/schemas/ApiError
          description: Jamf Pro Server URL is managed by Jamf Cloud
        503:
          content:
            application/json:
              schema:
                $ref: _MonolithLibrary.yaml#/components/schemas/ApiError
          description: Jamf Pro Server URL history does not exist.
      summary: |
        Add Jamf Pro Server URL settings history notes
      tags:
        - jamf-pro-server-url-preview
      x-required-privileges:
        - Update JSS URL
servers:
  - url: /api
