components:
  schemas:
    Credentials:
      properties:
        accessKeyID:
          example: TESTYBLF477T5THW6BNN
          format: password
          nullable: false
          type: string
        bucketName:
          example: sbox-test-bucket
          nullable: false
          type: string
        expiration:
          example: 1678386302
          format: int64
          nullable: false
          type: integer
        path:
          example: tmp/fc041b05-516e-4bde-9882-a08b1cc5473c/
          nullable: false
          type: string
        region:
          example: us-east-1
          nullable: false
          type: string
        secretAccessKey:
          example: tEstNvpw2AC9mggf08/Yw7krkPfYxWNoByGClLr7
          format: password
          nullable: false
          type: string
        sessionToken:
          example: TEsTb3JpZ2luX2VjEKr//////////wEaCXVzLWVhc3QtMSJHMEUCIQCwp+L32PlSQjeb/Pimk3AUPv3SADpSQv22pK2YqpOjhAIgDfrMNA9asxymToN9ntJrXn9i0bbOhkPAmewDBJ9RqCsqrQIIYxADGgw1NTI2NTM4ODEzMTkiDCmmPWNQKIMfmVIXNSqKAlWem+7n2ApbcAlPxtl5l8mQJz5wqPaUuBlwhuG9Fn7dPUeaHA6ZZjrEegjJOvMkATPEfoD/2o272WXegzC+VVuadrRP+x+pmSnkikqNVz43t6csUTZC61GXsEcsfgRcLHauRoR6vq9aVPRYXckztGjmFb4GpICbR/wc94nJZ6Yw1YZ63UrmEdnJIKSvy/tAoFhJuufy/JOFQEuyW/N38bg+d/xLMNfhMMUSfOE9TOFlI9gOvyOPQVBocckknPD+HWj+nin1SSIy+mH6wMoZNYdRe/J8d5lmjgeiL7l/FmdMmbB7vDdPGCe5hPvJwGpGv6FRnk31NZNFNP//csVTVszGiUmRuY3R2hPUMO6sqKAGOp0BvZ5WAPpip/YMfvCzkzLI0EHlLwHHenor0IenM75eCW+pGqJreU/VIbadRyzncUL4zIa3DBKxgIP/h5uFoSm0ZGdQSAovXtHRQwDBNhdksvqsxQsExn8BjjLh6tFVkBGb4IXY9sS5K7tIwnqOtcT1FEYxQ08RqkJAaP08eCIYbBrWW71S2bNUfIv6KFOG77pz88vw9vHOjxVRjTrfCQ==
          nullable: false
          type: string
        uuid:
          example: fc041b05-516e-4bde-9882-a08b1cc5473c
          nullable: false
          type: string
      type: object
    DownloadUrl:
      description: The URL to download a file from.
      properties:
        uri:
          example: https://example.cloudfront.net/96213b8b-a3ab-487d?response-content-disposition=attachment%3B+filename%3D%226gb.pkg%22&Expires=1678908843&Signature=hLsNd2__&Key-Pair-Id=K32YV
          nullable: false
          type: string
      type: object
    FileData:
      description: Metadata pertaining to the file.
      properties:
        fileName:
          description: The name of the file
          example: test.txt
          nullable: false
          readOnly: true
          type: string
        length:
          description: The length in bytes
          example: 1321654
          nullable: false
          readOnly: true
          type: integer
        md5:
          description: The MD5 in hex
          example: 9e47d8266df642dc2c3cd73206189781
          nullable: false
          readOnly: true
          type: string
        region:
          description: The region the file is hosted in
          example: us-east-1
          nullable: false
          readOnly: true
          type: string
        sha3:
          description: The SHA3_512 in hex
          example: 4b2c9436a4e3e330bad91eaa55b66591cd4823548a681eff970b9b949d96201f8c6862ba8308dac1fdf53b9f4356d287bd1062b4f4b89dc2205d9f15776fd58f
          nullable: false
          readOnly: true
          type: string
      type: object
info:
  title: Jamf Pro API - Jcds
  version: 0.0.1
openapi: 3.0.1
paths:
  /v1/jcds/files:
    get:
      deprecated: true
      description: Retrieve a list of files and file metadata from the Jamf Cloud Distribution Service.
      responses:
        200:
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/FileData'
                minItems: 0
                type: array
          description: Retrieved the list of files and file metadata from the Jamf Cloud Distribution Service.
      summary: Retrieve a list of files and file metadata from the Jamf Cloud Distribution Service
      tags:
        - jamf-cloud-distribution-service
      x-authentication-required: true
      x-deprecation-date: "2025-08-28"
      x-required-privileges:
        - Read Jamf Cloud Distribution Service Files
    post:
      deprecated: true
      description: Creates a temporary record and returns the credentials and information needed for uploading the file to the Jamf Cloud Distribution Service.
      responses:
        201:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Credentials'
          description: File upload was initiated to the Jamf Cloud Distribution Service.
      summary: Initiate an upload to the Jamf Cloud Distribution Service
      tags:
        - jamf-cloud-distribution-service
      x-action: true
      x-authentication-required: true
      x-deprecation-date: "2025-08-28"
      x-required-privileges:
        - Create Jamf Cloud Distribution Service Files
  /v1/jcds/files/{fileName}:
    delete:
      deprecated: true
      description: Delete a file by filename from the Jamf Cloud Distribution Service.
      parameters:
        - description: Name of the file that will be deleted from the Jamf Cloud Distribution Service.
          explode: false
          in: path
          name: fileName
          required: true
          schema:
            type: string
          style: simple
      responses:
        204:
          description: File was deleted
      summary: Delete a file from the Jamf Cloud Distribution Service
      tags:
        - jamf-cloud-distribution-service
      x-authentication-required: true
      x-deprecation-date: "2025-08-28"
      x-required-privileges:
        - Delete Jamf Cloud Distribution Service Files
    get:
      deprecated: true
      description: Retrieve a download URL for a specific file from the Jamf Cloud Distribution Service.
      parameters:
        - description: Name of the file stored in the Jamf Cloud Distribution Service.
          explode: false
          in: path
          name: fileName
          required: true
          schema:
            type: string
          style: simple
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DownloadUrl'
          description: The URL to download the file from was retrieved.
      summary: Retrieve a download URL for a specific file from the Jamf Cloud Distribution Service
      tags:
        - jamf-cloud-distribution-service
      x-authentication-required: true
      x-deprecation-date: "2025-08-28"
      x-required-privileges:
        - Read Jamf Cloud Distribution Service Files
  /v1/jcds/refresh-inventory:
    post:
      deprecated: true
      description: "Refreshes the inventory and status of uploads in Jamf Pro. This will update the \nstatus of uploads in the Jamf Pro database and allow the uploads to be deployed.\nUsing the filename as a query parameter will query JCDS for the availability of\nthe file using an exponential back-off during the allocated time period. If the\nfilename is not supplied, all inventory will be refreshed, and this action is\nlimited to once every 15 seconds.\n"
      parameters:
        - description: Name of the file to check the availability of in JCDS. If available, the inventory and status will be updated in Jamf Pro. If no file is specified, it will force an immediate inventory refresh at a rate-limit of once every 15 seconds.
          explode: true
          in: query
          name: file-name
          required: false
          schema:
            default: ""
            example: filename.pkg
            maxLength: 255
            type: string
          style: form
      responses:
        204:
          description: Inventory refresh completed.
        500:
          content:
            application/json:
              schema:
                $ref: _MonolithLibrary.yaml#/components/schemas/ApiError
          description: Failure, unable to complete inventory refresh.
      summary: "Refreshes the inventory and status of uploads in Jamf Pro. This will update the \nstatus of uploads in the Jamf Pro database and allow the uploads to be deployed.\n"
      tags:
        - jamf-cloud-distribution-service
      x-action: true
      x-authentication-required: true
      x-deprecation-date: "2025-08-28"
      x-required-privileges:
        - Read Jamf Cloud Distribution Service Files
  /v1/jcds/renew-credentials:
    post:
      deprecated: true
      description: Renews the credentials needed for uploading the file to the Jamf Cloud Distribution Service.
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Credentials'
          description: Credentials were renewed for an upload to the Jamf Cloud Distribution Service.
      summary: Renew credentials for an upload to the Jamf Cloud Distribution Service
      tags:
        - jamf-cloud-distribution-service
      x-action: true
      x-authentication-required: true
      x-deprecation-date: "2025-08-28"
      x-required-privileges:
        - Create Jamf Cloud Distribution Service Files
servers:
  - url: /api
