components:
  schemas:
    LdapGroup:
      description: An LDAP group.
      properties:
        distinguishedName:
          example: Grade School Teachers
          type: string
        id:
          example: "1"
          type: string
        ldapServerId:
          example: 1
          type: integer
        name:
          example: Grade School Teachers
          type: string
        uuid:
          example: 89AF33FC-123C-1231-AEFD-9C3ED123AFCC
          type: string
      type: object
    LdapGroupSearchResults:
      properties:
        results:
          items:
            $ref: '#/components/schemas/LdapGroup'
          type: array
        totalCount:
          example: 3
          minimum: 0
          type: integer
      type: object
    LdapServer:
      description: An LDAP Server.
      properties:
        id:
          example: 1
          type: integer
        name:
          example: Server name
          type: string
      type: object
info:
  title: Jamf Pro API - LdapRs
  version: 0.0.1
openapi: 3.0.1
paths:
  /ldap/groups:
    get:
      description: Retrieves the configured access groups that contain the text in the searchParam.
      parameters:
        - description: Will perform a "contains" search on the names of access groups
          explode: true
          in: query
          name: q
          required: false
          schema:
            default: "null"
            type: string
          style: form
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LdapGroupSearchResults'
          description: Successful search.
      summary: |
        Retrieve the configured access groups that contain the text in the search param
      tags:
        - ldap
      x-required-privileges:
        - Read LDAP Servers
  /ldap/servers:
    get:
      description: Retrieve all Servers including LDAP and Cloud Identity Providers.
      responses:
        200:
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/LdapServer'
                type: array
          description: Successfully completed.
      summary: |
        Retrieve all Servers including LDAP and Cloud Identity Providers.
      tags:
        - ldap
      x-required-privileges:
        - Read LDAP Servers
  /v1/ldap/groups:
    get:
      description: Retrieves the configured access groups that contain the text in the searchParam.
      parameters:
        - description: Will perform a "contains" search on the names of access groups
          explode: true
          in: query
          name: q
          required: false
          schema:
            default: "null"
            type: string
          style: form
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LdapGroupSearchResults'
          description: Successful search.
      summary: |
        Retrieve the configured access groups that contain the text in the search param
      tags:
        - ldap
      x-required-privileges:
        - Read LDAP Servers
  /v1/ldap/ldap-servers:
    get:
      description: Retrieves all not migrated, LDAP Servers.
      responses:
        200:
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/LdapServer'
                type: array
          description: Successfully completed.
      summary: |
        Retrieve all LDAP Servers.
      tags:
        - ldap
      x-required-privileges:
        - Read LDAP Servers
  /v1/ldap/servers:
    get:
      description: Retrieve all active Servers including LDAP and Cloud Identity Providers.
      responses:
        200:
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/LdapServer'
                type: array
          description: Successfully completed.
      summary: |
        Retrieve all Servers including LDAP and Cloud Identity Providers.
      tags:
        - ldap
      x-required-privileges:
        - Read LDAP Servers
servers:
  - url: /api
