openapi: 3.0.1
info:
  title: Jamf Pro API - LDAP
  version: 0.0.1
paths:
  /v1/ldap/groups:
    get:
      tags:
        - ldap
      summary: |
        Retrieve the configured access groups that contain the text in the search param
      description: Retrieves the configured access groups that contain the text in
        the searchParam.
      parameters:
        - name: q
          in: query
          description: Will perform a "contains" search on the names of access groups
          schema:
            type: string
            default: 'null'
      responses:
        200:
          description: Successful search.
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/LdapGroupSearchResults'
      x-required-privileges:
        - Read LDAP Servers
  /v1/ldap/servers:
    get:
      tags:
        - ldap
      summary: |
        Retrieve all Servers including LDAP and Cloud Identity Providers.
      description: Retrieve all active Servers including LDAP and Cloud Identity Providers.
      responses:
        200:
          description: Successfully completed.
          content:
            'application/json':
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/LdapServer'
      x-required-privileges:
        - Read LDAP Servers
  /v1/ldap/ldap-servers:
    get:
      tags:
        - ldap
      summary: |
        Retrieve all LDAP Servers.
      description: Retrieves all not migrated, LDAP Servers.
      responses:
        200:
          description: Successfully completed.
          content:
            'application/json':
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/LdapServer'
      x-required-privileges:
        - Read LDAP Servers
  /ldap/groups:
    get:
      tags:
      - ldap
      summary: |
         Retrieve the configured access groups that contain the text in the search param
      description: Retrieves the configured access groups that contain the text in
        the searchParam.
      parameters:
      - name: q
        in: query
        description: Will perform a "contains" search on the names of access groups
        schema:
          type: string
          default: 'null'
      responses:
        200:
          description: Successful search.
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/LdapGroupSearchResults'
      x-required-privileges:
      - Read LDAP Servers
  /ldap/servers:
    get:
      tags:
      - ldap
      summary: |
         Retrieve all Servers including LDAP and Cloud Identity Providers.
      description: Retrieve all Servers including LDAP and Cloud Identity Providers.
      responses:
        200:
          description: Successfully completed.
          content:
            'application/json':
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/LdapServer'
      x-required-privileges:
      - Read LDAP Servers
components:
  schemas:
    LdapGroup:
      type: object
      properties:
        id:
          type: string
          example: 1
        uuid:
          type: string
          example: 89AF33FC-123C-1231-AEFD-9C3ED123AFCC
        ldapServerId:
          type: integer
          example: 1
        name:
          type: string
          example: Grade School Teachers
        distinguishedName:
          type: string
          example: Grade School Teachers
      description: An LDAP group.
    LdapGroupSearchResults:
      type: object
      properties:
        totalCount:
          minimum: 0
          type: integer
          example: 3
        results:
          type: array
          items:
            $ref: '#/components/schemas/LdapGroup'
    LdapServer:
      type: object
      properties:
        id:
          type: integer
          example: 1
        name:
          type: string
          example: Server name
      description: An LDAP Server.
