components:
  schemas:
    Locale:
      properties:
        description:
          example: English (United States)
          type: string
        identifier:
          example: en_US
          type: string
      type: object
info:
  title: Jamf Pro API - Locale
  version: 0.0.1
openapi: 3.0.1
paths:
  /v1/locales:
    get:
      description: |
        Returns locales that can be used in other features.
      responses:
        200:
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/Locale'
                type: array
          description: Successful response
      summary: |
        Return locales that can be used in other features
      tags:
        - locales-preview
      x-authentication-required: false
servers:
  - url: /api
