components:
  schemas:
    LoginContent:
      properties:
        actionText:
          example: Accept
          nullable: false
          type: string
        disclaimerHeading:
          example: Disclaimer header
          nullable: false
          type: string
        disclaimerMainText:
          example: Login disclaimer main text
          nullable: false
          type: string
        fedRampInstance:
          example: false
          nullable: false
          type: boolean
        highComplianceInstance:
          example: false
          nullable: false
          type: boolean
        includeCustomDisclaimer:
          example: true
          nullable: false
          type: boolean
        rampInstance:
          example: false
          nullable: false
          type: boolean
      required:
        - includeCustomDisclaimer
      type: object
    LoginContentPut:
      properties:
        actionText:
          example: Accept
          nullable: false
          type: string
        disclaimerHeading:
          example: Disclaimer header
          nullable: false
          type: string
        disclaimerMainText:
          example: Login disclaimer main text
          nullable: false
          type: string
        includeCustomDisclaimer:
          example: true
          nullable: false
          type: boolean
      required:
        - includeCustomDisclaimer
      type: object
info:
  title: Jamf Pro API - LoginCustomization
  version: 0.0.1
openapi: 3.0.1
paths:
  /v1/login-customization:
    get:
      description: Returns knob whether disclaimer is enabled and if saved, its contents.
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LoginContent'
          description: Get Login Customization disclaimer settings.
      summary: Get current login disclaimer settings
      tags:
        - login-customization
      x-authentication-required: true
    put:
      description: Update current login disclaimer settings.
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginContentPut'
        description: Login disclaimer settings to save.
        required: true
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LoginContentPut'
          description: Update login customization disclaimer settings.
      summary: Update current login disclaimer settings.
      tags:
        - login-customization
      x-authentication-required: true
      x-required-privileges:
        - Update Login Disclaimer
servers:
  - url: /api
