components:
  schemas:
    AvailableUpdates:
      properties:
        availableUpdates:
          example:
            - 12.0.1
            - 11.6.1
            - "11.6"
            - 11.5.2
          items:
            type: string
          type: array
      type: object
    MacOsManagedSoftwareUpdate:
      properties:
        applyMajorUpdate:
          default: false
          description: ApplyMajorUpdate setting is available only when updating to the latest version based on device eligibility. If no value is provided, the calculated latest version will only include minor version updates. If a value is provided, the calculated latest version will include minor and major version updates.
          example: false
          type: boolean
        deviceIds:
          example:
            - "1"
            - "2"
            - "3"
            - "4"
          items:
            type: string
          type: array
        forceRestart:
          default: false
          description: 'If not set, forceRestart will default to false. Can only be true if using the DownloadAndInstall install action and the devices the command is sent to are on macOs 11 or higher. If true, the DownloadAndInstall action is performed, a restart will be forced. MaxDeferral will be ignored if defined. '
          example: false
          type: boolean
        groupId:
          example: "1"
          type: string
        maxDeferrals:
          description: Allow users to defer the update the provided number of times before macOS forces the update. If a value is provided, the Software Update will use the InstallLater install action.
          example: 7
          minimum: 0
          type: integer
        priority:
          default: HIGH
          description: Priority can only be configured on macOS 12.3 and above, for minor updates only. Any version below 12.3 is always Low and cannot be changed until prerequisites are met. When qualified, if not explicitly set, priority will default to High
          enum:
            - HIGH
            - LOW
          example: HIGH
          type: string
        skipVersionVerification:
          default: false
          description: If no value is provided, the skipVersionVerification will default to false. If a value is provided, the specified version will be forced to complete DownloadAndInstall install action.
          example: false
          type: boolean
        updateAction:
          description: MaxDeferral is ignored if using the DownloadOnly install action.
          enum:
            - DOWNLOAD_AND_INSTALL
            - DOWNLOAD_ONLY
          example: DOWNLOAD_AND_INSTALL
          type: string
        version:
          description: If no value is provided, the version will default to latest version based on device eligibility.
          example: 12.0.1
          type: string
      type: object
    MacOsManagedSoftwareUpdateResponse:
      properties:
        errors:
          items:
            $ref: _MonolithLibrary.yaml#/components/schemas/ApiErrorCause
          type: array
        processManagerUuids:
          example:
            - 6E47EF55-5318-494F-A09E-70F613E0AFD1
            - 6E73EF55-5318-494F-A09E-70G613E0AFD1
          items:
            type: string
          type: array
      type: object
info:
  title: Jamf Pro API - MacOsManagedSoftwareUpdates
  version: 0.0.1
openapi: 3.0.1
paths:
  /v1/macos-managed-software-updates/available-updates:
    get:
      deprecated: true
      description: Retrieves available MacOs Managed Software Updates
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AvailableUpdates'
          description: Success
      summary: Retrieve available MacOs Managed Software Updates
      tags:
        - macos-managed-software-updates
      x-authentication-required: true
      x-deprecation-date: "2022-12-14"
  /v1/macos-managed-software-updates/send-updates:
    post:
      deprecated: true
      description: Sends MacOs Managed Software Updates
      requestBody:
        content:
          application/json:
            examples:
              MacOsManagedSoftwareUpdateDeviceIds:
                value:
                  applyMajorUpdate: false
                  deviceIds:
                    - "1"
                    - "2"
                    - "3"
                    - "4"
                  forceRestart: false
                  maxDeferrals: 7
                  priority: HIGH
                  skipVersionVerification: false
                  updateAction: DOWNLOAD_AND_INSTALL
                  version: 12.0.1
              MacOsManagedSoftwareUpdateGroupId:
                value:
                  applyMajorUpdate: false
                  forceRestart: false
                  groupId: 1
                  maxDeferrals: 7
                  priority: HIGH
                  skipVersionVerification: false
                  updateAction: DOWNLOAD_AND_INSTALL
                  version: 12.0.1
            schema:
              $ref: '#/components/schemas/MacOsManagedSoftwareUpdate'
        description: MacOs Managed Software Update to send
        required: true
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MacOsManagedSoftwareUpdateResponse'
          description: Success
        400:
          content:
            application/json:
              schema:
                $ref: _MonolithLibrary.yaml#/components/schemas/ApiError
          description: Bad Request
      summary: Send MacOs Managed Software Updates
      tags:
        - macos-managed-software-updates
      x-action: true
      x-deprecation-date: "2022-10-17"
      x-required-privileges:
        - Send Computer Remote Command to Download and Install OS X Update
servers:
  - url: /api
