components:
  schemas:
    AvailableOsUpdates:
      properties:
        availableUpdates:
          nullable: false
          properties:
            iOS:
              example:
                - 16.1.1
                - 16.0.1
                - 15.7.1
                - "9.1"
              items:
                type: string
              type: array
            macOS:
              example:
                - 12.0.1
                - 11.6.1
                - "11.6"
                - 11.5.2
              items:
                type: string
              type: array
          type: object
      type: object
    ManagedSoftwareUpdateStatus:
      properties:
        created:
          example: "2022-12-22T21:09:00.661Z"
          format: date-time
          type: string
        deferralsRemaining:
          description: not applicable to all managed software update statuses
          example: 4
          type: integer
        device:
          properties:
            deviceId:
              type: string
            href:
              type: string
            objectType:
              enum:
                - COMPUTER
                - MOBILE_DEVICE
                - APPLE_TV
              type: string
          type: object
        downloadPercentComplete:
          example: 0.8
          type: number
        downloaded:
          example: false
          type: boolean
        maxDeferrals:
          description: not applicable to all managed software update statuses
          example: 5
          type: integer
        nextScheduledInstall:
          description: not applicable to all managed software update statuses
          example: "2022-12-25T21:09:31.661Z"
          format: date-time
          type: string
        osUpdatesStatusId:
          example: "1"
          type: string
        pastNotifications:
          description: not applicable to all managed software update statuses
          example:
            - "2022-12-22T21:09:31.661Z"
            - "2022-12-23T21:09:31.661Z"
            - "2022-12-24T21:09:31.661Z"
          items:
            format: date-time
            type: string
          type: array
        productKey:
          example: iOSUpdate19F77
          type: string
        status:
          enum:
            - DOWNLOADING
            - IDLE
            - INSTALLING
            - INSTALLED
            - ERROR
            - DOWNLOAD_FAILED
            - DOWNLOAD_REQUIRES_COMPUTER
            - DOWNLOAD_INSUFFICIENT_SPACE
            - DOWNLOAD_INSUFFICIENT_POWER
            - DOWNLOAD_INSUFFICIENT_NETWORK
            - INSTALL_INSUFFICIENT_SPACE
            - INSTALL_INSUFFICIENT_POWER
            - INSTALL_PHONE_CALL_IN_PROGRESS
            - INSTALL_FAILED
            - UNKNOWN
          example: DOWNLOADING
          type: string
        updated:
          example: "2022-12-24T21:09:31.661Z"
          format: date-time
          type: string
      type: object
    ManagedSoftwareUpdateStatuses:
      properties:
        results:
          items:
            $ref: '#/components/schemas/ManagedSoftwareUpdateStatus'
          type: array
        totalCount:
          example: 1
          type: integer
      type: object
info:
  title: Jamf Pro API - ManagedSoftwareUpdates
  version: 0.0.1
openapi: 3.0.1
paths:
  /v1/managed-software-updates/available-updates:
    get:
      description: |
        Retrieves available macOS and iOS Managed Software Updates
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AvailableOsUpdates'
          description: Success
      summary: Retrieve available macOS and iOS Managed Software Updates
      tags:
        - managed-software-updates
      x-authentication-required: true
  /v1/managed-software-updates/update-statuses:
    get:
      description: |
        Retrieve Managed Software Update Statuses
      parameters:
        - description: 'Query in the RSQL format, allowing to filter Managed Software Updates collection. Default filter is empty query - returning all results for the requested page. Fields allowed in the query: osUpdatesStatusId, device.deviceId, device.objectType, downloaded, downloadPercentComplete, productKey, status, deferralsRemaining, maxDeferrals, nextScheduledInstall, created and updated.'
          explode: true
          in: query
          name: filter
          required: false
          schema:
            default: ""
            type: string
          style: form
      responses:
        200:
          content:
            application/json:
              examples:
                ComputerManagedSoftwareUpdateStatus:
                  value:
                    results:
                      - created: "2022-12-22T21:09:00.661Z"
                        deferralsRemaining: 5
                        device:
                          deviceId: 1
                          href: /v1/computers-inventory/1
                          objectType: COMPUTER
                        downloadPercentComplete: 0.8
                        downloaded: true
                        maxDeferrals: 5
                        nextScheduledInstall: "2022-12-25T21:09:31.661Z"
                        osUpdatesStatusId: "1"
                        pastNotifications:
                          - "2022-12-22T21:09:31.661Z"
                          - "2022-12-23T21:09:31.661Z"
                          - "2022-12-24T21:09:31.661Z"
                        productKey: macOSUpdate19F77
                        status: DOWNLOADING
                        updated: "2022-12-24T21:09:31.661Z"
                    totalCount: 1
                MobileDeviceManagedSoftwareUpdateStatus:
                  value:
                    results:
                      - created: "2022-12-22T21:09:00.661Z"
                        device:
                          deviceId: 1
                          href: /v2/mobile-devices/1
                          objectType: MOBILE_DEVICE
                        downloadPercentComplete: 0.8
                        downloaded: true
                        osUpdatesStatusId: "1"
                        productKey: iOSUpdate19F77
                        status: DOWNLOADING
                        updated: "2022-12-22T21:09:00.661Z"
                    totalCount: 1
              schema:
                $ref: '#/components/schemas/ManagedSoftwareUpdateStatuses'
          description: Success
      summary: Retrieve Managed Software Update Statuses
      tags:
        - managed-software-updates
      x-required-privileges:
        - Read Computers
        - Read Mobile Devices
  /v1/managed-software-updates/update-statuses/computer-groups/{id}:
    get:
      description: |
        Retrieve Managed Software Update Statuses for Computer Groups
      parameters:
        - description: Computer Group identifier
          explode: false
          in: path
          name: id
          required: true
          schema:
            type: string
          style: simple
      responses:
        200:
          content:
            application/json:
              examples:
                ComputerManagedSoftwareUpdateStatus:
                  value:
                    results:
                      - created: "2022-12-22T21:09:00.661Z"
                        deferralsRemaining: 5
                        device:
                          deviceId: 1
                          href: /v1/computers-inventory/1
                          objectType: COMPUTER
                        downloadPercentComplete: 0.8
                        downloaded: true
                        maxDeferrals: 5
                        nextScheduledInstall: "2022-12-25T21:09:31.661Z"
                        osUpdatesStatusId: "1"
                        pastNotifications:
                          - "2022-12-22T21:09:31.661Z"
                          - "2022-12-23T21:09:31.661Z"
                          - "2022-12-24T21:09:31.661Z"
                        productKey: macOSUpdate19F77
                        status: DOWNLOADING
                        updated: "2022-12-24T21:09:31.661Z"
                    totalCount: 1
              schema:
                $ref: '#/components/schemas/ManagedSoftwareUpdateStatuses'
          description: Success
      summary: Retrieve Managed Software Update Statuses for Computer Groups
      tags:
        - managed-software-updates
      x-required-privileges:
        - Read Computers
        - Read Smart Computer Groups
        - Read Static Computer Groups
  /v1/managed-software-updates/update-statuses/computers/{id}:
    get:
      description: |
        Retrieve Managed Software Update Statuses for Computers
      parameters:
        - description: Computer identifier
          explode: false
          in: path
          name: id
          required: true
          schema:
            type: string
          style: simple
      responses:
        200:
          content:
            application/json:
              examples:
                ComputerManagedSoftwareUpdateStatus:
                  value:
                    results:
                      - created: "2022-12-22T21:09:00.661Z"
                        deferralsRemaining: 5
                        device:
                          deviceId: 1
                          href: /v1/computers-inventory/1
                          objectType: COMPUTER
                        downloadPercentComplete: 0.8
                        downloaded: true
                        maxDeferrals: 5
                        nextScheduledInstall: "2022-12-25T21:09:31.661Z"
                        osUpdatesStatusId: "1"
                        pastNotifications:
                          - "2022-12-22T21:09:31.661Z"
                          - "2022-12-23T21:09:31.661Z"
                          - "2022-12-24T21:09:31.661Z"
                        productKey: macOSUpdate19F77
                        status: DOWNLOADING
                        updated: "2022-12-24T21:09:31.661Z"
                    totalCount: 1
              schema:
                $ref: '#/components/schemas/ManagedSoftwareUpdateStatuses'
          description: Success
      summary: Retrieve Managed Software Update Statuses for Computers
      tags:
        - managed-software-updates
      x-required-privileges:
        - Read Computers
  /v1/managed-software-updates/update-statuses/mobile-device-groups/{id}:
    get:
      description: |
        Retrieve Managed Software Update Statuses for Mobile Device Groups
      parameters:
        - description: Mobile Device Group identifier
          explode: false
          in: path
          name: id
          required: true
          schema:
            type: string
          style: simple
      responses:
        200:
          content:
            application/json:
              examples:
                MobileDeviceManagedSoftwareUpdateStatus:
                  value:
                    results:
                      - created: "2022-12-22T21:09:00.661Z"
                        device:
                          deviceId: 1
                          href: /v2/mobile-devices/1
                          objectType: MOBILE_DEVICE
                        downloadPercentComplete: 0.8
                        downloaded: true
                        osUpdatesStatusId: "1"
                        productKey: iOSUpdate19F77
                        status: DOWNLOADING
                        updated: "2022-12-22T21:09:00.661Z"
                    totalCount: 1
              schema:
                $ref: '#/components/schemas/ManagedSoftwareUpdateStatuses'
          description: Success
      summary: Retrieve Managed Software Update Statuses for Mobile Device Groups
      tags:
        - managed-software-updates
      x-required-privileges:
        - Read Mobile Devices
        - Read Smart Mobile Device Groups
        - Read Static Mobile Device Groups
  /v1/managed-software-updates/update-statuses/mobile-devices/{id}:
    get:
      description: |
        Retrieve Managed Software Update Statuses for Mobile Devices
      parameters:
        - description: Mobile Device identifier
          explode: false
          in: path
          name: id
          required: true
          schema:
            type: string
          style: simple
      responses:
        200:
          content:
            application/json:
              examples:
                MobileDeviceManagedSoftwareUpdateStatus:
                  value:
                    results:
                      - created: "2022-12-22T21:09:00.661Z"
                        device:
                          deviceId: 1
                          href: /v2/mobile-devices/1
                          objectType: MOBILE_DEVICE
                        downloadPercentComplete: 0.8
                        downloaded: true
                        osUpdatesStatusId: "1"
                        productKey: iOSUpdate19F77
                        status: DOWNLOADING
                        updated: "2022-12-22T21:09:00.661Z"
                    totalCount: 1
              schema:
                $ref: '#/components/schemas/ManagedSoftwareUpdateStatuses'
          description: Success
      summary: Retrieve Managed Software Update Statuses for Mobile Devices
      tags:
        - managed-software-updates
      x-required-privileges:
        - Read Mobile Devices
servers:
  - url: /api
