openapi: 3.0.1
info:
  title: Jamf Pro API - Managed Application List Command Definition
  description: This MDM commands exist to be re-used by multiple other Swagger files.
  version: 0.0.1
paths: {}
components:
  schemas:
    ManagedApplicationListCommand:
      allOf:
        - $ref: 'MdmDefinitionsLibrary.yaml#/components/schemas/MdmCommandBase'
        - type: object
          properties:
            identifiers:
              type: array
              nullable: true
              minItems: 0
              items:
                type: string
                nullable: false
                minLength: 1
              example: ["com.example.app1", "com.example.app2", "com.example.app3"]
              description: Array of application identifiers to manage