openapi: 3.0.1
info:
  title: Jamf Pro API - MDM Commands Library
  description: These MDM commands exist to be re-used by multiple other Swagger files.
  version: 0.0.1
paths: {}
components:
  schemas:
    EnableLostModeCommand:
      allOf:
        - $ref: 'MdmDefinitionsLibrary.yaml#/components/schemas/MdmCommandBase'
        - type: object
          properties:
            lostModeMessage:
              type: string
              example: 'Lost Mode Message'
            lostModePhone:
              type: string
              example: '123-456-7890'
            lostModeFootnote:
              type: string
              example: 'This is a footnote'
    ClearRestrictionsPasswordCommand:
      allOf:
        - $ref: 'MdmDefinitionsLibrary.yaml#/components/schemas/MdmCommandBase'
        - type: object
    DeleteUserCommand:
      allOf:
        - $ref: 'MdmDefinitionsLibrary.yaml#/components/schemas/MdmCommandBase'
        - type: object
          properties:
            userName:
              type: string
              example: 'user123'
            forceDeletion:
              type: boolean
              example: true
            deleteAllUsers:
              type: boolean
              example: true
    LogOutUserCommand:
      allOf:
        - $ref: 'MdmDefinitionsLibrary.yaml#/components/schemas/MdmCommandBase'
        - type: object