openapi: 3.0.1
info:
  title: Jamf Pro API - MDM Definitions Library
  description: These MDM definitions exist to be re-used by multiple other Swagger files.
  version: 0.0.1
paths: {}
components:
  schemas:
    MdmCommandResults:
      type: object
      properties:
        totalCount:
          type: integer
          example: 1
        results:
          type: array
          items:
            $ref: '#/components/schemas/MdmCommand'
    MdmCommandClientRequest:
      type: object
      properties:
        managementId:
          type: string
          example: "aaaaaaaa-3f1e-4b3a-a5b3-ca0cd7430937"
    MdmCommandClient:
      type: object
      properties:
        managementId:
          type: string
          example: "aaaaaaaa-3f1e-4b3a-a5b3-ca0cd7430937"
        clientType:
          $ref: "#/components/schemas/MdmClientType"
    MdmCommandError:
      type: object
      properties:
        errorCode:
          type: integer
          example: 1234
        errorDomain:
          type: string
          example: "An error occurred while processing the command."
        errorLocalizedDescription:
          type: string
          example: "An error occurred while processing the command."
        errorEnglishDescription:
          type: string
          example: "An error occurred while processing the command."
    MdmCommand:
      type: object
      properties:
        uuid:
          type: string
          example: "aaaaaaaa-3f1e-4b3a-a5b3-ca0cd7430937"
        dateSent:
          type: string
          example: "2019-05-16T20:43:43.945Z"
          format: date-time
        dateCompleted:
          type: string
          example: "2019-05-16T20:43:43.945Z"
          format: date-time
        client:
          $ref: '#/components/schemas/MdmCommandClient'
        commandState:
          $ref: '#/components/schemas/MdmCommandState'
        commandType:
          $ref: '#/components/schemas/MdmCommandType'
        commandError:
          $ref: '#/components/schemas/MdmCommandError'
        profileId:
          type: integer
          example: 1
    MdmCommandRequest:
      type: object
      properties:
        clientData:
          type: array
          items:
            $ref: '#/components/schemas/MdmCommandClientRequest'
        commandData:
          example:
              commandType: "ENABLE_LOST_MODE"
              lostModeMessage: 'Lost Mode Message'
              lostModePhone: '123-456-7890'
              lostModeFootnote: 'This is a footnote'
          oneOf:
            - $ref: 'ApplyRedemptionCodeCommandDef.yaml#/components/schemas/ApplyRedemptionCodeCommand'
            - $ref: 'CertificateListCommandDef.yaml#/components/schemas/CertificateListCommand'
            - $ref: 'ClearPasscodeCommandDef.yaml#/components/schemas/ClearPasscodeCommand'
            - $ref: 'DeclarativeManagementCommandDef.yaml#/components/schemas/DeclarativeManagementCommand'
            - $ref: 'DeviceInformationCommandDef.yaml#/components/schemas/DeviceInformationCommand'
            - $ref: 'DeviceLocationCommandDef.yaml#/components/schemas/DeviceLocationCommand'
            - $ref: 'DeviceLockCommandDef.yaml#/components/schemas/DeviceLockCommand'
            - $ref: 'DisableLostModeCommandDef.yaml#/components/schemas/DisableLostModeCommand'
            - $ref: 'DisableRemoteDesktopCommandDef.yaml#/components/schemas/DisableRemoteDesktopCommand'
            - $ref: 'EnableRemoteDesktopCommandDef.yaml#/components/schemas/EnableRemoteDesktopCommand'
            - $ref: 'EraseDeviceCommandDef.yaml#/components/schemas/EraseDeviceCommand'
            - $ref: 'ManagedApplicationListCommandDef.yaml#/components/schemas/ManagedApplicationListCommand'
            - $ref: 'InstalledApplicationListCommandDef.yaml#/components/schemas/InstalledApplicationListCommand'
            - $ref: 'MdmCommandsLibrary.yaml#/components/schemas/ClearRestrictionsPasswordCommand'
            - $ref: 'MdmCommandsLibrary.yaml#/components/schemas/DeleteUserCommand'
            - $ref: 'MdmCommandsLibrary.yaml#/components/schemas/EnableLostModeCommand'
            - $ref: 'MdmCommandsLibrary.yaml#/components/schemas/LogOutUserCommand'
            - $ref: 'ManagedMediaListCommandDef.yaml#/components/schemas/ManagedMediaListCommand'
            - $ref: 'PlayLostModeSoundCommandDef.yaml#/components/schemas/PlayLostModeSoundCommand'
            - $ref: 'ProfileListCommandDef.yaml#/components/schemas/ProfileListCommand'
            - $ref: 'ProvisioningProfileListCommandDef.yaml#/components/schemas/ProvisioningProfileListCommand'
            - $ref: 'RefreshCellularPlansCommandDef.yaml#/components/schemas/RefreshCellularPlansCommand'
            - $ref: 'RestartDeviceCommandDef.yaml#/components/schemas/RestartDeviceCommand'
            - $ref: 'RequestMirroringCommandDef.yaml#/components/schemas/RequestMirroringCommand'
            - $ref: 'SecurityInfoCommandDef.yaml#/components/schemas/SecurityInfoCommand'
            - $ref: 'SetAutoAdminPasswordCommandDef.yaml#/components/schemas/SetAutoAdminPasswordCommand'
            - $ref: 'SetRecoveryLockCommandDef.yaml#/components/schemas/SetRecoveryLockCommand'
            - $ref: 'SettingsCommandDef.yaml#/components/schemas/SettingsCommand'
            - $ref: 'ShutDownDeviceCommandDef.yaml#/components/schemas/ShutDownDeviceCommand'
            - $ref: 'StopMirroringCommandDef.yaml#/components/schemas/StopMirroringCommand'
            - $ref: 'UnlockUserAccountCommandDef.yaml#/components/schemas/UnlockUserAccountCommand'
            - $ref: 'ValidateApplicationsCommandDef.yaml#/components/schemas/ValidateApplicationsCommand'
            - $ref: 'ValidateRecoveryLockCommandDef.yaml#/components/schemas/VerifyRecoveryLockCommand'
          discriminator:
            propertyName: commandType
            mapping:
              APPLY_REDEMPTION_CODE: '#/components/schemas/ApplyRedemptionCodeCommand'
              CERTIFICATE_LIST: '#/components/schemas/CertificateListCommand'
              CLEAR_PASSCODE: '#/components/schemas/ClearPasscodeCommand'
              CLEAR_RESTRICTIONS_PASSWORD: '#/components/schemas/ClearRestrictionsPasswordCommand'
              DECLARATIVE_MANAGEMENT: '#/components/schemas/DeclarativeManagementCommand'
              DELETE_USER: '#/components/schemas/DeleteUserCommand'
              DEVICE_INFORMATION: '#/components/schemas/DeviceInformationCommand'
              DEVICE_LOCATION: '#/components/schemas/DeviceLocationCommand'
              DEVICE_LOCK: '#/components/schemas/DeviceLockCommand'
              DISABLE_LOST_MODE: '#/components/schemas/DisableLostModeCommand'
              DISABLE_REMOTE_DESKTOP: '#/components/schemas/DisableRemoteDesktopCommand'
              ENABLE_LOST_MODE: '#/components/schemas/EnableLostModeCommand'
              ENABLE_REMOTE_DESKTOP: '#/components/schemas/EnableRemoteDesktopCommand'
              ERASE_DEVICE: '#/components/schemas/EraseDeviceCommand'
              INSTALLED_APPLICATION_LIST: '#/components/schemas/InstalledApplicationListCommand'
              LOG_OUT_USER: '#/components/schemas/LogOutUserCommand'
              MANAGED_APPLICATION_LIST: '#/components/schemas/ManagedApplicationListCommand'
              MANAGED_MEDIA_LIST: '#/components/schemas/ManagedMediaListCommand'
              PLAY_LOST_MODE_SOUND: '#/components/schemas/PlayLostModeSoundCommand'
              PROFILE_LIST: '#/components/schemas/ProfileListCommand'
              PROVISIONING_PROFILE_LIST: '#/components/schemas/ProvisioningProfileListCommand'
              REFRESH_CELLULAR_PLANS: '#/components/schemas/RefreshCellularPlansCommand'
              RESTART_DEVICE: '#/components/schemas/RestartDeviceCommand'
              REQUEST_MIRRORING: '#/components/schemas/RequestMirroringCommand'
              SECURITY_INFO: '#/components/schemas/SecurityInfoCommand'
              SETTINGS: '#/components/schemas/SettingsCommand'
              SET_AUTO_ADMIN_PASSWORD: '#/components/schemas/SetAutoAdminPasswordCommand'
              SET_RECOVERY_LOCK: '#/components/schemas/SetRecoveryLockCommand'
              SHUT_DOWN_DEVICE: '#/components/schemas/ShutDownDeviceCommand'
              STOP_MIRRORING: '#/components/schemas/StopMirroringCommand'
              UNLOCK_USER_ACCOUNT: '#/components/schemas/UnlockUserAccountCommand'
              VALIDATE_APPLICATIONS: '#/components/schemas/ValidateApplicationsCommand'
              VALIDATE_RECOVERY_LOCK: '#/components/schemas/VerifyRecoveryLockCommand'
    MdmClientType:
      type: string
      example: MOBILE_DEVICE
      enum:
        - MOBILE_DEVICE
        - TV
        - VISION_PRO
        - WATCH
        - COMPUTER
        - COMPUTER_USER
        - MOBILE_DEVICE_USER
        - UNKNOWN
    MdmCommandState:
      type: string
      example: PENDING
      enum:
        - PENDING
        - ACKNOWLEDGED
        - NOT_NOW
        - ERROR
    MdmCommandType:
      type: string
      example: ENABLE_LOST_MODE
      enum:
        - APPLY_REDEMPTION_CODE
        - CERTIFICATE_LIST
        - CLEAR_PASSCODE
        - CLEAR_RESTRICTIONS_PASSWORD
        - DECLARATIVE_MANAGEMENT
        - DELETE_USER
        - DEVICE_INFORMATION
        - DEVICE_LOCATION
        - DEVICE_LOCK
        - DISABLE_LOST_MODE
        - DISABLE_REMOTE_DESKTOP
        - ENABLE_LOST_MODE
        - ENABLE_REMOTE_DESKTOP
        - ERASE_DEVICE
        - INSTALLED_APPLICATION_LIST
        - LOG_OUT_USER
        - MANAGED_APPLICATION_LIST
        - MANAGED_MEDIA_LIST
        - REFRESH_CELLULAR_PLANS
        - PLAY_LOST_MODE_SOUND
        - PROFILE_LIST
        - PROVISIONING_PROFILE_LIST
        - RESTART_DEVICE
        - REQUEST_MIRRORING
        - SECURITY_INFO
        - SETTINGS
        - SET_AUTO_ADMIN_PASSWORD
        - SET_RECOVERY_LOCK
        - SHUT_DOWN_DEVICE
        - STOP_MIRRORING
        - UNLOCK_USER_ACCOUNT
        - VALIDATE_APPLICATIONS
        - VALIDATE_RECOVERY_LOCK
    MdmCommandBase:
      type: object
      required:
        - commandType
      properties:
        commandType:
          $ref: '#/components/schemas/MdmCommandType'
