info:
  title: Jamf Pro API - MobileDeviceSmartGroup
  version: 0.0.1
openapi: 3.0.1
paths:
  /v1/mobile-devices/{id}/recalculate-smart-groups:
    post:
      description: |
        Recalculates all smart groups for the given device id and then
        returns the count of smart groups the device falls into
      parameters:
        - description: id of mobile device
          explode: false
          in: path
          name: id
          required: true
          schema:
            type: integer
          style: simple
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: _MonolithLibrary.yaml#/components/schemas/RecalculationResults
          description: Successful response
        400:
          content:
            application/json:
              schema:
                $ref: _MonolithLibrary.yaml#/components/schemas/ApiError
          description: smart group not found
      summary: |
        Recalculate all smart groups for the given device id and then return count of smart groups that device fall into
      tags:
        - smart-mobile-device-groups-preview
      x-action: true
      x-required-privileges:
        - Update Smart Mobile Device Groups
  /v1/smart-mobile-device-groups/{id}/recalculate:
    post:
      description: |
        recalculates a smart group for the given id and then
        returns the ids for the devices in the smart group
      parameters:
        - description: instance id of smart group
          explode: false
          in: path
          name: id
          required: true
          schema:
            type: integer
          style: simple
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: _MonolithLibrary.yaml#/components/schemas/RecalculationResults
          description: Successful response
        400:
          content:
            application/json:
              schema:
                $ref: _MonolithLibrary.yaml#/components/schemas/ApiError
          description: smart group not found
      summary: |
        Recalculate a smart group for the given id then return the ids for the devices in the smart group
      tags:
        - smart-mobile-device-groups-preview
      x-action: true
      x-required-privileges:
        - Update Smart Mobile Device Groups
servers:
  - url: /api
