info:
  title: Jamf Pro API - MobileDevicePrestageScopeV2
  version: 0.0.1
openapi: 3.0.1
paths:
  /v2/mobile-device-prestages/scope:
    get:
      description: Get all device scope for all mobile device prestages
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: _MonolithLibrary.yaml#/components/schemas/PrestageScopeV2
          description: Successful response
      summary: |
        Get all Device Scope for all Mobile Device Prestages
      tags:
        - mobile-device-prestages
      x-required-privileges:
        - Read Mobile Device PreStage Enrollments
  /v2/mobile-device-prestages/{id}/scope:
    get:
      description: Get device scope for a specific mobile device prestage
      parameters:
        - description: Mobile Device Prestage identifier
          explode: false
          in: path
          name: id
          required: true
          schema:
            type: string
          style: simple
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: _MonolithLibrary.yaml#/components/schemas/PrestageScopeResponseV2
          description: Successful response
        404:
          content:
            application/json:
              schema:
                $ref: _MonolithLibrary.yaml#/components/schemas/ApiError
          description: Mobile Device Prestage with that id does not exist
      summary: |
        Get Device Scope for a specific Mobile Device Prestage
      tags:
        - mobile-device-prestages
      x-required-privileges:
        - Read Mobile Device PreStage Enrollments
    post:
      description: Add device scope for a specific mobile device prestage
      parameters:
        - description: Mobile Device Prestage identifier
          explode: false
          in: path
          name: id
          required: true
          schema:
            type: string
          style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: _MonolithLibrary.yaml#/components/schemas/PrestageScopeUpdate
        description: Serial Numbers to scope
        required: true
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: _MonolithLibrary.yaml#/components/schemas/PrestageScopeResponseV2
          description: Successful response
        400:
          content:
            application/json:
              schema:
                $ref: _MonolithLibrary.yaml#/components/schemas/ApiError
          description: One or more serial numbers are not valid
        404:
          content:
            application/json:
              schema:
                $ref: _MonolithLibrary.yaml#/components/schemas/ApiError
          description: Mobile Device Prestage with that id does not exist
        409:
          content:
            application/json:
              schema:
                $ref: _MonolithLibrary.yaml#/components/schemas/ApiError
          description: Optimistic Lock Error - The prestage you are trying to update has been updated by another process
      summary: |
        Add Device Scope for a specific Mobile Device Prestage
      tags:
        - mobile-device-prestages
      x-action: true
      x-required-privileges:
        - Update Mobile Device PreStage Enrollments
    put:
      description: Replace device scope for a specific mobile device prestage
      parameters:
        - description: Mobile Device Prestage identifier
          explode: false
          in: path
          name: id
          required: true
          schema:
            type: string
          style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: _MonolithLibrary.yaml#/components/schemas/PrestageScopeUpdate
        description: Serial Numbers to scope
        required: true
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: _MonolithLibrary.yaml#/components/schemas/PrestageScopeResponseV2
          description: Successful response
        400:
          content:
            application/json:
              schema:
                $ref: _MonolithLibrary.yaml#/components/schemas/ApiError
          description: One or more serial numbers are not valid
        404:
          content:
            application/json:
              schema:
                $ref: _MonolithLibrary.yaml#/components/schemas/ApiError
          description: Mobile Device Prestage with that id does not exist
        409:
          content:
            application/json:
              schema:
                $ref: _MonolithLibrary.yaml#/components/schemas/ApiError
          description: Optimistic Lock Error - The prestage you are trying to update has been updated by another process
      summary: |
        Replace Device Scope for a specific Mobile Device Prestage
      tags:
        - mobile-device-prestages
      x-required-privileges:
        - Update Mobile Device PreStage Enrollments
  /v2/mobile-device-prestages/{id}/scope/delete-multiple:
    post:
      description: Remove device scope for a specific mobile device prestage
      parameters:
        - description: Mobile Device Prestage identifier
          explode: false
          in: path
          name: id
          required: true
          schema:
            type: string
          style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: _MonolithLibrary.yaml#/components/schemas/PrestageScopeUpdate
        description: Serial Numbers to remove from scope
        required: true
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: _MonolithLibrary.yaml#/components/schemas/PrestageScopeResponseV2
          description: Successful response
        400:
          content:
            application/json:
              schema:
                $ref: _MonolithLibrary.yaml#/components/schemas/ApiError
          description: One or more serial numbers are not valid
        404:
          content:
            application/json:
              schema:
                $ref: _MonolithLibrary.yaml#/components/schemas/ApiError
          description: Mobile Device Prestage with that id does not exist
        409:
          content:
            application/json:
              schema:
                $ref: _MonolithLibrary.yaml#/components/schemas/ApiError
          description: Optimistic Lock Error - The prestage you are trying to update has been updated by another process
      summary: |
        Remove Device Scope for a specific Mobile Device Prestage
      tags:
        - mobile-device-prestages
      x-action: true
      x-required-privileges:
        - Update Mobile Device PreStage Enrollments
servers:
  - url: /api
