info:
  title: Jamf Pro API - MobileDeviceEnrollmentProfile
  version: 0.0.1
openapi: 3.0.1
paths:
  /v1/mobile-device-enrollment-profile/{id}/download-profile:
    get:
      description: Retrieve the MDM Enrollment Profile
      parameters:
        - description: MDM Enrollment Profile identifier
          explode: false
          in: path
          name: id
          required: true
          schema:
            type: string
          style: simple
      responses:
        200:
          content:
            application/x-apple-aspen-config:
              schema:
                format: binary
                type: string
          description: Success
        404:
          description: Not Found
      summary: |
        Retrieve the MDM Enrollment Profile
      tags:
        - mobile-device-enrollment-profile
      x-required-privileges:
        - Read Enrollment Profiles
servers:
  - url: /api
