components:
  schemas:
    MobileDeviceExtensionAttributeSearchResults:
      properties:
        results:
          items:
            $ref: '#/components/schemas/MobileDeviceExtensionAttributes'
          minItems: 0
          type: array
        totalCount:
          example: 1
          type: integer
      required:
        - totalCount
      type: object
    MobileDeviceExtensionAttributes:
      allOf:
        - $ref: _MonolithLibrary.yaml#/components/schemas/ExtensionAttributes
        - properties:
            inputType:
              default: TEXT
              description: Extension attributes collect inventory data by using an input type.The type of the Input used to populate the extension attribute.
              enum:
                - TEXT
                - POPUP
                - DIRECTORY_SERVICE_ATTRIBUTE_MAPPING
              type: string
            inventoryDisplayType:
              default: GENERAL
              description: Category in which to display the extension attribute in Jamf Pro.
              enum:
                - GENERAL
                - HARDWARE
                - USER_AND_LOCATION
                - PURCHASING
                - EXTENSION_ATTRIBUTES
              example: GENERAL
              type: string
            ldapAttributeMapping:
              description: Directory Service attribute use to populate the extension attribute. <br/> Required when inputType is "DIRECTORY_SERVICE_ATTRIBUTE_MAPPING"
              example: ldapAttributeMapping
              type: string
            ldapExtensionAttributeAllowed:
              default: false
              description: Collect multiple values for this extension attribute. ldapExtensionAttributeAllowed is disabled by default, only for inputType 'DIRECTORY_SERVICE_ATTRIBUTE_MAPPING' it can be enabled. It's value cannot be modified during edit operation.<br/> Possible values are:<br/> false <br/> true <br/>
              example: false
              type: boolean
            popupMenuChoices:
              description: When added with list of choices while creating mobile device extension attributes these Pop-up menu can be displayed in inventory information. User can choose a value from the pop-up menu list when enrolling a mobile device any time using Jamf Pro. Provide popupMenuChoices only when inputType is 'POPUP'.
              example:
                - Test
                - Popup
              items:
                description: Popup Menu choices.
                type: string
              minItems: 0
              type: array
          required:
            - inputType
            - inventoryDisplayType
          type: object
info:
  title: Jamf Pro API - MobileDeviceExtensionAttribute
  version: 0.0.1
openapi: 3.0.1
paths:
  /v1/mobile-device-extension-attributes:
    get:
      description: Retrieves all mobile device extension attributes configuration.
      parameters:
        - $ref: _MonolithLibrary.yaml#/components/parameters/page
        - $ref: _MonolithLibrary.yaml#/components/parameters/page-size
        - description: Sorts results by one or more criteria, following the format property:asc/desc.<br/> Default sort is name:asc.<br/> If using multiple criteria, separate with commas. Allows sort for id and name.
          explode: true
          in: query
          name: sort
          required: false
          schema:
            default:
              - name.asc
            items:
              type: string
            type: array
          style: form
        - description: 'Filters results. Use RSQL format for query. Allows for many fields, including ID, name, etc.<br/> Can be combined with paging and sorting.<br/> Fields allowed in the query: id, name <br/> Default filter is an empty query and returns all results from the requested page.'
          explode: true
          in: query
          name: filter
          required: false
          schema:
            default: ""
            type: string
          style: form
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MobileDeviceExtensionAttributeSearchResults'
          description: Mobile Device Extension Attribute objects has been fetched successfully.
        404:
          content:
            application/json:
              schema:
                $ref: _MonolithLibrary.yaml#/components/schemas/ApiError
          description: Mobile Device Extension Attribute objects could not be found. The server either did not find a current representation for the requested resource or is trying to hide its existence from an unauthorized client.
      summary: Retrieve Mobile Device Extension Attributes.
      tags:
        - mobile-device-extension-attributes
      x-required-privileges:
        - Read Mobile Device Extension Attributes
    post:
      description: Create Mobile Device Extension Attribute to collect extra inventory information.
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MobileDeviceExtensionAttributes'
        description: Mobile Device Extension Attribute to be created.
        required: true
      responses:
        201:
          content:
            application/json:
              schema:
                $ref: _MonolithLibrary.yaml#/components/schemas/HrefResponse
          description: Mobile Device Extension Attribute was successfully created.
        400:
          content:
            application/json:
              schema:
                $ref: _MonolithLibrary.yaml#/components/schemas/ApiError
          description: Bad Request. The server could not understand the request because of invalid syntax. Possible reasons are:</br> 1) Required fields are not provided in request body.</br> 2) Fields which are not associated with provided inputType has some value.</br> 3) Any values outside of the allowed range are included in the request body.</br> 4) LDAP is not configured.</br> 5) Error occurred during database create operation.</br> 6) Duplicate name is provided.</br>
      summary: Create Mobile Device Extension Attribute.
      tags:
        - mobile-device-extension-attributes
      x-action: true
      x-required-privileges:
        - Create Mobile Device Extension Attributes
  /v1/mobile-device-extension-attributes/{id}:
    delete:
      description: |
        Deletes the Mobile Device Extension Attribute identified by the provided ID.<\br>
        In addition to removing the attribute itself, this operation will also delete any related dependent data, including:<\br>
          - Associated popup menu choices.<\br>
          - Fields used in saved search displays.<\br>
          - User preferences that reference the attribute.
      parameters:
        - description: Unique ID of Mobile Device Extension Attribute.
          explode: false
          in: path
          name: id
          required: true
          schema:
            type: string
          style: simple
      responses:
        204:
          description: The Mobile Device Extension was successfully deleted.
        400:
          description: Bad Request. The server could not process the request due to invalid input. Possible reasons are:</br> - The specified extension attribute ID is not a valid number. - The ID is missing or improperly formatted.
        404:
          description: Not Found. The specified Mobile Device Extension Attribute does not exist. This may indicate that the resource is missing, or the client is not authorized to access it.
      summary: Delete a Mobile Device Extension Attribute by ID.
      tags:
        - mobile-device-extension-attributes
      x-required-privileges:
        - Delete Mobile Device Extension Attributes
    get:
      description: Gets specified Mobile Device Extension Attribute object.
      parameters:
        - description: Unique ID of Mobile Device Extension Attribute.
          explode: false
          in: path
          name: id
          required: true
          schema:
            type: string
          style: simple
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MobileDeviceExtensionAttributes'
          description: Mobile Device Extension Attribute object has been fetched successfully.
        400:
          description: Bad Request. The server could not understand the request because of invalid syntax. Possible reason can be 'The specified extension attribute id does not include a valid number.'
        404:
          content:
            application/json:
              schema:
                $ref: _MonolithLibrary.yaml#/components/schemas/ApiError
          description: Specified Mobile Device Extension Attribute object could not be found. The server either did not find a current representation for the requested resource or is trying to hide its existence from an unauthorized client.
      summary: Get specified Mobile Device Extension Attribute object.
      tags:
        - mobile-device-extension-attributes
      x-required-privileges:
        - Read Mobile Device Extension Attributes
    put:
      description: Update specified Mobile Device Extension Attribute object.
      parameters:
        - description: Unique ID of Mobile Device Extension Attribute.
          explode: false
          in: path
          name: id
          required: true
          schema:
            type: string
          style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MobileDeviceExtensionAttributes'
        description: Mobile Device Extension Attribute object to be updated. IDs defined in this body will be ignored.
        required: true
      responses:
        202:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MobileDeviceExtensionAttributes'
          description: Mobile Device Extension Attribute updated successfully.
        400:
          content:
            application/json:
              schema:
                $ref: _MonolithLibrary.yaml#/components/schemas/ApiError
          description: Bad Request. Specified Mobile Device Extension Attribute could not be updated due to bad request. Possible reasons are:</br> 1) The specified extension attribute id does not include a valid number.</br> 2) Duplicate name is provided.</br> 3) Required fields are not provided in request body.</br> 4) Fields which are not associated with provided inputType has some value.</br> 5) Any values outside of the allowed range are included in the request body.</br> 6) LDAP is not configured.</br> 7) Error occurred during database update operation.
        404:
          content:
            application/json:
              schema:
                $ref: _MonolithLibrary.yaml#/components/schemas/ApiError
          description: Specified Mobile Device Extension Attribute object does not exist. The server either did not find a current representation for the requested resource or is trying to hide its existence from an unauthorized client.
      summary: Update specified Mobile Device Extension Attribute object.
      tags:
        - mobile-device-extension-attributes
      x-required-privileges:
        - Update Mobile Device Extension Attributes
  /v1/mobile-device-extension-attributes/{id}/data-dependency:
    get:
      description: Get smart group dependent object for a specified mobile device extension attribute
      parameters:
        - description: Unique ID of mobile device extension attribute.
          explode: false
          in: path
          name: id
          required: true
          schema:
            type: string
          style: simple
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: _MonolithLibrary.yaml#/components/schemas/DependencyObjectResults
          description: Fetches list of dependent objects for a specified mobile device extension attribute.
        400:
          content:
            application/json:
              schema:
                $ref: _MonolithLibrary.yaml#/components/schemas/ApiError
          description: Bad Request. The server could not understand the request because of invalid syntax.
        404:
          content:
            application/json:
              schema:
                $ref: _MonolithLibrary.yaml#/components/schemas/ApiError
          description: Specified mobile device extension attribute id were not found in database.
      summary: Get smart group dependent object for a specified mobile device extension attribute
      tags:
        - mobile-device-extension-attributes
      x-required-privileges:
        - Read Mobile Device Extension Attributes
  /v1/mobile-device-extension-attributes/{id}/history:
    get:
      description: Get specified Mobile Device Extension Attribute history object
      parameters:
        - description: Instance ID of Mobile Device Extension Attribute
          explode: false
          in: path
          name: id
          required: true
          schema:
            type: string
          style: simple
        - $ref: _MonolithLibrary.yaml#/components/parameters/page
        - $ref: _MonolithLibrary.yaml#/components/parameters/page-size
        - description: Sorts results by one or more criteria, following the format property:asc/desc. Default sort is ID:asc. If using multiple criteria, separate with commas.
          explode: true
          in: query
          name: sort
          required: false
          schema:
            default:
              - id:asc
            items:
              type: string
            type: array
          style: form
        - description: Filters results. Use RSQL format for query. Allows for many fields, including ID, name, etc. Can be combined with paging and sorting. Default filter is an empty query and returns all results from the requested page.
          explode: true
          in: query
          name: filter
          required: false
          schema:
            default: ""
            type: string
          style: form
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: _MonolithLibrary.yaml#/components/schemas/HistorySearchResults
          description: Details of Mobile Device Extension Attribute history were found.
        400:
          content:
            application/json:
              schema:
                $ref: _MonolithLibrary.yaml#/components/schemas/ApiError
          description: Bad Request. Specified Mobile Device Extension Attribute history object could not be found. Possible reason can be 'Provided id field is not string of positive numeric value or -1'.
      summary: Get specified Mobile Device Extension Attribute History object
      tags:
        - mobile-device-extension-attributes
      x-required-privileges:
        - Read Mobile Device Extension Attributes
    post:
      description: Add specified Mobile Device Extension Attribute history object notes
      parameters:
        - description: Instance ID of Mobile Device Extension Attribute
          explode: false
          in: path
          name: id
          required: true
          schema:
            type: string
          style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: _MonolithLibrary.yaml#/components/schemas/ObjectHistoryNote
        description: History note to be created
        required: true
      responses:
        201:
          content:
            application/json:
              schema:
                $ref: _MonolithLibrary.yaml#/components/schemas/ObjectHistory
          description: Mobile Device Extension Attribute history note created successfully.
        400:
          content:
            application/json:
              schema:
                $ref: _MonolithLibrary.yaml#/components/schemas/ApiError
          description: Bad Request. Error creating history note. Possible reason can be 'Provided id field is not string of positive numeric value or -1'.
      summary: Add specified Mobile Device Extension Attribute history object notes
      tags:
        - mobile-device-extension-attributes
      x-required-privileges:
        - Update Mobile Device Extension Attributes
servers:
  - url: /api
