openapi: 3.0.1
info:
  title: API Role Privileges
  description: This endpoint is used to get API role privileges
  version: 0.0.1
paths:
  /v1/api-role-privileges:
    get:
      tags:
        - api-role-privileges
      description: Get role privileges
      summary: Get the current Jamf API Role Privileges
      responses:
        200:
          description: A sorted list of the current Jamf API Roles Privileges
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/ApiRolePrivileges'
      x-required-privileges:
        - Read API Roles
  /v1/api-role-privileges/search:
    get:
      tags:
        - api-role-privileges
      description: Search role privileges
      summary: Search the current Jamf API Role Privileges
      parameters:
        - name: name
          in: query
          description: The partial or complete privilege name we are searching for
          required: true
          schema:
            type: string
            example: "Flush"
        - name: limit
          in: query
          description: Limit the query results, defaults to 15
          required: false
          schema:
              type: string
              default: "15"
              example: "50"
      responses:
        200:
          description: A list of matches Jamf API Roles Privileges
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/ApiRolePrivileges'
      x-required-privileges:
          - Read API Roles

components:
  schemas:
    ApiRolePrivileges:
      required:
        - privileges
      type: object
      properties:
        privileges:
          type: array
          minItems: 0
          items:
            type: string
            example: "Flush MDM Commands"
