openapi: 3.0.1
info:
  title: API Role
  description: These endpoints are used for the CRUD of API roles
  version: 0.0.1
paths:
  /v1/api-roles:
    post:
      x-action: true
      tags:
        - api-roles
      summary: Create a new API role
      operationId: postCreateApiRole
      description: Post to create new Role
      requestBody:
        description: API Integrations Role to create
        content:
          'application/json':
            schema:
              $ref: '#/components/schemas/ApiRoleRequest'
        required: true
      responses:
        200:
          description: The created Role
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/ApiRole'
        400:
          description: Bad Request
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/ApiError'
      x-required-privileges:
        - Create API Roles
    get:
      tags:
        - api-roles
      description: Get roles with Search Criteria
      operationId: getAllApiRoles
      summary: Get the current Jamf API Roles
      parameters:
        - $ref: 'DefinitionsLibrary.yaml#/components/parameters/page'
        - $ref: 'DefinitionsLibrary.yaml#/components/parameters/page-size'
        - name: sort
          in: query
          description: 'Sorting criteria in the format: property:asc/desc. Default sort
                      is id:asc. Multiple sort criteria are supported and must be separated with
                      a comma. Fields allowed in the query: id, displayName. Example: sort=displayName:desc'
          explode: true
          schema:
            type: array
            items:
              type: string
            default: [ id:asc ]
        - name: filter
          in: query
          description: 'Query in the RSQL format, allowing to filter app titles collection.
                        Default filter is empty query - returning all results for the requested page.
                        Fields allowed in the query: id, displayName.
                        Example: displayName=="*myRole*"'
          schema:
            type: string
            default: ''
      responses:
        200:
          description: A list of the current Jamf API Roles
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/ApiRoleResult'
      x-required-privileges:
        - Read API Roles

  /v1/api-roles/{id}:
    get:
      tags:
        - api-roles
      description: Get specific Role
      operationId: getOneApiRole
      summary: Get the specific Jamf API Role
      parameters:
        - name: id
          in: path
          description: instance id of API role
          required: true
          schema:
            type: string
      responses:
        200:
          description: The requested Jamf API Role
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/ApiRole'
        404:
          description: Role not found
          content:
            'application/json':
              schema:
                $ref: 'DefinitionsLibrary.yaml#/components/schemas/ApiError'
      x-required-privileges:
        - Read API Roles
    put:
      tags:
        - api-roles
      description: Update specific Role
      operationId: putUpdateApiRole
      summary: Update API Integrations Role
      parameters:
        - name: id
          in: path
          description: instance id of API role
          required: true
          schema:
            type: string
      requestBody:
        description: API Integrations Role to update
        content:
          'application/json':
            schema:
              $ref: '#/components/schemas/ApiRoleRequest'
        required: true
      responses:
        200:
          description: Jamf API Integrations Role updated
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/ApiRole'
        404:
          description: Role not found
          content:
            'application/json':
              schema:
                $ref: 'DefinitionsLibrary.yaml#/components/schemas/ApiError'
        400:
          description: Bad Request, could not parse input.
          content:
            'application/json':
              schema:
                $ref: 'DefinitionsLibrary.yaml#/components/schemas/ApiError'
      x-required-privileges:
        - Update API Roles
    delete:
      tags:
        - api-roles
      description: Delete specific Role
      operationId: deleteApiRole
      summary: Delete API Integrations Role
      parameters:
        - name: id
          in: path
          description: instance id of API role
          required: true
          schema:
            type: string
      responses:
        204:
          description: Jamf API Integrations Role deleted
        409:
          description: Role in use by an Integration/Client
          content:
            'application/json':
              schema:
                $ref: 'DefinitionsLibrary.yaml#/components/schemas/ApiError'
        404:
          description: Role not found.
          content:
            'application/json':
              schema:
                $ref: 'DefinitionsLibrary.yaml#/components/schemas/ApiError'
      x-required-privileges:
        - Delete API Roles

components:
  schemas:
    ApiRoleRequest:
      required:
        - displayName
        - privileges
      type: object
      properties:
        displayName:
          type: string
          example: "One Role to Rule them all"
        privileges:
          type: array
          minItems: 0
          items:
            type: string
            example: "View License Serial Numbers"
    ApiRole:
      required:
        - id
        - displayName
        - privileges
      type: object
      properties:
        id:
          readOnly: true
          type: string
          example: "1"
        displayName:
          type: string
          example: "One Role to Rule them all"
        privileges:
          type: array
          minItems: 0
          items:
            type: string
            example: "View License Serial Numbers"

    ApiRoleResult:
      required:
        - totalCount
        - results
      type: object
      properties:
        totalCount:
          readOnly: true
          type: integer
          minimum: 0
          example: 1
        results:
          type: array
          minItems: 0
          items:
            $ref: '#/components/schemas/ApiRole'
