openapi: 3.0.1
info:
    title: Jamf Pro API - OIDC
    version: 0.0.1
paths:
    /v1/oidc/generate-certificate:
        post:
            tags:
                - oidc
            summary: |
                Generate a new keystore used for signing OIDC messages
            description: Generates a new certificate used for signing OIDC messages
            responses:
                201:
                    description: Successful response
                503:
                    description: OIDC is disabled
                    content:
                        'application/json':
                            schema:
                                $ref: 'DefinitionsLibrary.yaml#/components/schemas/ApiError'
            x-required-privileges:
                - Update SSO Settings
            x-action: true
    /v1/oidc/public-key:
        get:
            tags:
                - oidc
            summary: |
                Get the public key of the keystore used for signing OIDC messages as a JWT
            description: Gets the public key of the keystore used for signing OIDC messages as a JWT
            responses:
                200:
                    description: Successful response
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/OidcJwksResponse'
                404:
                    description: Unable to retrieve OIDC certificate public key
                    content:
                        'application/json':
                            schema:
                                $ref: 'DefinitionsLibrary.yaml#/components/schemas/ApiError'
                503:
                    description: OIDC is disabled
                    content:
                        'application/json':
                            schema:
                                $ref: 'DefinitionsLibrary.yaml#/components/schemas/ApiError'
            x-authentication-required: false
    /v1/oidc/dispatch:
        post:
            deprecated: true
            x-deprecation-date: 2026-02-17
            tags:
                - oidc
            summary: Provide the url to redirect for OIDC login
            description: Provide the url to redirect for OIDC login based on email
            requestBody:
                content:
                    'application/json':
                        schema:
                            $ref: '#/components/schemas/OidcLoginDispatchRequest'
                required: true
            responses:
                200:
                    description: Successful response
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/OidcLoginDispatchResponse'
                400:
                    description: Email address or original URL parameter is invalid
                    content:
                        'application/json':
                            schema:
                                $ref: 'DefinitionsLibrary.yaml#/components/schemas/ApiError'

                500:
                    description: Unexpected error
                    content:
                        'application/json':
                            schema:
                                $ref: 'DefinitionsLibrary.yaml#/components/schemas/ApiError'
            x-action: true
            x-authentication-required: false
    /v2/oidc/dispatch:
        post:
            tags:
                - oidc
            summary: Provide the url to redirect for OIDC login
            description: Provide the url to redirect for OIDC login based on email
            requestBody:
                content:
                    'application/json':
                        schema:
                            $ref: '#/components/schemas/OidcLoginDispatchRequest'
                required: true
            responses:
                200:
                    description: Successful response
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/OidcLoginDispatchResponseV2'
                400:
                    description: Email address or original URL parameter is invalid
                    content:
                        'application/json':
                            schema:
                                $ref: 'DefinitionsLibrary.yaml#/components/schemas/ApiError'

                500:
                    description: Unexpected error
                    content:
                        'application/json':
                            schema:
                                $ref: 'DefinitionsLibrary.yaml#/components/schemas/ApiError'
            x-action: true
            x-authentication-required: false
    /v1/oidc/public-features:
        get:
            tags:
                - oidc
            summary: Get the public features of the OIDC configuration
            description: Retrieves public OIDC configuration features.
            responses:
              200:
                description: Successful response
                content:
                  application/json:
                    schema:
                      $ref: '#/components/schemas/OidcPublicFeaturesResponse'
            x-authentication-required: false
    /v1/oidc/direct-idp-login-url:
        get:
            tags:
                - oidc
            summary: |
                Retrieve the URL to directly login to the IdP
            description: Retrieve the URL to directly login to the IdP
            responses:
                200:
                    description: Successful response
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/OidcDirectIdpLoginSkipUrl'
                404:
                    description: OIDC is disabled or no authorization registration ID found
                    content:
                        'application/json':
                            schema:
                                $ref: 'DefinitionsLibrary.yaml#/components/schemas/ApiError'
            x-authentication-required: true
components:
    schemas:
        OidcJwksResponse:
            type: object
            properties:
                keys:
                    type: array
                    items:
                        type: object
                        properties:
                            kty:
                                type: string
                                example: "RSA"
                            e:
                                type: string
                                example: "AQAB"
                            use:
                                type: string
                                example: "sig"
                            kid:
                                type: string
                                example: "695eccd8c1918105c0f57fcac412651245d778cd301fca44a5ee6f7e0c5320ce"
                            alg:
                                type: string
                                example: "RS256"
                            iat:
                                type: integer
                                example: 1717518913
                            n:
                                type: string
                                example: "yvoRJjwm_JR3z0_MQS5zU8RQCav82PbdZOG8DYcDzRrbklVJZXAGOH16m6egW5B-hb_zxncsSCZTvwmXYiUsWcYE8Lu-CZ0-O2WmpOsk-rc5mklQlEGlD2N3u6MZWIpOofyrbM2AhVssmzgFRHR_22O05KDsNKMKy7ZQaUvvIbqBrnvGRKJMZ4GqzeWyo3rmBpdhmY1wLoPQBAQgwO-TTy5xLhTmLLimAV6ckkLtxjUUdwu4pSKiiJGkJAlDEFXJA5-Y9GE3CZOywj1sJsuHvfHGcgWbEDYVVqdD6PB4NRKmuvj_yJ1BACObaFSLNzfw693FBvuyH1s9D-zGT58Kvw"
        OidcLoginDispatchRequest:
            required:
                - originalUrl
                - emailAddress
            type: object
            properties:
                originalUrl:
                    type: string
                    example: "aHR0cHM6Ly9qYW1mLXByby11cmwuY29tL2xvZ2dpbmcuaHRtbA=="
                    description: 'Original Url'
                emailAddress:
                    type: string
                    example: "admin@domain.name"
                    description: 'User email address'
        OidcLoginDispatchResponse:
            required:
                - redirectUrl
            type: object
            properties:
                redirectUrl:
                    type: string
                    example: "/oauth2/authorization/jamf-account-domain.name?original_url=aHR0cHM6Ly9qYW1mLXByby11cmwuY29tL2xvZ2dpbmcuaHRtbA==&login_hint=YWRtaW5AZG9tYWluLm5hbWU="
        OidcLoginDispatchResponseV2:
            required:
                - redirectUrl
            type: object
            properties:
                idpRedirects:
                    type: array
                    items:
                        type: object
                        properties:
                            redirectUrl:
                                type: string
                                example: "/oauth2/authorization/jamf-account-domain.name?original_url=aHR0cHM6Ly9qYW1mLXByby11cmwuY29tL2xvZ2dpbmcuaHRtbA==&login_hint=YWRtaW5AZG9tYWluLm5hbWU="
                            idpName:
                                type: string
                                example: "SomeIdp"
                            idpType:
                                type: string
                                example: "GENERIC_OIDC"
        OidcPublicFeaturesResponse:
            required:
                - jamfIdAuthenticationEnabled
            type: object
            properties:
              jamfIdAuthenticationEnabled:
                    type: boolean
                    example: true
                    description: "Indicates whether Jamf ID authentication is enabled for this instance. When true, users can authenticate using Jamf ID credentials. When false, Jamf ID login option is not available."
        OidcDirectIdpLoginSkipUrl:
            required:
                - url
            type: object
            properties:
                url:
                    type: string
                    example: "https://jamf-pro-server/oauth2/authorization/idp-region-domain.com"
                    description: 'Direct IdP login URL to skip unified login page.'

