components:
  schemas:
    OnboardingEligibleItem:
      properties:
        id:
          example: "1"
          nullable: false
          type: string
        name:
          example: Item 1
          nullable: false
          type: string
        scopeDescription:
          example: All Computers
          nullable: false
          type: string
        siteDescription:
          example: Example Site
          nullable: false
          type: string
      required:
        - id
        - name
        - scopeDescription
        - siteDescription
      type: object
    OnboardingEligibleItemsSearchResult:
      description: A list of onboarding eligible items
      properties:
        results:
          items:
            $ref: '#/components/schemas/OnboardingEligibleItem'
          type: array
        totalCount:
          example: 1
          nullable: false
          type: integer
      type: object
info:
  title: Jamf Pro API - Onboarding
  version: 0.0.1
openapi: 3.0.1
paths:
  /v1/onboarding/eligible-apps:
    get:
      description: Retrieves a list of applications that are eligible to be used in an onboarding configuration
      parameters:
        - $ref: _MonolithLibrary.yaml#/components/parameters/page
        - $ref: _MonolithLibrary.yaml#/components/parameters/page-size
        - description: 'Sorting criteria in the format: property:asc/desc. Default sort is id:asc. Multiple sort criteria are supported and must be separated with a comma. Example: sort=date:desc,name:asc '
          explode: true
          in: query
          name: sort
          required: false
          schema:
            default:
              - id:asc
            items:
              type: string
            type: array
          style: form
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OnboardingEligibleItemsSearchResult'
          description: OK
      summary: Retrieves a list of applications that are eligible to be used in an onboarding configuration
      tags:
        - onboarding
      x-required-privileges:
        - Read Onboarding Configuration
  /v1/onboarding/eligible-configuration-profiles:
    get:
      description: Retrieves a list of configuration profiles that are eligible to be used in an onboarding configuration
      parameters:
        - $ref: _MonolithLibrary.yaml#/components/parameters/page
        - $ref: _MonolithLibrary.yaml#/components/parameters/page-size
        - description: 'Sorting criteria in the format: property:asc/desc. Default sort is id:asc. Multiple sort criteria are supported and must be separated with a comma. Example: sort=date:desc,name:asc '
          explode: true
          in: query
          name: sort
          required: false
          schema:
            default:
              - id:asc
            items:
              type: string
            type: array
          style: form
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OnboardingEligibleItemsSearchResult'
          description: OK
      summary: Retrieves a list of configuration profiles that are eligible to be used in an onboarding configuration
      tags:
        - onboarding
      x-required-privileges:
        - Read Onboarding Configuration
  /v1/onboarding/eligible-policies:
    get:
      description: Retrieves a list of policies that are eligible to be used in an onboarding configuration
      parameters:
        - $ref: _MonolithLibrary.yaml#/components/parameters/page
        - $ref: _MonolithLibrary.yaml#/components/parameters/page-size
        - description: 'Sorting criteria in the format: property:asc/desc. Default sort is id:asc. Multiple sort criteria are supported and must be separated with a comma. Example: sort=date:desc,name:asc '
          explode: true
          in: query
          name: sort
          required: false
          schema:
            default:
              - id:asc
            items:
              type: string
            type: array
          style: form
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OnboardingEligibleItemsSearchResult'
          description: OK
      summary: Retrieves a list of policies that are eligible to be used in an onboarding configuration
      tags:
        - onboarding
      x-required-privileges:
        - Read Onboarding Configuration
  /v1/onboarding/history:
    get:
      description: |
        Gets Onboarding history object
      parameters:
        - $ref: _MonolithLibrary.yaml#/components/parameters/page
        - $ref: _MonolithLibrary.yaml#/components/parameters/page-size
        - description: 'Sorting criteria in the format: property:asc/desc. Default sort is date:desc. Multiple sort criteria are supported and must be separated with a comma. Example: sort=date:desc,name:asc '
          explode: true
          in: query
          name: sort
          required: false
          schema:
            default:
              - date:desc
            items:
              type: string
            type: array
          style: form
        - description: 'Query in the RSQL format, allowing to filter history notes collection. Default filter is empty query - returning all results for the requested page. Fields allowed in the query: username, date, note, details. This param can be combined with paging and sorting. Example: filter=username!=admin and date<2019-12-15'
          explode: true
          in: query
          name: filter
          required: false
          schema:
            default: ""
            type: string
          style: form
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: _MonolithLibrary.yaml#/components/schemas/HistorySearchResults
          description: Details of onboarding history were found
      summary: |
        Get Onboarding history object
      tags:
        - onboarding
      x-required-privileges:
        - Read Onboarding Configuration
    post:
      description: |
        Adds Onboarding history object notes
      requestBody:
        content:
          application/json:
            schema:
              $ref: _MonolithLibrary.yaml#/components/schemas/ObjectHistoryNote
        description: history notes to create
        required: true
      responses:
        201:
          content:
            application/json:
              schema:
                $ref: _MonolithLibrary.yaml#/components/schemas/HrefResponse
          description: Notes of onboarding history were added
        503:
          content:
            application/json:
              schema:
                $ref: _MonolithLibrary.yaml#/components/schemas/ApiError
          description: Onboarding history can not be saved
      summary: |
        Add Onboarding history object notes
      tags:
        - onboarding
      x-required-privileges:
        - Update Onboarding Configuration
  /v1/onboarding/history/export:
    post:
      description: |
        Export history object collection in specified format for Onboarding
      parameters:
        - $ref: _MonolithLibrary.yaml#/components/parameters/export-fields
        - $ref: _MonolithLibrary.yaml#/components/parameters/export-labels
        - $ref: _MonolithLibrary.yaml#/components/parameters/page
        - $ref: _MonolithLibrary.yaml#/components/parameters/page-size
        - description: 'Sorting criteria in the format: property:asc/desc. Default sort is date:desc. Multiple sort criteria are supported and must be separated with a comma. Example: sort=date:desc,name:asc '
          explode: true
          in: query
          name: sort
          required: false
          schema:
            default:
              - date:desc
            items:
              type: string
            type: array
          style: form
        - description: 'Query in the RSQL format, allowing to filter history notes collection. Default filter is empty query - returning all results for the requested page. Fields allowed in the query: username, date, note, details. This param can be combined with paging and sorting. Example: filter=username!=admin and date<2019-12-15'
          explode: true
          in: query
          name: filter
          required: false
          schema:
            default: ""
            type: string
          style: form
      requestBody:
        content:
          application/json:
            schema:
              $ref: _MonolithLibrary.yaml#/components/schemas/ExportParameters
        description: Optional. Override query parameters since they can make URI exceed 2,000 character limit.
        required: false
      responses:
        200:
          content:
            text/csv:
              schema:
                example: |
                  username,date,note,details
                  admin,2019-02-04 21:09:31,Edited,item detail
                format: binary
          description: Export successful
        400:
          content:
            application/json:
              schema:
                $ref: _MonolithLibrary.yaml#/components/schemas/ApiError
          description: Export fields specified incorrectly - non-existing column or duplicate on the list.
        503:
          content:
            application/json:
              schema:
                $ref: _MonolithLibrary.yaml#/components/schemas/ApiError
          description: Export currently unavailable, all export-related resources are in use. Try again later.
      summary: |
        Export history object collection in specified format for Onboarding
      tags:
        - onboarding
      x-action: true
      x-required-privileges:
        - Read Onboarding Configuration
servers:
  - url: /api
