components:
  schemas:
    OnboardingConfiguration:
      properties:
        enabled:
          example: true
          nullable: false
          type: boolean
        id:
          example: "1"
          readOnly: true
          type: string
        onboardingItems:
          items:
            $ref: '#/components/schemas/OnboardingItem'
          type: array
      required:
        - enabled
        - onboardingItems
      type: object
    OnboardingItem:
      properties:
        entityId:
          description: "The id of the Jamf Pro object that should be added to the onboarding workflow for end users.\nUse this in conjunction with the selfServiceEntityType. For example, if the policy with id 132\nshould be added to onboarding, then entityId should be 132 and selfServiceEntityType should be \nOS_X_POLICY.\n"
          example: "1"
          nullable: false
          type: string
        entityName:
          example: Policy 1
          readOnly: true
          type: string
        id:
          example: "3"
          nullable: true
          type: string
        priority:
          example: 35
          nullable: false
          type: integer
        scopeDescription:
          example: All Computers
          readOnly: true
          type: string
        selfServiceEntityType:
          enum:
            - OS_X_POLICY
            - OS_X_CONFIG_PROFILE
            - OS_X_MAC_APP
            - OS_X_APP_INSTALLER
            - OS_X_EBOOK
            - OS_X_PATCH_POLICY
            - UNKNOWN
          example: OS_X_POLICY
          nullable: false
          type: string
        siteDescription:
          example: None
          readOnly: true
          type: string
      required:
        - entityId
        - priority
        - selfServiceEntityType
      type: object
info:
  title: Jamf Pro API - OnboardingConfiguration
  version: 0.0.1
openapi: 3.0.1
paths:
  /v1/onboarding:
    get:
      description: Get the current onboarding settings configuration.
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OnboardingConfiguration'
          description: Success
      summary: Get the current onboarding settings configuration.
      tags:
        - onboarding
      x-required-privileges:
        - Read Onboarding Configuration
    put:
      description: Update the onboarding configuration.
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/OnboardingConfiguration'
        description: Onboarding settings to save.
        required: true
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OnboardingConfiguration'
          description: Successfully updated
        400:
          content:
            application/json:
              schema:
                $ref: _MonolithLibrary.yaml#/components/schemas/ApiError
          description: Unable to add invalid or ineligible items to the onboarding configuration.
      summary: Update the onboarding configuration.
      tags:
        - onboarding
      x-required-privileges:
        - Update Onboarding Configuration
servers:
  - url: /api
