components:
  schemas:
    DayOfWeek:
      enum:
        - MONDAY
        - TUESDAY
        - WEDNESDAY
        - THURSDAY
        - FRIDAY
        - SATURDAY
        - SUNDAY
      type: string
    ParentApp:
      properties:
        allowClearPasscode:
          example: true
          type: boolean
        allowTemplates:
          example: true
          type: boolean
        deviceGroupId:
          example: 1
          type: integer
        disassociateOnWipeAndReEnroll:
          example: true
          type: boolean
        isEnabled:
          example: true
          type: boolean
        restrictedTimes:
          additionalProperties:
            $ref: '#/components/schemas/TimeFrame'
          example:
            SUNDAY:
              beginTime: 08:30:00
              endTime: 15:45:00
          properties:
            key:
              $ref: '#/components/schemas/DayOfWeek'
          type: object
        safelistedApps:
          items:
            $ref: _MonolithLibrary.yaml#/components/schemas/SafelistedApp
          type: array
        timezoneId:
          example: Europe/Paris
          type: string
      required:
        - deviceGroupId
        - isEnabled
        - restrictedTimes
        - timezoneId
      type: object
    TimeFrame:
      properties:
        beginTime:
          example: 08:30:00
          type: string
        endTime:
          example: 15:45:00
          type: string
      type: object
info:
  title: Jamf Pro API - ParentApp
  version: 0.0.1
openapi: 3.0.1
paths:
  /v1/parent-app:
    get:
      description: |
        Get the current Jamf Parent app settings
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ParentApp'
          description: Details of the current Jamf Parent app settings.
      summary: |
        Get the current Jamf Parent app settings
      tags:
        - parent-app-preview
      x-required-privileges:
        - Read Parent App Settings
    put:
      description: |
        Update Jamf Parent app settings
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ParentApp'
        description: Jamf Parent app settings to save.
        required: true
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ParentApp'
          description: Jamf Parent app settings updated
        400:
          content:
            application/json:
              schema:
                $ref: _MonolithLibrary.yaml#/components/schemas/ApiError
          description: Bad Request, could not parse input.
      summary: |
        Update Jamf Parent app settings
      tags:
        - parent-app-preview
      x-required-privileges:
        - Update Parent App Settings
  /v1/parent-app/history:
    get:
      description: |
        Gets Jamf Parent app settings history
      parameters:
        - $ref: _MonolithLibrary.yaml#/components/parameters/page
        - $ref: _MonolithLibrary.yaml#/components/parameters/page-size
        - $ref: _MonolithLibrary.yaml#/components/parameters/filter
        - description: 'Sorting criteria in the format: property:asc/desc. Default sort is date:desc. Multiple sort criteria are supported and must be separated with a comma. Example: sort=date:desc,name:asc '
          explode: true
          in: query
          name: sort
          required: false
          schema:
            default: date:desc
            type: string
          style: form
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: _MonolithLibrary.yaml#/components/schemas/HistorySearchResults
          description: Details of Jamf Parent app settings history were found
      summary: |
        Get Jamf Parent app settings history
      tags:
        - parent-app-preview
      x-required-privileges:
        - Read Parent App Settings
    post:
      description: |
        Adds Jamf Parent app settings history notes
      requestBody:
        content:
          application/json:
            schema:
              $ref: _MonolithLibrary.yaml#/components/schemas/ObjectHistoryNote
        description: history notes to create
        required: true
      responses:
        201:
          content:
            application/json:
              schema:
                $ref: _MonolithLibrary.yaml#/components/schemas/ObjectHistory
          description: Notes to Jamf Parent app settings history were added
        503:
          content:
            application/json:
              schema:
                $ref: _MonolithLibrary.yaml#/components/schemas/ApiError
          description: Jamf Parent app history can not be saved
      summary: |
        Add Jamf Parent app settings history notes
      tags:
        - parent-app-preview
      x-required-privileges:
        - Update Parent App Settings
servers:
  - url: /api
