openapi: 3.0.1
info:
  title: Jamf Pro API - Definitions Library
  description: These definitions exist to be re-used by other Parent and Teacher app swagger files.
  version: 0.0.1
paths: {}
components:
  schemas:
    SafelistedApp:
      type: object
      properties:
        name:
          type: string
          example: Content Filter
        bundleId:
          type: string
          example: com.jamf.parent
