components:
  schemas:
    PatchPolicyLogDetail:
      properties:
        actions:
          items:
            $ref: '#/components/schemas/PatchPolicyLogDetailAction'
          type: array
        attemptNumber:
          example: 1
          type: integer
        deviceId:
          example: "1"
          type: string
        id:
          example: "1"
          type: string
      type: object
    PatchPolicyLogDetailAction:
      properties:
        action:
          example: Installing...
          type: string
        actionOrder:
          example: 1
          type: integer
        id:
          example: "1"
          type: string
      type: object
    PatchPolicyLogEligibleRetryCount:
      properties:
        count:
          example: 5
          type: integer
      type: object
    PatchPolicyLogRetry:
      properties:
        deviceIds:
          example:
            - "1"
            - "3"
          items:
            type: string
          type: array
      type: object
    PatchPolicyLogV2:
      properties:
        attemptNumber:
          example: 1
          type: integer
        deviceId:
          example: "1"
          type: string
        deviceName:
          example: Admins Macbook
          type: string
        ignoredForPatchPolicyId:
          example: "1"
          type: string
        patchPolicyId:
          example: "1"
          type: string
        statusCode:
          example: 1
          type: integer
        statusDate:
          example: "2019-02-04T21:09:31.661Z"
          format: date-time
          type: string
        statusEnum:
          enum:
            - UNKNOWN
            - PENDING
            - COMPLETED
            - FAILED
          example: COMPLETED
          type: string
      type: object
    PatchPolicyLogs:
      properties:
        results:
          items:
            $ref: '#/components/schemas/PatchPolicyLogV2'
          type: array
        totalCount:
          example: 1
          type: integer
      type: object
info:
  title: Jamf Pro API - PatchPolicyLogs
  version: 0.0.1
openapi: 3.0.1
paths:
  /v2/patch-policies/{id}/logs:
    get:
      description: Retrieves Patch Policy Logs
      parameters:
        - description: patch policy id
          explode: false
          in: path
          name: id
          required: true
          schema:
            type: string
          style: simple
        - $ref: _MonolithLibrary.yaml#/components/parameters/page
        - $ref: _MonolithLibrary.yaml#/components/parameters/page-size
        - description: 'Sorting criteria in the format: property:asc/desc. Default sort is deviceName:asc. Multiple sort criteria are supported and must be separated with a comma.'
          explode: true
          in: query
          name: sort
          required: false
          schema:
            default:
              - deviceName:asc
            items:
              type: string
            type: array
          style: form
        - description: 'Query in the RSQL format, allowing to filter Patch Policy Logs collection. Default filter is empty query - returning all results for the requested page. Fields allowed in the query: deviceId, deviceName, statusCode, statusDate, attemptNumber, ignoredForPatchPolicyId. This param can be combined with paging and sorting.'
          explode: true
          in: query
          name: filter
          required: false
          schema:
            default: ""
            type: string
          style: form
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PatchPolicyLogs'
          description: Success
        400:
          content:
            application/json:
              schema:
                $ref: _MonolithLibrary.yaml#/components/schemas/ApiError
          description: Bad Request
        404:
          content:
            application/json:
              schema:
                $ref: _MonolithLibrary.yaml#/components/schemas/ApiError
          description: Patch Policy Log with that id does not exist
      summary: |
        Retrieve Patch Policy Logs
      tags:
        - patch-policy-logs
      x-required-privileges:
        - Read Patch Policies
  /v2/patch-policies/{id}/logs/eligible-retry-count:
    get:
      description: return the count of the patch policy logs for the patch policy id that  are eligible for a retry attempt
      parameters:
        - description: patch policy id
          explode: false
          in: path
          name: id
          required: true
          schema:
            type: string
          style: simple
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PatchPolicyLogEligibleRetryCount'
          description: Number of patch policy logs found
      summary: |
        Return the count of the Patch Policy Logs for the patch policy id that are eligible for a retry attempt
      tags:
        - patch-policy-logs
      x-required-privileges:
        - Read Patch Policies
  /v2/patch-policies/{id}/logs/retry:
    post:
      description: Send retry attempts for specific devices
      parameters:
        - description: patch policy id
          explode: false
          in: path
          name: id
          required: true
          schema:
            type: string
          style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PatchPolicyLogRetry'
        required: true
      responses:
        204:
          description: OK
      summary: Send retry attempts for specific devices
      tags:
        - patch-policy-logs
      x-action: true
      x-required-privileges:
        - Update Patch Policies
  /v2/patch-policies/{id}/logs/retry-all:
    post:
      description: Send retry attempts for all devices
      parameters:
        - description: patch policy id
          explode: false
          in: path
          name: id
          required: true
          schema:
            type: string
          style: simple
      responses:
        202:
          description: OK
        204:
          description: OK
      summary: Send retry attempts for all devices
      tags:
        - patch-policy-logs
      x-action: true
      x-required-privileges:
        - Update Patch Policies
  /v2/patch-policies/{id}/logs/{deviceId}:
    get:
      description: Retrieves a single Patch Policy Log
      parameters:
        - description: patch policy id
          explode: false
          in: path
          name: id
          required: true
          schema:
            type: string
          style: simple
        - description: device id
          explode: false
          in: path
          name: deviceId
          required: true
          schema:
            type: string
          style: simple
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PatchPolicyLogV2'
          description: Patch Policy Log
        404:
          content:
            application/json:
              schema:
                $ref: _MonolithLibrary.yaml#/components/schemas/ApiError
          description: Patch Policy Logs with those ids do not exist
      summary: |
        Retrieves a single Patch Policy Log
      tags:
        - patch-policy-logs
      x-required-privileges:
        - Read Patch Policies
  /v2/patch-policies/{id}/logs/{deviceId}/details:
    get:
      description: Return attempt details for a specific log
      parameters:
        - description: patch policy id
          explode: false
          in: path
          name: id
          required: true
          schema:
            type: string
          style: simple
        - description: device id
          explode: false
          in: path
          name: deviceId
          required: true
          schema:
            type: string
          style: simple
      responses:
        200:
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/PatchPolicyLogDetail'
                type: array
          description: Attempt details
        404:
          content:
            application/json:
              schema:
                $ref: _MonolithLibrary.yaml#/components/schemas/ApiError
          description: Patch Policy Logs with those ids do not exist
      summary: Return attempt details for a specific log
      tags:
        - patch-policy-logs
      x-required-privileges:
        - Read Patch Policies
servers:
  - url: /api
