info:
  title: Jamf Pro API - PatchTitles
  version: 0.0.1
openapi: 3.0.1
paths:
  /v2/patch-management-accept-disclaimer:
    post:
      description: Accept Patch Management disclaimer
      responses:
        202:
          description: Accepted
      summary: |
        Accept Patch Management disclaimer
      tags:
        - patch-management
      x-action: true
      x-required-privileges:
        - Update Patch Management Software Titles
servers:
  - url: /api
