openapi: 3.0.1
info:
  title: Jamf Pro API - Refresh Cellular Plans Command Definition
  description: This MDM command definition exists to be re-used by multiple other Swagger files.
  version: 0.0.1
paths: {}
components:
  schemas:
    RefreshCellularPlansCommand:
      allOf:
        - $ref: 'MdmDefinitionsLibrary.yaml#/components/schemas/MdmCommandBase'
        - type: object
          properties:
            esimServerUrl:
              type: string
              example: 'https://esim.example.com'
              description: The URL of the eSIM server that the device should contact to refresh
                cellular plans.
              minLength: 1
              maxLength: 2048
          required:
            - esimServerUrl
