openapi: 3.0.3
info:
  title: Jamf Pro API - Remove Computer MDM Profile
  description: Jamf Pro API - Remove Computer MDM Profile
  version: 0.0.1
paths:
  /v1/computer-inventory/{id}/remove-mdm-profile:
    post:
      tags:
        - computer-inventory
      summary: |
        Remove a computer's MDM profile
      description: Remove a computer's MDM profile
      parameters:
        - name: id
          in: path
          description: Id of the computer to remove the MDM profile from
          required: true
          schema:
            type: string
      responses:
        200:
          description: Command to remove the mdm profile was queued
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/RemoveComputerMdmProfileResponse'
        403:
          description: Insufficient privileges to perform this action.
        500:
          description: Failure, unable to queue command.
          content:
            'application/json':
              schema:
                $ref: 'DefinitionsLibrary.yaml#/components/schemas/ApiError'
      x-required-privileges:
        - Send Computer Unmanage Command
      x-action: true
components:
  schemas:
    RemoveComputerMdmProfileResponse:
      type: object
      properties:
        deviceId:
          type: string
          example: 1234
          description: Id of the computer whose MDM profile was removed
        commandUuid:
          type: string
          example: "1234-5678-90ab-cdef-1234567890ab"
          description: Uuid of the command queued that removes the MDM profile