info:
  title: Jamf Pro API - RemoveComputerMdmProfile
  version: 0.0.1
openapi: 3.0.1
paths:
  /v1/computer-inventory/{id}/remove-mdm-profile:
    post:
      deprecated: true
      description: Remove a computer's MDM profile
      parameters:
        - description: Id of the computer to remove the MDM profile from
          explode: false
          in: path
          name: id
          required: true
          schema:
            type: string
          style: simple
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: _MonolithLibrary.yaml#/components/schemas/RemoveComputerMdmProfileResponse
          description: Command to remove the mdm profile was queued
        403:
          description: Insufficient privileges to perform this action.
        500:
          content:
            application/json:
              schema:
                $ref: _MonolithLibrary.yaml#/components/schemas/ApiError
          description: Failure, unable to queue command.
      summary: |
        Remove a computer's MDM profile
      tags:
        - computer-inventory
      x-action: true
      x-deprecation-date: "2026-07-14"
      x-required-privileges:
        - Send Computer Unmanage Command
servers:
  - url: /api
