openapi: 3.0.1
info:
  title: Jamf Pro API - Remote administration configurations
  version: 0.0.1
paths:
  /preview/remote-administration-configurations:
    get:
      tags:
        - remote-administration
      summary: Get information about all remote administration configurations.
      description: Remote administration feature creates a secure screen-sharing experience between Jamf Pro administrators and their end-users.
      parameters:
        - $ref: 'DefinitionsLibrary.yaml#/components/parameters/page'
        - $ref: 'DefinitionsLibrary.yaml#/components/parameters/page-size'
      responses:
        200:
          description: Remote administration configurations returned.
          content:
            'application/json':
              schema:
                $ref: 'RemoteAdministrationDefinitions.yaml#/components/schemas/RemoteAdministrationSearchResults'
        404:
          description: Remote Administration feature is not available.
          content:
            'application/json':
              schema:
                $ref: 'DefinitionsLibrary.yaml#/components/schemas/ApiError'
      x-required-privileges:
        - Read Remote Administration

components:
  schemas: {}
