components:
  schemas:
    UnmanageMobileDeviceResponse:
      properties:
        commandUuid:
          description: Uuid of the command queued that removes the MDM profile
          example: 1234-5678-90ab-cdef-1234567890ab
          type: string
        deviceId:
          description: Id of the mobile device whose MDM profile was removed
          example: "1234"
          type: string
      required:
        - commandUuid
        - deviceId
      type: object
info:
  title: Jamf Pro API - RemoveMobileDeviceMdmProfile
  version: 0.0.1
openapi: 3.0.1
paths:
  /v2/mobile-devices/{id}/unmanage:
    post:
      description: Unmanage a Mobile Device
      parameters:
        - description: Id of the mobile device to remove the MDM profile from
          explode: false
          in: path
          name: id
          required: true
          schema:
            type: string
          style: simple
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UnmanageMobileDeviceResponse'
          description: Command to remove the mdm profile was queued
        403:
          description: Insufficient privileges to perform this action.
        500:
          content:
            application/json:
              schema:
                $ref: _MonolithLibrary.yaml#/components/schemas/ApiError
          description: Failure, unable to queue command.
      summary: |
        Unmanage a Mobile Device
      tags:
        - mobile-devices
      x-action: true
      x-required-privileges:
        - Unmanage Mobile Devices
servers:
  - url: /api
