components:
  schemas:
    RenewMdmProfileResponse:
      properties:
        udidsNotProcessed:
          $ref: '#/components/schemas/Udids'
      type: object
    Udids:
      properties:
        udids:
          items:
            example: 6E47EF55-5318-494F-A09E-70F613E0AFD1
            type: string
          type: array
      type: object
info:
  title: Jamf Pro API - RenewMdmProfile
  version: 0.0.1
openapi: 3.0.1
paths:
  /v1/mdm/renew-profile:
    post:
      description: |
        Renews the device's MDM Profile, including the device identity certificate within the MDM Profile.
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Udids'
        description: List of devices' UDIDs to perform MDM profile renewal
        required: true
      responses:
        202:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RenewMdmProfileResponse'
          description: |
            The Renew MDM Profile action was queued with APNs for submitted devices. Any device udids returned were unknown and not submitted.
        403:
          description: Insufficient privileges to perform this action or Renew MDM Profile is not enabled.
      summary: |
        Renew MDM Profile
      tags:
        - mdm
      x-action: true
      x-required-privileges:
        - Send Command to Renew MDM Profile
servers:
  - url: /api
