openapi: 3.0.1
info:
  title: Jamf Pro API - Restart Device Command Definition
  description: This MDM commands exist to be re-used by multiple other Swagger files.
  version: 0.0.1
paths: {}
components:
  schemas:
    RestartDeviceCommand:
      allOf:
        - $ref: 'MdmDefinitionsLibrary.yaml#/components/schemas/MdmCommandBase'
        - type: object
          properties:
            rebuildKernelCache:
              type: boolean
              example: true
              required: false
            kextPaths:
              type: array
              items:
                type: string
              example:
                - extension1
                - extension2
              required: false
              description: Only used if RebuildKernelCache is true
            notifyUser:
              type: boolean
              example: true
              required: false