components:
  schemas:
    ReturnToServiceConfiguration:
      properties:
        displayName:
          default: "false"
          example: displayName
          nullable: false
          type: string
        id:
          description: Id of the Return to Service Configuration.
          example: "1"
          minimum: 1
          nullable: false
          type: string
        wifiProfileId:
          description: Id of the wifi profile that is associated with the return to service configuration.
          example: "1"
          nullable: false
          type: string
      type: object
    ReturnToServiceConfigurationRequest:
      properties:
        displayName:
          default: "false"
          description: Display name of the Return to Service Configuration.
          example: displayName
          nullable: false
          type: string
        wifiProfileId:
          description: Id of the wifi profile that is associated with the return to service configuration.
          example: "1"
          nullable: false
          type: string
      type: object
    ReturnToServiceConfigurationSearchResults:
      properties:
        results:
          items:
            $ref: '#/components/schemas/ReturnToServiceConfiguration'
          minItems: 0
          type: array
        totalCount:
          example: 1
          minimum: 0
          type: integer
      type: object
info:
  title: Jamf Pro API - ReturnToServiceConfiguration
  version: 0.0.1
openapi: 3.0.1
paths:
  /v1/return-to-service:
    get:
      description: Gets all return to service configurations.
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ReturnToServiceConfigurationSearchResults'
          description: Successful response
      summary: |
        Get all Return to Service Configurations
      tags:
        - return-to-service
      x-required-privileges:
        - View Return To Service Configurations
    post:
      description: Create a return to service configuration
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ReturnToServiceConfigurationRequest'
        description: Return to Service Configuration to create. ids defined in this body will be ignored
        required: true
      responses:
        201:
          content:
            application/json:
              schema:
                $ref: _MonolithLibrary.yaml#/components/schemas/HrefResponse
          description: Return to Service Configuration was created
        400:
          content:
            application/json:
              schema:
                $ref: _MonolithLibrary.yaml#/components/schemas/ApiError
          description: Bad Request
      summary: |
        Create a Return to Service Configuration
      tags:
        - return-to-service
      x-required-privileges:
        - Edit Return To Service Configurations
  /v1/return-to-service/{id}:
    delete:
      description: Deletes a Return To Service Configuration with the supplied id
      parameters:
        - description: Return To Service Configurations identifier
          explode: false
          in: path
          name: id
          required: true
          schema:
            type: string
          style: simple
      responses:
        204:
          description: Success
        404:
          content:
            application/json:
              schema:
                $ref: _MonolithLibrary.yaml#/components/schemas/ApiError
          description: Return to Service Configuration with that id does not exist
      summary: |
        Delete a Return To Service Configuration with the supplied id
      tags:
        - return-to-service
      x-required-privileges:
        - Delete Return To Service Configurations
    get:
      description: Retrieves a Return to Service Configuration with the supplied id
      parameters:
        - description: Return to Service Configuration identifier
          explode: false
          in: path
          name: id
          required: true
          schema:
            type: string
          style: simple
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ReturnToServiceConfiguration'
          description: Success
        404:
          content:
            application/json:
              schema:
                $ref: _MonolithLibrary.yaml#/components/schemas/ApiError
          description: Return to Service Configuration with that id does not exist
      summary: |
        Retrieve a Return to Service Configuration with the supplied id
      tags:
        - return-to-service
      x-required-privileges:
        - View Return To Service Configurations
    put:
      description: Updates a Return to Service Configuration
      parameters:
        - description: Return to Service Configuration identifier
          explode: false
          in: path
          name: id
          required: true
          schema:
            type: string
          style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ReturnToServiceConfigurationRequest'
        description: Return to Service Configuration to update
        required: true
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ReturnToServiceConfiguration'
          description: Success
        400:
          content:
            application/json:
              schema:
                $ref: _MonolithLibrary.yaml#/components/schemas/ApiError
          description: Bad Request
        404:
          content:
            application/json:
              schema:
                $ref: _MonolithLibrary.yaml#/components/schemas/ApiError
          description: Return to Service Configuration with that id does not exist
        409:
          content:
            application/json:
              schema:
                $ref: _MonolithLibrary.yaml#/components/schemas/ApiError
          description: The Return to Service Configuration was modified by another process. Read the Return to Service Configuration again for updated changes.
      summary: |
        Update a Return to Service Configuration
      tags:
        - return-to-service
      x-required-privileges:
        - Edit Return To Service Configurations
servers:
  - url: /api
