components:
  schemas:
    SchedulerJob:
      properties:
        results:
          items:
            $ref: '#/components/schemas/SchedulerTrigger'
          type: array
        totalCount:
          example: 1
          type: integer
      readOnly: true
      type: object
    SchedulerJobs:
      properties:
        jobKeys:
          items:
            example: EXAMPLE_JOB
            type: string
          type: array
      readOnly: true
      type: object
    SchedulerSummary:
      properties:
        numberOfExecutedJobs:
          example: 1
          type: integer
        numberOfExecutingJobs:
          example: 1
          type: integer
        numberOfPendingJobs:
          example: 1
          type: integer
        started:
          example: true
          type: boolean
      readOnly: true
      type: object
    SchedulerTrigger:
      properties:
        nextFireTime:
          example: "2023-08-21T21:30:34.35Z"
          format: date-time
          type: string
        previousFireTime:
          example: "2023-08-21T21:20:34.35Z"
          format: date-time
          type: string
        triggerKey:
          example: EXAMPLE_TRIGGER
          type: string
      readOnly: true
      type: object
info:
  title: Jamf Pro API - Scheduler
  version: 0.0.1
openapi: 3.0.1
paths:
  /v1/scheduler/jobs:
    get:
      description: Retrieves the names of all Jamf Pro Scheduler jobs
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SchedulerJobs'
          description: Success
      summary: Retrieve all Jamf Pro Scheduler jobs
      tags:
        - scheduler
      x-authentication-required: true
  /v1/scheduler/jobs/{jobKey}/triggers:
    get:
      description: Retrieves all triggers for a Jamf Pro Scheduler job
      parameters:
        - description: Jamf Pro Scheduler Job Key
          explode: false
          in: path
          name: jobKey
          required: true
          schema:
            type: string
          style: simple
        - $ref: _MonolithLibrary.yaml#/components/parameters/page
        - $ref: _MonolithLibrary.yaml#/components/parameters/page-size
        - description: Sorts results by one or more criteria, following the format property:asc/desc. Default sort is nextFireTime:asc. If using multiple criteria, separate with commas.
          explode: true
          in: query
          name: sort
          required: false
          schema:
            default:
              - nextFireTime:asc
            items:
              type: string
            type: array
          style: form
        - description: 'Query in the RSQL format, allowing to filter the Jamf Pro Scheduler triggers collection. Default filter is empty query - returning all results for the requested page. Fields allowed in the query: triggerKey, previousFireTime, nextFireTime.'
          explode: true
          in: query
          name: filter
          required: false
          schema:
            default: ""
            type: string
          style: form
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SchedulerJob'
          description: Success
      summary: Retrieve all triggers for a Jamf Pro Scheduler job
      tags:
        - scheduler
      x-authentication-required: true
  /v1/scheduler/summary:
    get:
      description: Retrieves a summary of the Jamf Pro Scheduler
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SchedulerSummary'
          description: Success
      summary: Retrieve a summary of the Jamf Pro Scheduler
      tags:
        - scheduler
      x-authentication-required: true
servers:
  - url: /api
