components:
  schemas:
    SelfServicePlusSettings:
      properties:
        enabled:
          description: Whether Self Service Plus is enabled
          example: true
          nullable: false
          type: boolean
      type: object
info:
  title: Jamf Pro API - SelfServicePlus
  version: 0.0.1
openapi: 3.0.1
paths:
  /v1/self-service-plus/feature-toggle/enabled:
    get:
      description: |
        This endpoint is used to determine if the Self Service Plus feature toggle is enabled.
      operationId: getSelfServicePlusFeatureToggleEnabled
      responses:
        204:
          description: Feature toggle is enabled
        404:
          description: Feature toggle is disabled
      summary: Determines if Self Service Plus feature toggle is enabled.
      tags:
        - self-service-plus
      x-authentication-required: true
  /v1/self-service-plus/settings:
    get:
      description: Get Self Service Plus settings.
      operationId: getSelfServicePlusSettings
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SelfServicePlusSettings'
          description: Self Service Plus settings
      summary: Get Self Service Plus settings.
      tags:
        - self-service-plus
      x-required-privileges:
        - Read Self Service
    put:
      description: Save Self Service Plus settings.
      operationId: putSelfServicePlusSettings
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SelfServicePlusSettings'
        description: Self Service Plus settings
        required: true
      responses:
        204:
          description: Successful PUT
      summary: Save Self Service Plus settings.
      tags:
        - self-service-plus
      x-required-privileges:
        - Update Self Service
servers:
  - url: /api
