components:
  schemas:
    IosBrandingConfiguration:
      properties:
        brandingName:
          example: Self Service
          type: string
        brandingNameColorCode:
          example: "000000"
          type: string
        headerBackgroundColorCode:
          example: FFFFFF
          type: string
        iconId:
          example: 1
          type: integer
        id:
          example: "1"
          readOnly: true
          type: string
        menuIconColorCode:
          example: "000001"
          type: string
        statusBarTextColor:
          example: dark
          type: string
      required:
        - brandingName
        - brandingNameColorCode
        - headerBackgroundColorCode
        - menuIconColorCode
        - statusBarTextColor
      type: object
    IosBrandingSearchResults:
      properties:
        results:
          items:
            $ref: '#/components/schemas/IosBrandingConfiguration'
          type: array
        totalCount:
          example: 1
          minimum: 0
          type: integer
      type: object
    MacOsBrandingConfiguration:
      properties:
        applicationName:
          example: Self Service
          type: string
        brandingHeaderImageId:
          example: 1
          type: integer
        brandingName:
          example: Self Service
          type: string
        brandingNameSecondary:
          example: Self Service
          type: string
        homeHeading:
          example: Welcome to Self Service
          type: string
        homeSubheading:
          example: We help organizations succeed with Apple
          type: string
        iconId:
          example: 1
          type: integer
        id:
          example: "1"
          readOnly: true
          type: string
      type: object
    MacOsBrandingSearchResults:
      properties:
        results:
          items:
            $ref: '#/components/schemas/MacOsBrandingConfiguration'
          type: array
        totalCount:
          example: 1
          minimum: 0
          type: integer
      type: object
info:
  title: Jamf Pro API - SelfServiceBranding
  version: 0.0.1
openapi: 3.0.1
paths:
  /self-service/branding/images:
    post:
      description: Uploads an image
      requestBody:
        content:
          multipart/form-data:
            schema:
              properties:
                file:
                  description: The file to upload
                  format: binary
                  type: string
              required:
                - file
              type: object
        required: true
      responses:
        201:
          content:
            application/json:
              schema:
                $ref: _MonolithLibrary.yaml#/components/schemas/BrandingImageUrl
          description: Image successfully uploaded
      summary: |
        Upload an image
      tags:
        - self-service-branding-preview
      x-required-privileges:
        - Update Self Service Branding Configuration
  /v1/self-service/branding/ios:
    get:
      description: Search for sorted and paged iOS branding configurations
      parameters:
        - $ref: _MonolithLibrary.yaml#/components/parameters/page
        - $ref: _MonolithLibrary.yaml#/components/parameters/page-size
        - description: 'Sorting criteria in the format: property:asc/desc. Default sort is id:asc. Multiple sort criteria are supported and must be separated with a comma. Example: sort=id:desc,brandingName:asc '
          explode: true
          in: query
          name: sort
          required: false
          schema:
            default:
              - id:asc
            items:
              type: string
            type: array
          style: form
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/IosBrandingSearchResults'
          description: Successful response
      summary: |
        Search for sorted and paged iOS branding configurations
      tags:
        - self-service-branding-ios
      x-required-privileges:
        - Read Self Service Branding Configuration
    post:
      description: Create a Self Service iOS branding configuration with the supplied details
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/IosBrandingConfiguration'
        description: The iOS branding configuration to create
        required: false
      responses:
        201:
          content:
            application/json:
              schema:
                $ref: _MonolithLibrary.yaml#/components/schemas/HrefResponse
          description: Successful response
      summary: |
        Create a Self Service iOS branding configuration with the supplied
      tags:
        - self-service-branding-ios
      x-required-privileges:
        - Create Self Service Branding Configuration
  /v1/self-service/branding/ios/{id}:
    delete:
      description: Delete the Self Service iOS branding configuration indicated by the provided id.
      parameters:
        - description: id of iOS branding configuration
          explode: false
          in: path
          name: id
          required: true
          schema:
            type: string
          style: simple
      responses:
        204:
          description: Successful response
        404:
          content:
            application/json:
              schema:
                $ref: _MonolithLibrary.yaml#/components/schemas/ApiError
          description: Invalid id
      summary: |
        Delete the Self Service iOS branding configuration indicated by the provided id
      tags:
        - self-service-branding-ios
      x-required-privileges:
        - Delete Self Service Branding Configuration
    get:
      description: Read a single Self Service iOS branding configuration indicated by the provided id.
      parameters:
        - description: id of iOS branding configuration
          explode: false
          in: path
          name: id
          required: true
          schema:
            type: string
          style: simple
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/IosBrandingConfiguration'
          description: Successful response
      summary: |
        Read a single Self Service iOS branding configuration indicated by the provided id
      tags:
        - self-service-branding-ios
      x-required-privileges:
        - Read Self Service Branding Configuration
    put:
      description: Update a Self Service iOS branding configuration with the supplied details
      parameters:
        - description: id of iOS branding configuration
          explode: false
          in: path
          name: id
          required: true
          schema:
            type: string
          style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/IosBrandingConfiguration'
        description: The iOS branding configuration values to update
        required: false
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/IosBrandingConfiguration'
          description: Successful response
        404:
          content:
            application/json:
              schema:
                $ref: _MonolithLibrary.yaml#/components/schemas/ApiError
          description: Invalid id
      summary: |
        Update a Self Service iOS branding configuration with the supplied details
      tags:
        - self-service-branding-ios
      x-required-privileges:
        - Update Self Service Branding Configuration
  /v1/self-service/branding/macos:
    get:
      description: Search for sorted and paged macOS branding configurations
      parameters:
        - $ref: _MonolithLibrary.yaml#/components/parameters/page
        - $ref: _MonolithLibrary.yaml#/components/parameters/page-size
        - description: 'Sorting criteria in the format: property:asc/desc. Default sort is id:asc. Multiple sort criteria are supported and must be separated with a comma. Example: sort=id:desc,brandingName:asc '
          explode: true
          in: query
          name: sort
          required: false
          schema:
            default:
              - id:asc
            items:
              type: string
            type: array
          style: form
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MacOsBrandingSearchResults'
          description: Successful response
      summary: |
        Search for sorted and paged macOS branding configurations
      tags:
        - self-service-branding-macos
      x-required-privileges:
        - Read Self Service Branding Configuration
        - Read Self Service
    post:
      description: Create a Self Service macOS branding configuration with the supplied details
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MacOsBrandingConfiguration'
        description: The macOS branding configuration to create
        required: false
      responses:
        201:
          content:
            application/json:
              schema:
                $ref: _MonolithLibrary.yaml#/components/schemas/HrefResponse
          description: Successful response
      summary: |
        Create a Self Service macOS branding configuration with the supplied
      tags:
        - self-service-branding-macos
      x-required-privileges:
        - Create Self Service Branding Configuration
  /v1/self-service/branding/macos/{id}:
    delete:
      description: Delete the Self Service macOS branding configuration indicated by the provided id.
      parameters:
        - description: id of macOS branding configuration
          explode: false
          in: path
          name: id
          required: true
          schema:
            type: string
          style: simple
      responses:
        204:
          description: Successful response
        404:
          content:
            application/json:
              schema:
                $ref: _MonolithLibrary.yaml#/components/schemas/ApiError
          description: Invalid id
      summary: |
        Delete the Self Service macOS branding configuration indicated by the provided id
      tags:
        - self-service-branding-macos
      x-required-privileges:
        - Delete Self Service Branding Configuration
    get:
      description: Read a single Self Service macOS branding configuration indicated by the provided id.
      parameters:
        - description: id of macOS branding configuration
          explode: false
          in: path
          name: id
          required: true
          schema:
            type: string
          style: simple
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MacOsBrandingConfiguration'
          description: Successful response
      summary: |
        Read a single Self Service macOS branding configuration indicated by the provided id
      tags:
        - self-service-branding-macos
      x-required-privileges:
        - Read Self Service Branding Configuration
    put:
      description: Update a Self Service macOS branding configuration with the supplied details
      parameters:
        - description: id of macOS branding configuration
          explode: false
          in: path
          name: id
          required: true
          schema:
            type: string
          style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MacOsBrandingConfiguration'
        description: The macOS branding configuration values to update
        required: false
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MacOsBrandingConfiguration'
          description: Successful response
        404:
          content:
            application/json:
              schema:
                $ref: _MonolithLibrary.yaml#/components/schemas/ApiError
          description: Invalid id
      summary: |
        Update a Self Service macOS branding configuration with the supplied details
      tags:
        - self-service-branding-macos
      x-required-privileges:
        - Update Self Service Branding Configuration
servers:
  - url: /api
