components:
  schemas:
    SelfServiceInstallSettings:
      description: |
        object representation of Self Service settings regarding installation
      properties:
        installAutomatically:
          default: false
          description: |
            true if Self Service is installed automatically, false if not
          type: boolean
        installLocation:
          description: |
            path at which Self Service is installed. Required if installAutomatically is true
          example: /Applications
          type: string
      required:
        - installLocation
      type: object
    SelfServiceInteractionSettings:
      description: |
        object representation of Self Service settings regarding user interaction
      properties:
        alertUserApprovedMdm:
          default: true
          description: |
            whether users should be notified they need to approve organization's MDM profile
          type: boolean
        bookmarksName:
          description: |
            renamed string for bookmarks if the admin wishes
          example: Bookmarks
          type: string
        defaultHomeCategoryId:
          default: -1
          description: |
            id for the default home category in Self Service
          format: int32
          minimum: -4
          type: integer
        defaultLandingPage:
          default: HOME
          description: |
            the default landing page in Self Service
          enum:
            - HOME
            - BROWSE
            - HISTORY
            - NOTIFICATIONS
          example: HOME
          type: string
        notificationsEnabled:
          default: false
          description: |
            global Self Service setting for if notifications are on or off
          type: boolean
      required:
        - bookmarksName
      type: object
    SelfServiceLoginSettings:
      description: |
        object representation of Self Service settings regarding login
      properties:
        allowRememberMe:
          default: false
          description: |
            true if remember me functionality is allowed, false if not
          type: boolean
        authType:
          description: |
            login type to be used when asking users to log in
          enum:
            - Basic
            - Saml
          example: Basic
          type: string
        useFido2:
          default: false
          description: |
            true if use FIDO2 functionality is allowed, false if not
          type: boolean
        userLoginLevel:
          description: |
            login setting to tell clients how to let users log in
          enum:
            - NotRequired
            - Anonymous
            - Required
          example: NotRequired
          type: string
      required:
        - authType
        - userLoginLevel
      type: object
    SelfServiceSettings:
      description: |
        object representation of Self Service settings
      properties:
        configurationSettings:
          $ref: '#/components/schemas/SelfServiceInteractionSettings'
        installSettings:
          $ref: '#/components/schemas/SelfServiceInstallSettings'
        loginSettings:
          $ref: '#/components/schemas/SelfServiceLoginSettings'
      type: object
info:
  title: Jamf Pro API - SelfServiceSettings
  version: 0.0.1
openapi: 3.0.1
paths:
  /v1/self-service/settings:
    get:
      description: |
        gets an object representation of Self Service settings
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SelfServiceSettings'
          description: |
            successful GET
      summary: |
        Get an object representation of Self Service settings
      tags:
        - self-service
      x-required-privileges:
        - Read Self Service
    put:
      description: |
        puts an object representation of Self Service settings
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SelfServiceSettings'
        description: |
          object that contains all editable global fields to alter Self Service settings
        required: true
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SelfServiceSettings'
          description: |
            successful PUT
      summary: |
        Put an object representation of Self Service settings
      tags:
        - self-service
      x-required-privileges:
        - Update Self Service
  /v1/self-service/settings/history:
    get:
      description: |
        Get a page of Self Service settings history
      parameters:
        - $ref: _MonolithLibrary.yaml#/components/parameters/page
        - $ref: _MonolithLibrary.yaml#/components/parameters/page-size
        - $ref: _MonolithLibrary.yaml#/components/parameters/sort
        - $ref: _MonolithLibrary.yaml#/components/parameters/filter
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: _MonolithLibrary.yaml#/components/schemas/HistorySearchResults
          description: Details of Self Service settings history were found
      summary: |
        Get a page of Self Service settings history
      tags:
        - self-service
      x-required-privileges:
        - Read Self Service
    post:
      description: |
        Add Self Service settings history notes
      requestBody:
        content:
          application/json:
            schema:
              $ref: _MonolithLibrary.yaml#/components/schemas/ObjectHistoryNote
        description: history notes to create
        required: true
      responses:
        201:
          content:
            application/json:
              schema:
                $ref: _MonolithLibrary.yaml#/components/schemas/HrefResponse
          description: Notes to Self Service settings history were added
      summary: |
        Add Self Service settings history notes
      tags:
        - self-service
      x-required-privileges:
        - Update Self Service
servers:
  - url: /api
