info:
  title: Jamf Pro API - Server
  version: 0.0.1
openapi: 3.0.1
paths:
  /settings/issueTomcatSslCertificate:
    post:
      description: generate a SSL Certificate using Jamf Certificate Authority
      responses:
        204:
          description: SSL certificate created successfully
      summary: |
        Generate a SSL Certificate using Jamf Certificate Authority
      tags:
        - tomcat-settings-preview
      x-action: true
      x-required-privileges:
        - Update Apache Tomcat Settings
servers:
  - url: /api
