openapi: 3.0.1
info:
  title: Jamf Pro API - Set Auto Admin Password Command Definition
  description: This MDM commands exist to be re-used by multiple other Swagger files.
  version: 0.0.1
paths: {}
components:
  schemas:
    SetAutoAdminPasswordCommand:
      allOf:
        - $ref: 'MdmDefinitionsLibrary.yaml#/components/schemas/MdmCommandBase'
        - type: object
          required:
            - guid
            - password
          properties:
            guid:
              type: string
              example: 76d765f1-651b-4032-9eea-a10e09a62d50
              description: The unique identifier of the local administrator account. Must match the GUID of an administrator account that MDM created during Device Enrollment Program (DEP) enrollment.
            password:
              type: string
              example: newQuerty1234
              format: password
              minLength: 1
              writeOnly: true
              description: The new password for the local administrator account.