components:
  schemas:
    SlasaAcceptance:
      properties:
        slasaAcceptanceStatus:
          enum:
            - ACCEPTED
            - NOT_ACCEPTED
          example: ACCEPTED
          nullable: false
          type: string
      type: object
info:
  title: Jamf Pro API - Slasa
  version: 0.0.1
openapi: 3.0.1
paths:
  /v1/slasa:
    get:
      description: Get if SLASA has been accepted or not
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SlasaAcceptance'
          description: Whether SLASA has been accepted or not
      summary: Get the status of SLASA
      tags:
        - slasa
      x-authentication-required: false
    post:
      description: Accept the SLASA for Jamf Pro.
      responses:
        204:
          description: SLASA has been accepted
      summary: Accept the SLASA
      tags:
        - slasa
      x-action: true
      x-required-privileges:
        - Update License Information
        - View JSS Information
servers:
  - url: /api
