components:
  schemas:
    SsoFailoverData:
      properties:
        failoverUrl:
          example: https://jamf.jamfcloud.com/?failover=0123456789ABCDEF
          type: string
        generationTime:
          description: Generation time of failover key
          example: 1674133253000
          format: int64
          minimum: 0
          type: integer
      type: object
info:
  title: Jamf Pro API - SsoFailover
  version: 0.0.1
openapi: 3.0.1
paths:
  /v1/sso/failover:
    get:
      description: Retrieve the current failover settings
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SsoFailoverData'
          description: Successful response
        400:
          content:
            application/json:
              schema:
                $ref: _MonolithLibrary.yaml#/components/schemas/ApiError
          description: Failover url not generated
      summary: Retrieve the current failover settings
      tags:
        - sso-failover
      x-required-privileges:
        - Read SSO Settings
  /v1/sso/failover/generate:
    post:
      description: Regenerates failover url, by changing failover key to new one, and returns new failover settings
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SsoFailoverData'
          description: The generation was successful and generated failover settings are returned.
      summary: Regenerates failover url
      tags:
        - sso-failover
      x-action: true
      x-required-privileges:
        - Update SSO Settings
servers:
  - url: /api
