openapi: 3.0.1
info:
    title: Jamf Pro API - Definitions Library
    description: These definitions exist to be re-used by other SSO Settings
        Swagger files.
    version: 0.0.1
paths: { }
components:
    schemas:
        EnrollmentCustomizationDependency:
            type: object
            properties:
                name:
                    type: string
                    example: Name
                humanReadableName:
                    type: string
                    example: Enrollment Customization
                hyperlink:
                    type: string
                    example: /enrollment-customization/id
        EnrollmentCustomizationDependencies:
            type: object
            properties:
                dependencies:
                    type: array
                    items:
                        $ref: '#/components/schemas/EnrollmentCustomizationDependency'
        #       V3
        SsoSettingsV3:
            required:
                - configurationType
                - oidcSettings
                - samlSettings
                - ssoBypassAllowed
                - ssoEnabled
                - ssoForMacOsSelfServiceEnabled
                - groupEnrollmentAccessEnabled
                - ssoForEnrollmentEnabled
                - enrollmentSsoForAccountDrivenEnrollmentEnabled
            type: object
            properties:
                configurationType:
                    type: string
                    enum:
                        - SAML
                        - OIDC
                        - OIDC_WITH_SAML
                    example: SAML
                oidcSettings:
                    $ref: '#/components/schemas/OidcSettings'
                samlSettings:
                    $ref: '#/components/schemas/SamlSettings'
                ssoForEnrollmentEnabled:
                    type: boolean
                    default: false
                ssoBypassAllowed:
                    type: boolean
                    default: false
                ssoEnabled:
                    type: boolean
                    default: false
                ssoForMacOsSelfServiceEnabled:
                    type: boolean
                    default: false
                enrollmentSsoForAccountDrivenEnrollmentEnabled:
                    type: boolean
                    default: false
                enrollmentSsoConfig:
                    $ref: '#/components/schemas/EnrollmentSsoConfig'
                groupEnrollmentAccessEnabled:
                    type: boolean
                    default: false
                groupEnrollmentAccessName:
                    type: string
                    default: ' '
        SamlSettings:
            type: object
            properties:
                tokenExpirationDisabled:
                    type: boolean
                    default: false
                userAttributeEnabled:
                    type: boolean
                    default: false
                userAttributeName:
                    type: string
                    default: ' '
                userMapping:
                    type: string
                    enum:
                        - USERNAME
                        - EMAIL
                    example: USERNAME
                groupAttributeName:
                    type: string
                    default: http://schemas.xmlsoap.org/claims/Group
                groupRdnKey:
                    type: string
                    default: ' '
                idpProviderType:
                    type: string
                    enum:
                        - ADFS
                        - OKTA
                        - GOOGLE
                        - SHIBBOLETH
                        - ONELOGIN
                        - PING
                        - CENTRIFY
                        - AZURE
                        - OTHER
                    example: ADFS
                idpUrl:
                    type: string
                    example: https://example.idp.com/app/id/sso/saml/metadata
                entityId:
                    type: string
                    example: saml/metadata
                metadataFileName:
                    type: string
                    example: if MetadataSource is set to URL, remove this field
                otherProviderTypeName:
                    type: string
                    default: ' '
                federationMetadataFile:
                    example: ZXhhbXBsZSBvZiBhIGJhc2U2NCBlbmNvZGVkIHZhbGlkIHAxMi4ga2V5c3RvcmUgZmlsZQ==
                    pattern: ^(?:[A-Za-z0-9+/]{4})*(?:[A-Za-z0-9+/]{2}==|[A-Za-z0-9+/]{3}=)?$
                    type: string
                    format: byte
                metadataSource:
                    type: string
                    enum:
                        - URL
                        - FILE
                        - UNKNOWN
                    example: URL
                sessionTimeout:
                    type: integer
                    format: int32
                    default: 480
        OidcSettings:
            required:
                - userMapping
            type: object
            properties:
                userMapping:
                    type: string
                    enum:
                        - USERNAME
                        - EMAIL
                    example: USERNAME
                jamfIdAuthenticationEnabled:
                    type: boolean
                    default: true
                usernameAttributeClaimMapping:
                    type: string
                    enum:
                        - USERNAME
                        - EMAIL
                    example: EMAIL
        EnrollmentSsoConfig:
            type: object
            properties:
                hosts:
                    type: array
                    items:
                        type: string
                    example: [ dev-12324233.okta.com, example.okta.com ]
                    minItems: 0
                    default: [ ]
                managementHint:
                    type: string
                    default: ''
