openapi: 3.0.1
info:
    title: Jamf Pro API - SSO Settings
    version: 0.0.1
paths:
    #    v3 API
    /v3/sso:
        get:
            tags:
                - sso-settings
            summary: |
                Retrieve the current Single Sign On configuration settings
            description: Retrieves the current Single Sign On configuration settings
            responses:
                200:
                    description: Successful response
                    content:
                        'application/json':
                            schema:
                                $ref: '#/components/schemas/SsoSettingsV3'
            x-required-privileges:
                - Read SSO Settings
        put:
            tags:
                - sso-settings
            summary: |
                Updates the current Single Sign On configuration settings
            description: Updates the current Single Sign On configuration settings
            requestBody:
                content:
                    'application/json':
                        schema:
                            $ref: '#/components/schemas/SsoSettingsV3'
            responses:
                200:
                    description: The update was successful and the newly updated object is returned.
                    content:
                        'application/json':
                            schema:
                                $ref: '#/components/schemas/SsoSettingsV3'
                400:
                    description: Bad Request. Either required fields are missing or there was
                        a validation exception.
                    content:
                        'application/json':
                            schema:
                                $ref: '#/components/schemas/ApiError'
            x-required-privileges:
                - Update SSO Settings
    /v3/sso/history:
        get:
            tags:
                - sso-settings
            summary: |
                Get SSO history object
            description: |
                Gets SSO history object
            parameters:
                -   $ref: 'DefinitionsLibrary.yaml#/components/parameters/page'
                -   $ref: 'DefinitionsLibrary.yaml#/components/parameters/page-size'
                -   name: sort
                    in: query
                    description: 'Sorting criteria in the format: property:asc/desc. Default sort
          is date:desc. Multiple sort criteria are supported and must be separated
          with a comma. Example: sort=date:desc,name:asc '
                    style: form
                    explode: true
                    schema:
                        type: array
                        items:
                            type: string
                        default: [ id:desc ]
                -   name: filter
                    in: query
                    description: 'Query in the RSQL format, allowing to filter history notes collection.
          Default filter is empty query - returning all results for the requested page.
          Fields allowed in the query: username, date, note, details.
          This param can be combined with paging and sorting.
          Example: filter=username!=admin and details==*disabled* and date<2019-12-15'
                    schema:
                        type: string
                        default: ''
            responses:
                200:
                    description: Details of SSO history were found
                    content:
                        'application/json':
                            schema:
                                $ref: '#/components/schemas/HistorySearchResults'
            x-required-privileges:
                - Read SSO Settings
        post:
            tags:
                - sso-settings
            summary: |
                Add SSO history object notes
            description: Adds SSO history object notes
            requestBody:
                description: history notes to create
                content:
                    'application/json':
                        schema:
                            $ref: '#/components/schemas/ObjectHistoryNote'
                required: true
            responses:
                201:
                    description: Notes of SSO history were added
                    content:
                        'application/json':
                            schema:
                                $ref: 'DefinitionsLibrary.yaml#/components/schemas/HrefResponse'
                503:
                    description: SSO object history can not be saved
                    content:
                        'application/json':
                            schema:
                                $ref: '#/components/schemas/ApiError'
            x-required-privileges:
                - Update SSO Settings
    /v3/sso/metadata/download:
        get:
            tags:
                - sso-settings
            summary: |
                Download the Jamf Pro SAML metadata file
            description: Download the Jamf Pro SAML metadata file
            responses:
                200:
                    description: Successful resposne
                    content:
                        'text/plain':
                            schema:
                                type: string
                                format: binary
            x-required-privileges:
                - Read SSO Settings
    /v3/sso/disable:
        post:
            tags:
                - sso-settings
            summary: |
                Disable SSO
            description: Disable SSO
            responses:
                202:
                    description: SSO has been disabled
                400:
                    description: SSO object don't exist or is already disabled
            x-required-privileges:
                - Update SSO Settings
            x-action: true
    /v3/sso/dependencies:
        get:
            tags:
                - sso-settings
            summary: |
                Retrieve the list of Enrollment Customizations using SSO
            description: Retrieves the list of Enrollment Customizations using SSO
            responses:
                200:
                    description: Success
                    content:
                        'application/json':
                            schema:
                                $ref: '#/components/schemas/EnrollmentCustomizationDependencies'
            x-required-privileges:
                - Read SSO Settings