components:
  schemas:
    StaticUserGroup:
      properties:
        description:
          example: A group containing all grade school teachers
          type: string
        id:
          example: 1
          type: integer
        name:
          example: Grade School Teachers
          type: string
      type: object
info:
  title: Jamf Pro API - StaticUserGroup
  version: 0.0.1
openapi: 3.0.1
paths:
  /v1/static-user-groups:
    get:
      description: |
        Returns a list of all static user groups.
      responses:
        200:
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/StaticUserGroup'
                type: array
          description: Success
      summary: |
        Return a list of all Static User Groups
      tags:
        - static-user-groups-preview
      x-required-privileges:
        - Read Static User Groups
  /v1/static-user-groups/{id}:
    get:
      description: |
        Returns a specific static user group by id.
      parameters:
        - description: Instance id of static user group record
          explode: false
          in: path
          name: id
          required: true
          schema:
            type: integer
          style: simple
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StaticUserGroup'
          description: Success
        404:
          content:
            application/json:
              schema:
                $ref: _MonolithLibrary.yaml#/components/schemas/ApiError
          description: Specified static user group object does not exist.
      summary: |
        Return a specific Static User Group by id
      tags:
        - static-user-groups-preview
      x-required-privileges:
        - Read Static User Groups
servers:
  - url: /api
