components:
  schemas:
    StaticComputerGroup:
      properties:
        description:
          example: A test static computer group
          nullable: true
          type: string
        id:
          example: "1"
          minLength: 1
          type: string
        name:
          example: Test Static Computer Group
          minLength: 1
          type: string
        siteId:
          example: "1"
          nullable: true
          type: string
      required:
        - id
        - name
      type: object
    StaticComputerGroupAssignment:
      properties:
        assignments:
          description: Array of computer IDs to assign to the static group
          items:
            example: "1"
            minLength: 1
            type: string
          type: array
        description:
          example: A test static computer group
          nullable: true
          type: string
        id:
          example: "1"
          readOnly: true
          type: string
        name:
          example: Test Static Computer Group
          minLength: 1
          type: string
        siteId:
          example: "1"
          nullable: true
          type: string
      required:
        - name
      type: object
    StaticComputerGroupSearchResults:
      properties:
        results:
          items:
            $ref: '#/components/schemas/StaticComputerGroupSummary'
          type: array
        totalCount:
          example: 2
          minimum: 0
          type: integer
      required:
        - results
        - totalCount
      type: object
    StaticComputerGroupSummary:
      properties:
        count:
          example: 5
          minimum: 0
          type: integer
        description:
          example: A test static computer group
          nullable: true
          type: string
        id:
          example: "1"
          minLength: 1
          type: string
        name:
          example: Test Static Computer Group
          minLength: 1
          type: string
        siteId:
          example: "1"
          nullable: true
          type: string
      required:
        - id
        - name
      type: object
info:
  title: Jamf Pro API - StaticComputerGroups
  version: 0.0.1
openapi: 3.0.1
paths:
  /v2/computer-groups/static-groups:
    get:
      description: |
        Search for Static Computer Groups
      parameters:
        - $ref: _MonolithLibrary.yaml#/components/parameters/page
        - $ref: _MonolithLibrary.yaml#/components/parameters/page-size
        - description: 'Sorting criteria in the format: property:asc/desc. Default sort is id:asc. Multiple sort criteria are supported and must be separated with a comma. Example: sort=name:asc'
          explode: true
          in: query
          name: sort
          required: false
          schema:
            default:
              - id:asc
            items:
              type: string
            type: array
          style: form
        - description: 'Query in the RSQL format, allowing to filter static computer group collection. Default filter is empty query - returning all results for the requested page. Fields allowed in the query: id, name, siteId. The siteId field can only be filtered by admins with full access. Any sited admin will have siteId filtered automatically. Example: name=="*group*"'
          explode: true
          in: query
          name: filter
          required: false
          schema:
            default: ""
            type: string
          style: form
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StaticComputerGroupSearchResults'
          description: Successful response
      summary: |
        Search for Static Computer Groups
      tags:
        - computer-groups
      x-required-privileges:
        - Read Static Computer Groups
    post:
      description: |
        Create membership of a static computer group.
      parameters:
        - description: Optional. Return platform identifiers instead of internal identifiers when set to true.
          explode: true
          in: query
          name: platform
          required: false
          schema:
            default: false
            type: boolean
          style: form
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/StaticComputerGroupAssignment'
        required: true
      responses:
        201:
          content:
            application/json:
              schema:
                $ref: _MonolithLibrary.yaml#/components/schemas/HrefResponse
          description: Static computer group created successfully
        400:
          content:
            application/json:
              schema:
                $ref: _MonolithLibrary.yaml#/components/schemas/ApiError
          description: Could not save static computer group.
        422:
          content:
            application/json:
              schema:
                $ref: _MonolithLibrary.yaml#/components/schemas/ApiError
          description: Duplicated name in static computer group.
      summary: |
        Create membership of a static computer group.
      tags:
        - computer-groups
      x-required-privileges:
        - Create Static Computer Groups
  /v2/computer-groups/static-groups/{id}:
    delete:
      description: |
        Remove Static Computer Group by Id
      parameters:
        - description: instance id of static computer group
          explode: false
          in: path
          name: id
          required: true
          schema:
            type: string
          style: simple
      responses:
        204:
          description: Static Computer Group successfully removed
        404:
          content:
            application/json:
              schema:
                $ref: _MonolithLibrary.yaml#/components/schemas/ApiError
          description: Unable to delete static computer group with given id.
      summary: |
        Remove Static Computer Group by Id
      tags:
        - computer-groups
      x-required-privileges:
        - Delete Static Computer Groups
    get:
      description: |
        Get Static Computer Group by Id
      parameters:
        - description: instance id of static computer group
          explode: false
          in: path
          name: id
          required: true
          schema:
            type: string
          style: simple
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StaticComputerGroup'
          description: Successful response
        404:
          content:
            application/json:
              schema:
                $ref: _MonolithLibrary.yaml#/components/schemas/ApiError
          description: Static Computer Group with the specified id does not exist
      summary: |
        Get Static Computer Group by Id
      tags:
        - computer-groups
      x-required-privileges:
        - Read Static Computer Groups
    put:
      description: |
        Update membership of a static computer group.
      parameters:
        - description: instance id of a static computer group
          explode: false
          in: path
          name: id
          required: true
          schema:
            type: string
          style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/StaticComputerGroupAssignment'
        required: true
      responses:
        202:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StaticComputerGroupAssignment'
          description: Successful response
        404:
          content:
            application/json:
              schema:
                $ref: _MonolithLibrary.yaml#/components/schemas/ApiError
          description: No static computer group found with the given id.
        422:
          content:
            application/json:
              schema:
                $ref: _MonolithLibrary.yaml#/components/schemas/ApiError
          description: Duplicated name in static computer group.
      summary: |
        Update membership of a static computer group.
      tags:
        - computer-groups
      x-required-privileges:
        - Update Static Computer Groups
servers:
  - url: /api
