info:
  title: Jamf Pro API - StaticComputerGroups
  version: 0.0.1
openapi: 3.0.1
paths:
  /v2/computer-groups/static-groups:
    get:
      deprecated: true
      description: |
        Search for Static Computer Groups
      parameters:
        - $ref: _MonolithLibrary.yaml#/components/parameters/page
        - $ref: _MonolithLibrary.yaml#/components/parameters/page-size
        - description: 'Sorting criteria in the format: property:asc/desc. Default sort is id:asc. Multiple sort criteria are supported and must be separated with a comma. Example: sort=name:asc'
          explode: true
          in: query
          name: sort
          required: false
          schema:
            default:
              - id:asc
            items:
              type: string
            type: array
          style: form
        - description: 'Query in the RSQL format, allowing to filter static computer group collection. Default filter is empty query - returning all results for the requested page. Fields allowed in the query: id, name, siteId. The siteId field can only be filtered by admins with full access. Any sited admin will have siteId filtered automatically. Example: name=="*group*"'
          explode: true
          in: query
          name: filter
          required: false
          schema:
            default: ""
            type: string
          style: form
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: _MonolithLibrary.yaml#/components/schemas/StaticComputerGroupSearchResults
          description: Successful response
      summary: |
        Search for Static Computer Groups
      tags:
        - computer-groups
      x-deprecation-date: "2026-05-28"
      x-required-privileges:
        - Read Static Computer Groups
    post:
      deprecated: true
      description: |
        Create membership of a static computer group.
      parameters:
        - description: Optional. Return platform identifiers instead of internal identifiers when set to true.
          explode: true
          in: query
          name: platform
          required: false
          schema:
            default: false
            type: boolean
          style: form
      requestBody:
        content:
          application/json:
            schema:
              $ref: _MonolithLibrary.yaml#/components/schemas/StaticComputerGroupAssignment
        required: true
      responses:
        201:
          content:
            application/json:
              schema:
                $ref: _MonolithLibrary.yaml#/components/schemas/HrefResponse
          description: Static computer group created successfully
        400:
          content:
            application/json:
              schema:
                $ref: _MonolithLibrary.yaml#/components/schemas/ApiError
          description: Could not save static computer group.
        422:
          content:
            application/json:
              schema:
                $ref: _MonolithLibrary.yaml#/components/schemas/ApiError
          description: Duplicated name in static computer group.
      summary: |
        Create membership of a static computer group.
      tags:
        - computer-groups
      x-deprecation-date: "2026-05-28"
      x-required-privileges:
        - Create Static Computer Groups
  /v2/computer-groups/static-groups/{id}:
    delete:
      deprecated: true
      description: |
        Remove Static Computer Group by Id
      parameters:
        - description: instance id of static computer group
          explode: false
          in: path
          name: id
          required: true
          schema:
            type: string
          style: simple
      responses:
        204:
          description: Static Computer Group successfully removed
        404:
          content:
            application/json:
              schema:
                $ref: _MonolithLibrary.yaml#/components/schemas/ApiError
          description: Unable to delete static computer group with given id.
      summary: |
        Remove Static Computer Group by Id
      tags:
        - computer-groups
      x-deprecation-date: "2026-05-28"
      x-required-privileges:
        - Delete Static Computer Groups
    get:
      deprecated: true
      description: |
        Get Static Computer Group by Id
      parameters:
        - description: instance id of static computer group
          explode: false
          in: path
          name: id
          required: true
          schema:
            type: string
          style: simple
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: _MonolithLibrary.yaml#/components/schemas/StaticComputerGroup
          description: Successful response
        404:
          content:
            application/json:
              schema:
                $ref: _MonolithLibrary.yaml#/components/schemas/ApiError
          description: Static Computer Group with the specified id does not exist
      summary: |
        Get Static Computer Group by Id
      tags:
        - computer-groups
      x-deprecation-date: "2026-05-28"
      x-required-privileges:
        - Read Static Computer Groups
    put:
      deprecated: true
      description: |
        Update membership of a static computer group.
      parameters:
        - description: instance id of a static computer group
          explode: false
          in: path
          name: id
          required: true
          schema:
            type: string
          style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: _MonolithLibrary.yaml#/components/schemas/StaticComputerGroupAssignment
        required: true
      responses:
        202:
          content:
            application/json:
              schema:
                $ref: _MonolithLibrary.yaml#/components/schemas/StaticComputerGroupAssignment
          description: Successful response
        404:
          content:
            application/json:
              schema:
                $ref: _MonolithLibrary.yaml#/components/schemas/ApiError
          description: No static computer group found with the given id.
        422:
          content:
            application/json:
              schema:
                $ref: _MonolithLibrary.yaml#/components/schemas/ApiError
          description: Duplicated name in static computer group.
      summary: |
        Update membership of a static computer group.
      tags:
        - computer-groups
      x-deprecation-date: "2026-05-28"
      x-required-privileges:
        - Update Static Computer Groups
servers:
  - url: /api
