openapi: 3.0.1
info:
  title: Jamf Pro API - static-user-groups
  version: 0.0.1
servers:
- url: /
paths:
  /v1/static-user-groups:
    get:
      tags:
      - static-user-groups-preview
      summary: |
        Return a list of all Static User Groups
      description: |
        Returns a list of all static user groups.
      responses:
        200:
          description: Success
          content:
            'application/json':
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/StaticUserGroup'
      x-required-privileges:
      - Read Static User Groups
  /v1/static-user-groups/{id}:
    get:
      tags:
      - static-user-groups-preview
      summary: |
        Return a specific Static User Group by id
      description: |
        Returns a specific static user group by id.
      parameters:
      - name: id
        in: path
        description: Instance id of static user group record
        required: true
        schema:
          type: integer
      responses:
        200:
          description: Success
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/StaticUserGroup'
        404:
          description: Specified static user group object does not exist.
          content:
            'application/json':
              schema:
                $ref: 'DefinitionsLibrary.yaml#/components/schemas/ApiError'
      x-required-privileges:
      - Read Static User Groups
components:
  schemas:
    StaticUserGroup:
      type: object
      properties:
        id:
          type: integer
          example: 1
        name:
          type: string
          example: Grade School Teachers
        description:
          type: string
          example: A group containing all grade school teachers
