openapi: 3.0.1
info:
  title: Jamf Pro API - Stop Mirroring Command Definition
  description: This MDM commands exist to be re-used by multiple other Swagger files.
  version: 0.0.1
paths: {}
components:
  schemas:
    StopMirroringCommand:
      allOf:
        - $ref: 'MdmDefinitionsLibrary.yaml#/components/schemas/MdmCommandBase'
        - type: object