openapi: 3.0.1
info:
  title: Jamf Pro API
  description: |
    ## Overview
    The Jamf Pro API is a RESTful API for Jamf Pro built to enable consistent and efficient programmatic access to Jamf Pro.<br/><br/>
    The swagger schema can be found [here](/api/schema/).
  version: "production"
  termsOfService: https://www.jamf.com/developer-resources/api-license-agreement/
servers:
  - url: /api
paths: {}
components:
  securitySchemes:
    Bearer:
      type: http
      scheme: bearer
      bearerFormat: JWT
    BasicAuth:
      type: http
      description: Basic auth is used only for obtaining bearer tokens from the /v1/auth/token endpoint
      scheme: basic
    ApiClient:
      type: oauth2
      description: Jamf Pro API Roles and Clients provide a client ID and secret for obtaining access tokens using the OAuth2 client_credentials grant type
      flows:
        clientCredentials:
          tokenUrl: /api/v1/oauth/token
          scopes: {}
security:
  - Bearer: []
  - ApiClient: []
  - BasicAuth:
      - /v1/auth/token
