components:
  schemas:
    InitializeV1:
      description: Initial Jamf Pro setup data
      properties:
        activationCode:
          example: VFAB-YDAB-DFAB-UDAB-DEAB-EFAB-ABAB-DEAB
          maxLength: 39
          minLength: 39
          type: string
        email:
          example: ITBob@jamf.com
          type: string
        eulaAccepted:
          example: false
          type: boolean
        institutionName:
          example: Jamf
          minLength: 1
          type: string
        jssUrl:
          example: https://jamf.jamfcloud.com
          minLength: 1
          type: string
        password:
          example: "12345"
          format: password
          minLength: 1
          type: string
          writeOnly: true
        username:
          example: admin
          minLength: 1
          type: string
      required:
        - activationCode
        - eulaAccepted
        - institutionName
        - jssUrl
        - password
        - username
      type: object
    PlatformInitializeV1:
      description: Platform Initial Jamf Pro setup data
      properties:
        activationCode:
          example: VFAB-YDAB-DFAB-UDAB-DEAB-EFAB-ABAB-DEAB
          maxLength: 39
          minLength: 39
          type: string
        email:
          description: Federated user OIDC email to create
          example: ITBob@jamf.com
          type: string
        eulaAccepted:
          example: false
          type: boolean
        institutionName:
          example: Jamf
          minLength: 1
          type: string
        jssUrl:
          example: https://jamf.jamfcloud.com
          minLength: 1
          type: string
        username:
          description: Federated user OIDC username to create
          example: admin
          minLength: 1
          type: string
      required:
        - activationCode
        - email
        - eulaAccepted
        - institutionName
        - jssUrl
        - username
      type: object
info:
  title: Jamf Pro API - System
  version: 0.0.1
openapi: 3.0.1
paths:
  /v1/system/initialize:
    post:
      description: |
        Set up fresh installed Jamf Pro Server
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/InitializeV1'
        required: true
      responses:
        202:
          description: Jamf Pro Server has been initialized
        400:
          content:
            application/json:
              schema:
                $ref: _MonolithLibrary.yaml#/components/schemas/ApiError
          description: |
            The following are codes returned by this call:
            INVALID_ACTIVATION_CODE - activation code provided is not valid or is expired
            INVALID_STATE - The system is in an invalid state to be initialized.
            FIELD_REQUIRED - A required field was not provided.  The field name will be provided on the response.
      summary: |
        Set up fresh installed Jamf Pro Server
      tags:
        - jamf-pro-initialization
      x-action: true
      x-authentication-required: false
  /v1/system/platform-initialize:
    post:
      description: |
        Set up fresh installed Jamf Pro Server with OIDC SSO enabled and single federated user
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PlatformInitializeV1'
        required: true
      responses:
        202:
          description: Jamf Pro Server has been initialized
        400:
          content:
            application/json:
              schema:
                $ref: _MonolithLibrary.yaml#/components/schemas/ApiError
          description: |
            The following are codes returned by this call:
            INVALID_ACTIVATION_CODE - activation code provided is not valid or is expired
            INVALID_STATE - The system is in an invalid state to be initialized.
            FIELD_REQUIRED - A required field was not provided.  The field name will be provided on the response.
      summary: |
        Set up fresh installed Jamf Pro Server for Platform
      tags:
        - jamf-pro-initialization
      x-action: true
      x-authentication-required: false
servers:
  - url: /api
