components:
  schemas:
    TeacherFeatures:
      properties:
        isAllowAppLock:
          example: true
          type: boolean
        isAllowAttentionScreen:
          example: true
          type: boolean
        isAllowClearPasscode:
          example: true
          type: boolean
        isAllowRestrictions:
          example: true
          type: boolean
        isAllowWebLock:
          example: true
          type: boolean
      type: object
    TeacherSettingsRequest:
      properties:
        autoClear:
          example: 05:30
          nullable: true
          type: string
        isEnabled:
          example: true
          type: boolean
        maxRestrictionLengthSeconds:
          example: 600
          type: integer
        safelistedApps:
          items:
            $ref: _MonolithLibrary.yaml#/components/schemas/SafelistedApp
          type: array
        timezoneId:
          example: Europe/Paris
          type: string
      type: object
    TeacherSettingsResponse:
      properties:
        autoClear:
          example: 05:30
          type: string
        displayNameType:
          example: user
          type: string
        features:
          $ref: '#/components/schemas/TeacherFeatures'
        isEnabled:
          example: true
          type: boolean
        maxRestrictionLengthSeconds:
          example: 600
          type: integer
        safelistedApps:
          items:
            $ref: _MonolithLibrary.yaml#/components/schemas/SafelistedApp
          type: array
        timezoneId:
          example: Europe/Paris
          type: string
      type: object
info:
  title: Jamf Pro API - TeacherSettings
  version: 0.0.1
openapi: 3.0.1
paths:
  /v1/teacher-app:
    get:
      description: Get the Jamf Teacher settings that you have access to see.
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TeacherSettingsResponse'
          description: List of Jamf Teacher settings
      summary: |
        Get the Jamf Teacher settings that you have access to see
      tags:
        - teacher-app
      x-required-privileges:
        - Read Teacher App Settings
    put:
      description: Update a Jamf Teacher settings object.
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TeacherSettingsRequest'
        description: Teacher settings to create.
        required: true
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TeacherSettingsResponse'
          description: Updated Jamf Teacher settings.
        500:
          content:
            application/json:
              schema:
                $ref: _MonolithLibrary.yaml#/components/schemas/ApiError
          description: Update Failed.
      summary: |
        Update a Jamf Teacher settings object
      tags:
        - teacher-app
      x-required-privileges:
        - Update Teacher App Settings
  /v1/teacher-app/history:
    get:
      description: |
        Gets Jamf Teacher app settings history
      parameters:
        - $ref: _MonolithLibrary.yaml#/components/parameters/page
        - $ref: _MonolithLibrary.yaml#/components/parameters/page-size
        - $ref: _MonolithLibrary.yaml#/components/parameters/sort
        - $ref: _MonolithLibrary.yaml#/components/parameters/filter
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: _MonolithLibrary.yaml#/components/schemas/HistorySearchResults
          description: Details of Jamf Teacher app settings history were found
      summary: |
        Get Jamf Teacher app settings history
      tags:
        - teacher-app
      x-required-privileges:
        - Read Teacher App Settings
    post:
      description: |
        Adds Jamf Teacher app settings history notes
      requestBody:
        content:
          application/json:
            schema:
              $ref: _MonolithLibrary.yaml#/components/schemas/ObjectHistoryNote
        description: history notes to create
        required: true
      responses:
        201:
          content:
            application/json:
              schema:
                $ref: _MonolithLibrary.yaml#/components/schemas/HrefResponse
          description: Notes to Jamf Teacher app settings history were added
        503:
          content:
            application/json:
              schema:
                $ref: _MonolithLibrary.yaml#/components/schemas/ApiError
          description: Jamf Teacher app history can not be saved
      summary: |
        Add Jamf Teacher app settings history notes
      tags:
        - teacher-app
      x-required-privileges:
        - Update Teacher App Settings
servers:
  - url: /api
