components:
  schemas:
    TimeZone:
      properties:
        displayName:
          example: Chicago - CT (-0500)
          type: string
        region:
          enum:
            - Africa
            - America
            - Asia
            - Atlantic
            - Australia
            - Europe
            - Indian
            - Pacific
            - None
          example: America
          type: string
        zoneId:
          example: America/Chicago
          type: string
      type: object
info:
  title: Jamf Pro API - TimeZones
  version: 0.0.1
openapi: 3.0.1
paths:
  /v1/time-zones:
    get:
      description: |
        Returns information about the currently supported time zones
      responses:
        200:
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/TimeZone'
                type: array
          description: Successful response
      summary: |
        Return information about the currently supported Time Zones
      tags:
        - time-zones-preview
      x-authentication-required: false
servers:
  - url: /api
