openapi: 3.0.1
info:
  title: Jamf Pro API - users
  version: 0.0.1
paths:
  /v1/users:
    get:
      tags:
      - users
      summary: |
        Search for Users
      description: |
        Retrieves a paginated list of users with optional filtering and sorting.
      parameters:
        - $ref: 'DefinitionsLibrary.yaml#/components/parameters/page'
        - $ref: 'DefinitionsLibrary.yaml#/components/parameters/page-size'
        - name: sort
          in: query
          description: 'Sorting criteria in the format: property(:asc|desc). Default
            sort is id:asc. Multiple sort criteria are supported and must be separated
            with a comma. Example: sort=username:asc,realname:desc'
          explode: true
          schema:
            type: array
            items:
              type: string
            default: [id:asc]
        - name: filter
          in: query
          description: 'Query in the RSQL format, allowing to filter users collection.
            Default filter is empty query - returning all results for the requested
            page. Fields allowed in the query: id, username, realname, email, phone,
            position. Example: filter=username=="jsmith*"'
          schema:
            type: string
            default: ''
      responses:
        200:
          description: Successful response
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/UserSearchResults'
      x-required-privileges:
      - Read User
    post:
      tags:
      - users
      summary: |
        Create User record
      description: |
        Creates a new user in inventory.
      requestBody:
        description: User object to create. ids defined in this body will be ignored.
        content:
          'application/json':
            schema:
              $ref: '#/components/schemas/User'
        required: true
      responses:
        201:
          description: User record was created
          content:
            'application/json':
              schema:
                $ref: 'DefinitionsLibrary.yaml#/components/schemas/HrefResponse'
      x-required-privileges:
      - Create User
  /v1/users/{id}:
    get:
      tags:
      - users
      summary: |
        Get specified User object
      description: |
        Gets the specified User object.
      parameters:
      - name: id
        in: path
        description: instance id of user record
        required: true
        schema:
          type: string
      responses:
        200:
          description: Successful response
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/User'
        404:
          description: User with specified id does not exist
      x-required-privileges:
      - Read User
    put:
      tags:
      - users
      summary: |
        Update specified User object
      description: |
        Updates the specified User object.
      parameters:
      - name: id
        in: path
        description: instance id of user record
        required: true
        schema:
          type: string
      requestBody:
        description: User object to update
        content:
          'application/json':
            schema:
              $ref: '#/components/schemas/User'
        required: true
      responses:
        200:
          description: Successful response
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/User'
        404:
          description: User with specified id does not exist
      x-required-privileges:
      - Update User
    delete:
      tags:
      - users
      summary: |
        Delete specified User object
      description: |
        Deletes the specified User object.
      parameters:
      - name: id
        in: path
        description: instance id of user record
        required: true
        schema:
          type: string
      responses:
        204:
          description: User record was deleted
        404:
          description: User with specified id does not exist
      x-required-privileges:
      - Delete User
components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: string
          readOnly: true
          example: "1"
        username:
          type: string
          example: jsmith
        realname:
          type: string
          example: John Smith
        email:
          type: string
          example: john.smith@example.com
        phone:
          type: string
          nullable: true
          example: 555-123-4567
        position:
          type: string
          nullable: true
          example: IT Administrator
        enableCustomPhotoUrl:
          type: boolean
          default: false
        customPhotoUrl:
          type: string
          nullable: true
        managedAppleId:
          type: string
          nullable: true
    UserSearchResults:
      type: object
      properties:
        totalCount:
          type: integer
          format: int32
        results:
          type: array
          items:
            $ref: '#/components/schemas/User'
