components:
  schemas:
    VenafiCaRecord:
      properties:
        clientId:
          example: jamf-pro
          type: string
        id:
          example: 4
          readOnly: true
          type: integer
        name:
          example: Venafi Certificate Authority
          type: string
        proxyAddress:
          example: localhost:9443
          type: string
        refreshToken:
          example: qdkP4SrCFKd7tefAVM6N
          type: string
          writeOnly: true
        refreshTokenConfigured:
          example: true
          readOnly: true
          type: boolean
        revocationEnabled:
          example: true
          type: boolean
      required:
        - name
      type: object
    VenafiPkiPayloadRecord:
      properties:
        name:
          example: Configuration Profile Name
          type: string
        urlPath:
          example: OSXConfigurationProfile.html?id=1
          type: string
      type: object
    VenafiPkiPayloadRecordSearchResults:
      properties:
        results:
          items:
            $ref: '#/components/schemas/VenafiPkiPayloadRecord'
          type: array
        totalCount:
          example: 3
          minimum: 0
          type: integer
      type: object
    VenafiServiceStatus:
      properties:
        status:
          example: Successfully connected
          readOnly: true
          type: string
      type: object
info:
  title: Jamf Pro API - Venafi
  version: 0.0.1
openapi: 3.0.1
paths:
  /v1/pki/venafi:
    post:
      description: |
        Creates a Venafi PKI configuration in Jamf Pro, which can be used to issue certificates
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/VenafiCaRecord'
        required: true
      responses:
        201:
          content:
            application/json:
              schema:
                $ref: _MonolithLibrary.yaml#/components/schemas/HrefResponse
          description: Successful response creates a Venafi PKI configuration
        400:
          content:
            application/json:
              schema:
                $ref: _MonolithLibrary.yaml#/components/schemas/ApiError
          description: Invalid attributes for Certificate Authority configuration
      summary: |
        Create a PKI configuration in Jamf Pro for Venafi
      tags:
        - venafi-preview
      x-required-privileges:
        - Update PKI
  /v1/pki/venafi/{id}:
    delete:
      description: |
        Delete a Venafi PKI configuration from Jamf Pro
      parameters:
        - description: ID of the Venafi configuration
          explode: false
          in: path
          name: id
          required: true
          schema:
            type: string
          style: simple
      responses:
        204:
          description: Successful response deletes Venafi PKI configuration from Jamf Pro
        404:
          content:
            application/json:
              schema:
                $ref: _MonolithLibrary.yaml#/components/schemas/ApiError
          description: Certificate Authority not found for Id
        409:
          content:
            application/json:
              schema:
                $ref: _MonolithLibrary.yaml#/components/schemas/ApiError
          description: Conflict deleting target, Venafi PKI configuration still in use on Configuration Profile
      summary: |
        Delete a Venafi PKI configuration from Jamf Pro
      tags:
        - venafi-preview
      x-required-privileges:
        - Update PKI
    get:
      description: |
        Retrieve a Venafi PKI configuration from Jamf Pro
      parameters:
        - description: ID of the Venafi configuration
          explode: false
          in: path
          name: id
          required: true
          schema:
            type: string
          style: simple
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VenafiCaRecord'
          description: Successful response returns a Venafi PKI configuration
        404:
          content:
            application/json:
              schema:
                $ref: _MonolithLibrary.yaml#/components/schemas/ApiError
          description: Certificate Authority not found for Id
      summary: |
        Retrieve a Venafi PKI configuration from Jamf Pro
      tags:
        - venafi-preview
      x-required-privileges:
        - Read PKI
    patch:
      description: |
        Update a Venafi PKI configuration in Jamf Pro
      parameters:
        - description: ID of the Venafi configuration
          explode: false
          in: path
          name: id
          required: true
          schema:
            type: string
          style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/VenafiCaRecord'
        required: true
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VenafiCaRecord'
          description: Successful response returns a Venafi PKI configuration
        400:
          content:
            application/json:
              schema:
                $ref: _MonolithLibrary.yaml#/components/schemas/ApiError
          description: Invalid attributes for Certificate Authority configuration
        404:
          content:
            application/json:
              schema:
                $ref: _MonolithLibrary.yaml#/components/schemas/ApiError
          description: Certificate Authority not found for Id
      summary: |
        Update a Venafi PKI configuration in Jamf Pro
      tags:
        - venafi-preview
      x-required-privileges:
        - Update PKI
  /v1/pki/venafi/{id}/connection-status:
    get:
      description: |
        Tests the communication between Jamf Pro and a Jamf Pro PKI Proxy Server
      parameters:
        - description: ID of the Venafi configuration
          explode: false
          in: path
          name: id
          required: true
          schema:
            type: string
          style: simple
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VenafiServiceStatus'
          description: Successfully connected to Venafi
        503:
          content:
            application/json:
              schema:
                $ref: _MonolithLibrary.yaml#/components/schemas/ApiError
          description: Why we failed to connect
      summary: |
        Tests the communication between Jamf Pro and a Jamf Pro PKI Proxy Server
      tags:
        - venafi-preview
      x-required-privileges:
        - Read PKI
  /v1/pki/venafi/{id}/dependent-profiles:
    get:
      description: |
        Get configuration profile data using specified Venafi CA object
      parameters:
        - description: ID of the Venafi configuration
          explode: false
          in: path
          name: id
          required: true
          schema:
            type: string
          style: simple
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VenafiPkiPayloadRecordSearchResults'
          description: Successfully returns a list of configuration profile data connected to the Venafi CA
      summary: |
        Get configuration profile data using specified Venafi CA object
      tags:
        - venafi-preview
      x-required-privileges:
        - Read PKI
  /v1/pki/venafi/{id}/history:
    get:
      description: |
        Get specified Venafi CA history object
      parameters:
        - description: ID of the Venafi configuration
          explode: false
          in: path
          name: id
          required: true
          schema:
            type: string
          style: simple
        - $ref: _MonolithLibrary.yaml#/components/parameters/page
        - $ref: _MonolithLibrary.yaml#/components/parameters/page-size
        - description: 'Sorting criteria in the format: property:asc/desc. Default sort is date:desc. Multiple sort criteria are supported and must be separated with a comma. Example: sort=date:desc,name:asc '
          explode: true
          in: query
          name: sort
          required: false
          schema:
            default:
              - date:desc
            items:
              type: string
            type: array
          style: form
        - description: 'Query in the RSQL format, allowing to filter history notes collection. Default filter is empty query - returning all results for the requested page. Fields allowed in the query: username, date, note, details. This param can be combined with paging and sorting. Example: filter=username!=admin and details==*disabled* and date<2019-12-15'
          explode: true
          in: query
          name: filter
          required: false
          schema:
            default: ""
            type: string
          style: form
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: _MonolithLibrary.yaml#/components/schemas/HistorySearchResults
          description: Details of Venafi CA history was found
        404:
          content:
            application/json:
              schema:
                $ref: _MonolithLibrary.yaml#/components/schemas/ApiError
          description: Specified Venafi CA object does not exist
      summary: |
        Get specified Venafi CA history object
      tags:
        - venafi-preview
      x-required-privileges:
        - Read PKI
    post:
      description: |
        Adds specified Venafi CA Object Note
      parameters:
        - description: instance id of Venafi CA history record
          explode: false
          in: path
          name: id
          required: true
          schema:
            type: string
          style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: _MonolithLibrary.yaml#/components/schemas/ObjectHistoryNote
        description: venafi ca history notes to create
        required: true
      responses:
        201:
          content:
            application/json:
              schema:
                $ref: _MonolithLibrary.yaml#/components/schemas/HrefResponse
          description: Notes of Venafi CA history were added
        404:
          content:
            application/json:
              schema:
                $ref: _MonolithLibrary.yaml#/components/schemas/ApiError
          description: Specified Venafi CA object does not exist
        503:
          content:
            application/json:
              schema:
                $ref: _MonolithLibrary.yaml#/components/schemas/ApiError
          description: Venafi CA history can not be saved
      summary: |
        Add specified Venafi CA Object Note
      tags:
        - venafi-preview
      x-required-privileges:
        - Update PKI
  /v1/pki/venafi/{id}/jamf-public-key:
    get:
      description: |
        Downloads a certificate for an existing Venafi configuration that can be used to secure communication between Jamf Pro and a Jamf Pro PKI Proxy Server
      parameters:
        - description: ID of the Venafi configuration
          explode: false
          in: path
          name: id
          required: true
          schema:
            type: string
          style: simple
      responses:
        200:
          content:
            application/pem-certificate-chain:
              schema:
                format: binary
                type: string
          description: Successful response downloads the certificate
        400:
          content:
            application/json:
              schema:
                $ref: _MonolithLibrary.yaml#/components/schemas/ApiError
          description: Keystore not found for Certificate Authority
        404:
          content:
            application/json:
              schema:
                $ref: _MonolithLibrary.yaml#/components/schemas/ApiError
          description: Certificate not found for Id
      summary: |
        Downloads a certificate used to secure communication between Jamf Pro and a Jamf Pro PKI Proxy Server
      tags:
        - venafi-preview
      x-required-privileges:
        - Read PKI
  /v1/pki/venafi/{id}/jamf-public-key/regenerate:
    post:
      description: |
        Regenerates a certificate for an existing Venafi configuration that can be used to secure communication between Jamf Pro and a Jamf Pro PKI Proxy Server
      parameters:
        - description: ID of the Venafi configuration
          explode: false
          in: path
          name: id
          required: true
          schema:
            type: string
          style: simple
      responses:
        204:
          description: Successful response regenerates the certificate
        404:
          content:
            application/json:
              schema:
                $ref: _MonolithLibrary.yaml#/components/schemas/ApiError
          description: Certificate Authority not found for Id
      summary: |
        Regenerates a certificate used to secure communication between Jamf Pro and a Jamf Pro PKI Proxy Server
      tags:
        - venafi-preview
      x-action: true
      x-required-privileges:
        - Update PKI
  /v1/pki/venafi/{id}/proxy-trust-store:
    delete:
      description: |
        Removes the uploaded PKI Proxy Server public key to do basic TLS certificate validation between Jamf Pro and a Jamf Pro PKI Proxy Server
      parameters:
        - description: ID of the Venafi configuration
          explode: false
          in: path
          name: id
          required: true
          schema:
            type: string
          style: simple
      responses:
        204:
          description: Successful removes public key
        404:
          content:
            application/json:
              schema:
                $ref: _MonolithLibrary.yaml#/components/schemas/ApiError
          description: Certificate Authority not found for Id
      summary: |
        Removes the PKI Proxy Server public key used to secure communication between Jamf Pro and a Jamf Pro PKI Proxy Server
      tags:
        - venafi-preview
      x-required-privileges:
        - Update PKI
    get:
      description: |
        Downloads the uploaded PKI Proxy Server public key to do basic TLS certificate validation between Jamf Pro and a Jamf Pro PKI Proxy Server
      parameters:
        - description: ID of the Venafi configuration
          explode: false
          in: path
          name: id
          required: true
          schema:
            type: string
          style: simple
      responses:
        200:
          content:
            application/pem-certificate-chain:
              schema:
                format: binary
                type: string
          description: Successful response downloads the certificate
        400:
          content:
            application/json:
              schema:
                $ref: _MonolithLibrary.yaml#/components/schemas/ApiError
          description: Keystore not found for Certificate Authority
        404:
          content:
            application/json:
              schema:
                $ref: _MonolithLibrary.yaml#/components/schemas/ApiError
          description: Certificate not found for Certificate Authority
      summary: |
        Downloads the PKI Proxy Server public key to secure communication between Jamf Pro and a Jamf Pro PKI Proxy Server
      tags:
        - venafi-preview
      x-required-privileges:
        - Read PKI
    post:
      description: |
        Uploads the PKI Proxy Server public key to do basic TLS certificate validation between Jamf Pro and a Jamf Pro PKI Proxy Server
      parameters:
        - description: ID of the Venafi configuration
          explode: false
          in: path
          name: id
          required: true
          schema:
            type: string
          style: simple
      requestBody:
        content:
          application/pem-certificate-chain:
            schema:
              format: binary
              type: string
        required: true
      responses:
        204:
          description: Successful response replaces or removes public key
        400:
          content:
            application/json:
              schema:
                $ref: _MonolithLibrary.yaml#/components/schemas/ApiError
          description: Keystore not found for Certificate Authority
        404:
          content:
            application/json:
              schema:
                $ref: _MonolithLibrary.yaml#/components/schemas/ApiError
          description: Certificate not found for Certificate Authority
      summary: |
        Uploads the PKI Proxy Server public key to secure communication between Jamf Pro and a Jamf Pro PKI Proxy Server
      tags:
        - venafi-preview
      x-required-privileges:
        - Update PKI
servers:
  - url: /api
