components:
  schemas:
    VolumePurchasingContent:
      properties:
        adamId:
          example: "748057890"
          readOnly: true
          type: string
        contentType:
          enum:
            - IOS_APP
            - MAC_APP
            - BOOK
            - UNKNOWN
          example: IOS_APP
          readOnly: true
          type: string
        deviceTypes:
          items:
            enum:
              - IOS
              - MACOS
              - TVOS
            example: IOS
            type: string
          readOnly: true
          type: array
        iconUrl:
          example: https://is4-ssl.mzstatic.com/image/thumb/Purple113/v4/73/d4/73/73d47332-fefc-d350-2984-5b4a4755a502/AppIcon-0-1x_U007emarketing-0-0-GLES2_U002c0-512MB-sRGB-0-0-0-85-220-0-0-0-6.png/360x216bb.png
          readOnly: true
          type: string
        licenseCountInUse:
          example: 1
          readOnly: true
          type: integer
        licenseCountReported:
          example: 1
          readOnly: true
          type: integer
        licenseCountTotal:
          example: 1
          readOnly: true
          type: integer
        name:
          example: Example Content
          readOnly: true
          type: string
        pricingParam:
          enum:
            - STDQ
            - PLUS
            - Unknown
          example: STDQ
          readOnly: true
          type: string
      type: object
    VolumePurchasingContentList:
      properties:
        results:
          items:
            $ref: '#/components/schemas/VolumePurchasingContent'
          type: array
        totalCount:
          example: 1
          type: integer
      type: object
    VolumePurchasingLocation:
      allOf:
        - $ref: '#/components/schemas/VolumePurchasingLocationListView'
        - properties:
            content:
              items:
                $ref: '#/components/schemas/VolumePurchasingContent'
              readOnly: true
              type: array
          type: object
    VolumePurchasingLocationListView:
      properties:
        appleId:
          example: testUser@appleId.com
          readOnly: true
          type: string
        autoRegisterManagedUsers:
          example: false
          type: boolean
        automaticallyPopulatePurchasedContent:
          example: false
          type: boolean
        clientContextMismatch:
          description: If this is "true", the clientContext used by this server does not match the clientContext returned by the Volume Purchasing API.
          example: false
          readOnly: true
          type: boolean
        countryCode:
          description: The two-letter ISO 3166-1 code that designates the country where the Volume Purchasing account is located.
          example: US
          readOnly: true
          type: string
        email:
          example: testUser@email.com
          readOnly: true
          type: string
        id:
          example: "1"
          readOnly: true
          type: string
        lastSyncTime:
          example: "2022-09-25T21:09:31.661Z"
          readOnly: true
          type: string
        locationName:
          example: Example Location
          readOnly: true
          type: string
        name:
          example: Example Location
          type: string
        organizationName:
          example: Jamf
          readOnly: true
          type: string
        sendNotificationWhenNoLongerAssigned:
          example: false
          type: boolean
        siteId:
          example: "1"
          type: string
        siteName:
          example: Example Name
          type: string
        tokenExpiration:
          example: "2022-04-25T21:09:31.661Z"
          readOnly: true
          type: string
        totalPurchasedLicenses:
          example: 1
          readOnly: true
          type: integer
        totalUsedLicenses:
          example: 1
          readOnly: true
          type: integer
      type: object
    VolumePurchasingLocationPatch:
      properties:
        autoRegisterManagedUsers:
          default: false
          example: false
          type: boolean
        automaticallyPopulatePurchasedContent:
          example: false
          nullable: false
          type: boolean
        name:
          example: Example Location
          nullable: false
          type: string
        sendNotificationWhenNoLongerAssigned:
          example: false
          nullable: false
          type: boolean
        serviceToken:
          example: eyJleHBEYXRlIjoiMjAyMi0wMy0yOVQxNTozNjoyNiswMDAwIiwidG9rZW4iOiJWR2hwY3lCcGN5QnViM1FnWVNCMGIydGxiaTRnU0c5d1pXWjFiR3g1SUdsMElHeHZiMnR6SUd4cGEyVWdZU0IwYjJ0bGJpd2dZblYwSUdsMEozTWdibTkwTGc9PSIsIm9yZ05hbWUiOiJFeGFtcGxlIE9yZyJ9
          nullable: false
          type: string
        siteId:
          example: "1"
          nullable: false
          type: string
      type: object
    VolumePurchasingLocationPost:
      properties:
        autoRegisterManagedUsers:
          default: false
          example: false
          type: boolean
        automaticallyPopulatePurchasedContent:
          default: false
          example: false
          type: boolean
        name:
          description: If no value is provided when creating a VolumePurchasingLocation object, the 'name' will default to the 'locationName' value
          example: Example Location
          type: string
        sendNotificationWhenNoLongerAssigned:
          default: false
          example: false
          type: boolean
        serviceToken:
          example: eyJleHBEYXRlIjoiMjAyMi0wMy0yOVQxNTozNjoyNiswMDAwIiwidG9rZW4iOiJWR2hwY3lCcGN5QnViM1FnWVNCMGIydGxiaTRnU0c5d1pXWjFiR3g1SUdsMElHeHZiMnR6SUd4cGEyVWdZU0IwYjJ0bGJpd2dZblYwSUdsMEozTWdibTkwTGc9PSIsIm9yZ05hbWUiOiJFeGFtcGxlIE9yZyJ9
          type: string
        siteId:
          default: "-1"
          example: "1"
          type: string
      required:
        - serviceToken
      type: object
    VolumePurchasingLocations:
      properties:
        results:
          items:
            $ref: '#/components/schemas/VolumePurchasingLocationListView'
          type: array
        totalCount:
          example: 1
          type: integer
      type: object
info:
  title: Jamf Pro API - VppLocations
  version: 0.0.1
openapi: 3.0.1
paths:
  /v1/volume-purchasing-locations:
    get:
      description: Retrieves Volume Purchasing Locations
      parameters:
        - $ref: _MonolithLibrary.yaml#/components/parameters/page
        - $ref: _MonolithLibrary.yaml#/components/parameters/page-size
        - description: 'Sorting criteria in the format: property:asc/desc. Default sort is id:asc. Multiple sort criteria are supported and must be separated with a comma.'
          explode: true
          in: query
          name: sort
          required: false
          schema:
            default:
              - id:asc
            items:
              type: string
            type: array
          style: form
        - description: 'Query in the RSQL format, allowing to filter Volume Purchasing Location collection. Default filter is empty query - returning all results for the requested page. Fields allowed in the query: id, name, appleId, email, organizationName, tokenExpiration, countryCode, locationName, automaticallyPopulatePurchasedContent, sendNotificationWhenNoLongerAssigned, siteId and siteName. This param can be combined with paging and sorting.'
          explode: true
          in: query
          name: filter
          required: false
          schema:
            default: ""
            type: string
          style: form
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VolumePurchasingLocations'
          description: Success
      summary: Retrieve Volume Purchasing Locations
      tags:
        - volume-purchasing-locations
      x-required-privileges:
        - Read Volume Purchasing Locations
    post:
      description: Creates a Volume Purchasing Location using an sToken
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/VolumePurchasingLocationPost'
        description: Volume Purchasing Location to create
        required: true
      responses:
        201:
          content:
            application/json:
              schema:
                $ref: _MonolithLibrary.yaml#/components/schemas/HrefResponse
          description: Volume Purchasing Location was created
        400:
          content:
            application/json:
              schema:
                $ref: _MonolithLibrary.yaml#/components/schemas/ApiError
          description: Bad Request
      summary: Create a Volume Purchasing Location
      tags:
        - volume-purchasing-locations
      x-required-privileges:
        - Create Volume Purchasing Locations
  /v1/volume-purchasing-locations/{id}:
    delete:
      description: Deletes a Volume Purchasing Location with the supplied id
      parameters:
        - description: Volume Purchasing Location identifier
          explode: false
          in: path
          name: id
          required: true
          schema:
            type: string
          style: simple
      responses:
        204:
          description: Success
        404:
          content:
            application/json:
              schema:
                $ref: _MonolithLibrary.yaml#/components/schemas/ApiError
          description: Specified Volume Purchasing Location object does not exist.
      summary: Delete a Volume Purchasing Location with the supplied id
      tags:
        - volume-purchasing-locations
      x-required-privileges:
        - Delete Volume Purchasing Locations
    get:
      description: Retrieves a Volume Purchasing Location with the supplied id
      parameters:
        - description: Volume Purchasing Location identifier
          explode: false
          in: path
          name: id
          required: true
          schema:
            type: string
          style: simple
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VolumePurchasingLocation'
          description: Success
        404:
          content:
            application/json:
              schema:
                $ref: _MonolithLibrary.yaml#/components/schemas/ApiError
          description: Volume Purchasing Location with that id does not exist
      summary: Retrieve a Volume Purchasing Location with the supplied id
      tags:
        - volume-purchasing-locations
      x-required-privileges:
        - Read Volume Purchasing Locations
    patch:
      description: Updates a Volume Purchasing Location
      parameters:
        - description: Volume Purchasing Location identifier
          explode: false
          in: path
          name: id
          required: true
          schema:
            type: string
          style: simple
      requestBody:
        content:
          application/merge-patch+json:
            schema:
              $ref: '#/components/schemas/VolumePurchasingLocationPatch'
        description: Volume Purchasing Location to update
        required: true
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VolumePurchasingLocation'
          description: Success
        400:
          content:
            application/json:
              schema:
                $ref: _MonolithLibrary.yaml#/components/schemas/ApiError
          description: Bad Request
        404:
          content:
            application/json:
              schema:
                $ref: _MonolithLibrary.yaml#/components/schemas/ApiError
          description: Volume Purchasing Location with that id does not exist
        422:
          content:
            application/json:
              schema:
                $ref: _MonolithLibrary.yaml#/components/schemas/ApiError
          description: There was an error applying the patch
      summary: Update a Volume Purchasing Location
      tags:
        - volume-purchasing-locations
      x-required-privileges:
        - Update Volume Purchasing Locations
  /v1/volume-purchasing-locations/{id}/content:
    get:
      description: Retrieves the Volume Purchasing Content for the Volume Purchasing Location with the supplied id
      parameters:
        - description: Volume Purchasing Location identifier
          explode: false
          in: path
          name: id
          required: true
          schema:
            type: string
          style: simple
        - $ref: _MonolithLibrary.yaml#/components/parameters/page
        - $ref: _MonolithLibrary.yaml#/components/parameters/page-size
        - description: 'Sorting criteria in the format: property:asc/desc. Default sort is name:asc. Multiple sort criteria are supported and must be separated with a comma.'
          explode: true
          in: query
          name: sort
          required: false
          schema:
            default:
              - id:asc
            items:
              type: string
            type: array
          style: form
        - description: 'Query in the RSQL format, allowing to filter Volume Purchasing Content collection. Default filter is empty query - returning all results for the requested page. Fields allowed in the query: name, licenseCountTotal, licenseCountInUse, licenseCountReported, contentType, and pricingParam. This param can be combined with paging and sorting.'
          explode: true
          in: query
          name: filter
          required: false
          schema:
            default: ""
            type: string
          style: form
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VolumePurchasingContentList'
          description: Success
        404:
          content:
            application/json:
              schema:
                $ref: _MonolithLibrary.yaml#/components/schemas/ApiError
          description: Volume Purchasing Location with that id does not exist
      summary: Retrieve the Volume Purchasing Content for the Volume Purchasing Location with the supplied id
      tags:
        - volume-purchasing-locations
      x-required-privileges:
        - Read Volume Purchasing Locations
  /v1/volume-purchasing-locations/{id}/history:
    get:
      description: |
        Gets specified Volume Purchasing Location history object
      parameters:
        - description: instance id of Volume Purchasing Location history record
          explode: false
          in: path
          name: id
          required: true
          schema:
            type: string
          style: simple
        - $ref: _MonolithLibrary.yaml#/components/parameters/page
        - $ref: _MonolithLibrary.yaml#/components/parameters/page-size
        - description: 'Sorting criteria in the format: property:asc/desc. Default sort is date:desc. Multiple sort criteria are supported and must be separated with a comma. '
          explode: true
          in: query
          name: sort
          required: false
          schema:
            default:
              - date:desc
            items:
              type: string
            type: array
          style: form
        - description: 'Query in the RSQL format, allowing to filter history notes collection. Default filter is empty query - returning all results for the requested page. Fields allowed in the query: username, date, note, details. This param can be combined with paging and sorting. Example: filter=username!=admin and details==*disabled* and date<2019-12-15'
          explode: true
          in: query
          name: filter
          required: false
          schema:
            default: ""
            type: string
          style: form
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: _MonolithLibrary.yaml#/components/schemas/HistorySearchResults
          description: Details of Volume Purchasing Location history were found
        404:
          content:
            application/json:
              schema:
                $ref: _MonolithLibrary.yaml#/components/schemas/ApiError
          description: Specified Volume Purchasing Location object does not exist.
      summary: |
        Get specified Volume Purchasing Location history object
      tags:
        - volume-purchasing-locations
      x-required-privileges:
        - Read Volume Purchasing Locations
    post:
      description: |
        Adds specified Volume Purchasing Location history object notes
      parameters:
        - description: instance id of Volume Purchasing Location history record
          explode: false
          in: path
          name: id
          required: true
          schema:
            type: string
          style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: _MonolithLibrary.yaml#/components/schemas/ObjectHistoryNote
        description: history note to create
        required: true
      responses:
        201:
          content:
            application/json:
              schema:
                $ref: _MonolithLibrary.yaml#/components/schemas/ObjectHistory
          description: Notes of Volume Purchase Location history were added
        404:
          content:
            application/json:
              schema:
                $ref: _MonolithLibrary.yaml#/components/schemas/ApiError
          description: Specified Volume Purchase Location object does not exist.
        503:
          content:
            application/json:
              schema:
                $ref: _MonolithLibrary.yaml#/components/schemas/ApiError
          description: Volume Purchase Location history can not be saved
      summary: |
        Add specified Volume Purchasing Location history object notes
      tags:
        - volume-purchasing-locations
      x-required-privileges:
        - Update Volume Purchasing Locations
  /v1/volume-purchasing-locations/{id}/reclaim:
    post:
      description: Reclaims a Volume Purchasing Location with the supplied id
      parameters:
        - description: Volume Purchasing Location identifier
          explode: false
          in: path
          name: id
          required: true
          schema:
            type: string
          style: simple
      responses:
        202:
          description: Request accepted
      summary: Reclaim a Volume Purchasing Location with the supplied id
      tags:
        - volume-purchasing-locations
      x-action: true
      x-required-privileges:
        - Update Volume Purchasing Locations
  /v1/volume-purchasing-locations/{id}/revoke-licenses:
    post:
      description: Revokes licenses for a Volume Purchasing Location with the supplied id. The licenses must be revokable - any asset whose licenses are irrevocable will not be revoked.
      parameters:
        - description: Volume Purchasing Location identifier
          explode: false
          in: path
          name: id
          required: true
          schema:
            type: string
          style: simple
      responses:
        202:
          description: Request accepted
        404:
          content:
            application/json:
              schema:
                $ref: _MonolithLibrary.yaml#/components/schemas/ApiError
          description: Volume Purchasing Location with that id does not exist
      summary: Revoke licenses for a Volume Purchasing Location with the supplied id
      tags:
        - volume-purchasing-locations
      x-action: true
      x-required-privileges:
        - Update Volume Purchasing Locations
servers:
  - url: /api
