// Copyright 2026, Jamf Software LLC

package gateway

import (
	"bytes"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"strconv"
)

// Emit writes the runtime coverage table to path as package gateway. The
// runtime package does not import this one — a generator tree has no business
// being linked into the shipped binary — so the Level constants are declared on
// both sides and TestLevelsMatchTheGenerator pins them together.
func Emit(cov *Coverage, entries []Entry, path string) error {
	var b bytes.Buffer

	proVer, classicVer, sdkCommit := "", "", ""
	if cov != nil {
		proVer, classicVer = cov.Sources.Pro.Version, cov.Sources.Classic.Version
		sdkCommit = cov.Sources.SDKCommit
	}

	fmt.Fprintf(&b, `// Copyright 2026, Jamf Software LLC

// Code generated by generator/gateway. DO NOT EDIT.
//
// Which Jamf Pro and Classic operations this CLI can send that the Jamf
// Platform gateway does not publish, derived from jamfplatform-go-sdk's
// api/pro_api.json and api/classic_api_resource_documentation.json via
// specs/gateway/coverage.json. Regenerate with:
//
//	make sync-gateway-coverage-from-sdk JAMFPLATFORM_SDK_PATH=/path/to/jamfplatform-go-sdk
//
// Only the operations this CLI actually sends are listed, so the table is the
// intersection of "the gateway omits it" and "a command exists for it" — not a
// mirror of the gateway's spec.

package gateway

// Provenance of the manifest this table was derived from. Empty when the tree
// held no manifest at generate time, which is the "unknown" case: Lookup then
// finds nothing and no command is refused.
const (
	ProAPIVersion     = %s
	ClassicAPIVersion = %s
	SDKCommit         = %s
)

// unserved is sorted by path then method. Paths are gateway-form with every
// path parameter rendered as {}, matched segment-wise by Lookup. Every entry is
// refused before a request is sent on a gateway profile; Basis selects the
// wording, not the behaviour.
var unserved = []Finding{
`, strconv.Quote(proVer), strconv.Quote(classicVer), strconv.Quote(sdkCommit))

	for _, e := range entries {
		fmt.Fprintf(&b, "\t{Method: %s, Path: %s, Level: %s, Basis: %s, Detail: %s},\n",
			strconv.Quote(e.Method), strconv.Quote(e.Path),
			levelConst(e.Level), basisConst(e.Basis), strconv.Quote(e.Detail))
	}
	b.WriteString("}\n")

	src, err := format.Source(b.Bytes())
	if err != nil {
		return fmt.Errorf("formatting %s: %w", path, err)
	}
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return err
	}
	return os.WriteFile(path, src, 0o644)
}

func levelConst(l Level) string {
	if l == Unserved {
		return "Unserved"
	}
	return "Served"
}

func basisConst(b Basis) string {
	if b == BasisProbe {
		return "BasisProbe"
	}
	return "BasisUnpublished"
}
